const slideConfigs = [
  // --- 1. COVER SLIDE ---
  {
    type: 'cover',
    moduleTitle: 'MODULE 01 · TOPIC 06 · PART 1',
    topicNum: '06',
    topicTag: 'T6',
    title: 'Dual-OS Installation<br>& Post-Config <em>Part 1</em>',
    subtitle: 'Setting up the dual-OS administration environment: WSL 2 architecture, VirtualBox VM networking, and Windows Server 2022 post-configuration.',
    graphicText: 'Bridge <em>Windows</em><br>and <em>Linux</em><br>seamlessly.',
    miniObjectives: ['Understand WSL 2 vs Type-2 VMs', 'Install & Manage WSL 2', 'VirtualBox Networking Modes', 'Windows Server Post-Config']
  },

  // --- 2. OBJECTIVES SLIDE ---
  {
    type: 'objectives',
    header: 'MODULE 01 · TOPIC 06',
    kicker: 'ITP 141 · M1 · T6',
    desc: 'This topic bridges the Windows and Linux worlds. You will learn to set up WSL 2 for quick command-line tasks and VirtualBox for full server environments.',
    lede: 'A modern sysadmin works across both Windows and Linux. Mastering WSL 2 and hypervisors like VirtualBox is essential for a dual-OS workflow.',
    list: [
      'Explain WSL 2 architecture and differentiate WSL 1, WSL 2, and a full Type-2 VM.',
      'Enable WSL 2 and install a Linux distribution with wsl --install.',
      'Manage WSL 2 distributions (export, import, shutdown) and configure interoperability.',
      'Create a VirtualBox VM sized for Windows Server 2022.',
      'Compare VirtualBox networking modes (NAT, Internal, Bridged).'
    ]
  },

  // 1. Dual-OS Environment Overview
  { type: 'lesson', category: 'Overview', title: 'Dual-OS: The Sysadmin Lab', subtitle: 'Topic Overview', desc: 'Modern system administration requires fluency in both Windows and Linux. We use two technologies to achieve this: WSL 2 for lightweight CLI tasks, and VirtualBox for full-scale server deployment.', syntax: 'C:\\> wsl --install -d Ubuntu-24.04', term: [{raw: '<span class="out" style="color:#E8A07A">Windows Host</span><br><span class="cmd">> wsl --install -d Ubuntu-24.04</span><br><span class="out">Installing: Ubuntu 24.04 LTS...</span><br><span class="out" style="color:#E8A07A">Linux Subsystem</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">uname -r</span><br><span class="out">5.15.153.1-microsoft-standard-WSL2</span>'}], explain: '<strong>Explanation:</strong> WSL 2 provides a real Linux kernel running in a lightweight utility VM. It boots in seconds and shares your Windows filesystem. For full server roles (like Active Directory), we will use VirtualBox.' },
  
  // 2. WSL 2 Architecture
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: Architecture', subtitle: 'Utility VM vs Type-2', desc: 'WSL 2 uses a lightweight utility VM running a real Linux kernel. It is not a full virtual machine like VirtualBox, but a highly optimized container-style environment.', syntax: 'WSL 1 (Translation) -> WSL 2 (Utility VM) -> Type-2 VM (Full Hypervisor)', term: [{raw: '<span class="out"># Comparing the layers:</span><br><span class="out">1. WSL 1: Syscall translation (No real Linux kernel)</span><br><span class="out">2. WSL 2: Real Linux kernel in a Utility VM (Fast, CLI focus)</span><br><span class="out">3. VirtualBox: Full Type-2 Hypervisor (Isolated, GUI, Server roles)</span>'}], explain: '<strong>Why it matters:</strong> WSL 2 is perfect for running <code>grep</code>, <code>awk</code>, and <code>bash</code> scripts on your Windows laptop without the overhead of a full VM. For Windows Server 2022, you must use a Type-2 VM like VirtualBox.' },
  
  // 3. WSL 1 vs WSL 2
  { type: 'lesson', category: 'WSL 2', title: 'WSL 1 vs WSL 2', subtitle: 'Key Differences', desc: 'WSL 1 translates Linux syscalls to Windows NT API calls. WSL 2 runs a genuine Linux kernel in a lightweight virtual machine. WSL 2 offers 100% system call compatibility.', syntax: 'wsl --set-version Ubuntu-24.04 2', term: [{raw: '<span class="out" style="color:#E8A07A">Feature Comparison Matrix</span><br><span class="out">1. Linux Kernel: WSL 1 (No) -> WSL 2 (Yes)</span><br><span class="out">2. Full Syscall Compat: WSL 1 (Some) -> WSL 2 (Yes)</span><br><span class="out">3. File System Perf (/mnt/c): WSL 1 (Fast) -> WSL 2 (Slower)</span><br><span class="out">4. Network Isolation: WSL 1 (Shares host IP) -> WSL 2 (Own VM IP)</span>'}], explain: '<strong>Explanation:</strong> WSL 2 is better for running Docker containers and Linux-specific tools because it has a real kernel. However, if you need to read/write files heavily on the Windows C: drive, WSL 1 might be faster. We default to WSL 2 for this course.' },
  
  // 4. WSL 2: Kernel Update
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: Kernel Update', subtitle: 'wsl --update', desc: 'WSL 2 uses a custom Microsoft-built Linux kernel. You can update it manually to get the latest features and security patches.', syntax: 'wsl --update', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> wsl --update</span><br><span class="out">Checking for updates...</span><br><span class="out">Installing: Wsl Kernel Update Package</span><br><span class="out">Successfully installed the Wsl Kernel Update Package.</span>'}], explain: '<strong>Explanation:</strong> Unlike a traditional Linux VM where you update the kernel via <code>apt</code>, WSL 2 manages its own kernel via Windows Update or the <code>wsl --update</code> command. This ensures optimal compatibility with the Windows host.' },
  
  // 5. Enabling WSL 2
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: Enabling', subtitle: 'Prerequisites', desc: 'Before installing a Linux distribution, you must enable the Windows Subsystem for Linux feature and the Virtual Machine Platform.', syntax: 'wsl --install\ndism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> wsl --install</span><br><span class="out">Installing: Virtual Machine Platform...</span><br><span class="out">Installing: Windows Subsystem for Linux...</span><br><span class="cmd">> wsl --set-default-version 2</span><br><span class="out">The operation completed successfully.</span>'}], explain: '<strong>Explanation:</strong> The <code>wsl --install</code> command enables the necessary Windows features and downloads the default Linux kernel. Setting the default version to 2 ensures all future distributions use the real Linux kernel.' },
  
  // 6. Installing Linux Distros
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: Installing Distros', subtitle: 'wsl --install -d', desc: 'You can install various Linux distributions on WSL 2. For this course, we will use Ubuntu-24.04 LTS to match our syllabus.', syntax: 'wsl --list --online\nwsl --install -d Ubuntu-24.04', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell</span><br><span class="cmd">> wsl --list --online</span><br><span class="out">The following is a list of valid distributions...</span><br><span class="out">Ubuntu-24.04</span><br><span class="cmd">> wsl --install -d Ubuntu-24.04</span><br><span class="out">Installing: Ubuntu 24.04 LTS...</span><br><span class="out">Please create a default UNIX user account.</span><br><span class="out">Enter new UNIX username: </span>'}], explain: '<strong>Explanation:</strong> The <code>--list --online</code> command shows available distros. The <code>-d</code> flag specifies which one to install. After installation, you will be prompted to create a standard Linux user account.' },
  
  // 7. Managing WSL 2
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: Management', subtitle: 'List, Shutdown', desc: 'You can manage the state of your WSL 2 instances using command-line tools. This includes backing up (exporting) and restoring (importing) distributions.', syntax: 'wsl -l -v\nwsl --shutdown', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell</span><br><span class="cmd">> wsl -l -v</span><br><span class="out">  NAME            STATE           VERSION</span><br><span class="out">* Ubuntu-24.04    Running         2</span><br><span class="cmd">> wsl --shutdown</span><br><span class="out">(Terminates all WSL instances to free RAM)</span>'}], explain: '<strong>Explanation:</strong> <code>wsl -l -v</code> shows your installed distributions and their running state. <code>--shutdown</code> is useful if WSL is consuming too much memory in the background.' },
  
  // 8. Backup and Restore
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: Backup & Restore', subtitle: 'Export / Import', desc: 'To back up your Linux environment, you can export the entire distribution to a .tar file. This is highly useful for saving your lab configurations.', syntax: 'wsl --export Ubuntu-24.04 C:\\backup.tar\nwsl --unregister Ubuntu-24.04\nwsl --import Ubuntu-24.04 C:\\wsl\\ubuntu C:\\backup.tar', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell</span><br><span class="cmd">> wsl --export Ubuntu-24.04 C:\\Users\\Admin\\wsl-backup.tar</span><br><span class="out">Exporting... this may take a few minutes.</span><br><span class="cmd">> wsl --unregister Ubuntu-24.04</span><br><span class="cmd">> wsl --import Ubuntu-24.04 C:\\wsl\\ubuntu C:\\Users\\Admin\\wsl-backup.tar</span><br><span class="out">Importing... complete.</span>'}], explain: '<strong>Explanation:</strong> <code>--export</code> creates a tarball backup of your entire Linux filesystem. <code>--unregister</code> deletes the instance. <code>--import</code> restores it from the tarball. This is the definitive way to move WSL environments between computers.' },
  
  // 9. Resource Limits
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: Resource Limits', subtitle: '.wslconfig', desc: 'By default, WSL 2 can consume up to 50% of your system RAM. You can limit this by creating a <code>.wslconfig</code> file in your Windows user profile.', syntax: '# C:\\Users\\YourName\\.wslconfig\n[wsl2]\nmemory=4GB\nprocessors=2\nswap=1GB', term: [{editor: "C:\\Users\\Admin\\.wslconfig", code: "[wsl2]\nmemory=4GB\nprocessors=2\nswap=1GB"}, {raw: '<span class="out" style="color:#E8A07A">Windows PowerShell</span><br><span class="cmd">> wsl --shutdown</span><br><span class="cmd">> wsl</span><br><span class="out">(Restarts WSL with new limits applied)</span>'}], explain: '<strong>Explanation:</strong> Create this file in Notepad. The <code>memory</code> setting caps how much RAM the Linux VM can use. You must run <code>wsl --shutdown</code> for the changes to take effect.' },
  
  // 10. Interop: /mnt/c
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: Interoperability', subtitle: '/mnt/c', desc: 'WSL 2 mounts your Windows C: drive automatically under <code>/mnt/c</code>. You can access Windows files directly from Linux.', syntax: '# Access Windows files from Linux\ncd /mnt/c/Users/Admin/Documents\nls', term: [{raw: '<span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">cd /mnt/c/Users/Admin/Desktop</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">/mnt/c/Users/Admin/Desktop</span>$</span> <span class="cmd">ls</span><br><span class="out">labs  scripts  notes.txt</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">/mnt/c/Users/Admin/Desktop</span>$</span> <span class="cmd">cp notes.txt ~</span><br><span class="out">(Copied to Linux home directory)</span>'}], explain: '<strong>Explanation:</strong> The C: drive is accessible at <code>/mnt/c</code>. You can read and write files across the OS boundary seamlessly. This is highly useful for moving scripts written on Windows into your Linux environment.' },
  
  // 11. Interop: VS Code
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: Interoperability', subtitle: 'VS Code Remote', desc: 'You can use VS Code Remote-WSL to edit Linux files directly from Windows. VS Code runs its UI on Windows, but executes commands in WSL.', syntax: '# Open Linux project in VS Code (run from WSL)\ncode .', term: [{raw: '<span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">mkdir my_project && cd my_project</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~/my_project</span>$</span> <span class="cmd">echo "print(\'Hello\')" > app.py</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~/my_project</span>$</span> <span class="cmd">code .</span><br><span class="out">Launching VS Code Server...</span><br><span class="out">VS Code opens on Windows, editing WSL files!</span>'}], explain: '<strong>Explanation:</strong> The <code>code .</code> command launches Visual Studio Code on Windows, but it seamlessly connects to the WSL 2 filesystem to edit files. This is the ultimate dual-OS development environment.' },
  
  // 12. WSL 2: PATH Sharing
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: PATH Sharing', subtitle: 'Windows Executables', desc: 'WSL 2 shares the Windows PATH environment variable. This means you can launch Windows applications directly from the Linux command line.', syntax: 'notepad.exe /mnt/c/Users/Admin/file.txt\nexplorer.exe .', term: [{raw: '<span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">echo "Hello" > notes.txt</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">notepad.exe notes.txt</span><br><span class="out">(Notepad opens on Windows displaying the Linux file)</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">explorer.exe .</span><br><span class="out">(Windows File Explorer opens in the current directory)</span>'}], explain: '<strong>Explanation:</strong> The Windows PATH is inherited by WSL 2. You can run <code>.exe</code> files like <code>notepad.exe</code> or <code>ipconfig.exe</code> directly from Bash. This tight integration bridges the gap between the two operating systems.' },
  
  // 13. WSL 2: File System Performance
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: File System Performance', subtitle: 'Best Practices', desc: 'For best performance, store Linux project files inside the WSL 2 filesystem (<code>/home/user</code>), not on the Windows drive (<code>/mnt/c</code>).', syntax: '# Best Performance:\ncd ~ && mkdir project\n# Slower:\ncd /mnt/c/Users/Admin/project', term: [{raw: '<span class="out" style="color:#E8A07A">Performance Comparison:</span><br><span class="out">1. Linux FS (/home): Native ext4, fast read/write</span><br><span class="out">2. Windows FS (/mnt/c): 9P protocol translation, slower</span><br><br><span class="out" style="color:#E8A07A">Recommendation:</span><br><span class="out">- Store code & scripts in ~ (WSL2)</span><br><span class="out">- Access media/docs from /mnt/c</span>'}], explain: '<strong>Explanation:</strong> WSL 2 uses an ext4 virtual disk for Linux files, which is native and fast. Accessing <code>/mnt/c</code> requires a protocol translation between the VM and Windows host. For heavy I/O (like <code>git</code> operations or compiling), work in the <code>~</code> directory.' },
  
  // 14. WSL 2: GUI Apps (WSLg)
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: GUI Apps (WSLg)', subtitle: 'Linux GUI on Windows', desc: 'WSLg allows running Linux GUI applications seamlessly on your Windows desktop. They appear in their own window, just like native apps.', syntax: 'sudo apt install x11-apps -y\nxcalc', term: [{raw: '<span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt install x11-apps -y</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">xcalc &</span><br><span class="out">(A Linux calculator window opens on your Windows desktop)</span>'}], explain: '<strong>Explanation:</strong> WSLg (WSL GUI) is built into Windows 11 and recent versions of Windows 10. It handles the X11 server and Wayland automatically, so you don\'t need to configure a third-party X server like Xming.' },
  
  // 15. WSL 2 Limits vs VM
  { type: 'lesson', category: 'WSL 2', title: 'WSL 2: Limits vs VM', subtitle: 'When to use what', desc: 'WSL 2 is fast but lacks a full init system and GUI by default. A full Type-2 VM like VirtualBox provides complete isolation, GUI support, and server roles.', syntax: 'WSL 2 = Fast CLI, Scripting, Dev\nVirtualBox = Full Server Roles, GUI, Isolation', term: [{raw: '<span class="out" style="color:#E8A07A">WSL 2 Limits:</span><br><span class="out">- No systemd by default (no systemctl)</span><br><span class="out">- No GUI (unless using WSLg)</span><br><span class="out">- Shares host IP (NAT by default)</span><br><br><span class="out" style="color:#E8A07A">VirtualBox Strengths:</span><br><span class="out">- Full systemd and kernel</span><br><span class="out">- GUI Desktop Environment</span><br><span class="out">- Bridged IP (visible on LAN)</span>'}], explain: '<strong>Explanation:</strong> If you just need to run <code>awk</code> or a Bash script, use WSL 2. If you need to install Windows Server 2022 with Active Directory, or run Ubuntu Server with a static LAN IP, you must use VirtualBox.' },
  
  // 16. VBox: VM Setup
  { type: 'lesson', category: 'VirtualBox', title: 'VirtualBox: VM Setup', subtitle: 'Windows Server 2022', desc: 'For full server roles, we use a Type-2 Hypervisor (VirtualBox). We will create a VM sized for Windows Server 2022.', syntax: 'Name: WIN-SRV-01\nType: Microsoft Windows\nVersion: Windows Server 2022 (64-bit)\nRAM: 4096 MB (4GB)\nDisk: 50.00 GB', term: [{raw: '<span class="out" style="color:#E8A07A">VirtualBox Manager</span><br><span class="out">[ ] Name: WIN-SRV-01</span><br><span class="out">[ ] ISO Image: Windows_Server_2022.iso</span><br><span class="out">[ ] Base Memory: 4096 MB</span><br><span class="out">[ ] Processors: 2</span><br><span class="out">[ ] Disk Size: 50.00 GB</span><br><span class="out">(Click \'Finish\' to create the VM)</span>'}], explain: '<strong>Explanation:</strong> Windows Server 2022 requires at least 4GB of RAM and 50GB of disk space. Assigning 2 processors ensures the installation and server roles run smoothly.' },
  
  // 17. VBox: Virtual Hard Disk
  { type: 'lesson', category: 'VirtualBox', title: 'VirtualBox: Virtual Hard Disk', subtitle: 'Dynamic vs Fixed', desc: 'When creating the VM, choose a Virtual Hard Disk. You can select "Dynamically allocated" (grows as needed) or "Fixed size" (faster but uses full space immediately).', syntax: 'File Type: VDI (VirtualBox Disk Image)\nStorage: Dynamically allocated\nSize: 50.00 GB', term: [{raw: '<span class="out" style="color:#E8A07A">VirtualBox Disk Creation</span><br><span class="out">[X] Dynamically allocated</span><br><span class="out">[ ] Fixed size</span><br><br><span class="out">Location: WIN-SRV-01.vdi</span><br><span class="out">Size: 50.00 GB</span>'}], explain: '<strong>Explanation:</strong> For labs, "Dynamically allocated" is best because it only consumes physical disk space as the VM uses it. A fixed-size disk takes longer to create but offers slightly better read/write performance for production servers.' },
  
  // 18. VBox: Guest Additions
  { type: 'lesson', category: 'VirtualBox', title: 'VirtualBox: Guest Additions', subtitle: 'Enhanced Drivers', desc: 'Install VirtualBox Guest Additions to enable clipboard sharing, dynamic display resizing, and better performance inside the VM.', syntax: 'Devices -> Insert Guest Additions CD image', term: [{raw: '<span class="out" style="color:#E8A07A">VirtualBox Menu</span><br><span class="out">1. Click "Devices" in the VM menu bar.</span><br><span class="out">2. Select "Insert Guest Additions CD image..."</span><br><br><span class="out" style="color:#E8A07A">Inside Windows Server VM</span><br><span class="cmd">> E:\\VBoxWindowsAdditions.exe</span><br><span class="out">(Installs drivers. Reboot required.)</span>'}], explain: '<strong>Explanation:</strong> Without Guest Additions, you cannot copy-paste text between your host and the VM, and the VM screen will be stuck at a low resolution. This is a critical post-installation step for any VirtualBox VM.' },
  
  // 19. VBox: Snapshots
  { type: 'lesson', category: 'VirtualBox', title: 'VirtualBox: Snapshots', subtitle: 'Point-in-Time State', desc: 'Snapshots allow you to save the VM state and revert back if an installation fails. Essential for lab environments.', syntax: 'Machine -> Take Snapshot', term: [{raw: '<span class="out" style="color:#E8A07A">VirtualBox Menu</span><br><span class="out">1. Click "Machine" in the menu bar.</span><br><span class="out">2. Select "Take Snapshot..."</span><br><span class="out">3. Name it: "Clean Install" or "Pre-AD-DS"</span><br><br><span class="out" style="color:#E8A07A">Why use snapshots?</span><br><span class="out">If a lab breaks the server, you can restore the snapshot in 5 seconds instead of reinstalling Windows.</span>'}], explain: '<strong>Explanation:</strong> Snapshots are a lifesaver for sysadmin labs. Before installing Active Directory or Docker, take a snapshot. If the configuration fails, you can instantly revert to the clean state.' },
  
  // 20. VBox: NAT
  { type: 'lesson', category: 'VirtualBox', title: 'VirtualBox: Networking', subtitle: 'NAT Mode', desc: 'By default, VirtualBox uses NAT (Network Address Translation). The VM gets a private IP and can access the internet, but cannot be reached from the host.', syntax: 'Attached to: NAT\nVM IP: 10.0.2.15\nHost IP: Cannot reach VM', term: [{raw: '<span class="out" style="color:#E8A07A">VirtualBox Network Settings</span><br><span class="out">Attached to: [NAT] v</span><br><br><span class="out" style="color:#E8A07A">Inside VM (Win Server)</span><br><span class="cmd">> ipconfig</span><br><span class="out">IPv4 Address. . . . . . . . . . . : 10.0.2.15</span><br><br><span class="out" style="color:#E8A07A">From Host (Windows)</span><br><span class="cmd">> ping 10.0.2.15</span><br><span class="err">PING: Request timed out.</span>'}], explain: '<strong>Explanation:</strong> NAT is great for browsing the web from a VM safely, but it hides the VM behind the host. You cannot RDP into a NAT VM from your host machine without complex port forwarding.' },
  
  // 21. VBox: Internal
  { type: 'lesson', category: 'VirtualBox', title: 'VirtualBox: Networking', subtitle: 'Internal Network', desc: 'Internal Network mode creates a private LAN strictly between your VMs. The VMs have no internet access, and the host cannot reach them.', syntax: 'Attached to: Internal Network\nName: intnet-lab', term: [{raw: '<span class="out" style="color:#E8A07A">VirtualBox Network Settings</span><br><span class="out">Attached to: [Internal Network] v</span><br><span class="out">Name: [intnet-lab] v</span><br><br><span class="out">Result:</span><br><span class="out">Win Server <----> Ubuntu Server</span><br><span class="out">No Internet. No Host Access.</span>'}], explain: '<strong>Explanation:</strong> This is perfect for testing Active Directory replication between two VMs in a safe, isolated environment without risking DHCP conflicts on your classroom network.' },
  
  // 22. VBox: Bridged
  { type: 'lesson', category: 'VirtualBox', title: 'VirtualBox: Networking', subtitle: 'Bridged Adapter', desc: 'For server administration, we need Bridged Networking. This makes the VM act like a physical machine on your physical LAN.', syntax: 'Attached to: Bridged Adapter\nName: [Your Physical Network Card]', term: [{raw: '<span class="out" style="color:#E8A07A">VirtualBox Network Settings</span><br><span class="out">Attached to: [Bridged Adapter] v</span><br><span class="out">Name: [Realtek PCIe GbE Family Controller] v</span><br><span class="out">Advanced -> Promiscuous Mode: [Allow All] v</span><br><br><span class="out" style="color:#E8A07A">Inside VM (Win Server)</span><br><span class="cmd">> ipconfig</span><br><span class="out">IPv4 Address. . . . . . . . . . . : 192.168.1.10</span><br><br><span class="out" style="color:#E8A07A">From Host (Windows)</span><br><span class="cmd">> ping 192.168.1.10</span><br><span class="out">Reply from 192.168.1.10: bytes=32 time=1ms TTL=128</span>'}], explain: '<strong>Explanation:</strong> To RDP into the server or for the server to communicate with a Linux VM later, we must use <strong>Bridged Adapter</strong>. It requests an IP directly from your physical router.' },
  
  // 23. Win Server: Boot ISO
  { type: 'lesson', category: 'Windows Server', title: 'Windows Server: Install', subtitle: 'Booting the ISO', desc: 'Boot the VM from the Windows Server 2022 ISO. You will be greeted with the standard Windows Setup screen.', syntax: 'Language: English\nTime: English\nKeyboard: US\n[Next] -> [Install now]', term: [{raw: '<span class="out" style="color:#E8A07A">Windows Setup</span><br><span class="out">Language to install: English (United States)</span><br><span class="out">Time and currency format: English (United States)</span><br><span class="out">Keyboard or input method: US</span><br><br><span class="out">[ Next ]   [ Repair your computer ]</span><br><br><span class="out">[ Install now ]</span>'}], explain: '<strong>Explanation:</strong> Ensure the VirtualBox VM\'s optical drive is mapped to the Windows Server 2022 ISO file. Upon boot, the VM will load the Windows Preinstallation Environment (WinPE).' },
  
  // 24. Win Server: Admin Password
  { type: 'lesson', category: 'Windows Server', title: 'Windows Server: Install', subtitle: 'Admin Password', desc: 'During installation, Windows Server prompts you to set the built-in Administrator password before logging in.', syntax: 'User: Administrator\nPassword: P@ssw0rd123!', term: [{raw: '<span class="out" style="color:#E8A07A">Windows Setup</span><br><span class="out">The user\'s password must be changed before logging on the first time.</span><br><br><span class="out">User: Administrator</span><br><span class="out">New Password: P@ssw0rd123!</span><br><span class="out">Confirm Password: P@ssw0rd123!</span><br><br><span class="out">[ OK ]</span>'}], explain: '<strong>Explanation:</strong> Unlike Ubuntu where you create a standard user, Windows Server uses the built-in <code>Administrator</code> account by default. The password must meet complexity requirements (uppercase, lowercase, numbers, symbols) or the installation will reject it.' },
  
  // 25. Win Server: Desktop Experience
  { type: 'lesson', category: 'Windows Server', title: 'Windows Server: Install', subtitle: 'Desktop Experience', desc: 'For this course, we will install the "Desktop Experience" version (GUI) rather than the Server Core (CLI-only) version to make administration labs easier.', syntax: 'Select: Windows Server 2022 Standard (Desktop Experience)\nInstall Type: Custom (advanced)', term: [{raw: '<span class="out" style="color:#E8A07A">Select operating system to install</span><br><span class="out">[ ] Windows Server 2022 Standard</span><br><span class="out">[X] Windows Server 2022 Standard (Desktop Experience)</span><br><span class="out">[ ] Windows Server 2022 Datacenter</span><br><br><span class="out">Which type of installation do you want?</span><br><span class="out">[ Upgrade ]   [X] Custom: Install Windows only (advanced) ]</span><br><br><span class="out">[ Drive 0 Unallocated Space ] -> [ Next ]</span>'}], explain: '<strong>Explanation:</strong> The Desktop Experience provides the familiar Windows GUI, which is easier for administration labs. Server Core is more secure and uses less RAM, but requires managing everything via PowerShell.' },
  
  // 26. Win Server: Core vs Desktop
  { type: 'lesson', category: 'Windows Server', title: 'Win Server: Core vs Desktop', subtitle: 'Installation Choices', desc: 'A deeper look at the two installation options. Core is lightweight and secure, Desktop Experience has the full GUI.', syntax: 'Server Core: CLI/PowerShell only\nDesktop Experience: Full GUI', term: [{raw: '<span class="out" style="color:#E8A07A">Server Core</span><br><span class="out">- No GUI, only command prompt/PowerShell.</span><br><span class="out">- Smaller attack surface (fewer patches).</span><br><span class="out">- Uses 1-2GB less RAM.</span><br><br><span class="out" style="color:#E8A07A">Desktop Experience</span><br><span class="out">- Full GUI (Start menu, Server Manager).</span><br><span class="out">- Easier for beginners, requires more patches.</span><br><span class="out">- Used in this course for lab simplicity.</span>'}], explain: '<strong>Explanation:</strong> In production, Microsoft recommends Server Core for most roles (DNS, DHCP, AD). However, managing it requires advanced PowerShell skills. We use Desktop Experience in the lab so you can visually see what is happening.' },
  
  // 27. Win Server: sconfig
  { type: 'lesson', category: 'Windows Server', title: 'Win Server: sconfig', subtitle: 'Quick Configuration', desc: 'Server Configuration (sconfig) is a text-based menu for quick setup of hostname, network, and updates. It works on both Core and Desktop.', syntax: 'sconfig', term: [{raw: '<span class="out" style="color:#E8A07A">Server Configuration</span><br><span class="out">1) Domain/Workgroup: Workgroup: WORKGROUP</span><br><span class="out">2) Computer Name:     WIN-SRV-01</span><br><span class="out">3) Network Settings: 192.168.1.10</span><br><span class="out">4) Windows Update:    Manual</span><br><br><span class="out">Enter number to select an option: 2</span><br><span class="out">(Allows you to rename the computer quickly)</span>'}], explain: '<strong>Explanation:</strong> <code>sconfig</code> is a legacy tool but still highly useful. It allows you to join a domain, set a static IP, and install updates without remembering complex PowerShell cmdlets.' },
  
  // 28. Win Server: Hostname
  { type: 'lesson', category: 'Windows Server', title: 'Windows Server: Post-Config', subtitle: 'Hostname', desc: 'After installation, change the hostname to prepare for Active Directory and DNS roles. The default name is usually a random string.', syntax: 'Rename-Computer -NewName "WIN-SRV-01" -Restart', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> hostname</span><br><span class="out">DESKTOP-WIN7X9</span><br><span class="cmd">> Rename-Computer -NewName "WIN-SRV-01" -Restart</span><br><span class="out">WARNING: The changes will take effect after you restart the computer.</span><br><span class="out">(Computer restarts...)</span><br><span class="cmd">> hostname</span><br><span class="out">WIN-SRV-01</span>'}], explain: '<strong>Explanation:</strong> A clean, descriptive hostname is critical for network identification. Active Directory relies heavily on the hostname for its DNS records. We use PowerShell to rename and restart.' },
  
  // 29. Win Server: Static IP
  { type: 'lesson', category: 'Windows Server', title: 'Windows Server: Post-Config', subtitle: 'Static IP', desc: 'Configure a static IP address. Servers must not rely on DHCP, as their IP must never change for clients to find them.', syntax: 'New-NetIPAddress -InterfaceAlias "Ethernet" -IPAddress "192.168.1.10" -PrefixLength 24 -DefaultGateway "192.168.1.1"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> New-NetIPAddress -InterfaceAlias "Ethernet" -IPAddress "192.168.1.10" -PrefixLength 24 -DefaultGateway "192.168.1.1"</span><br><span class="cmd">> Set-DnsClientServerAddress -InterfaceAlias "Ethernet" -ServerAddresses "192.168.1.1"</span><br><span class="cmd">> ipconfig /all</span><br><span class="out">IPv4 Address. . . . . . . . . . . : 192.168.1.10(Preferred)</span><br><span class="out">Subnet Mask . . . . . . . . . . . : 255.255.255.0</span><br><span class="out">Default Gateway . . . . . . . . . . : 192.168.1.1</span>'}], explain: '<strong>Explanation:</strong> Active Directory requires a static IP. The <code>New-NetIPAddress</code> cmdlet assigns the IP. We also set the DNS server (in Part 2, this will point to the server itself once AD is installed).' },
  
  // 30. Win Server: Timezone
  { type: 'lesson', category: 'Windows Server', title: 'Windows Server: Post-Config', subtitle: 'Timezone', desc: 'Set the correct timezone to ensure log timestamps are accurate and Kerberos authentication does not fail due to time skew.', syntax: 'Set-TimeZone -Id "Asia/Manila"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Set-TimeZone -Id "Asia/Manila"</span><br><br><span class="out" style="color:#E8A07A">Verify Timezone</span><br><span class="cmd">> Get-TimeZone</span><br><span class="out">Id                         : Asia/Manila</span><br><span class="out">DisplayName                : (UTC+08:00) Taipei</span><br><span class="out">StandardName               : Taipei Standard Time</span>'}], explain: '<strong>Explanation:</strong> Active Directory relies on Kerberos for authentication. Kerberos tickets have a 5-minute time tolerance. If the server clock is off by more than 5 minutes from the client, authentication will fail. Setting the correct timezone is essential.' },
  
  // 31. Win Server: RDP
  { type: 'lesson', category: 'Windows Server', title: 'Windows Server: Post-Config', subtitle: 'Enable RDP', desc: 'Enable Remote Desktop Protocol (RDP) so you can manage the server from your host machine in a full-screen window.', syntax: 'Set-ItemProperty -Path \'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server\' -name "fDenyTSConnections" -value 0\nEnable-NetFirewallRule -DisplayGroup "Remote Desktop"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Set-ItemProperty -Path \'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server\' -name "fDenyTSConnections" -value 0</span><br><span class="cmd">> Enable-NetFirewallRule -DisplayGroup "Remote Desktop"</span><br><span class="out">(RDP is now enabled and firewall is open)</span><br><br><span class="out" style="color:#E8A07A">From Host Machine (Windows 10/11)</span><br><span class="cmd">> mstsc /v:192.168.1.10</span><br><span class="out">(Remote Desktop Connection opens to the server)</span>'}], explain: '<strong>Explanation:</strong> By enabling RDP, you don\'t have to use the small VirtualBox window. You can open Remote Desktop Connection (<code>mstsc</code>) on your Windows host and connect to <code>192.168.1.10</code> for a full-screen experience.' },
  
  // 32. Win Server: RSAT
  { type: 'lesson', category: 'Windows Server', title: 'Windows Server: Post-Config', subtitle: 'Install RSAT', desc: 'Install Remote Server Administration Tools (RSAT). This includes the GUI tools for Active Directory, DNS, and Group Policy management.', syntax: 'Get-WindowsCapability -Name RSAT* -Online | Add-WindowsCapability -Online', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Get-WindowsCapability -Name RSAT* -Online | Add-WindowsCapability -Online</span><br><span class="out">Installing: Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0</span><br><span class="out">Installing: Rsat.Dns.Tools~~~~0.0.1.0</span><br><span class="out">Installing: Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0</span><br><span class="out">Path :</span><br><span class="out">Online : True</span><br><span class="out">RestartNeeded : False</span>'}], explain: '<strong>Explanation:</strong> While we can manage AD via PowerShell, the RSAT GUI tools make it much easier to visualize Organizational Units (OUs) and users. This prepares us for Module 4.' },
  
  // 33. Win Server: Windows Update
  { type: 'lesson', category: 'Windows Server', title: 'Windows Server: Post-Config', subtitle: 'Windows Update', desc: 'Install the latest security patches and cumulative updates via PowerShell or Settings to ensure the server is secure.', syntax: 'Install-Module PSWindowsUpdate\nInstall-WindowsUpdate -AcceptAll -AutoReboot', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Install-Module PSWindowsUpdate -Force</span><br><span class="cmd">> Install-WindowsUpdate -AcceptAll -AutoReboot</span><br><br><span class="out">ComputerName Status  KB         Size  Title</span><br><span class="out">WIN-SRV-01    -D----  KB500...  12MB  2024-10 Cumulative Update</span><br><span class="out">(Server will reboot automatically after updates)</span>'}], explain: '<strong>Explanation:</strong> A fresh Windows Server ISO is often months out of date. Applying the latest cumulative update patches hundreds of vulnerabilities and fixes bugs before we install server roles like AD DS.' },
  
  // 34. Win Server: Server Manager & Roles
  { type: 'lesson', category: 'Windows Server', title: 'Win Server: Server Manager', subtitle: 'Adding Roles', desc: 'Server Manager is the central hub for adding roles (AD DS, IIS, DNS) and managing the server.', syntax: 'ServerManager.exe', term: [{raw: '<span class="out" style="color:#E8A07A">Server Manager Dashboard</span><br><span class="out">1. Configure this local server</span><br><span class="out">2. Add roles and features</span><br><br><span class="out" style="color:#E8A07A">Add Roles Wizard</span><br><span class="out">[X] Active Directory Domain Services</span><br><span class="out">[X] DNS Server</span><br><span class="out">[X] Web Server (IIS)</span>'}], explain: '<strong>Explanation:</strong> Server Manager opens automatically on login. It is the Windows equivalent of <code>apt install</code>. You select the roles you want, and Windows installs the binaries and management tools automatically.' },
  
  // 35. Win Server: Network GUI Check
  { type: 'lesson', category: 'Windows Server', title: 'Win Server: GUI Check', subtitle: 'Server Manager & Network', desc: 'After logging in, Server Manager opens automatically. Verify your static IP and hostname visually using the GUI tools.', syntax: 'ncpa.cpl   (Network Connections)\nsysdm.cpl  (System Properties)', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> ncpa.cpl</span><br><span class="out">(Opens Network Connections control panel)</span><br><span class="out">Right-click "Ethernet" -> Status -> Details</span><br><span class="out">IPv4 Address: 192.168.1.10</span><br><br><span class="cmd">> sysdm.cpl</span><br><span class="out">(Opens System Properties)</span><br><span class="out">Full computer name: WIN-SRV-01</span>'}], explain: '<strong>Explanation:</strong> <code>ncpa.cpl</code> opens the Network Connections control panel, allowing you to verify the static IP visually. Server Manager is your central hub for adding roles (like AD DS), managing local servers, and checking firewall status.' },
  
  // 36. Cross-OS Verification
  { type: 'lesson', category: 'Verification', title: 'Cross-OS Verification', subtitle: 'Final Check', desc: 'Final verification: ping the Windows VM from the Ubuntu VM to confirm the dual-OS lab is ready for Part 2.', syntax: 'ping 192.168.1.10', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ping -c 4 192.168.1.10</span><br><span class="out">PING 192.168.1.10 (192.168.1.10) 56(84) bytes of data.</span><br><span class="out">64 bytes from 192.168.1.10: icmp_seq=1 ttl=128 time=0.521 ms</span><br><span class="out">64 bytes from 192.168.1.10: icmp_seq=2 ttl=128 time=0.485 ms</span><br><br><span class="out">--- 192.168.1.10 ping statistics ---</span><br><span class="out">4 packets transmitted, 4 received, 0% packet loss</span>'}], explain: '<strong>Explanation:</strong> If both VMs are on Bridged Adapters, they should be able to ping each other. This confirms the network foundation is ready for the Ubuntu Server installation in Part 2.' },
  
  // 37. Summary
  { type: 'lesson', category: 'Summary', title: 'Topic Summary', subtitle: 'Next Steps', desc: 'We have established our dual-OS administration lab. WSL 2 is ready for Linux scripting, and Windows Server is ready in VirtualBox for GUI-based roles.', syntax: 'wsl -l -v\nping 192.168.1.10', term: [{raw: '<span class="out" style="color:#E8A07A">Checklist for Part 2:</span><br>[x] WSL 2 installed and memory limited<br>[x] Windows Server 2022 installed in VirtualBox<br>[x] Bridged Networking configured<br>[x] Hostname changed to WIN-SRV-01<br>[x] Static IP configured (192.168.1.10)<br>[x] RDP enabled and tested from host<br><br><span class="out">Next: We will install Ubuntu Server 24.04 as a second VM and bridge them together.</span>'}], explain: '<strong>Explanation:</strong> With the Windows side fully configured, we are ready to add a Linux server to the network. In Part 2, we will configure Netplan, SSH, and test cross-OS connectivity.' },

  // --- 4. CLOSING SLIDE (Put this at the very end of the array) ---
  {
    type: 'closing',
    header: 'MODULE 01 · TOPIC 06',
    tag: 'End of Topic 06 Part 1',
    title: 'Two OSes, <em>One</em> Workspace.',
    leftCardNum: '§ wsl 2',
    leftCardTitle: 'Lightweight & Native',
    leftCardDesc: 'Use WSL 2 for fast, resource-efficient Linux command-line tasks directly on Windows. Ideal for text processing, scripting, and development.',
    rightCardNum: '§ virtualbox',
    rightCardTitle: 'Full Isolation',
    rightCardDesc: 'Use VirtualBox for full-scale server simulations. Windows Server 2022 requires a full Type-2 VM to properly simulate Active Directory and network services.'
  }

];