const slideConfigs = [
  // --- 1. COVER SLIDE ---
  {
    type: 'cover',
    moduleTitle: 'MODULE 04 · TOPIC 10',
    topicNum: '10',
    topicTag: 'T10',
    title: 'User, Group<br>& <em>Identity</em> Management',
    subtitle: 'Centralizing authentication and authorization: Deploying Active Directory Domain Services, configuring RBAC in Linux, and auditing system access.',
    graphicText: 'Control <em>Access</em><br>Delegate <em>Authority</em><br>Audit Actions.',
    miniObjectives: [
      'AD DS & Domain Controllers',
      'OU Structure & GPOs',
      'Linux RBAC & PAM',
      'Sudoers & Auditd'
    ]
  },

// --- 2. OBJECTIVES SLIDE ---
  {
    type: 'objectives',
    header: 'MODULE 04 · TOPIC 10',
    kicker: 'ITP 141 · M4 · T10',
    desc: 'Identity is the new perimeter. You will learn to manage users and groups across both Windows AD and Linux, enforce policies, and audit who did what.',
    lede: 'A misconfigured permission is a data breach waiting to happen. Master RBAC and AD to ensure users only have the access they absolutely need.',
    list: [
      'Install AD DS and promote Windows Server 2022 to a domain controller for dorsu.lab.',
      'Design an Organizational Unit (OU) hierarchy for a university IT department.',
      'Create users and groups within Active Directory Users and Computers.',
      'Configure a Group Policy Object (GPO) for Password Policy.',
      'Configure Linux Role-Based Access Control (RBAC) using useradd and groupadd.',
      'Understand Pluggable Authentication Modules (PAM) in Linux.',
      'Configure sudoers with explicit allow and deny rules for privilege escalation.',
      'Configure auditd to log /etc/passwd changes, sudoers edits, and login events.'
    ]
  },

  // --- 3. LESSON SLIDES ---
  // 1. Identity Management Overview
  { type: 'lesson', category: 'Overview', title: 'Identity Management', subtitle: 'The New Perimeter', desc: 'Identity management (IdM) is the process of verifying who a user is (Authentication) and what they can do (Authorization). In modern IT, identity is the primary security boundary, not the network firewall.', syntax: 'Authentication: Who are you? (Passwords, Keys)\nAuthorization: What can you do? (RBAC, GPOs)', term: [{raw: '<span class="out" style="color:#E8A07A">Core Concepts</span><br><span class="out">1. Authentication: Verifying identity (AuthN).</span><br><span class="out">2. Authorization: Granting access rights (AuthZ).</span><br><span class="out">3. Auditing: Recording actions for accountability.</span><br><br><span class="out" style="color:#E8A07A">Dual-OS Reality</span><br><span class="out">Windows uses centralized AD DS for the enterprise.</span><br><span class="out">Linux uses local /etc/passwd and PAM, or joins AD via realmd.</span>'}], explain: '<strong>Explanation:</strong> In this module, we build the identity infrastructure. Windows Server becomes the central authority (AD DS), while Ubuntu is configured with local RBAC and auditing to secure its own resources.' },
  
  // 2. Windows AD: Introduction
  { type: 'lesson', category: 'Windows AD DS', title: 'AD DS: Introduction', subtitle: 'Active Directory', desc: 'Active Directory Domain Services (AD DS) is a centralized database that stores information about network resources (users, computers, printers) and authenticates domain users.', syntax: 'Domain: dorsu.lab\nForest: dorsu.lab\nDC: WIN-SRV-01', term: [{raw: '<span class="out" style="color:#E8A07A">AD Components</span><br><span class="out">1. Domain Controller (DC): Server running AD DS.</span><br><span class="out">2. Domain: Logical group of computers (e.g., dorsu.lab).</span><br><span class="out">3. Forest: Collection of one or more domains sharing trust.</span><br><span class="out">4. NTDS.dit: The actual database file on the DC.</span>'}], explain: '<strong>Explanation:</strong> When a user logs into their Windows 10 PC, the PC sends their credentials to the Domain Controller (DC). The DC checks the NTDS.dit database and issues a Kerberos ticket if the password is correct.' },
  
  // 3. Windows AD: Architecture
  { type: 'lesson', category: 'Windows AD DS', title: 'AD DS: Architecture', subtitle: 'Forests, Trees, Domains', desc: 'AD is hierarchical. A Forest is the top-level security boundary. Inside the forest, Domains represent administrative boundaries. Trusts connect domains.', syntax: 'Forest Root: dorsu.lab\n  -> Domain: dorsu.lab\n     -> OU: Admins\n     -> OU: Developers', term: [{raw: '<span class="out" style="color:#E8A07A">Why a hierarchy?</span><br><span class="out">1. Forest: Defines the security boundary. Admins in Forest A have no access to Forest B.</span><br><span class="out">2. Domain: Defines the replication boundary. DCs in a domain replicate their databases.</span><br><span class="out">3. OU (Org Unit): Defines the Group Policy and delegation boundary.</span>'}], explain: '<strong>Explanation:</strong> For this course, we will build a single-domain forest (dorsu.lab). In enterprise environments, a forest might contain multiple domains like asia.dorsu.lab and us.dorsu.lab, connected by trusts.' },
  
  // 4. Windows AD: Install Role
  { type: 'lesson', category: 'Windows AD DS', title: 'AD DS: Install Role', subtitle: 'PowerShell', desc: 'To create a domain, you first install the AD DS role on the Windows Server. This prepares the server but does not yet promote it to a Domain Controller.', syntax: 'Install-WindowsFeature -Name AD-Domain-Services -IncludeManagementTools', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Install-WindowsFeature -Name AD-Domain-Services -IncludeManagementTools</span><br><br><span class="out">Success Restart Needed Exit Code      Feature Result</span><br><span class="out">------- -------------- ---------      --------------</span><br><span class="out">True    No             Success        {Active Directory Domain Services, Group P...</span><br><br><span class="out">(Installs AD DS, RSAT tools, and Group Policy Management)</span>'}], explain: '<strong>Explanation:</strong> This command installs the binaries required for Active Directory and the management GUI tools (Active Directory Users and Computers). The server must have a static IP and be pointing to itself for DNS before promotion.' },
  
  // 5. Windows AD: Promote to DC
  { type: 'lesson', category: 'Windows AD DS', title: 'AD DS: Promote to DC', subtitle: 'Forest Configuration', desc: 'After installing the role, promote the server to a Domain Controller for a new forest named <code>dorsu.lab</code>.', syntax: 'Install-ADDSForest -DomainName "dorsu.lab" -InstallDNS', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Install-ADDSForest -DomainName "dorsu.lab" -InstallDNS</span><br><br><span class="out">The script will prompt you for Safe Mode Administrator Password:</span><br><span class="out">Type the Directory Services Restore Mode (DSRM) password: ********</span><br><br><span class="out">The server will be configured as a DC and restarted.</span><br><span class="out">After reboot, login as DORSU\\Administrator.</span>'}], explain: '<strong>Explanation:</strong> This command installs the DNS server (crucial for AD), creates the <code>dorsu.lab</code> forest, and reboots the server. The DSRM password is a break-glass password used if AD breaks and you need to restore the database offline.' },
  
  // 6. Windows AD: OUs
  { type: 'lesson', category: 'Windows AD DS', title: 'AD DS: OUs', subtitle: 'Organizational Units', desc: 'Organizational Units (OUs) are containers within a domain used to organize users, computers, and groups for the purpose of delegation and Group Policy application.', syntax: 'New-ADOrganizationalUnit -Name "ITDept" -Path "DC=dorsu,DC=lab"', term: [{raw: '<span class="out" style="color:#E8A07A">Active Directory Users and Computers (ADUC)</span><br><span class="out">dorsu.lab</span><br><span class="out">  |-- Builtin (Default groups)</span><br><span class="out">  |-- Users (Default users)</span><br><span class="out">  |-- Computers (Default computers)</span><br><span class="out">  |-- ITDept (Custom OU)</span><br><span class="out">       |-- Admins</span><br><span class="out">       |-- Developers</span><br><span class="out">       |-- HelpDesk</span>'}], explain: '<strong>Explanation:</strong> OUs are not security boundaries (users in the Admins OU can still access a computer in the Developers OU if permissions allow). They are purely administrative containers. You link Group Policy Objects (GPOs) to OUs.' },
  
  // 7. Windows AD: Create OU Hierarchy
  { type: 'lesson', category: 'Windows AD DS', title: 'AD DS: Create OUs', subtitle: 'PowerShell Script', desc: 'Create the OU hierarchy for the DOrSU IT Department as specified in the syllabus: Admins, Developers, and HelpDesk.', syntax: 'New-ADOrganizationalUnit -Name "Admins" -Path "OU=ITDept,DC=dorsu,DC=lab"\nNew-ADOrganizationalUnit -Name "Developers" -Path "OU=ITDept,DC=dorsu,DC=lab"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> New-ADOrganizationalUnit -Name "ITDept" -Path "DC=dorsu,DC=lab"</span><br><span class="cmd">> New-ADOrganizationalUnit -Name "Admins" -Path "OU=ITDept,DC=dorsu,DC=lab"</span><br><span class="cmd">> New-ADOrganizationalUnit -Name "Developers" -Path "OU=ITDept,DC=dorsu,DC=lab"</span><br><span class="cmd">> New-ADOrganizationalUnit -Name "HelpDesk" -Path "OU=ITDept,DC=dorsu,DC=lab"</span><br><br><span class="out">(OUs are now visible in Active Directory Users and Computers)</span>'}], explain: '<strong>Explanation:</strong> By separating users into different OUs, we can apply different policies. For example, we can give the HelpDesk OU permission to reset passwords, but not to create new Admins. This is called "Delegation of Control".' },
  
  // 8. Windows AD: Create Users
  { type: 'lesson', category: 'Windows AD DS', title: 'AD DS: Create Users', subtitle: 'PowerShell', desc: 'Create user accounts inside the newly created OUs. A user account requires a SamAccountName, UserPrincipalName (UPN), and a password.', syntax: 'New-ADUser -Name "John Doe" -SamAccountName "jdoe" -UserPrincipalName "jdoe@dorsu.lab" -Path "OU=Developers,OU=ITDept,DC=dorsu,DC=lab"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> $pwd = ConvertTo-SecureString "P@ssw0rd123!" -AsPlainText -Force</span><br><span class="cmd">> New-ADUser -Name "John Doe" -SamAccountName "jdoe" -Path "OU=Developers,OU=ITDept,DC=dorsu,DC=lab" -AccountPassword $pwd -Enabled $true</span><br><span class="out">(User created in the Developers OU)</span><br><br><span class="cmd">> New-ADUser -Name "Jane Smith" -SamAccountName "jsmith" -Path "OU=Admins,OU=ITDept,DC=dorsu,DC=lab" -AccountPassword $pwd -Enabled $true</span><br><span class="out">(User created in the Admins OU)</span>'}], explain: '<strong>Explanation:</strong> PowerShell requires the password to be a SecureString object, not plain text. The <code>-Path</code> parameter places the user into the specific OU. <code>-Enabled $true</code> activates the account immediately.' },
  
  // 9. Windows AD: Create Groups
  { type: 'lesson', category: 'Windows AD DS', title: 'AD DS: Create Groups', subtitle: 'Security Groups', desc: 'Groups are used to assign permissions to resources. It is easier to grant access to a "Developers" group than to 50 individual user accounts.', syntax: 'New-ADGroup -Name "Developers" -GroupScope Global -Path "OU=Developers,OU=ITDept,DC=dorsu,DC=lab"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> New-ADGroup -Name "Developers" -GroupScope Global -Path "OU=Developers,OU=ITDept,DC=dorsu,DC=lab"</span><br><span class="out">Group created successfully.</span><br><br><span class="cmd">> Add-ADGroupMember -Identity "Developers" -Members "jdoe"</span><br><span class="out">(John Doe is now a member of the Developers group)</span>'}], explain: '<strong>Explanation:</strong> In AD, use Global Groups for grouping users with similar access needs. You then add the Global Group to a resource\'s Access Control List (ACL). This is known as AGDLP (Account -> Global Group -> Domain Local Group -> Permission).' },
  
  // 10. Windows AD: GPOs
  { type: 'lesson', category: 'Windows AD DS', title: 'AD DS: GPOs', subtitle: 'Group Policy Objects', desc: 'A Group Policy Object (GPO) is a virtual collection of policy settings. When linked to an OU, it enforces configuration (like password length) on all users and computers in that OU.', syntax: 'New-GPO -Name "PasswordPolicy" -Comment "Enforce 12 char passwords"\nNew-GPLink -Name "PasswordPolicy" -Target "OU=Developers,OU=ITDept,DC=dorsu,DC=lab"', term: [{raw: '<span class="out" style="color:#E8A07A">Group Policy Management</span><br><span class="out">Domain: dorsu.lab</span><br><span class="out">  |-- OUs</span><br><span class="out">       |-- ITDept</span><br><span class="out">            |-- Admins (Linked: Default Domain Policy)</span><br><span class="out">            |-- Developers (Linked: PasswordPolicy GPO)</span><br><span class="out">            |-- HelpDesk (Linked: Default Domain Policy)</span><br><br><span class="out" style="color:#E8A07A">Result:</span><br><span class="out">Developers must use 12+ char passwords. Admins use 8+.</span>'}], explain: '<strong>Explanation:</strong> GPOs apply settings automatically. If a user is moved from the Admins OU to the Developers OU, their password policy changes instantly because the GPO linked to their new OU takes precedence.' },
  
  // 11. Windows AD: Password Policy GPO
  { type: 'lesson', category: 'Windows AD DS', title: 'AD DS: Password GPO', subtitle: 'Settings', desc: 'Configure the Password Policy GPO to require 12 characters, complexity, and a 30-day maximum age for the Developers OU.', syntax: '# In Group Policy Management Console:\nComputer Configuration -> Policies -> Windows Settings -> Security Settings -> Account Policies -> Password Policy', term: [{raw: '<span class="out" style="color:#E8A07A">Password Policy Settings (Developers GPO)</span><br><span class="out">Enforce password history: 24 passwords remembered</span><br><span class="out">Maximum password age: 30 days</span><br><span class="out">Minimum password age: 1 day</span><br><span class="out">Minimum password length: 12 characters</span><br><span class="out">Password must meet complexity requirements: Enabled</span><br><span class="out">Store passwords using reversible encryption: Disabled</span>'}], explain: '<strong>Explanation:</strong> Complexity requires at least 3 of the following: uppercase, lowercase, numbers, symbols. Reversible encryption should always be disabled unless an application specifically requires it (rare).' },
  
  // 12. Windows AD: RBAC in AD
  { type: 'lesson', category: 'Windows AD DS', title: 'AD DS: RBAC', subtitle: 'Role-Based Access Control', desc: 'RBAC in AD is implemented by mapping job titles to security groups, and giving those groups permissions to resources (file shares, printers, servers).', syntax: 'Role -> AD Group -> Resource Permission', term: [{raw: '<span class="out" style="color:#E8A07A">Example: HelpDesk RBAC</span><br><span class="out">1. Role: IT Support Staff</span><br><span class="out">2. AD Group: HelpDesk_Group</span><br><span class="out">3. Delegation: "Reset User Passwords" on the Users OU.</span><br><br><span class="out" style="color:#E8A07A">Delegation of Control Wizard</span><br><span class="out">Right-click OU -> Delegate Control -> Select HelpDesk_Group -> Create Custom Task -> Reset Password.</span>'}], explain: '<strong>Explanation:</strong> Instead of making HelpDesk staff Domain Admins (a huge security risk), we delegate a specific task (password resets) to their group. They gain the ability to unlock accounts without gaining control of the whole server.' },
  
  // 13. Linux Identity: Local Users
  { type: 'lesson', category: 'Linux Identity', title: 'Linux: Local Users', subtitle: 'Authentication Files', desc: 'Linux stores user account information in plain text files. <code>/etc/passwd</code> holds account info, and <code>/etc/shadow</code> holds the actual password hashes.', syntax: 'cat /etc/passwd\ncat /etc/shadow', term: [{raw: '<span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">cat /etc/passwd</span><br><span class="out">ajsacay:x:1000:1000:Ar-Jay,,,:/home/ajsacay:/bin/bash</span><br><br><span class="out" style="color:#E8A07A">Format:</span><br><span class="out">username : password(x) : UID : GID : GECOS : Home : Shell</span><br><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo cat /etc/shadow</span><br><span class="out">ajsacay:$6$hashstring...:19000:0:99999:7:::</span><br><br><span class="out" style="color:#E8A07A">Format:</span><br><span class="out">username : hash : daysincechange : min : max : warn : inactive : expire</span>'}], explain: '<strong>Explanation:</strong> The <code>x</code> in /etc/passwd means the password is stored in /etc/shadow. /etc/shadow is only readable by root, protecting the hashes from offline cracking attacks. UID 1000+ are standard users; UID 0 is root.' },
  
  // 14. Linux Identity: /etc/shadow
  { type: 'lesson', category: 'Linux Identity', title: 'Linux: /etc/shadow', subtitle: 'Password Hashing', desc: 'The /etc/shadow file stores password hashes securely. Only the root user can read it, preventing regular users from copying hashes for offline cracking.', syntax: 'sudo cat /etc/shadow | grep ajsacay\n# Hash format: $Algorithm$Salt$Hash', term: [{raw: '<span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo cat /etc/shadow | grep ajsacay</span><br><span class="out">ajsacay:$6$rounds=5000$abcdefg$hijklmnop...:19000:0:99999:7:::</span><br><br><span class="out" style="color:#E8A07A">Hash Algorithms ($ID)</span><br><span class="out">$1$ = MD5 (Insecure, do not use)</span><br><span class="out">$5$ = SHA-256 (Standard)</span><br><span class="out">$6$ = SHA-512 (Most secure, default on Ubuntu)</span><br><span class="out">$y$ = YesCrypt (Newer, highly resistant to GPU cracking)</span>'}], explain: '<strong>Explanation:</strong> When a user types their password, PAM hashes it using the algorithm defined in /etc/pam.d/common-password and compares it to the hash in /etc/shadow. Storing hashes (not plain text) means a stolen shadow file still takes billions of guesses to crack.' },
  
  // 15. Linux Identity: useradd
  { type: 'lesson', category: 'Linux Identity', title: 'Linux: useradd', subtitle: 'Creating Users', desc: 'The <code>useradd</code> command creates new user accounts. The <code>-m</code> flag creates the home directory, and <code>-s</code> sets the login shell.', syntax: 'sudo useradd -m -s /bin/bash dev_user', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo useradd -m -s /bin/bash dev_user</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo passwd dev_user</span><br><span class="out">New password: </span><br><span class="out">Retype new password: </span><br><span class="out">passwd: password updated successfully</span><br><br><span class="out" style="color:#E8A07A">Flags used:</span><br><span class="out">-m: Create /home/dev_user</span><br><span class="out">-s: Set shell to bash (default is often sh)</span>'}], explain: '<strong>Explanation:</strong> <code>useradd</code> creates the account and adds it to /etc/passwd, but does NOT prompt for a password. You must run <code>passwd username</code> separately to set the password and unlock the account. <code>adduser</code> is a friendlier wrapper script that does both.' },
  
  // 16. Linux Identity: usermod
  { type: 'lesson', category: 'Linux Identity', title: 'Linux: usermod', subtitle: 'Modifying Users', desc: 'The <code>usermod</code> command modifies existing user accounts, such as adding them to groups or changing their shell.', syntax: 'sudo usermod -aG sudo dev_user', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo usermod -aG docker dev_user</span><br><span class="out">(Adds dev_user to the docker group)</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">groups dev_user</span><br><span class="out">dev_user : dev_user docker</span><br><br><span class="out" style="color:#E8A07A">Important Flag:</span><br><span class="out">-a (append): MUST be used with -G. Otherwise, the user is removed from all other secondary groups.</span>'}], explain: '<strong>Explanation:</strong> The <code>-aG</code> flags are critical. If you just use <code>-G</code>, you overwrite the user\'s group membership list. If they were in the sudo group, running <code>usermod -G docker dev_user</code> would remove them from sudo. Always use <code>-aG</code> to append.' },
  
  // 17. Linux Identity: groupadd
  { type: 'lesson', category: 'Linux Identity', title: 'Linux: groupadd', subtitle: 'Creating Groups', desc: 'Groups in Linux are used to organize users who share access to the same files or services. Use <code>groupadd</code> to create a new group.', syntax: 'sudo groupadd developers\nsudo usermod -aG developers dev_user', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo groupadd developers</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo usermod -aG developers dev_user</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">cat /etc/group | grep developers</span><br><span class="out">developers:x:1002:dev_user</span><br><br><span class="out" style="color:#E8A07A">Format:</span><br><span class="out">group_name : password(x) : GID : member_list</span>'}], explain: '<strong>Explanation:</strong> By adding a user to a group, they inherit the group\'s permissions. If a directory is owned by the <code>developers</code> group, any member of that group can read and write to it. This is the core of Linux RBAC.' },
  
  // 18. Linux Identity: RBAC
  { type: 'lesson', category: 'Linux Identity', title: 'Linux: RBAC', subtitle: 'Role-Based Access Control', desc: 'RBAC in Linux is implemented by creating groups that represent roles (e.g., db_admins, web_admins) and setting file permissions (chown, chmod) for those groups.', syntax: 'sudo mkdir /var/www/dev\nsudo chown :developers /var/www/dev\nsudo chmod 775 /var/www/dev', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo mkdir /var/www/dev</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo chown :developers /var/www/dev</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo chmod 775 /var/www/dev</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ls -ld /var/www/dev</span><br><span class="out">drwxrwxr-x 2 root developers 4096 Oct 24 10:00 /var/www/dev</span><br><br><span class="out" style="color:#E8A07A">Result:</span><br><span class="out">Owner (root): rwx (7)</span><br><span class="out">Group (developers): rwx (7) -> Role-Based Access</span><br><span class="out">Others: r-x (5)</span>'}], explain: '<strong>Explanation:</strong> By changing the group ownership of the directory to <code>developers</code> and giving the group write access (775), any user in the <code>developers</code> group can now edit files in that folder without needing sudo.' },
  
  // 19. Linux Identity: PAM Introduction
  { type: 'lesson', category: 'Linux Identity', title: 'Linux: PAM', subtitle: 'Pluggable Auth Modules', desc: 'PAM is a suite of shared libraries that enable the local system administrator to choose how applications authenticate users. It decouples applications from authentication logic.', syntax: '/etc/pam.d/', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ls /etc/pam.d/</span><br><span class="out">common-auth  common-password  login  sudo  sshd  su</span><br><br><span class="out" style="color:#E8A07A">How PAM Works</span><br><span class="out">1. User runs a command (e.g., sudo apt update).</span><br><span class="out">2. Sudo reads /etc/pam.d/sudo.</span><br><span class="out">3. PAM checks /etc/shadow via common-auth.</span><br><span class="out">4. PAM enforces rules (e.g., password complexity via common-password).</span>'}], explain: '<strong>Explanation:</strong> Historically, every program (login, ssh, su) had its own hardcoded authentication. PAM standardized this. If you want to enforce passwords must be 12 chars long, you edit <code>/etc/pam.d/common-password</code> once, and it applies to all programs that use PAM.' },
  
  // 20. Linux Identity: PAM Config
  { type: 'lesson', category: 'Linux Identity', title: 'Linux: PAM Config', subtitle: 'Password Complexity', desc: 'Configure PAM to enforce password complexity using the <code>pam_pwquality.so</code> module in <code>/etc/pam.d/common-password</code>.', syntax: 'sudo apt install libpam-pwquality\nsudo nano /etc/pam.d/common-password', term: [{editor: "/etc/pam.d/common-password", code: "# Enforce password complexity on Linux\npassword requisite pam_pwquality.so retry=3 minlen=12 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1\npassword [success=1 default=ignore] pam_unix.so obscure sha512"}, {raw: '<span class="out" style="color:#E8A07A">PAM Rules Explained</span><br><span class="out">retry=3: Allow 3 attempts before failing.</span><br><span class="out">minlen=12: Minimum length 12 chars.</span><br><span class="out">ucredit=-1: Require at least 1 uppercase.</span><br><span class="out">lcredit=-1: Require at least 1 lowercase.</span><br><span class="out">dcredit=-1: Require at least 1 digit.</span><br><span class="out">ocredit=-1: Require at least 1 symbol.</span>'}], explain: '<strong>Explanation:</strong> The negative numbers (<code>-1</code>) mean "require at least one of this type". If you put <code>1</code>, it means "give credit for having one, but don\'t require it". <code>obscure</code> checks if the new password is too similar to the old one. <code>sha512</code> sets the hashing algorithm.' },
  
  // 21. Linux Privilege: sudo vs su
  { type: 'lesson', category: 'Linux Privilege', title: 'sudo vs su', subtitle: 'Privilege Escalation', desc: '<code>su</code> switches the user entirely (you must know root\'s password). <code>sudo</code> runs a single command as root (you enter your own password).', syntax: 'sudo apt update\nsu -', term: [{raw: '<span class="out" style="color:#E8A07A">Comparison</span><br><br><span class="out">sudo apt update</span><br><span class="out">- Prompts for YOUR password.</span><br><span class="out">- Runs only one command as root.</span><br><span class="out">- Logged in /var/log/auth.log as YOUR user.</span><br><br><span class="out">su -</span><br><span class="out">- Prompts for ROOT\'s password.</span><br><br><span class="out">su - ajsacay</span><br><span class="out">- Prompts for ROOT\'s password (to switch to ajsacay).</span><br><br><span class="out" style="color:#E8A07A">Best Practice</span><br><span class="out">Disable root login via SSH. Force everyone to use sudo.</span>'}], explain: '<strong>Explanation:</strong> If 5 admins use <code>su</code>, they all share the root password. If one is fired, you must change the password and tell everyone. If 5 admins use <code>sudo</code>, they use their own passwords. If one is fired, you just delete their user account.' },
  
  // 22. Linux Privilege: /etc/sudoers
  { type: 'lesson', category: 'Linux Privilege', title: 'Linux: /etc/sudoers', subtitle: 'The Sudoers File', desc: 'The <code>/etc/sudoers</code> file controls who can run what commands as root. It is highly sensitive and must only be edited using the <code>visudo</code> command.', syntax: 'sudo visudo', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo visudo</span><br><br><span class="out" style="color:#E8A07A">Why visudo?</span><br><span class="out">visudo checks the syntax of the file before saving. If you edit /etc/sudoers with nano and make a typo, you could lock yourself out of root access permanently. visudo prevents this.</span>'}], explain: '<strong>Explanation:</strong> Never use <code>nano /etc/sudoers</code>. A syntax error in this file can break sudo entirely. <code>visudo</code> locks the file so two admins cannot edit it simultaneously, and it validates the syntax before applying the changes.' },
  
  // 23. Linux Privilege: Sudoers Allow
  { type: 'lesson', category: 'Linux Privilege', title: 'Linux: Sudoers Allow', subtitle: 'Granting Access', desc: 'Grant a user or group permission to run specific commands. The syntax is: <code>who where=(as_whom) what</code>.', syntax: '# Allow dev_user to restart nginx\ndev_user ALL=(ALL) /bin/systemctl restart nginx', term: [{editor: "/etc/sudoers", code: "# User privilege specification\nroot    ALL=(ALL:ALL) ALL\n\n# Members of the sudo group may run any command\n%sudo   ALL=(ALL:ALL) ALL\n\n# Custom RBAC rules\n# Allow dev_user to restart nginx without password\ndev_user ALL=(ALL) NOPASSWD: /bin/systemctl restart nginx\n\n# Allow developers group to run docker\n%developers ALL=(ALL) /usr/bin/docker"}, {raw: '<span class="out" style="color:#E8A07A">Syntax Breakdown</span><br><span class="out">dev_user: The user or %group</span><br><span class="out">ALL: From any terminal/host</span><br><span class="out">(ALL): Can run as any user (default root)</span><br><span class="out">NOPASSWD: No password required</span><br><span class="out">/bin/systemctl...: Exact absolute path of allowed command</span>'}], explain: '<strong>Explanation:</strong> By specifying the exact path (<code>/bin/systemctl restart nginx</code>), <code>dev_user</code> can run that specific command but cannot run <code>systemctl stop nginx</code>. This is granular RBAC for privilege escalation.' },
  
  // 24. Linux Privilege: Sudoers Deny
  { type: 'lesson', category: 'Linux Privilege', title: 'Linux: Sudoers Deny', subtitle: 'Restricting Access', desc: 'You can explicitly deny commands. In sudoers, the last match wins. So an allow rule followed by a deny rule will block the command.', syntax: '# Deny dev_user from using apt\ndev_user ALL=(ALL) ALL, !/usr/bin/apt, !/usr/bin/apt-get', term: [{editor: "/etc/sudoers", code: "# Give dev_user general sudo, but DENY apt access\n# This prevents them from installing unapproved software.\ndev_user ALL=(ALL) ALL, !/usr/bin/apt, !/usr/bin/apt-get, !/usr/bin/dpkg\n\n# Deny helpdesk from shutting down the server\n%helpdesk ALL=(ALL) ALL, !/sbin/shutdown, !/sbin/poweroff, !/sbin/reboot"}, {raw: '<span class="out" style="color:#E8A07A">The Exclamation Mark (!)</span><br><span class="out">! means NOT. It explicitly denies the command.</span><br><span class="out">Since sudoers parses top-to-bottom and the LAST match wins,</span><br><span class="out">if you allow ALL and then deny apt, apt is blocked.</span><br><br><span class="out" style="color:#E8A07A">Testing the Deny Rule</span><br><span class="prompt"><span class="user">dev_user@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt update</span><br><span class="err">Sorry, user dev_user is not allowed to execute /usr/bin/apt update as root.</span>'}], explain: '<strong>Explanation:</strong> This is highly useful for junior admins. You can give them broad sudo access for their daily tasks but explicitly deny dangerous commands like <code>rm -rf /</code> or <code>shutdown</code>. This provides a safety net while allowing them to work.' },
  
  // 25. Linux Privilege: sudoers.d
  { type: 'lesson', category: 'Linux Privilege', title: 'Linux: sudoers.d', subtitle: 'Drop-in Directory', desc: 'Instead of editing the main <code>/etc/sudoers</code> file, best practice is to create separate files in <code>/etc/sudoers.d/</code>.', syntax: 'sudo visudo -f /etc/sudoers.d/developers', term: [{editor: "/etc/sudoers.d/developers", code: "# RBAC file for the developers group\n# Place in /etc/sudoers.d/developers\n\n# Allow developers to manage docker containers\n%developers ALL=(ALL) /usr/bin/docker"}, {raw: '<span class="out" style="color:#E8A07A">Why use sudoers.d?</span><br><span class="out">1. Modularity: One file per group/role.</span><br><span class="out">2. Safety: If a file has a syntax error, only that file fails. The main sudoers still works.</span><br><span class="out">3. Automation: Ansible/Puppet can drop a file here without parsing the main config.</span><br><br><span class="out" style="color:#E8A07A">Important Rule:</span><br><span class="out">Do NOT use dots (.) in the filename. sudo ignores files with dots in sudoers.d. Name it developers not developers.conf.</span>'}], explain: '<strong>Explanation:</strong> The main <code>/etc/sudoers</code> file includes a line at the bottom: <code>@includedir /etc/sudoers.d</code>. Any valid file placed in that directory is read as part of the sudo policy. This keeps the main file clean and makes auditing roles much easier.' },
  
  // 26. Linux Auditing: auditd Intro
  { type: 'lesson', category: 'Linux Auditing', title: 'Linux: auditd Intro', subtitle: 'System Auditing', desc: '<code>auditd</code> is the Linux audit daemon. It logs system calls (file access, permission changes, logins) to a secure, tamper-proof log file for compliance and forensics.', syntax: 'sudo apt install auditd\nsudo systemctl status auditd', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt install auditd -y</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl status auditd</span><br><span class="out">● auditd.service - Security Auditing Service</span><br><span class="out">     Active: active (running) since Wed 2024-10-24 10:00:00 PST</span><br><br><span class="out" style="color:#E8A07A">Why auditd?</span><br><span class="out">Standard logs (syslog) only show app errors. auditd shows who accessed a file at exactly what time, even if they did not make changes.</span>'}], explain: '<strong>Explanation:</strong> If a sensitive file like <code>/etc/passwd</code> is read by a script, <code>syslog</code> will not record it. <code>auditd</code> hooks into the kernel and logs every <code>open()</code> or <code>read()</code> system call, providing deep forensic visibility required for security standards like CIS and NIST.' },
  
  // 27. Linux Auditing: Watch /etc/passwd
  { type: 'lesson', category: 'Linux Auditing', title: 'Audit: Watch /etc/passwd', subtitle: 'auditctl -w', desc: 'Use <code>auditctl</code> to watch the <code>/etc/passwd</code> file. The <code>-p wa</code> flag watches for write (w) and attribute (a) changes.', syntax: 'sudo auditctl -w /etc/passwd -p wa -k passwd_changes', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo auditctl -w /etc/passwd -p wa -k passwd_changes</span><br><br><span class="out" style="color:#E8A07A">Command Breakdown</span><br><span class="out">-w /etc/passwd: Watch this file path.</span><br><span class="out">-p wa: Trigger on Write (w) or Attribute (a) changes.</span><br><span class="out">-k passwd_changes: Tag this event with the key passwd_changes.</span><br><br><span class="out" style="color:#E8A07A">Test the Rule</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo useradd testuser</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ausearch -k passwd_changes</span>'}], explain: '<strong>Explanation:</strong> The <code>-k</code> flag assigns a key (like a label) to this watch rule. When you search the logs later with <code>ausearch -k passwd_changes</code>, it will instantly show who ran <code>useradd</code> or <code>usermod</code> and exactly when they did it.' },
  
  // 28. Linux Auditing: Watch Sudoers
  { type: 'lesson', category: 'Linux Auditing', title: 'Audit: Watch Sudoers', subtitle: 'Protecting Privilege', desc: 'Monitor the <code>/etc/sudoers</code> file and the <code>/etc/sudoers.d/</code> directory to catch unauthorized privilege escalations.', syntax: 'sudo auditctl -w /etc/sudoers -p wa -k sudoers_changes\nsudo auditctl -w /etc/sudoers.d/ -p wa -k sudoers_changes', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo auditctl -w /etc/sudoers -p wa -k sudoers_changes</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo auditctl -w /etc/sudoers.d/ -p wa -k sudoers_changes</span><br><br><span class="out" style="color:#E8A07A">Making Rules Permanent</span><br><span class="out">auditctl rules are lost on reboot. To make them permanent, add them to /etc/audit/rules.d/audit.rules</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">echo "-w /etc/sudoers -p wa -k sudoers_changes" | sudo tee -a /etc/audit/rules.d/audit.rules</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl restart auditd</span>'}], explain: '<strong>Explanation:</strong> If an attacker gets root access, they will try to add a backdoor to <code>sudoers</code>. By watching this file, any modification triggers an immediate log entry. Moving the rules to <code>/etc/audit/rules.d/</code> ensures the monitoring survives a server reboot.' },
  
  // 29. Linux Auditing: Watch Logins
  { type: 'lesson', category: 'Linux Auditing', title: 'Audit: Watch Logins', subtitle: 'login &; sshd', desc: 'Monitor user logins and failures. While syslog tracks successful SSH logins, auditd can track the execution of the login binary itself.', syntax: 'sudo auditctl -w /var/log/faillog -p wa -k logins\nsudo auditctl -w /var/log/lastlog -p wa -k logins', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo auditctl -w /var/log/faillog -p wa -k logins</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo auditctl -w /var/log/lastlog -p wa -k logins</span><br><br><span class="out" style="color:#E8A07A">Standard Linux Login Logs</span><br><span class="out">last: Shows successful login history (reads /var/log/wtmp)</span><br><span class="out">lastb: Shows failed login attempts (reads /var/log/btmp)</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">last -n 5</span><br><span class="out">ajsacay pts/0 192.168.1.50 Wed Oct 24 10:15 still logged in</span>'}], explain: '<strong>Explanation:</strong> Watching <code>faillog</code> and <code>lastlog</code> ensures that any update to these files (which happens when a user logs in or fails to log in) is recorded in the audit trail. Combined with <code>last</code> and <code>journalctl</code>, this provides a complete picture of login activity.' },
  
  // 30. Linux Auditing: ausearch
  { type: 'lesson', category: 'Linux Auditing', title: 'Audit: ausearch', subtitle: 'Querying Logs', desc: 'The <code>ausearch</code> command queries the audit daemon logs. You can search by key, user, file, or time.', syntax: 'sudo ausearch -k passwd_changes\nsudo ausearch -m USER_LOGIN -ts today', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ausearch -k passwd_changes</span><br><span class="out">----</span><br><span class="out">time->Wed Oct 24 10:20:01 2024</span><br><span class="out">type=PROCTITLE msg=audit(1729767601.123:45): proctitle=useradd testuser</span><br><span class="out">type=PATH msg=audit(1729767601.123:45): item=0 name=/etc/passwd inode=12345 dev=08:01 mode=0100644</span><br><span class="out">type=SYSCALL msg=audit(1729767601.123:45): arch=c000003e syscall=2 success=yes auid=1000 uid=0 gid=0 euid=0</span><br><br><span class="out" style="color:#E8A07A">Reading the output:</span><br><span class="out">- auid=1000: The admin who ran the command (ajsacay).</span><br><span class="out">- uid=0: The command ran as root (via sudo).</span><br><span class="out">- proctitle: The exact command run.</span>'}], explain: '<strong>Explanation:</strong> <code>ausearch</code> formats the raw audit log into a readable structure. The <code>auid</code> (Audit UID) is highly important: it records the original user who logged in, even if they used <code>sudo su -</code> to switch to root. The <code>auid</code> cannot be spoofed.' },
  
  // 31. Linux Auditing: aureport
  { type: 'lesson', category: 'Linux Auditing', title: 'Audit: aureport', subtitle: 'Summary Reports', desc: 'Instead of scrolling through logs, use <code>aureport</code> to generate summary reports of system activity, logins, and failures.', syntax: 'sudo aureport --summary\nsudo aureport --failed', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo aureport --summary</span><br><span class="out">Range of time in audit log: 10/01/2024 10:00:00 - 10/24/2024 10:15:00</span><br><span class="out">Number of changes in configuration: 15</span><br><span class="out">Number of changes to accounts, groups, or roles: 8</span><br><span class="out">Number of logins: 12</span><br><span class="out">Number of failed logins: 3</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo aureport --failed</span><br><span class="out">Failed Login Report</span><br><span class="out">1. 10/24/2024 10:05 ajsacay ssh 192.168.1.50</span>'}], explain: '<strong>Explanation:</strong> <code>aureport</code> is the sysadmin\'s dashboard for audits. <code>--summary</code> gives a quick health check. <code>--failed</code> isolates only the failed events (like denied sudo attempts or failed logins), which are usually the most important for security investigation.' },
  
  // 32. Windows Auditing: Event Viewer
  { type: 'lesson', category: 'Windows Auditing', title: 'Windows: Event Viewer', subtitle: 'Security Logs', desc: 'To track who logged in or who changed a file in Windows, you must enable Audit Policy in Group Policy, then view the logs in Event Viewer.', syntax: 'GPO -> Computer Configuration -> Windows Settings -> Security Settings -> Advanced Audit Policy Configuration', term: [{raw: '<span class="out" style="color:#E8A07A">Enable Auditing</span><br><span class="out">Audit Logon: Success, Failure</span><br><span class="out">Audit Account Management: Success</span><br><br><span class="out" style="color:#E8A07A">View Logs in Event Viewer (eventvwr.msc)</span><br><span class="out">Windows Logs -> Security</span><br><br><span class="out" style="color:#E8A07A">Key Event IDs</span><br><span class="out">4624: Successful Logon</span><br><span class="out">4625: Failed Logon (Brute Force)</span><br><span class="out">4720: User Account Created</span><br><span class="out">4724: User Password Reset</span>'}], explain: '<strong>Explanation:</strong> By default, Windows only logs failed logons. To track account creation (Event 4720), you must enable "Audit Account Management". Event ID 4625 is the most important for detecting brute-force attacks against Remote Desktop (RDP).' },
  
  // 33. Windows Auditing: Key Event IDs
  { type: 'lesson', category: 'Windows Auditing', title: 'Windows: Key Event IDs', subtitle: 'Security Monitoring', desc: 'Knowing the key Security Event IDs allows sysadmins to quickly filter the Event Viewer for attacks and administrative changes.', syntax: 'Get-EventLog -LogName Security -InstanceId 4720', term: [{raw: '<span class="out" style="color:#E8A07A">Critical Security Event IDs</span><br><br><span class="out">4624: Successful Logon (Who logged in?)</span><br><span class="out">4625: Failed Logon (Brute force attack?)</span><br><span class="out">4720: User Account Created (New admin?)</span><br><span class="out">4722: User Account Enabled</span><br><span class="out">4724: User Password Reset</span><br><span class="out">4732: Member Added to Security Group (Privilege escalation)</span><br><span class="out">4728: Member Added to Global Group</span><br><br><span class="out" style="color:#E8A07A">PowerShell Query</span><br><span class="cmd">> Get-EventLog -LogName Security -InstanceId 4720 -Newest 5</span>'}], explain: '<strong>Explanation:</strong> Event 4732 is a major red flag. If a standard user is added to the "Domain Admins" group, Event 4732 fires. Monitoring this event is how you detect attackers who have compromised an account and are trying to escalate their privileges.' },
  
  // 34. Hybrid Identity: Joining Linux to AD
  { type: 'lesson', category: 'Hybrid Identity', title: 'Hybrid: Linux to AD', subtitle: 'realmd &; SSSD', desc: 'In a hybrid environment, you can join the Ubuntu Server to the Windows AD domain. This allows users to SSH into Linux using their AD credentials.', syntax: 'sudo apt install realmd sssd sssd-tools\nsudo realm join dorsu.lab -U Administrator', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt install realmd sssd sssd-tools -y</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo realm join dorsu.lab -U Administrator</span><br><span class="out">Password for Administrator:</span><br><span class="out">Successfully joined dorsu.lab</span><br><br><span class="out" style="color:#E8A07A">Result</span><br><span class="out">You can now SSH as: ssh jdoe@dorsu.lab@192.168.1.20</span><br><span class="out">SSSD caches the AD credentials, so Linux still works if the DC goes offline.</span>'}], explain: '<strong>Explanation:</strong> <code>realmd</code> discovers the AD domain and configures <code>sssd</code> (System Security Services Daemon). SSSD handles the communication with the Domain Controller. This provides single sign-on (SSO) across both OSes.' },
  
  // 35. Hybrid Identity: SSSD Config
  { type: 'lesson', category: 'Hybrid Identity', title: 'Hybrid: SSSD Config', subtitle: '/etc/sssd/sssd.conf', desc: 'SSSD requires a configuration file to know which domain to query and how to map AD users to Linux users.', syntax: 'sudo nano /etc/sssd/sssd.conf\nsudo systemctl restart sssd', term: [{editor: "/etc/sssd/sssd.conf", code: "[sssd]\ndomains = dorsu.lab\nconfig_file_version = 2\nservices = nss, pam\n\n[domain/dorsu.lab]\nid_provider = ad\nauth_provider = ad\naccess_provider = ad\ncache_credentials = true\nuse_fully_qualified_names = false"}, {raw: '<span class="out" style="color:#E8A07A">Key Settings</span><br><span class="out">id_provider: ad (Active Directory)</span><br><span class="out">auth_provider: ad (Authenticate via AD)</span><br><span class="out">cache_credentials: true (Allows offline login if DC is down)</span><br><span class="out">use_fully_qualified_names: false (Login as jdoe, not jdoe@dorsu.lab)</span>'}], explain: '<strong>Explanation:</strong> The sssd.conf file must have permissions set to 600 (read/write for root only) or sssd will refuse to start. Once configured, Linux uses PAM to pass login requests to SSSD, which queries AD.' },
  
  // 36. Windows vs Linux: Identity Comparison
  { type: 'lesson', category: 'Summary', title: 'Windows vs Linux', subtitle: 'Identity Comparison', desc: 'Compare the tools and concepts used for identity management across both operating systems.', syntax: 'Windows: AD DS, GPOs, Event Viewer\nLinux: /etc/passwd, PAM, auditd', term: [{raw: '<span class="out" style="color:#E8A07A">Feature Comparison</span><br><span class="out">1. Directory: AD (NTDS.dit) vs /etc/passwd (flat file)</span><br><span class="out">2. Hierarchy: OUs vs Groups</span><br><span class="out">3. Policy: GPOs vs PAM (pam.d/*)</span><br><span class="out">4. Privilege: Domain Admins vs sudoers</span><br><span class="out">5. Auditing: Event Viewer (Security) vs auditd (ausearch)</span><br><span class="out">6. Centralization: AD is centralized; Linux is local unless using realmd/SSSD to join AD.</span>'}], explain: '<strong>Explanation:</strong> Windows is designed for centralization from the start. Linux is designed for independence but can join AD via <code>realmd</code>. In hybrid environments, sysadmins often configure Linux to authenticate against AD so users have one password for both OSes.' },
  
  // 37. Topic Summary
  { type: 'lesson', category: 'Summary', title: 'Topic Summary', subtitle: 'Module 4 Complete', desc: 'You have built the identity infrastructure: a central AD domain for Windows, local RBAC and sudoers for Linux, and auditing configured to catch unauthorized access.', syntax: 'New-ADUser\ndev_user ALL=(ALL) /usr/bin/docker\nsudo auditctl -w /etc/passwd -p wa -k passwd_changes', term: [{raw: '<span class="out" style="color:#E8A07A">Module 4 Checklist:</span><br>[x] AD DS installed and promoted to DC (dorsu.lab)<br>[x] OU Hierarchy created (Admins, Devs, HelpDesk)<br>[x] GPO linked for Password Policy<br>[x] Linux RBAC configured (useradd, groupadd, chmod)<br>[x] PAM configured for password complexity<br>[x] Sudoers allow/deny rules tested<br>[x] Auditd watching /etc/passwd, sudoers, and logins<br><br><span class="out">Next: We will move to Storage, File Systems, and Backup.</span>'}], explain: '<strong>Explanation:</strong> Identity is the foundation of security. By organizing users into OUs/Groups and enforcing least-privilege via GPOs and sudoers, you ensure users only have the access they need. Auditd provides the forensic trail to prove compliance.' },

  // --- 4. CLOSING SLIDE ---
  {
    type: 'closing',
    header: 'MODULE 04 · TOPIC 10',
    tag: 'End of Topic 10',
    title: 'Identity is the <em>Perimeter</em>.',
    quote: 'Trust, but verify. Give users the permissions they need to do their jobs, and use auditd to verify they don\'t abuse them.',
    leftCardNum: '§ windows',
    leftCardTitle: 'AD DS & GPOs',
    leftCardDesc: 'Active Directory centralizes Windows identity. OUs organize objects, and GPOs enforce security policies across the domain.',
    middleCardNum: '§ linux',
    middleCardTitle: 'RBAC & Auditd',
    middleCardDesc: 'Linux relies on flat files and PAM for authentication. RBAC restricts access, and auditd gives you the forensic trail needed for accountability.',
    rightCardNum: '§ trust',
    rightCardTitle: 'Least Privilege',
    rightCardDesc: 'Give users only the permissions they need, review that access regularly, and let the logs prove who changed what.'
  }
];