const slideConfigs = [
  // --- 1. COVER SLIDE ---
  {
    type: 'cover',
    moduleTitle: 'MODULE 01 · TOPIC 01 · WEEK 01–02',
    topicNum: '01',
    topicTag: 'T1',
    title: 'Foundations of <em>System</em><br>Administration',
    subtitle: 'The discipline of keeping computers useful: the roles, the lifecycle, the command line, and the operating system that runs most of the world\'s servers — Linux.',
    graphicText: 'From the <em>shell prompt</em><br>to the filesystem tree —<br>where administration begins.',
    miniObjectives: [
      'Describe the sysadmin role & lifecycle',
      'Choose CLI over GUI with reason',
      'Trace Linux from 1969 to today',
      'Read the filesystem hierarchy',
      'Run 35 essential commands'
    ]
  },

  // --- 2. OBJECTIVES SLIDE ---
  {
    type: 'objectives',
    header: 'MODULE 01 · TOPIC 01',
    kicker: 'ITP 141 · M1 · T1',
    desc: 'Topic 1 establishes the working vocabulary of a systems administrator — the roles, the lifecycle of a system, the tools, and the operating system on which most of the discipline is practised.',
    lede: 'A graduate of this topic can walk to any Linux machine in the laboratory, open a terminal, and explain — without guessing — what each command does and where each file lives.',
    list: [
      'Define the roles and responsibilities of a system administrator across the system lifecycle.',
      'Distinguish the command-line interface from the graphical interface and justify when each is appropriate.',
      'Recount the history of Linux from its UNIX origins to modern distributions.',
      'Compare Linux with UNIX in terms of licensing, kernel design, and ecosystem.',
      'Classify Linux distributions and explain how package management differs across families.',
      'Navigate the Linux filesystem hierarchy and identify the purpose of each top-level directory.',
      'Execute essential Linux commands for file, text, network, and process management with correct syntax.',
      'Begin treating a Linux machine as a system to be administered, not merely used.'
    ]
  },

  // --- 3. SCOPE SLIDE ---
  {
    type: 'scope',
    header: 'MODULE 01 · TOPIC 01',
    kicker: 'Week 01 — 02 · 6 hours',
    title: 'Six threads, <em>one foundation.</em>',
    topics: [
      { no: '01', tag: 'Roles & Lifecycle', title: 'The administrator\'s work, from procurement to retirement.', desc: 'Who a sysadmin is, what they are accountable for, and the lifecycle stages every system passes through: plan, deploy, configure, operate, maintain, retire.', pts: ['Sysadmin roles', 'Skill profile', 'Lifecycle stages'] },
      { no: '02', tag: 'CLI vs GUI', title: 'Why the terminal is the administrator\'s primary tool.', desc: 'Two ways to reach the same machine. The GUI is friendly; the CLI is scriptable, remote-friendly, precise, and reproducible — the working language of system administration.', pts: ['Trade-offs', 'Remote access', 'Automation'] },
      { no: '03', tag: 'Linux & its History', title: 'From a student\'s hobby to the dominant server OS.', desc: 'UNIX (1969), the GNU Project (1983), the Linux kernel (1991), and the distributions that followed — a sixty-year arc that produced the system you will administer.', pts: ['UNIX roots', 'GNU project', 'Linux kernel'] },
      { no: '04', tag: 'Distros & Packages', title: 'Families of Linux and how software is installed on each.', desc: 'Debian, Red Hat, Arch and their derivatives. Package managers — apt, dnf, pacman — and the repositories that make a Linux system install, update, and remove software safely.', pts: ['Distribution families', 'Package managers', 'Repositories'] },
      { no: '05', tag: 'Linux vs UNIX', title: 'Two operating systems, one ancestry, different futures.', desc: 'Linux is UNIX-like, not UNIX. The distinction is licensing, kernel architecture, source availability, and the ecosystems each has produced.', pts: ['POSIX & SUS', 'Licensing', 'Kernel design'] },
      { no: '06', tag: 'Filesystem & Commands', title: 'The directory tree and the working vocabulary.', desc: 'The single rooted tree — /, /etc, /home, /var, /usr — and essential commands a sysadmin types every day, each demonstrated with a working example.', pts: ['FHS standard', '35 essential commands', 'Worked examples'] }
    ]
  },

  // --- 4. ORIENTATION SLIDE ---
  {
    type: 'orientation',
    header: 'MODULE 01 · TOPIC 01',
    title: 'Why this <em>topic</em> matters.',
    lede: 'Before you can install, secure, or repair a system, you must understand what a system administrator is — and the operating system on which the work is done.',
    desc: 'A BSIT graduate who can configure a firewall but cannot explain what /var holds, or why a senior administrator prefers the terminal over the desktop, has only half the craft. This topic supplies the other half: the vocabulary, the history, the tools, and the discipline\'s first commands.',
    anchors: [
      'A DOrSU laboratory workstation configured for a programming class',
      'A barangay office server kept online with limited bandwidth',
      'A research workstation processing Pujada Bay imagery'
    ],
    boxTitle: 'A sysadmin opens a terminal and types one command.',
    boxDesc: 'In that minute the machine has: read its package database, validated a user\'s credentials against /etc/passwd, written a log line to /var/log/auth.log, scheduled a process onto the CPU, and answered a network request from another machine on the LAN. Every one of those actions is what this topic will make legible.',
    stats: [
      { n: '96.3%', l: 'of public cloud servers run Linux' },
      { n: '35', l: 'essential commands you will master here' },
      { n: '1', l: 'filesystem tree, rooted at /' }
    ],
    standard: 'A graduate who recites Linux commands but cannot reason about <em>why</em> the filesystem is hierarchical, or <em>why</em> a package manager exists, has not yet earned the discipline\'s first lesson.'
  },

  // --- 5. ROLES & LIFECYCLE ---
  {
    type: 'roles',
    header: 'MODULE 01 · TOPIC 01',
    bigNum: '01',
    title: 'The administrator\'s <em>work.</em>',
    sub: 'A system administrator keeps computing systems available, secure, and useful to the people who depend on them — across the full life of every machine.',
    roles: [
      { n: '01', title: 'Installation & Provisioning', desc: 'Install the OS, partition disks, set the hostname, and bring the machine to a known-good baseline.' },
      { n: '02', title: 'Configuration', desc: 'Edit configuration files under /etc, set network parameters, define user accounts, and apply security baselines.' },
      { n: '03', title: 'Maintenance & Updates', desc: 'Apply patches, rotate logs, monitor disk and memory, and replace failing hardware before it fails the service.' },
      { n: '04', title: 'Security & Access Control', desc: 'Manage users, groups, permissions, SSH keys, and firewall rules. Audit logs for unauthorized access.' },
      { n: '05', title: 'Backup & Recovery', desc: 'Ensure data survives disk failures, accidental deletion, and disasters. Test restores — an untested backup is no backup.' },
      { n: '06', title: 'Monitoring & Troubleshooting', desc: 'Read logs, trace bottlenecks with top and ps, and diagnose why a service is slow, unreachable, or broken.' },
      { n: '07', title: 'Documentation', desc: 'Record what was changed, why, and when. The next administrator — or future you — will need it.' }
    ],
    stages: [
      { n: '1', title: 'Plan', desc: 'Define requirements, choose hardware and OS, estimate capacity and cost.' },
      { n: '2', title: 'Deploy', desc: 'Install the OS, partition storage, configure the network, and join the machine to the domain.' },
      { n: '3', title: 'Configure', desc: 'Install packages, harden the system, create user accounts, and apply the baseline.' },
      { n: '4', title: 'Operate', desc: 'The system serves its users. The sysadmin monitors, supports, and intervenes as needed.' },
      { n: '5', title: 'Maintain', desc: 'Apply patches, replace failing parts, expand storage, tune performance, and back up data.' },
      { n: '6', title: 'Retire', desc: 'Wipe sensitive data, decommission accounts, recycle hardware, and archive configuration records.' }
    ],
    skillText: '<strong>A sysadmin reads and writes.</strong> Reads logs, man pages, configuration files, and other people\'s scripts. Writes shell scripts, documentation, and careful commands — because one keystroke on a production server can take a service offline for a thousand users.'
  },

  // --- 6. CLI vs GUI ---
  {
    type: 'cligui',
    header: 'MODULE 01 · TOPIC 01',
    bigNum: '02',
    title: 'Two interfaces, <em>one</em> machine.',
    sub: 'The graphical interface is how most users meet a computer. The command line is how administrators meet it. The difference is not preference — it is the work each was designed for.'
  },

  // --- 7. LINUX HISTORY ---
  {
    type: 'history',
    header: 'MODULE 01 · TOPIC 01',
    bigNum: '03',
    title: 'Sixty years, <em>one</em> lineage.',
    sub: 'Linux did not appear from nothing. It is the most successful branch of a family tree whose root is UNIX, planted at Bell Labs in 1969.',
    historyText: 'In 1991, Linus Torvalds, a 21-year-old computer science student at the University of Helsinki, posted a now-famous message to the comp.os.minix newsgroup: he was writing a free operating system "just a hobby, won\'t be big and professional."',
    quote: '"I\'m doing a (free) operating system — just a hobby, won\'t be big and professional."',
    quoteCite: '— Linus Torvalds · 25 August 1991',
    timeline: [
      { yr: '1969', title: 'UNIX at Bell Labs', desc: 'Ken Thompson, Dennis Ritchie and others build UNIX at AT&T. Written in C, portable, and the ancestor of every system in this topic.' },
      { yr: '1983', title: 'The GNU Project', desc: 'Richard Stallman announces GNU — "GNU\'s Not UNIX" — to build a free, UNIX-compatible operating system. Most user-space tools are written.' },
      { yr: '1987', title: 'MINIX', desc: 'Andrew Tanenbaum releases MINIX, a small UNIX-like OS for teaching. Linus Torvalds reads its source code.' },
      { yr: '1991', title: 'Linux 0.01', desc: 'Torvalds releases the first Linux kernel. Combined with GNU tools, it forms a complete, free operating system.' },
      { yr: '1993', title: 'Distributions emerge', desc: 'Slackware and Debian appear. The distribution — kernel plus packages plus installer — becomes the unit of Linux deployment.' },
      { yr: '2003', title: 'Enterprise Linux', desc: 'Red Hat Enterprise Linux and later Ubuntu Server establish Linux in the data centre.' },
      { yr: '2008', title: 'Android', desc: 'Android ships on a Linux kernel, putting Linux in billions of pockets.' },
      { yr: '2013+', title: 'Containers & cloud', desc: 'Docker, Kubernetes, AWS, Azure and GCP run on Linux. The dominant server and cloud operating system.' }
    ]
  },

  // --- 8. LINUX vs UNIX ---
  {
    type: 'linuxunix',
    header: 'MODULE 01 · TOPIC 01',
    bigNum: '04',
    title: 'Linux is <em>UNIX-like</em>,<br>not UNIX.',
    sub: 'The two share an ancestry, a philosophy, and most commands — but differ in licensing, kernel design, and the ecosystems they produced.'
  },

  // --- 9. DISTRIBUTIONS & PACKAGES ---
  {
    type: 'distros',
    header: 'MODULE 01 · TOPIC 01',
    bigNum: '05',
    title: 'Distributions, and how software <em>arrives</em>.',
    sub: 'A Linux distribution is the kernel, plus a package manager, plus a curated set of software — assembled into a single installable system. The choice of distribution is, in practice, the choice of a package manager.'
  },

  // --- 10. FILESYSTEM HIERARCHY ---
  {
    type: 'filesystem',
    header: 'MODULE 01 · TOPIC 01',
    bigNum: '06',
    title: 'One tree, rooted at <em style="font-style:italic;color:var(--rust)">/</em>.',
    sub: 'Unlike Windows, Linux has no drive letters. Every file and device — local disks, USB sticks, network shares — lives somewhere under a single root directory called /.'
  }
];

// --- 11. THE 35 ESSENTIAL COMMANDS (Expands into 70 slides: Basic + Advanced) ---
var commandsData = [
  {name:'ls',cat:'File & Directory Management',basicTitle:'List files and folders',basicDesc:'Lists the contents of the current directory. Without any flags, it shows the names of visible files and folders.',syntax:'<strong>ls</strong> <span>[OPTION]... [FILE]...</span>',flags:[{f:'-l',s:'Long format',d:'Displays file permissions, owner, size, and modification date.'},{f:'-a',s:'All files',d:'Includes hidden files starting with a dot (.), which are omitted by default.'},{f:'-h',s:'Human-readable',d:'Prints file sizes in K, M, G instead of raw bytes.'}],basicTerm:[{p:'~',c:'ls'},{o:'Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos'}],advTerm:[{p:'~',c:'ls -lah'},{o:'total 124K'},{o:'drwxr-xr-x 24 ajsacay staff 4.0K Oct 24 10:00 .'},{o:'drwxr-xr-x  3 root    root  4.0K Oct 20 08:00 ..'},{o:'-rw-r--r--  1 ajsacay staff  220 Oct 23 14:15 .bashrc'},{o:'drwxr-xr-x  2 ajsacay staff 4.0K Oct 24 09:30 Documents'},{o:'-rw-r--r--  1 ajsacay staff  12M  Oct 22 11:30 notes.txt'}]},
  {name:'cd',cat:'File & Directory Management',basicTitle:'Change your current path',basicDesc:'Changes the current working directory to the specified path. Essential for navigating the Linux filesystem tree.',syntax:'<strong>cd</strong> <span>[DIRECTORY]</span>',flags:[{f:'cd ..',s:'Parent directory',d:'Moves up one level in the directory tree.'},{f:'cd ~',s:'Home directory',d:'Tilde (~) is a shortcut for the current user\'s home folder.'},{f:'cd -',s:'Previous directory',d:'Returns you to the last directory you were in.'}],basicTerm:[{p:'~',c:'cd /var/log'},{p:'/var/log',c:''}],advTerm:[{p:'/var/log',c:'cd ..'},{p:'/var',c:'cd -'},{o:'/var/log'},{p:'/var/log',c:'cd ~'},{p:'~',c:''}]},
  {name:'pwd',cat:'File & Directory Management',basicTitle:'Show your current folder path',basicDesc:'Prints the absolute pathname of the current working directory. Useful when you are deep in the filesystem and need to know exactly where you are.',syntax:'<strong>pwd</strong>',flags:[{f:'-P',s:'Physical path',d:'Avoids all symbolic links. Prints the actual physical location of the directory.'},{f:'-L',s:'Logical path',d:'Prints the path including symbolic links (default behavior).'}],basicTerm:[{p:'~/Documents/labs',c:'pwd'},{o:'/home/ajsacay/Documents/labs'}],advTerm:[{p:'/var/log',c:'pwd -P'},{o:'/usr/var/log'},{p:'/var/log',c:'pwd -L'},{o:'/var/log'}]},
  {name:'cp',cat:'File & Directory Management',basicTitle:'Copy files or folders',basicDesc:'Copies a file from a source to a destination. The original file remains untouched, and a duplicate is created.',syntax:'<strong>cp</strong> <span>SOURCE DEST</span>',flags:[{f:'-r',s:'Recursive',d:'Required when copying directories. Copies the folder and all its contents.'},{f:'-i',s:'Interactive',d:'Prompts for confirmation before overwriting an existing file.'},{f:'-v',s:'Verbose',d:'Prints the name of each file as it is copied.'}],basicTerm:[{p:'~',c:'cp notes.txt notes.bak.txt'},{p:'~',c:'ls'},{o:'notes.bak.txt  notes.txt'}],advTerm:[{p:'~',c:'cp -rv labs/ labs_backup/'},{o:"'labs/module01.txt' -> 'labs_backup/module01.txt'"},{o:"'labs/module02.txt' -> 'labs_backup/module02.txt'"}]},
  {name:'mv',cat:'File & Directory Management',basicTitle:'Move or rename files',basicDesc:'Moves a file from one location to another. If the destination is in the same directory, it effectively renames the file.',syntax:'<strong>mv</strong> <span>SOURCE DEST</span>',flags:[{f:'-u',s:'Update',d:'Moves the file only if the source is newer than the destination, or if the destination is missing.'},{f:'-i',s:'Interactive',d:'Prompts before overwriting an existing file.'},{f:'-t',s:'Target directory',d:'Specifies the destination directory explicitly, allowing multiple files to be moved at once.'}],basicTerm:[{p:'~',c:'mv old_name.txt new_name.txt'},{p:'~',c:'ls'},{o:'new_name.txt'}],advTerm:[{p:'~',c:'mv -t /tmp/ file1.txt file2.txt'},{p:'~',c:'ls /tmp/'},{o:'file1.txt  file2.txt'}]},
  {name:'rm',cat:'File & Directory Management',basicTitle:'Delete files or folders',basicDesc:'Removes files or directories permanently. Unlike a graphical interface, there is no recycle bin — deletion is final.',syntax:'<strong>rm</strong> <span>[FILE]...</span>',flags:[{f:'-r',s:'Recursive',d:'Removes directories and their contents. Required to delete a folder.'},{f:'-f',s:'Force',d:'Ignores nonexistent files and never prompts for confirmation. Use with extreme caution.'},{f:'-i',s:'Interactive',d:'Prompts for confirmation before every deletion. Safe for nervous administrators.'}],basicTerm:[{p:'~',c:'rm notes.bak.txt'},{p:'~',c:'ls'},{o:'notes.txt'}],advTerm:[{p:'~',c:'rm -rf old_projects/'},{p:'~',c:'ls'},{o:'notes.txt  labs'}]},
  {name:'mkdir',cat:'File & Directory Management',basicTitle:'Create a new folder',basicDesc:'Creates a new directory in the current location. You must have write permissions in the parent directory to create it.',syntax:'<strong>mkdir</strong> <span>[DIRECTORY]...</span>',flags:[{f:'-p',s:'Parents',d:'Creates parent directories as needed. Does not throw an error if the directory already exists.'},{f:'-v',s:'Verbose',d:'Prints a message for each directory created. Useful for scripting and debugging.'},{f:'-m',s:'Mode',d:'Sets the file permissions (like 777 or 755) at the moment of creation.'}],basicTerm:[{p:'~',c:'mkdir new_lab'},{p:'~',c:'ls'},{o:'new_lab  notes.txt'}],advTerm:[{p:'~',c:'mkdir -p -v labs/2023/October'},{o:"mkdir: created directory 'labs'"},{o:"mkdir: created directory 'labs/2023'"},{o:"mkdir: created directory 'labs/2023/October'"}]},
  {name:'touch',cat:'File & Directory Management',basicTitle:'Create an empty file',basicDesc:'Creates a new, empty file. If the file already exists, it updates the access and modification timestamps instead.',syntax:'<strong>touch</strong> <span>[FILE]...</span>',flags:[{f:'-c',s:'No create',d:'Do not create any files if they do not exist. Only updates timestamps of existing files.'},{f:'-a',s:'Access time',d:'Changes only the access time, leaving the modification time alone.'},{f:'-m',s:'Modification time',d:'Changes only the modification time, leaving the access time alone.'},{f:'-t',s:'Timestamp',d:'Use a specific time instead of the current time (e.g., -t 202312312359.59).'}],basicTerm:[{p:'~',c:'touch index.html'},{p:'~',c:'ls -l index.html'},{o:'-rw-r--r-- 1 ajsacay staff 0 Oct 24 10:15 index.html'}],advTerm:[{p:'~',c:'touch -t 202301010000 old_file.txt'},{p:'~',c:'ls -l old_file.txt'},{o:'-rw-r--r-- 1 ajsacay staff 0 Jan  1  2023 old_file.txt'}]},
  {name:'top',cat:'System Monitoring & Info',basicTitle:'View active system tasks',basicDesc:'Displays a real-time, dynamic view of running processes, CPU usage, memory consumption, and system load. Press \'q\' to quit.',syntax:'<strong>top</strong>',flags:[{f:'Shift+M',s:'Sort by memory',d:'Re-sorts the process list to show the highest memory consumers at the top.'},{f:'Shift+P',s:'Sort by CPU',d:'Re-sorts the process list to show the highest CPU consumers at the top.'},{f:'k',s:'Kill process',d:'Prompts for a PID (Process ID) and sends a kill signal to terminate it.'},{f:'-n 1',s:'Batch mode',d:'Outputs one iteration and exits. Useful for parsing in shell scripts.'}],basicTerm:[{p:'~',c:'top'},{o:'top - 10:30:15 up  2:22,  2 users,  load average: 0.02, 0.04, 0.00'},{o:'Tasks: 182 total,   1 running, 181 sleeping,   0 stopped'},{o:'%Cpu(s):  1.2 us,  0.3 sy,  0.0 ni, 98.5 id,  0.0 wa'},{o:'MiB Mem :   7976.0 total,   4500.2 free,   1500.1 used'},{o:'  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM'},{o:' 1024 ajsacay   20   0  456784  25120  12000 S   1.0   0.3 gnome-shell'}],advTerm:[{p:'~',c:'top -b -n 1 | head -n 5'},{o:'top - 10:31:02 up  2:23,  2 users,  load average: 0.02, 0.04, 0.00'},{o:'Tasks: 182 total,   1 running, 181 sleeping,   0 stopped'},{o:'%Cpu(s):  2.5 us,  1.0 sy,  0.0 ni, 96.5 id,  0.0 wa'},{o:'MiB Mem :   7976.0 total,   4500.2 free,   1500.1 used'}]},
  {name:'htop',cat:'System Monitoring & Info',basicTitle:'View tasks in a colorful list',basicDesc:'An enhanced, interactive alternative to `top`. Displays processes in a colorful, scrollable list with full command lines visible.',syntax:'<strong>htop</strong>',flags:[{f:'F5',s:'Tree view',d:'Displays processes in a hierarchical tree, showing parent-child relationships.'},{f:'F6',s:'Sort by',d:'Opens a menu to sort processes by PID, USER, CPU%, MEM%, or TIME.'},{f:'F9',s:'Kill process',d:'Sends a specific signal (like SIGTERM or SIGKILL) to the selected process.'},{f:'/',s:'Search',d:'Filters the process list by matching a text string in the command line.'}],basicTerm:[{p:'~',c:'htop'},{o:'    1  [|||||||||||||||||||||||||||    78.3%] '},{o:'    2  [|||||||||                       28.1%] '},{o:'Mem[|||||||||||||||||||         3.2G/7.9G] '},{o:'Swp[                              0K/2.0G] '},{o:'    PID USER   PRI  NI  VIRT   RES   SHR S CPU%  COMMAND '},{o:'   1024 ajsacay  20   0 456M  251M  120M S 12.0  /usr/bin/gnome-shell '}],advTerm:[{p:'~',c:'sudo apt install htop -y'},{o:'Reading package lists... Done'},{o:'Setting up htop (3.2.1-1) ...'}]},
  {name:'df',cat:'System Monitoring & Info',basicTitle:'Check disk space usage',basicDesc:'Reports the amount of used and available disk space on all mounted filesystems. The default output is in bytes, which is hard to read.',syntax:'<strong>df</strong>',flags:[{f:'-h',s:'Human-readable',d:'Prints sizes in K, M, G, making the output instantly understandable to humans.'},{f:'-T',s:'Type',d:'Adds a column showing the filesystem type (ext4, xfs, tmpfs, etc.).'},{f:'-i',s:'Inodes',d:'Shows inode usage instead of disk blocks. Useful when you run out of inodes but have free space.'}],basicTerm:[{p:'~',c:'df'},{o:'Filesystem     1K-blocks     Used Available Use% Mounted on'},{o:'/dev/sda2       52428800 15728640  34078720  32% /'},{o:'tmpfs            4085768        0   4085768   0% /dev/shm'},{o:'/dev/sda1        523248     6144    517104   2% /boot/efi'}],advTerm:[{p:'~',c:'df -hT'},{o:'Filesystem     Type   Size  Used Avail Use% Mounted on'},{o:'/dev/sda2      ext4    50G   15G   33G  32% /'},{o:'tmpfs          tmpfs  3.9G     0  3.9G   0% /dev/shm'},{o:'/dev/sda1      vfat   511M  6.1M  505M   2% /boot/efi'}]},
  {name:'du',cat:'System Monitoring & Info',basicTitle:'Check folder size usage',basicDesc:'Estimates and reports the disk space used by files and directories. By default, it lists the size of every subdirectory in blocks.',syntax:'<strong>du</strong> <span>[FILE]...</span>',flags:[{f:'-h',s:'Human-readable',d:'Prints sizes in K, M, G. Combines well with other flags.'},{f:'-s',s:'Summary',d:'Suppresses the output of subdirectories. Shows only the total size of the target directory.'},{f:'-a',s:'All',d:'Writes counts for all files, not just directories.'},{f:'--max-depth',s:'Depth limit',d:'Prints the total for a directory only if it is N or fewer levels below the command line argument.'}],basicTerm:[{p:'~',c:'du /var/log'},{o:'4884    /var/log/apt'},{o:'40      /var/log/cups'},{o:'4600    /var/log/installer'},{o:'45120   /var/log'}],advTerm:[{p:'~',c:'du -sh /var/log'},{o:'45M    /var/log'},{p:'~',c:'du -h --max-depth=1 /var/log'},{o:'4.8M    /var/log/apt'},{o:'4.5M    /var/log/installer'},{o:'45M     /var/log'}]},
  {name:'free',cat:'System Monitoring & Info',basicTitle:'Check available memory',basicDesc:'Displays the total amount of free and used physical and swap memory in the system, measured in bytes.',syntax:'<strong>free</strong>',flags:[{f:'-h',s:'Human-readable',d:'Shows all output values automatically scaled to the shortest three-digit unit (K, M, G).'},{f:'-m',s:'Megabytes',d:'Displays all memory values in megabytes. Useful for consistent parsing.'},{f:'-g',s:'Gigabytes',d:'Displays all memory values in gigabytes.'},{f:'-s 5',s:'Continuous',d:'Refreshes the display every 5 seconds until interrupted. Acts like a simple monitor.'}],basicTerm:[{p:'~',c:'free'},{o:'              total        used        free      shared  buff/cache   available'},{o:'Mem:        8159480     1532160     4500232      312140     2127088     6084720'},{o:'Swap:       2097148           0     2097148'}],advTerm:[{p:'~',c:'free -h'},{o:'              total        used        free      shared  buff/cache   available'},{o:'Mem:           7.8Gi       1.5Gi       4.3Gi       304Mi       2.0Gi       5.8Gi'},{o:'Swap:          2.0Gi          0B       2.0Gi'}]},
  {name:'uptime',cat:'System Monitoring & Info',basicTitle:'See how long the system is running',basicDesc:'Tells you how long the system has been running, how many users are currently logged in, and the system load averages.',syntax:'<strong>uptime</strong>',flags:[{f:'-p',s:'Pretty',d:'Shows uptime in a human-friendly format, omitting the time and user count (e.g., "up 2 days, 4 hours, 22 minutes").'},{f:'-s',s:'Since',d:'Prints the exact date and time the system was booted, rather than the duration.'},{f:'Load Avg',s:'Understanding the numbers',d:'The three load averages represent system load over the last 1, 5, and 15 minutes. A value of 1.0 means 100% CPU utilization on a single core.'}],basicTerm:[{p:'~',c:'uptime'},{o:' 10:30:15 up 2 days,  4:22,  3 users,  load average: 0.02, 0.04, 0.00'}],advTerm:[{p:'~',c:'uptime -p'},{o:'up 2 days, 4 hours, 22 minutes'},{p:'~',c:'uptime -s'},{o:'2023-10-22 06:08:13'}]},
  {name:'uname',cat:'System Monitoring & Info',basicTitle:'Show system kernel details',basicDesc:'Prints basic information about the operating system and the underlying hardware. By default, it simply prints the kernel name.',syntax:'<strong>uname</strong>',flags:[{f:'-a',s:'All information',d:'Prints all available system information in a single string. The most commonly used flag.'},{f:'-r',s:'Kernel release',d:'Prints the kernel release version (e.g., 5.15.0-76-generic). Essential when installing kernel modules.'},{f:'-m',s:'Machine hardware',d:'Prints the machine hardware name (e.g., x86_64). Useful to know if the OS is 32-bit or 64-bit.'},{f:'-n',s:'Hostname',d:'Prints the network node hostname of the machine.'}],basicTerm:[{p:'~',c:'uname'},{o:'Linux'}],advTerm:[{p:'~',c:'uname -a'},{o:'Linux dorsu 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux'},{p:'~',c:'uname -r'},{o:'5.15.0-76-generic'}]},
  {name:'cat',cat:'Text Processing & Viewing',basicTitle:'Print file content',basicDesc:'Reads data from files and outputs their contents. It is the simplest way to display the entire content of a short file.',syntax:'<strong>cat</strong> <span>[FILE]...</span>',flags:[{f:'-n',s:'Number lines',d:'Numbers all output lines, starting at 1.'},{f:'-b',s:'Number non-blank',d:'Numbers only non-empty lines, ignoring blank spaces.'},{f:'-s',s:'Squeeze blank',d:'Suppresses repeated empty output lines, combining them into one.'}],basicTerm:[{p:'~',c:'cat /etc/hostname'},{o:'dorsu-lab01'}],advTerm:[{p:'~',c:'cat -n /etc/hosts'},{o:'     1  127.0.0.1 localhost'},{o:'     2  127.0.1.1 dorsu'},{o:'     3  '},{o:'     4  # The following lines are desirable for IPv6'}]},
  {name:'less',cat:'Text Processing & Viewing',basicTitle:'Read a file page by page',basicDesc:'Opens a file in a scrollable pager. Unlike `cat`, it doesn\'t dump everything to the screen at once, making it ideal for large files.',syntax:'<strong>less</strong> <span>[FILE]</span>',flags:[{f:'/',s:'Search',d:'Type `/` followed by a pattern to search forward through the file. Press `n` for next match.'},{f:'Shift+G',s:'Go to end',d:'Jumps immediately to the very bottom of the file.'},{f:'g',s:'Go to start',d:'Jumps immediately back to the very top of the file.'},{f:'q',s:'Quit',d:'Exits the less pager and returns to the shell prompt.'}],basicTerm:[{p:'~',c:'less /var/log/syslog'},{o:'Oct 24 08:00:01 dorsu systemd[1]: Started Daily apt download activities.'},{o:'Oct 24 08:00:01 dorsu systemd[1]: Started Daily apt upgrade activities.'},{o:'Oct 24 08:15:10 dorsu kernel: [  12.345] USB device connected'},{o:':'}],advTerm:[{p:'~',c:'less +F /var/log/syslog'},{o:'Oct 24 10:00:00 dorsu kernel: [  15.123] Network manager started'},{o:'Oct 24 10:15:00 dorsu systemd[1]: Started Session 4.'},{o:'(Waiting for data... press Ctrl+C to interrupt)'}]},
  {name:'grep',cat:'Text Processing & Viewing',basicTitle:'Search for text inside files',basicDesc:'Searches for specific text patterns within files. It prints any line that contains a match for the given pattern.',syntax:'<strong>grep</strong> <span>"PATTERN" [FILE]</span>',flags:[{f:'-i',s:'Ignore case',d:'Performs a case-insensitive search, matching ERROR, Error, and error.'},{f:'-r',s:'Recursive',d:'Searches through all files under the specified directory and its subdirectories.'},{f:'-v',s:'Invert match',d:'Selects only lines that do NOT contain the specified pattern.'},{f:'-n',s:'Line number',d:'Prefixes each matching line with its line number in the file.'}],basicTerm:[{p:'~',c:'grep "error" /var/log/syslog'},{o:'Oct 24 08:15:22 dorsu systemd[1]: Error loading driver module'},{o:'Oct 24 09:01:10 dorsu kernel: [  45.678] disk I/O error'}],advTerm:[{p:'~',c:'grep -rn "127.0.0.1" /etc/'},{o:'/etc/hosts:1:127.0.0.1 localhost'},{o:'/etc/hosts:2:127.0.1.1 dorsu'},{o:'/etc/resolv.conf:4:nameserver 127.0.0.53'}]},
  {name:'head',cat:'Text Processing & Viewing',basicTitle:'View the first lines of a file',basicDesc:'Prints the first 10 lines of a file by default. It is the quickest way to peek at the beginning of a file without opening it.',syntax:'<strong>head</strong> <span>[FILE]</span>',flags:[{f:'-n N',s:'Number of lines',d:'Prints the first N lines instead of the default 10.'},{f:'-c N',s:'Number of bytes',d:'Prints the first N bytes of the file.'},{f:'-q',s:'Quiet',d:'Never print headers identifying the file name when processing multiple files.'},{f:'-v',s:'Verbose',d:'Always print headers identifying the file name, even with a single file.'}],basicTerm:[{p:'~',c:'head /etc/passwd'},{o:'root:x:0:0:root:/root:/bin/bash'},{o:'daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin'},{o:'bin:x:2:2:bin:/bin:/usr/sbin/nologin'},{o:'sys:x:3:3:sys:/dev:/usr/sbin/nologin'}],advTerm:[{p:'~',c:'head -n 2 /etc/passwd'},{o:'root:x:0:0:root:/root:/bin/bash'},{o:'daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin'}]},
  {name:'tail',cat:'Text Processing & Viewing',basicTitle:'View the last lines of a file',basicDesc:'Prints the last 10 lines of a file. It is most commonly used to check the latest entries in log files.',syntax:'<strong>tail</strong> <span>[FILE]</span>',flags:[{f:'-f',s:'Follow',d:'Continues to watch the file and print new lines as they are appended in real time. Invaluable for live log monitoring.'},{f:'-n N',s:'Number of lines',d:'Prints the last N lines instead of the default 10.'},{f:'-F',s:'Follow with retry',d:'Like -f, but also handles situations where the file is rotated or replaced.'},{f:'--pid',s:'Terminate with process',d:'Exits once the specified process ID dies.'}],basicTerm:[{p:'~',c:'tail /var/log/syslog'},{o:'Oct 24 10:20:01 dorsu systemd[1]: Started Session 4.'},{o:'Oct 24 10:22:15 dorsu kernel: [  12.345] USB device connected'},{o:'Oct 24 10:25:00 dorsu cron[1234]: (root) CMD (test -x /usr/sbin/anacron)'}],advTerm:[{p:'~',c:'tail -f /var/log/auth.log'},{o:'Oct 24 10:30:01 dorsu sshd[1234]: Accepted publickey for ajsacay'},{o:'Oct 24 10:30:02 dorsu systemd[1]: session-4.scope: Succeeded'},{o:'(Waiting for new log entries...)'}]},
  {name:'awk',cat:'Text Processing & Viewing',basicTitle:'Process and filter text data',basicDesc:'A powerful pattern-scanning and processing language. By default, it splits each line into fields separated by whitespace and lets you print specific columns.',syntax:'<strong>awk</strong> <span>\'{print $1}\' [FILE]</span>',flags:[{f:'-F:',s:'Field separator',d:'Changes the delimiter from whitespace to a colon. Useful for parsing `/etc/passwd`.'},{f:'$NF',s:'Last field',d:'Refers to the last column of the current line, regardless of how many fields there are.'},{f:'BEGIN/END',s:'Blocks',d:'Executes actions before processing starts or after all lines are read.'},{f:'Patterns',s:'Conditional logic',d:'Processes lines only if they match a specific pattern (e.g., `$3 > 1000`).'}],basicTerm:[{p:'~',c:"awk '{print $1}' /etc/hosts"},{o:'127.0.0.1'},{o:'127.0.1.1'},{o:'#'}],advTerm:[{p:'~',c:"awk -F: '$3 >= 1000 {print $1}' /etc/passwd"},{o:'nobody'},{o:'ajsacay'}]},
  {name:'sed',cat:'Text Processing & Viewing',basicTitle:'Edit text streams',basicDesc:'A stream editor used to perform basic text transformations on an input stream. It is most commonly used for find-and-replace operations.',syntax:'<strong>sed</strong> <span>\'s/old/new/\' [FILE]</span>',flags:[{f:'g',s:'Global',d:'Replaces all occurrences on a line, not just the first one. Appended to the command (e.g., `s/old/new/g`).'},{f:'-i',s:'In-place',d:'Edits the file directly on disk. Use `-i.bak` to create a backup first.'},{f:'-n',s:'Silent',d:'Suppresses automatic printing of pattern space. Usually paired with `p` to print only specific lines.'},{f:'d',s:'Delete',d:'Deletes lines matching a pattern instead of substituting text.'}],basicTerm:[{p:'~',c:'echo "hello world" | sed \'s/world/Linux/\''},{o:'hello Linux'}],advTerm:[{p:'~',c:"sed -i 's/localhost/dorsu/g' config.txt"},{p:'~',c:'cat config.txt'},{o:'127.0.0.1 dorsu'}]},
  {name:'ping',cat:'Network & Connectivity',basicTitle:'Test network reachability',basicDesc:'Sends ICMP echo request packets to a network host to check if it is reachable and measures the round-trip time.',syntax:'<strong>ping</strong> <span>[HOST]</span>',flags:[{f:'-c N',s:'Count',d:'Stops after sending N echo request packets and displays statistics.'},{f:'-i N',s:'Interval',d:'Waits N seconds between sending each packet. Default is 1 second.'},{f:'-W N',s:'Timeout',d:'Sets the time to wait for a response, in seconds.'},{f:'-f',s:'Flood',d:'Sends packets as fast as possible. Only for root; used for stress testing networks.'}],basicTerm:[{p:'~',c:'ping 8.8.8.8'},{o:'PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.'},{o:'64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=12.3 ms'},{o:'64 bytes from 8.8.8.8: icmp_seq=2 ttl=117 time=11.9 ms'}],advTerm:[{p:'~',c:'ping -c 3 dorsu.edu'},{o:'PING dorsu.edu (192.168.1.10) 56(84) bytes of data.'},{o:'64 bytes from 192.168.1.10: icmp_seq=1 ttl=64 time=0.452 ms'},{o:'--- dorsu.edu ping statistics ---'},{o:'3 packets transmitted, 3 received, 0% packet loss'}]},
  {name:'ip',cat:'Network & Connectivity',basicTitle:'Show network address settings',basicDesc:'Shows or manipulates routing, network devices, interfaces, and tunnels. It is the modern replacement for `ifconfig`.',syntax:'<strong>ip</strong> <span>addr</span>',flags:[{f:'link',s:'Network devices',d:'Displays or manipulates the state of network interfaces.'},{f:'route',s:'Routing table',d:'Shows or manipulates the IP routing table.'},{f:'-br',s:'Brief',d:'A shorthand flag that prints a concise summary of interfaces.'},{f:'addr add',s:'Assign IP',d:'Adds an IP address to an interface.'}],basicTerm:[{p:'~',c:'ip addr'},{o:'1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN'},{o:'    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00'},{o:'    inet 127.0.0.1/8 scope host lo'},{o:'2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP'},{o:'    link/ether 08:00:27:a8:12:45 brd ff:ff:ff:ff:ff:ff'},{o:'    inet 192.168.1.25/24 brd 192.168.1.255 scope global eth0'}],advTerm:[{p:'~',c:'ip -br addr'},{o:'lo               UNKNOWN        127.0.0.1/8 ::1/128'},{o:'eth0             UP             192.168.1.25/24 fe80::a00:27ff:fea8:1245/64'},{p:'~',c:'ip route'},{o:'default via 192.168.1.1 dev eth0 proto static'}]},
  {name:'curl',cat:'Network & Connectivity',basicTitle:'Transfer data using URLs',basicDesc:'A tool to transfer data to or from a server using protocols like HTTP, HTTPS, FTP. It is heavily used for testing APIs and downloading files.',syntax:'<strong>curl</strong> <span>[URL]</span>',flags:[{f:'-O',s:'Remote name',d:'Saves the output to a local file named after the remote file.'},{f:'-I',s:'Headers only',d:'Fetches only the HTTP headers, useful for checking if a URL exists.'},{f:'-X POST',s:'Method',d:'Specifies a custom HTTP method instead of the default GET.'},{f:'-d',s:'Data',d:'Sends specified data in a POST request.'}],basicTerm:[{p:'~',c:'curl http://example.com'},{o:'<!doctype html>'},{o:'<html>'},{o:'<head>'},{o:'    <title>Example Domain</title>'}],advTerm:[{p:'~',c:'curl -I https://dorsu.edu'},{o:'HTTP/2 200'},{o:'server: nginx'},{o:'content-type: text/html; charset=UTF-8'}]},
  {name:'wget',cat:'Network & Connectivity',basicTitle:'Download files from the web',basicDesc:'A non-interactive network downloader. It retrieves files from web servers using HTTP, HTTPS, and FTP protocols.',syntax:'<strong>wget</strong> <span>[URL]</span>',flags:[{f:'-c',s:'Continue',d:'Resumes a partially downloaded file, picking up where it left off.'},{f:'-r',s:'Recursive',d:'Downloads an entire website.'},{f:'-q',s:'Quiet',d:'Turns off output.'},{f:'-O',s:'Output document',d:'Writes downloaded content to a specific file name.'}],basicTerm:[{p:'~',c:'wget http://example.com/file.zip'},{o:'--2023-10-24 10:30:00--  http://example.com/file.zip'},{o:'Resolving example.com... 93.184.216.34'},{o:'Connecting to example.com|93.184.216.34|:80... connected.'},{o:'HTTP request sent, awaiting response... 200 OK'},{o:'Length: 1048576 (1.0M) [application/zip]'},{o:"Saving to: 'file.zip'"}],advTerm:[{p:'~',c:'wget -c -q -O backup.tar.gz http://example.com/backup.tar.gz'},{p:'~',c:'ls -lh backup.tar.gz'},{o:'-rw-r--r-- 1 ajsacay staff 4.5G Oct 24 10:31 backup.tar.gz'}]},
  {name:'netstat',cat:'Network & Connectivity',basicTitle:'Check network connections',basicDesc:'Prints network connections, routing tables, interface statistics, and multicast memberships. A classic tool for network troubleshooting.',syntax:'<strong>netstat</strong>',flags:[{f:'-t',s:'TCP',d:'Displays only TCP connections.'},{f:'-u',s:'UDP',d:'Displays only UDP connections.'},{f:'-l',s:'Listening',d:'Shows only listening sockets.'},{f:'-p',s:'Program',d:'Shows the PID and name of the program using the socket.'}],basicTerm:[{p:'~',c:'netstat'},{o:'Active Internet connections (w/o servers)'},{o:'Proto Recv-Q Send-Q Local Address           Foreign Address         State'},{o:'tcp        0      0 dorsu:ssh               192.168.1.5:54321        ESTABLISHED'}],advTerm:[{p:'~',c:'sudo netstat -tulpn'},{o:'Active Internet connections (only servers)'},{o:'Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program'},{o:'tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1234/sshd'}]},
  {name:'ss',cat:'Network & Connectivity',basicTitle:'Show socket statistics',basicDesc:'A modern, faster alternative to `netstat`. It dumps socket statistics, showing information about network connections.',syntax:'<strong>ss</strong>',flags:[{f:'-t',s:'TCP',d:'Displays only TCP sockets.'},{f:'-u',s:'UDP',d:'Displays only UDP sockets.'},{f:'-l',s:'Listening',d:'Shows only listening sockets.'},{f:'-p',s:'Process',d:'Shows the process using the socket.'},{f:'-n',s:'Numeric',d:'Prevents resolving port numbers to names.'}],basicTerm:[{p:'~',c:'ss'},{o:'Netid State  Recv-Q Send-Q  Local Address:Port   Peer Address:Port'},{o:'tcp   ESTAB  0      0       192.168.1.25:ssh     192.168.1.5:54321'}],advTerm:[{p:'~',c:'sudo ss -tulpn'},{o:'Netid State  Recv-Q Send-Q Local Address:Port  Peer Address:Port Process'},{o:'tcp   LISTEN 0      128    0.0.0.0:22         0.0.0.0:*      users:(("sshd",pid=1234,fd=3))'}]},
  {name:'chmod',cat:'Permissions & Management',basicTitle:'Change file access rights',basicDesc:'Changes file permissions (read, write, execute) for the owner, group, and others.',syntax:'<strong>chmod</strong> <span>[OPTIONS] MODE FILE</span>',flags:[{f:'+x',s:'Add execute',d:'Adds execute permissions.'},{f:'755',s:'Numeric',d:'Sets rwx for owner, rx for group and others.'},{f:'644',s:'Numeric',d:'Sets rw for owner, r for group and others.'},{f:'-R',s:'Recursive',d:'Changes permissions recursively.'}],basicTerm:[{p:'~',c:'ls -l script.sh'},{o:'-rw-r--r-- 1 ajsacay staff 0 Oct 24 10:25 script.sh'},{p:'~',c:'chmod +x script.sh'},{p:'~',c:'ls -l script.sh'},{o:'-rwxr-xr-x 1 ajsacay staff 0 Oct 24 10:25 script.sh'}],advTerm:[{p:'~',c:'chmod -R 755 /var/www/html/'},{p:'~',c:'ls -ld /var/www/html/'},{o:'drwxr-xr-x 2 www-data www-data 4096 Oct 24 10:30 /var/www/html/'}]},
  {name:'chown',cat:'Permissions & Management',basicTitle:'Change file owner',basicDesc:'Changes the owner and group of a file or directory.',syntax:'<strong>chown</strong> <span>[USER][:GROUP] FILE</span>',flags:[{f:'user:group',s:'Full ownership',d:'Changes both user and group simultaneously.'},{f:'-R',s:'Recursive',d:'Changes ownership recursively.'},{f:'--reference',s:'Reference file',d:'Uses owner and group from a reference file.'}],basicTerm:[{p:'~',c:'sudo chown www-data:www-data index.html'},{p:'~',c:'ls -l index.html'},{o:'-rw-r--r-- 1 www-data www-data 12K Oct 24 10:26 index.html'}],advTerm:[{p:'~',c:'sudo chown -R ajsacay:staff /var/www/html/'},{p:'~',c:'ls -ld /var/www/html/'},{o:'drwxr-xr-x 2 ajsacay staff 4096 Oct 24 10:30 /var/www/html/'}]},
  {name:'sudo',cat:'Permissions & Management',basicTitle:'Run a command as the root user',basicDesc:'Executes a single command with superuser (root) privileges.',syntax:'<strong>sudo</strong> <span>[COMMAND]</span>',flags:[{f:'-i',s:'Interactive shell',d:'Starts an interactive root shell.'},{f:'-u user',s:'As another user',d:'Runs the command as a specified user.'},{f:'-k',s:'Kill cache',d:'Invalidates cached credentials.'},{f:'-l',s:'List privileges',d:'Lists allowed commands.'}],basicTerm:[{p:'~',c:'sudo apt update'},{o:'[sudo] password for ajsacay:'},{o:'Hit:1 http://archive.ubuntu.com jammy InRelease'}],advTerm:[{p:'~',c:'sudo -u www-data ls /var/www'},{o:'index.html  images  css'},{p:'~',c:'sudo -l'},{o:'User ajsacay may run the following commands on dorsu:'}]},
  {name:'ps',cat:'Permissions & Management',basicTitle:'List running processes',basicDesc:'Reports a snapshot of current processes.',syntax:'<strong>ps</strong> <span>[OPTIONS]</span>',flags:[{f:'aux',s:'All processes',d:'Displays all system processes using BSD syntax.'},{f:'-ef',s:'Full format',d:'Displays all processes in full format.'},{f:'-u user',s:'By user',d:'Selects processes owned by a specific user.'}],basicTerm:[{p:'~',c:'ps'},{o:'    PID TTY          TIME CMD'},{o:'   1234 pts/0    00:00:00 bash'},{o:'   5678 pts/0    00:00:00 ps'}],advTerm:[{p:'~',c:'ps aux | grep nginx'},{o:'root      5678  0.0  0.1  14264  5120 ?        Ss   10:00   0:00 nginx: master process'}]},
  {name:'kill',cat:'Permissions & Management',basicTitle:'Stop a running process',basicDesc:'Sends a signal to a process, usually to terminate it.',syntax:'<strong>kill</strong> <span>[PID]</span>',flags:[{f:'-9',s:'SIGKILL',d:'Forces immediate termination.'},{f:'-15',s:'SIGTERM',d:'The default polite termination signal.'},{f:'-HUP',s:'SIGHUP',d:'Hangup signal to reload configuration.'},{f:'-l',s:'List signals',d:'Lists all available signal names.'}],basicTerm:[{p:'~',c:'ps aux | grep nginx'},{o:'root      5678  0.0  0.1  14264  5120 ?        Ss   10:00   0:00 nginx: master process'},{p:'~',c:'kill 5678'}],advTerm:[{p:'~',c:'kill -9 5678'},{p:'~',c:'kill -l'},{o:' 1) SIGHUP    2) SIGINT    3) SIGQUIT'}]},
  {name:'systemctl',cat:'Permissions & Management',basicTitle:'Control system services',basicDesc:'Used to introspect and control the state of systemd services.',syntax:'<strong>systemctl</strong> <span>[COMMAND] [SERVICE]</span>',flags:[{f:'start',s:'Start',d:'Starts a service.'},{f:'stop',s:'Stop',d:'Stops a service.'},{f:'restart',s:'Restart',d:'Restarts a service.'},{f:'status',s:'Status',d:'Shows current state.'},{f:'enable',s:'Enable',d:'Enables auto-start at boot.'}],basicTerm:[{p:'~',c:'sudo systemctl start nginx'},{p:'~',c:'sudo systemctl status nginx'},{o:'● nginx.service - The nginx HTTP and reverse proxy server'}],advTerm:[{p:'~',c:'sudo systemctl enable nginx'},{o:"Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service"},{p:'~',c:'sudo systemctl reload nginx'}]},
  {name:'journalctl',cat:'Permissions & Management',basicTitle:'Read system log files',basicDesc:'Used to query and display logs collected by systemd-journald.',syntax:'<strong>journalctl</strong> <span>[OPTIONS]</span>',flags:[{f:'-u service',s:'Unit',d:'Shows logs only for specified unit.'},{f:'-f',s:'Follow',d:'Displays recent log lines in real-time.'},{f:'-n N',s:'Lines',d:'Shows last N log lines.'},{f:'--since',s:'Time filter',d:'Shows logs from specific time.'}],basicTerm:[{p:'~',c:'sudo journalctl'},{o:'-- Logs begin at Tue 2023-10-24 08:00:00 UTC --'},{o:'Oct 24 08:00:01 dorsu systemd[1]: Started Daily apt download activities.'}],advTerm:[{p:'~',c:'sudo journalctl -u nginx -n 5 --since "1 hour ago"'},{o:'Oct 24 10:00:00 dorsu systemd[1]: Starting The nginx HTTP and reverse proxy server...'}]}
];

// Append commands dynamically as slide configurations
commandsData.forEach((cmd, idx) => {
  slideConfigs.push({ type: 'commandBasic', cmd: cmd, index: idx });
  slideConfigs.push({ type: 'commandAdv', cmd: cmd, index: idx });
});

// --- 12. CLOSING SLIDE ---
slideConfigs.push({
  type: 'closing',
  header: 'MODULE 01 · TOPIC 01',
  tag: 'End of Topic 01',
  title: 'A system administrator <em>reads</em> the machine<br>before changing it.',
  quote: 'In the beginning, the command line was the only interface. Today, it remains the most powerful. The GUI is for users; the CLI is for administrators.',
  leftCardNum: '§ 01 — 02',
  leftCardTitle: 'Roles & interfaces',
  leftCardDesc: 'The sysadmin\'s work spans the lifecycle; the CLI is the working interface because it is scriptable, remote-friendly, and precise.',
  middleCardNum: '§ 03 — 04',
  middleCardTitle: 'Linux in context',
  middleCardDesc: 'Linux continues a UNIX lineage begun in 1969. It is free, open, and runs most of the world\'s servers — but it is UNIX-like, not certified UNIX.',
  rightCardNum: '§ 05 — 06',
  rightCardTitle: 'Tools of the trade',
  rightCardDesc: 'Distributions deliver software via package managers. The filesystem is a single tree rooted at <code>/</code>. Thirty-five essential commands begin the working vocabulary.'
});