const slideConfigs = [
  {
    type: 'cover',
    moduleTitle: 'MODULE 01 · TOPIC 02',
    topicNum: '02',
    topicTag: 'T2',
    title: 'Text Processing:<br><em>grep</em> & <em>sed</em>',
    subtitle: 'Search, filter, and transform text streams with the classic UNIX utilities every sysadmin should know.',
    graphicText: 'Search <em>streams</em><br>edit <em>streams</em><br>automate everything.',
    miniObjectives: ['History of grep & sed', 'Pattern matching', 'Stream editing', 'Lab exercises']
  },

  {
    type: 'objectives',
    header: 'MODULE 01 · TOPIC 02',
    kicker: 'ITP 141 · M1 · T2',
    desc: 'This topic introduces two of the most useful Unix text-processing tools: grep for filtering and sed for stream editing.',
    lede: 'A system administrator who cannot parse logs or script text transformations is working blind. grep and sed open the door to automation.',
    list: [
      'Understand the history and purpose of grep and sed in UNIX systems.',
      'Use grep to search and filter lines by pattern and context.',
      'Apply common grep flags like -n, -v, -c, -w, -E, -r, and -q.',
      'Use sed to substitute, delete, and transform text in pipelines.',
      'Apply both tools in practical lab exercises using sample log files.'
    ]
  },

    // 3. HISTORY OF GREP
    { type: 'lesson', category: 'History', title: 'grep: Origin', subtitle: 'The Beginning', desc: 'In 1973, Ken Thompson wrote grep at Bell Labs, and it shipped in Version 4 UNIX that November. The name comes from the <code>ed</code> editor command <code>g/re/p</code> (globally search for a regular expression and print). Doug McIlroy had asked Thompson to lift the regex recognizer out of the editor and make it a one-pass program of its own.', syntax: 'g/re/p', term: [{raw:'<span class="out"># In the old "ed" editor, you typed:</span><br>g/re/p<br><span class="out"># Meaning: (g)lobally search for a (r)egular (e)xpression and (p)rint the result.</span>'}], explain: '<strong>Why it matters:</strong> This origin explains grep\'s behaviour exactly: it reads input line by line, applies a regex, and prints the whole line on a match. Note that grep did not invent regular expressions. <code>ed</code> and the earlier <code>qed</code> already had them; grep\'s contribution was making that power a standalone tool, which McIlroy credited with cementing the UNIX tools philosophy.' },

    // 4. HISTORY OF SED
    { type: 'lesson', category: 'History', title: 'sed: Origin', subtitle: 'The Stream Editor', desc: 'Lee E. McMahon built sed (Stream EDitor) at Bell Labs between 1973 and 1974, and it shipped in Version 7 UNIX. It began as a demand for <code>g/re/s</code>, a substitution counterpart to grep. Foreseeing that <code>g/re/d</code> and the rest would follow, McMahon wrote one general-purpose line-oriented editor instead.', syntax: 'command | sed "s/old/new/"', term: [{p:'~', c:'echo "hello world" | sed "s/world/Linux/"'}, {o:'hello Linux'}], explain: '<strong>Why it matters:</strong> Unlike nano or vim, sed never waits for user input, which is exactly what a script needs. It does not open the file into a buffer; it streams the text line by line, applies your commands, and writes the result out. That is why it edits files far larger than available memory.' },

    // 5. ENVIRONMENT SETUP (The Master Setup Script)
    { type: 'lesson', category: 'Setup', title: 'Lab Environment Setup', subtitle: 'Generate Temp Files', desc: 'To ensure you get output on Kali Linux, we will generate dummy files in <code>/tmp/itp141</code>. Copy and run this script in your terminal to create the logs and configs we will use.', syntax: 'mkdir -p /tmp/itp141 && cd /tmp/itp141', term: [{raw:'<span class="cmd">mkdir -p /tmp/itp141 &amp;&amp; cd /tmp/itp141</span><br><span class="cmd">echo "192.168.1.10 - - GET /index.html 200" &gt; access.log</span><br><span class="cmd">echo "192.168.1.50 - - GET /missing.html 404" &gt;&gt; access.log</span><br><span class="cmd">echo "192.168.1.50 - - GET /admin.php 404" &gt;&gt; access.log</span><br><span class="cmd">echo "10.0.0.5 - - GET /style.css 200" &gt;&gt; access.log</span><br><span class="cmd">echo "admin:/bin/bash" &gt; users.txt</span><br><span class="cmd">echo "root:/bin/bash" &gt;&gt; users.txt</span><br><span class="cmd">echo "guest:/usr/sbin/nologin" &gt;&gt; users.txt</span><br><span class="cmd">echo "# SSH Config" &gt; sshd_config</span><br><span class="cmd">echo "Port 22" &gt;&gt; sshd_config</span><br><span class="cmd">echo "" &gt;&gt; sshd_config</span><br><span class="cmd">echo "PermitRootLogin no" &gt;&gt; sshd_config</span><br><span class="cmd">echo -e "Sacay,Ar-Jay\\tadmin" &gt; users.csv</span><br><span class="cmd">echo -e "Doe,John\\teditor" &gt;&gt; users.csv</span><br><span class="cmd">echo "" &gt;&gt; users.csv</span><br><span class="cmd">echo -e "Smith,Jane\\tviewer" &gt;&gt; users.csv</span><br><span class="cmd">echo "Setup complete!"</span><br><span class="out">Setup complete!</span>'}], explain: '<strong>Explanation:</strong> This creates a safe lab directory in <code>/tmp/itp141</code>. We populate <code>access.log</code>, <code>users.txt</code>, <code>sshd_config</code>, and <code>users.csv</code>. All future examples and labs use these files.' },

    // 6. GREP BASIC
    { type: 'lesson', category: 'grep Basics', title: 'grep: Basic Search', subtitle: 'Simple Pattern', desc: 'The most basic use of grep. It tests every line against a pattern, a basic regular expression, and prints the whole line when it matches.', syntax: 'grep "PATTERN" [FILE]', term: [{p:'/tmp/itp141', c:'grep "404" access.log'}, {o:'192.168.1.50 - - GET /missing.html 404'}, {o:'192.168.1.50 - - GET /admin.php 404'}], explain: '<strong>Explanation:</strong> Grep reads the access.log file, finds the string "404" on two lines, and prints those whole lines to the terminal.' },

    // 7. GREP IGNORE CASE
    { type: 'lesson', category: 'grep Basics', title: 'grep: Case Insensitive', subtitle: 'grep -i', desc: 'Performs a case-insensitive search, matching ERROR, Error, and error.', syntax: 'grep -i "PATTERN" [FILE]', flags: [{f:'-i', s:'Ignore case', d:'Matches uppercase and lowercase equally.'}], term: [{p:'/tmp/itp141', c:'grep -i "ADMIN" access.log'}, {o:'192.168.1.50 - - GET /admin.php 404'}], explain: '<strong>Explanation:</strong> The -i flag tells grep to ignore case sensitivity. It catches "admin.php" even though we searched for "ADMIN".' },

    // 8. GREP INVERT
    { type: 'lesson', category: 'grep Basics', title: 'grep: Invert Match', subtitle: 'grep -v', desc: 'Selects only lines that do NOT contain the specified pattern. Great for filtering out noise.', syntax: 'grep -v "PATTERN" [FILE]', flags: [{f:'-v', s:'Invert match', d:'Excludes lines matching the pattern.'}], term: [{p:'/tmp/itp141', c:'grep -v "404" access.log'}, {o:'192.168.1.10 - - GET /index.html 200'}, {o:'10.0.0.5 - - GET /style.css 200'}], explain: '<strong>Explanation:</strong> The -v flag inverts the logic. It shows everything EXCEPT the lines containing "404". This is perfect for stripping out comments from config files.' },

    // 9. GREP LINE NUMBERS
    { type: 'lesson', category: 'grep Basics', title: 'grep: Line Numbers', subtitle: 'grep -n', desc: 'Prefixes every matching line with its line number in the source file, so you can jump straight to it in an editor.', syntax: 'grep -n "PATTERN" [FILE]', flags: [{f:'-n', s:'Line number', d:'Prefixes each match with its position in the file.'}], term: [{p:'/tmp/itp141', c:'grep -n "404" access.log'}, {o:'2:192.168.1.50 - - GET /missing.html 404'}, {o:'3:192.168.1.50 - - GET /admin.php 404'}], explain: '<strong>Explanation:</strong> The number before the colon is the line number inside <code>access.log</code>, not a count of matches. Once grep tells you the error is on line 2, you can open the file in <code>vim</code> and type <code>:2</code> to land on it directly.' },

    // 10. GREP COUNT
    { type: 'lesson', category: 'grep Basics', title: 'grep: Counting Matches', subtitle: 'grep -c', desc: 'Reports how many lines matched instead of printing the lines themselves. Ideal for quick health checks.', syntax: 'grep -c "PATTERN" [FILE]', flags: [{f:'-c', s:'Count', d:'Prints the number of matching lines.'}], term: [{p:'/tmp/itp141', c:'grep -c "404" access.log'}, {o:'2'}, {p:'/tmp/itp141', c:'grep -c "" access.log'}, {o:'4'}], explain: '<strong>Explanation:</strong> <code>-c</code> counts matching <strong>lines</strong>, not matches. A line containing "404" twice still counts once. Since an empty pattern matches every line, <code>grep -c ""</code> doubles as a quick line counter for any file.' },

    // 11. GREP WHOLE WORD
    { type: 'lesson', category: 'grep Basics', title: 'grep: Whole Word Match', subtitle: 'grep -w', desc: 'Matches the pattern only where it stands alone as a word, never when it is buried inside a longer word.', syntax: 'grep -w "PATTERN" [FILE]', flags: [{f:'-w', s:'Word match', d:'Requires word boundaries on both sides.'}], term: [{p:'~', c:'echo "admin administrator" | grep -o "admin"'}, {o:'admin'}, {o:'admin'}, {p:'~', c:'echo "admin administrator" | grep -ow "admin"'}, {o:'admin'}], explain: '<strong>Explanation:</strong> Without <code>-w</code>, grep also matches the "admin" hiding inside "administrator", so you get two hits. <code>-w</code> demands a non-word character on each side, leaving only the standalone word. This is what stops a search for "root" from dragging in "chroot".' },

    // 12. INTERMEDIATE: EXTENDED REGEX
    { type: 'lesson', category: 'grep Intermediate', title: 'grep: Extended Regex', subtitle: 'grep -E', desc: 'Enables extended regular expressions, allowing the use of OR operators (|) and quantifiers (+, ?).', syntax: 'grep -E "PATTERN1|PATTERN2" [FILE]', flags: [{f:'-E', s:'Extended', d:'Enables OR (|) and quantifiers.'}], term: [{p:'/tmp/itp141', c:'grep -E "admin|style" access.log'}, {o:'192.168.1.50 - - GET /admin.php 404'}, {o:'10.0.0.5 - - GET /style.css 200'}, {p:'/tmp/itp141', c:'grep "admin|style" access.log'}], explain: '<strong>Explanation:</strong> With <code>-E</code> the <code>|</code> is an OR, so one pass returns both the admin request and the stylesheet request. The second command drops <code>-E</code>: grep then hunts for the literal text <code>admin|style</code>, matches nothing, and prints nothing. <strong>Industry note:</strong> the old <code>egrep</code> and <code>fgrep</code> commands are deprecated and warn on modern systems. Use <code>grep -E</code> and <code>grep -F</code>.' },

    // 13. INTERMEDIATE: EXACT MATCH
    { type: 'lesson', category: 'grep Intermediate', title: 'grep: Only the Match', subtitle: 'grep -o', desc: 'By default, grep prints the whole line. The -o flag tells grep to print ONLY the matched text itself.', syntax: 'grep -o "PATTERN" [FILE]', flags: [{f:'-o', s:'Only match', d:'Prints only the matched pattern.'}], term: [{p:'/tmp/itp141', c:'grep -o "192\\.168\\.1\\.50" access.log'}, {o:'192.168.1.50'}, {o:'192.168.1.50'}], explain: '<strong>Explanation:</strong> Instead of printing the whole log entry, <code>-o</code> emits just the matched fragment, once per match. The dots are escaped because an unescaped <code>.</code> means "any character" in a regex. Do not confuse <code>-o</code> with <code>-x</code>, which matches only when the pattern fills the entire line.' },

    // 14. GREP ANCHORS
    { type: 'lesson', category: 'grep Intermediate', title: 'grep: Line Anchors', subtitle: '^ and $', desc: 'Anchors pin a pattern to the start or the end of a line instead of letting it match anywhere.', syntax: 'grep "^START" file   /   grep "END$" file', flags: [{f:'^', s:'Start of line', d:'Matches only at the beginning.'}, {f:'$', s:'End of line', d:'Matches only at the end.'}], term: [{p:'/tmp/itp141', c:'grep "^10" access.log'}, {o:'10.0.0.5 - - GET /style.css 200'}, {p:'/tmp/itp141', c:'grep "404$" access.log'}, {o:'192.168.1.50 - - GET /missing.html 404'}, {o:'192.168.1.50 - - GET /admin.php 404'}], explain: '<strong>Explanation:</strong> <code>^10</code> isolates the internal subnet without dragging in 192.168 addresses that merely contain "10" somewhere. <code>404$</code> matches only when 404 ends the line, which is what makes it a status code instead of part of a filename.' },

    // 15. GREP CHARACTER CLASSES
    { type: 'lesson', category: 'grep Intermediate', title: 'grep: Character Classes', subtitle: '[abc] and [^abc]', desc: 'Square brackets match any single character from a set. A caret inside the brackets flips the set into an exclusion.', syntax: 'grep "^[ar]" file   /   grep "^[^ar]" file', flags: [{f:'[ar]', s:'Any of these', d:'Matches one character: a or r.'}, {f:'[^ar]', s:'None of these', d:'Matches any character except a or r.'}, {f:'[0-9]', s:'Ranges', d:'Also [a-z] and [A-Za-z0-9].'}], term: [{p:'/tmp/itp141', c:'grep "^[ar]" users.txt'}, {o:'admin:/bin/bash'}, {o:'root:/bin/bash'}, {p:'/tmp/itp141', c:'grep "^[^ar]" users.txt'}, {o:'guest:/usr/sbin/nologin'}], explain: '<strong>Explanation:</strong> <code>[ar]</code> matches exactly one character, either a or r, so anchored with <code>^</code> it finds usernames starting with those letters. Moving the caret <strong>inside</strong> the brackets reverses the meaning to "any character that is not a or r".' },

    // 16. GREP CONTEXT LINES
    { type: 'lesson', category: 'grep Intermediate', title: 'grep: Context Lines', subtitle: '-A -B -C', desc: 'Prints the neighbouring lines around each match, so you can see what happened immediately before and after an event.', syntax: 'grep -A 1 "PATTERN" [FILE]', flags: [{f:'-A n', s:'After', d:'Prints n lines following each match.'}, {f:'-B n', s:'Before', d:'Prints n lines preceding each match.'}, {f:'-C n', s:'Context', d:'Prints n lines on both sides.'}], term: [{p:'/tmp/itp141', c:'grep -A 1 "missing" access.log'}, {o:'192.168.1.50 - - GET /missing.html 404'}, {o:'192.168.1.50 - - GET /admin.php 404'}, {p:'/tmp/itp141', c:'grep -B 1 "missing" access.log'}, {o:'192.168.1.10 - - GET /index.html 200'}, {o:'192.168.1.50 - - GET /missing.html 404'}], explain: '<strong>Explanation:</strong> A single matching line rarely tells the whole story. <code>-A 1</code> reveals that the same IP went from /missing.html straight to /admin.php, which is the signature of a directory scan. Use <code>-C 2</code> when you want both sides at once.' },

    // 17. GREP RECURSIVE
    { type: 'lesson', category: 'grep Intermediate', title: 'grep: Recursive Search', subtitle: 'grep -r', desc: 'Searches every file in a directory tree instead of one file, printing the filename beside each hit.', syntax: 'grep -r "PATTERN" [DIRECTORY]', flags: [{f:'-r', s:'Recursive', d:'Descends into every subdirectory.'}, {f:'-l', s:'Files only', d:'Prints filenames instead of matching lines.'}], term: [{p:'~', c:'grep -r "bash" /tmp/itp141'}, {o:'/tmp/itp141/users.txt:admin:/bin/bash'}, {o:'/tmp/itp141/users.txt:root:/bin/bash'}, {p:'~', c:'grep -rl "bash" /tmp/itp141'}, {o:'/tmp/itp141/users.txt'}], explain: '<strong>Explanation:</strong> With <code>-r</code>, grep prints <code>filename:line</code> so you know where every hit lives. Adding <code>-l</code> collapses that to filenames only, which is what you want when the question is "which config files mention this setting?" rather than "what do they say?".' },

    // 18. GREP QUIET MODE
    { type: 'lesson', category: 'grep Intermediate', title: 'grep: Quiet Mode', subtitle: 'grep -q', desc: 'Prints nothing and answers through the exit status instead. This is how grep is used inside shell scripts.', syntax: 'grep -q "PATTERN" file &amp;&amp; echo "FOUND"', flags: [{f:'-q', s:'Quiet', d:'No output, sets the exit status only.'}], term: [{p:'/tmp/itp141', c:'grep -q "404" access.log &amp;&amp; echo "Errors present"'}, {o:'Errors present'}, {p:'/tmp/itp141', c:'grep -q "500" access.log &amp;&amp; echo "Errors present"'}, {p:'/tmp/itp141', c:'echo $?'}, {o:'1'}], explain: '<strong>Explanation:</strong> grep exits with <code>0</code> when it finds a match and <code>1</code> when it does not. <code>&amp;&amp;</code> only runs the second command on exit status 0, so the failed search prints nothing at all. This is the standard way a script asks "is this directive already in the config?" before appending it.' },

    // 19. INTERMEDIATE: PIPELINE
    { type: 'lesson', category: 'grep Intermediate', title: 'grep: Piping Output', subtitle: 'cmd | grep', desc: 'Grep is often used to filter the output of other commands via a pipe (|).', syntax: 'command | grep "PATTERN"', term: [{p:'~', c:'ls /tmp/itp141 | grep "users"'}, {o:'users.csv'}, {o:'users.txt'}], explain: '<strong>Explanation:</strong> <code>ls</code> lists every file in the directory. The pipe (<code>|</code>) hands that listing to grep as standard input instead of a filename, and grep keeps only the lines containing "users". Any command that writes to standard output can be filtered this way.' },

    // 20. GREP LAB 1 (SECTION A): LOG ANALYSIS
    { type: 'lab', title: 'grep Lab 1 (Section A): Log Analysis', subtitle: 'Exercise', scenarioTitle: 'Extract 404 IPs', scenario: 'You are investigating a web server attack. You need to find the IP addresses responsible for 404 Not Found errors in <code>access.log</code>.', tasks: ['Filter <code>/tmp/itp141/access.log</code> down to the 404 lines first', 'Extract ONLY the IP address using <code>-oE</code> regex', 'Regex for IP: <code>"^([0-9]{1,3}\\.){3}[0-9]{1,3}"</code>'], term: [] },

    // 21. GREP LAB 1 (SECTION A): SOLUTION
    { type: 'lab_solution', title: 'grep Lab 1 (Section A): Solution', subtitle: 'Solution', desc: 'Combine -o and -E flags.', syntax: 'grep "404$" /tmp/itp141/access.log | grep -oE "^([0-9]{1,3}\\.){3}[0-9]{1,3}"', term: [{p:'/tmp/itp141', c:'grep "404$" access.log | grep -oE "^([0-9]{1,3}\\.){3}[0-9]{1,3}"'}, {o:'192.168.1.50'}, {o:'192.168.1.50'}], explain: '<strong>Explanation:</strong> Order matters. Filter first, extract second: <code>grep "404$"</code> keeps only the lines whose status code is 404, then the second grep lifts the IP off the front of each survivor. Doing it the other way round throws the status code away, so the later search would have nothing left to match on.' },

    // 22. GREP LAB 2 (SECTION B): CONFIG PARSING
    { type: 'lab', title: 'grep Lab 2 (Section B): Config Parsing', subtitle: 'Exercise', scenarioTitle: 'List Active Directives', scenario: 'A colleague hands you an <code>sshd_config</code> padded with comments and blank lines. You need a clean list of the directives that are actually in force, and the line number of each one.', tasks: ['Search <code>/tmp/itp141/sshd_config</code>', 'Exclude comment lines using <code>^#</code>', 'Exclude empty lines using <code>^$</code>', 'Combine both patterns with <code>-E</code> and the OR operator', 'Add <code>-n</code> to print the original line numbers'], term: [] },

    // 23. GREP LAB 2 (SECTION B): SOLUTION
    { type: 'lab_solution', title: 'grep Lab 2 (Section B): Solution', subtitle: 'Solution', desc: 'Invert the match against a two-part extended pattern.', syntax: 'grep -vnE "^#|^$" /tmp/itp141/sshd_config', term: [{p:'/tmp/itp141', c:'grep -vnE "^#|^$" sshd_config'}, {o:'2:Port 22'}, {o:'4:PermitRootLogin no'}], explain: '<strong>Explanation:</strong> <code>-E</code> turns <code>|</code> into an OR, so the pattern matches comment lines or blank lines. <code>-v</code> then keeps everything else. <code>-n</code> prefixes each surviving line with its number in the original file, so you can jump straight to it in an editor.' },

    // 24. GREP LAB 3 (SECTION C): LOG SANITIZATION
    { type: 'lab', title: 'grep Lab 3 (Section C): Log Sanitization', subtitle: 'Exercise', scenarioTitle: 'Publish a Safe Extract', scenario: 'The security team wants a public copy of <code>access.log</code> showing which pages were requested and how the server answered, with every client IP stripped out and all internal traffic removed.', tasks: ['Drop internal traffic from the <code>10.</code> range with <code>-v "^10\\."</code>', 'Pipe the survivors into a second <code>grep</code>', 'Print only the request and status with <code>-oE "GET .* [0-9]{3}$"</code>', 'Save the result to <code>access_public.log</code>', 'Leave the original <code>access.log</code> untouched'], term: [] },

    // 25. GREP LAB 3 (SECTION C): SOLUTION
    { type: 'lab_solution', title: 'grep Lab 3 (Section C): Solution', subtitle: 'Solution', desc: 'Filter with -v, then extract with -oE.', syntax: 'grep -v "^10\\." access.log | grep -oE "GET .* [0-9]{3}$" &gt; access_public.log', term: [{p:'/tmp/itp141', c:'grep -v "^10\\." access.log | grep -oE "GET .* [0-9]{3}$" &gt; access_public.log'}, {p:'/tmp/itp141', c:'cat access_public.log'}, {o:'GET /index.html 200'}, {o:'GET /missing.html 404'}, {o:'GET /admin.php 404'}], explain: '<strong>Explanation:</strong> The first <code>grep -v</code> removes every line beginning with <code>10.</code>, your internal subnet. The second <code>grep -oE</code> prints only the matched fragment, so the client IP never reaches the output at all. The <code>&gt;</code> writes the extract to a new file and leaves the evidence file intact.' },

    // 26. GREP LAB 4 (SECTION D): DATA TRANSFORMATION
    { type: 'lab', title: 'grep Lab 4 (Section D): Data Transformation', subtitle: 'Exercise', scenarioTitle: 'Extract the Role Column', scenario: 'The access-control team wants a plain list of the roles currently in use, one per line, pulled out of <code>users.csv</code>. The file carries a stray blank line and they do not want it in the output.', tasks: ['Use <code>grep -oE</code> on <code>/tmp/itp141/users.csv</code>', 'Match only the role at the end of the line: <code>"[a-z]+$"</code>', 'Save the result to <code>roles.txt</code>', 'Count what you extracted with <code>grep -c ""</code>', 'Be ready to explain why the blank line vanished on its own'], term: [] },

    // 27. GREP LAB 4 (SECTION D): SOLUTION
    { type: 'lab_solution', title: 'grep Lab 4 (Section D): Solution', subtitle: 'Solution', desc: 'Anchor the extraction to the end of the line.', syntax: 'grep -oE "[a-z]+$" /tmp/itp141/users.csv &gt; roles.txt', term: [{p:'/tmp/itp141', c:'grep -oE "[a-z]+$" users.csv &gt; roles.txt'}, {p:'/tmp/itp141', c:'cat roles.txt'}, {o:'admin'}, {o:'editor'}, {o:'viewer'}, {p:'/tmp/itp141', c:'grep -c "" roles.txt'}, {o:'3'}], explain: '<strong>Explanation:</strong> <code>-o</code> prints only the matched fragment and <code>$</code> pins that match to the end of the line, so you get the role without the surname, the first name, or the tab. The blank line needs no special handling at all: it contains no lowercase letters, so it never matches and <code>-o</code> emits nothing for it. <code>grep -c ""</code> then confirms three roles were written.' },

    // 28. SED INTRO
    { type: 'lesson', category: 'sed Basics', title: 'sed: Basic Substitution', subtitle: 's/old/new/', desc: 'Replaces the first occurrence of "old" with "new" on each line.', syntax: "sed 's/old/new/' file.txt", term: [{p:'~', c:"echo 'a a a' | sed 's/a/b/'"}, {o:'b a a'}], explain: '<strong>Explanation:</strong> The <code>s</code> stands for substitute. It finds the first "a" on the line and replaces it with "b". Notice it only replaced the FIRST one.' },

    // 29. SED GLOBAL
    { type: 'lesson', category: 'sed Basics', title: 'sed: Global Substitution', subtitle: 's/old/new/g', desc: 'By default, sed only replaces the first occurrence. Append g to replace all occurrences on a line.', syntax: "sed 's/old/new/g' file.txt", flags: [{f:'g', s:'Global', d:'Replaces all occurrences on a line.'}], term: [{p:'~', c:"echo 'a a a' | sed 's/a/b/g'"}, {o:'b b b'}], explain: '<strong>Explanation:</strong> The <code>g</code> flag stands for "global". It tells sed to continue searching and replacing across the entire line, not just stopping at the first match.' },

    // 30. SED INPLACE
    { type: 'lesson', category: 'sed Basics', title: 'sed: In-Place Editing', subtitle: 'sed -i', desc: 'Edits the file directly on disk instead of outputting to the terminal.', syntax: "sed -i 's/old/new/g' file.txt", flags: [{f:'-i', s:'In-place', d:'Modifies the file directly.'}], term: [{p:'/tmp/itp141', c:"sed -i 's/index/home/g' access.log"}, {p:'/tmp/itp141', c:'grep "200$" access.log'}, {o:'192.168.1.10 - - GET /home.html 200'}, {o:'10.0.0.5 - - GET /style.css 200'}], explain: '<strong>Explanation:</strong> Without <code>-i</code>, sed only prints changes to the screen. With <code>-i</code>, it writes them straight into <code>access.log</code>. Note that grep reads the file directly: <code>cat file | grep</code> spawns a second process for nothing. <strong>Warning: always run the command without -i first.</strong> This slide really does edit your lab data, so re-run the setup script before the labs.' },

    // 31. SED SAFE EDIT
    { type: 'lesson', category: 'sed Basics', title: 'sed: Safe In-Place', subtitle: 'sed -i.bak', desc: 'Creates a backup of the original file before modifying it in-place.', syntax: "sed -i.bak 's/old/new/g' file.txt", flags: [{f:'-i.bak', s:'Backup', d:'Saves original as file.txt.bak.'}], term: [{p:'/tmp/itp141', c:"sed -i.bak 's/404/403/g' access.log"}, {p:'/tmp/itp141', c:'ls access.log*'}, {o:'access.log  access.log.bak'}], explain: '<strong>Explanation:</strong> Appending <code>.bak</code> to <code>-i</code> saves the untouched original as <code>access.log.bak</code>, so a bad regex costs you nothing. <strong>Portability note:</strong> <code>-i</code> is not in POSIX. On GNU sed (Kali, Ubuntu, RHEL) the suffix is optional; on BSD sed (macOS) it is mandatory, so the same edit is written <code>sed -i \'\' \'s/old/new/g\' file</code> there.' },

    // 32. SED DELETE
    { type: 'lesson', category: 'sed Basics', title: 'sed: Deleting Lines', subtitle: '/pattern/d', desc: 'Deletes entire lines that match a pattern using the d command.', syntax: "sed '/PATTERN/d' file.txt", flags: [{f:'d', s:'Delete', d:'Removes lines matching the pattern.'}], term: [{p:'/tmp/itp141', c:"sed '/nologin/d' users.txt"}, {o:'admin:/bin/bash'}, {o:'root:/bin/bash'}], explain: '<strong>Explanation:</strong> The <code>d</code> command deletes lines. This command removes all lines containing "nologin", leaving only the active bash users.' },

    // 33. SED EMPTY LINES
    { type: 'lesson', category: 'sed Basics', title: 'sed: Delete Empty Lines', subtitle: '/^$/d', desc: 'A common sysadmin task to clean up files by removing all blank lines.', syntax: "sed '/^$/d' file.txt", term: [{p:'/tmp/itp141', c:"sed '/^$/d' sshd_config"}, {o:'# SSH Config'}, {o:'Port 22'}, {o:'PermitRootLogin no'}], explain: '<strong>Explanation:</strong> <code>^</code> is the start of the line, <code>$</code> is the end. <code>^$</code> means a line with nothing in between (an empty line). The <code>d</code> deletes it.' },

    // 34. SED MULTIPLE
    { type: 'lesson', category: 'sed Intermediate', title: 'sed: Multiple Commands', subtitle: '-e', desc: 'Execute multiple sed commands in a single pass.', syntax: "sed -e 'cmd1' -e 'cmd2' file", flags: [{f:'-e', s:'Execute', d:'Allows multiple commands.'}], term: [{p:'~', c:"echo 'cat' | sed -e 's/cat/dog/' -e 's/dog/wolf/'"}, {o:'wolf'}], explain: '<strong>Explanation:</strong> The <code>-e</code> flag allows us to chain commands. First it replaces "cat" with "dog". Then, on the same stream, it replaces "dog" with "wolf".' },

    // 35. SED DELIMITER
    { type: 'lesson', category: 'sed Intermediate', title: 'sed: Alternate Delimiters', subtitle: 's|old|new|', desc: 'When dealing with file paths, use a different delimiter to avoid escaping slashes.', syntax: "sed 's|/old/path|/new/path|' file", term: [{p:'~', c:"echo '/var/www' | sed 's|/var/www|/opt/nginx|'"}, {o:'/opt/nginx'}], explain: '<strong>Explanation:</strong> If you are replacing file paths with slashes, using <code>s/var/www//opt/nginx/</code> is messy. Sed allows ANY character as a delimiter. Using <code>|</code> makes it readable.' },

    // 36. SED CAPTURE GROUPS
    { type: 'lesson', category: 'sed Intermediate', title: 'sed: Capture Groups', subtitle: 's/(.*)/(\\1)/', desc: 'Use parentheses to capture parts of the pattern and reuse them in the replacement with \\1, \\2.', syntax: "sed -E 's/([^,]*),([^,]*)/\\2,\\1/'", term: [{p:'~', c:"echo 'Sacay,Ar-Jay' | sed -E 's/([^,]*),([^,]*)/\\2,\\1/'"}, {o:'Ar-Jay,Sacay'}], explain: '<strong>Explanation:</strong> <code>([^,]*)</code> captures everything before the comma into group 1. The second captures everything after into group 2. <code>\\2,\\1</code> outputs them in reverse order.' },

    // 37. SED LAB 1 (SECTION A): LOG ANALYSIS
    { type: 'lab', title: 'sed Lab 1 (Section A): Log Analysis', subtitle: 'Exercise', scenarioTitle: 'Reformat for the Report', scenario: 'Raw log lines are hard to read in an incident report. Rewrite every line of <code>access.log</code> so the status code comes first, then the page, then the client that asked for it.', tasks: ['Use <code>sed -E</code> on <code>/tmp/itp141/access.log</code>', 'Capture three fields: the IP, the path, and the status code', 'Pattern: <code>^([0-9.]+) - - GET ([^ ]+) ([0-9]{3})$</code>', 'Rebuild each line as <code>[status] path requested by IP</code>', 'Print to the screen only, do not modify the file'], term: [] },

    // 38. SED LAB 1 (SECTION A): SOLUTION
    { type: 'lab_solution', title: 'sed Lab 1 (Section A): Solution', subtitle: 'Solution', desc: 'Three capture groups, replayed in a new order.', syntax: "sed -E 's/^([0-9.]+) - - GET ([^ ]+) ([0-9]{3})$/[\\3] \\2 requested by \\1/' access.log", term: [{p:'/tmp/itp141', c:"sed -E 's/^([0-9.]+) - - GET ([^ ]+) ([0-9]{3})$/[\\3] \\2 requested by \\1/' access.log"}, {o:'[200] /index.html requested by 192.168.1.10'}, {o:'[404] /missing.html requested by 192.168.1.50'}, {o:'[404] /admin.php requested by 192.168.1.50'}, {o:'[200] /style.css requested by 10.0.0.5'}], explain: '<strong>Explanation:</strong> <code>([0-9.]+)</code> captures the IP, <code>([^ ]+)</code> captures the path by taking every character that is not a space, and <code>([0-9]{3})</code> captures the status code anchored to the end of the line. The replacement replays them as <code>\\3</code>, <code>\\2</code>, <code>\\1</code>, which reorders the line without deleting a single byte of data.' },

    // 39. SED LAB 2 (SECTION B): CONFIG PARSING
    { type: 'lab', title: 'sed Lab 2 (Section B): Config Parsing', subtitle: 'Exercise', scenarioTitle: 'Harden the SSH Config', scenario: 'Policy says SSH must move off port 22 and root may only log in with a key. Rewrite the two directives in <code>sshd_config</code>, but preview the result before you commit anything to disk.', tasks: ['Use <code>sed</code> on <code>/tmp/itp141/sshd_config</code>', 'Replace the whole port line: <code>s/^Port .*/Port 2222/</code>', 'Replace the root line with <code>PermitRootLogin prohibit-password</code>', 'Chain both substitutions using <code>-e</code>', 'Run it without <code>-i</code> first and read the output'], term: [] },

    // 40. SED LAB 2 (SECTION B): SOLUTION
    { type: 'lab_solution', title: 'sed Lab 2 (Section B): Solution', subtitle: 'Solution', desc: 'Anchor each directive, then overwrite the whole line.', syntax: "sed -e 's/^Port .*/Port 2222/' -e 's/^PermitRootLogin .*/PermitRootLogin prohibit-password/' /tmp/itp141/sshd_config", term: [{p:'/tmp/itp141', c:"sed -e 's/^Port .*/Port 2222/' -e 's/^PermitRootLogin .*/PermitRootLogin prohibit-password/' sshd_config"}, {o:'# SSH Config'}, {o:'Port 2222'}, {o:'&nbsp;'}, {o:'PermitRootLogin prohibit-password'}], explain: '<strong>Explanation:</strong> Anchoring with <code>^</code> and consuming the rest with <code>.*</code> replaces the directive whatever its current value is, so the same command works on any machine and can be re-run safely. Nothing is written to disk yet, which is exactly why you preview before reaching for <code>-i.bak</code>.' },

    // 41. SED LAB 3 (SECTION C): LOG SANITIZATION
    { type: 'lab', title: 'sed Lab 3 (Section C): Log Sanitization', subtitle: 'Exercise', scenarioTitle: 'Redact Attacker IPs', scenario: 'You need to share your <code>access.log</code> with an external consultant, but you must redact all IP addresses to comply with privacy policies.', tasks: ['Use <code>sed</code> on <code>/tmp/itp141/access.log</code>', 'Replace all IPs with the word <code>[HIDDEN]</code>', 'Use Extended Regex <code>-E</code> for the IP pattern', 'Save the output to <code>access_sanitized.log</code> (do not modify original)'], term: [] },

    // 42. SED LAB 3 (SECTION C): SOLUTION
    { type: 'lab_solution', title: 'sed Lab 3 (Section C): Solution', subtitle: 'Solution', desc: 'Use sed with -E for regex substitution.', syntax: "sed -E 's/([0-9]{1,3}\\.){3}[0-9]{1,3}/[HIDDEN]/g' /tmp/itp141/access.log > /tmp/itp141/access_sanitized.log", term: [{p:'/tmp/itp141', c:"sed -E 's/([0-9]{1,3}\\.){3}[0-9]{1,3}/[HIDDEN]/g' access.log > access_sanitized.log"}, {p:'/tmp/itp141', c:'cat access_sanitized.log'}, {o:'[HIDDEN] - - GET /index.html 200'}, {o:'[HIDDEN] - - GET /missing.html 404'}, {o:'[HIDDEN] - - GET /admin.php 404'}, {o:'[HIDDEN] - - GET /style.css 200'}], explain: '<strong>Explanation:</strong> <code>-E</code> enables extended regex. The regex matches an IP address. <code>[HIDDEN]</code> replaces it. The <code>&gt;</code> redirects the output to a new file, keeping the original safe.' },

    // 43. SED LAB 4 (SECTION D): DATA TRANSFORMATION
    { type: 'lab', title: 'sed Lab 4 (Section D): Data Transformation', subtitle: 'Exercise', scenarioTitle: 'Replace Delimiters', scenario: 'The <code>users.csv</code> file uses tabs (<code>\\t</code>) to separate the names from the role. You need to replace all tabs with commas to make it a standard CSV.', tasks: ['Use <code>sed</code> on <code>/tmp/itp141/users.csv</code>', 'Search for the tab character <code>\\t</code>', 'Replace with a comma <code>,</code>', 'Remove any empty lines in the same command using <code>-e</code>'], term: [] },

    // 44. SED LAB 4 (SECTION D): SOLUTION
    { type: 'lab_solution', title: 'sed Lab 4 (Section D): Solution', subtitle: 'Solution', desc: 'Use sed to replace tabs and remove empty lines.', syntax: "sed -e 's/\\t/,/g' -e '/^$/d' /tmp/itp141/users.csv", term: [{p:'/tmp/itp141', c:"sed -e 's/\\t/,/g' -e '/^$/d' users.csv"}, {o:'Sacay,Ar-Jay,admin'}, {o:'Doe,John,editor'}, {o:'Smith,Jane,viewer'}], explain: '<strong>Explanation:</strong> The first <code>-e</code> globally (<code>g</code>) replaces tabs with commas; the second deletes empty lines. The result is a well-formed CSV. <strong>Portability note:</strong> <code>\\t</code> inside a pattern is a GNU extension, not POSIX. On BSD sed, insert a literal tab by pressing Ctrl+V then Tab.' },

    // 45. MASTER PIPELINE 1
    { type: 'lesson', category: 'Master Pipeline', title: 'Master Pipeline: Grep + Sed', subtitle: 'Redacting Logs', desc: 'Combine grep and sed in a pipe to extract data and transform it on the fly.', syntax: 'grep "404" access.log | sed "s/192.168.1.50/[REDACTED]/g"', term: [{p:'/tmp/itp141', c:'grep "404" access.log | sed "s/192.168.1.50/[REDACTED]/g"'}, {o:'[REDACTED] - - GET /missing.html 404'}, {o:'[REDACTED] - - GET /admin.php 404'}], explain: '<strong>Explanation:</strong> Grep finds all 404 errors. It passes those lines to Sed via the pipe (|). Sed replaces the attacker IP with "[REDACTED]" for privacy. This is how sysadmins create safe log reports.' },

    // 46. MASTER PIPELINE 2
    { type: 'lesson', category: 'Master Pipeline', title: 'Master Pipeline: Cleanup + Sort', subtitle: 'Generating Reports', desc: 'Extract data, clean it, count it, and sort it. A classic log analysis pipeline.', syntax: 'grep -o "IP" auth.log | sort | uniq -c | sort -nr', term: [{p:'/tmp/itp141', c:'grep -oE "^([0-9]{1,3}\\.){3}[0-9]{1,3}" access.log | sort | uniq -c | sort -nr'}, {o:'      2 192.168.1.50'}, {o:'      1 192.168.1.10'}, {o:'      1 10.0.0.5'}], explain: '<strong>Explanation:</strong> 1. Grep extracts only IPs. 2. Sort organizes them. 3. Uniq -c counts duplicates. 4. Sort -nr sorts the counts numerically in reverse (highest first). This reveals the top attacker.' },

    // 47. MASTER PIPELINE 3
    { type: 'lesson', category: 'Master Pipeline', title: 'Master Pipeline: Kill Process', subtitle: 'Process Management', desc: 'Find a running process, extract its PID, and kill it gracefully.', syntax: 'ps aux | grep sshd | grep -v grep | sed "s/  */ /g" | cut -d" " -f2 | xargs kill -15', term: [{p:'~', c:'ps aux | grep sshd | grep -v grep | sed "s/  */ /g" | cut -d" " -f2'}, {o:'101'}], explain: '<strong>Explanation:</strong> 1. Find sshd processes. 2. <code>grep -v grep</code> excludes the grep command itself, which would otherwise match its own pattern. 3. sed collapses runs of spaces to one. 4. <code>cut</code> takes column 2, the PID. <strong>Industry note:</strong> learn this pipeline to understand the parts, but in production use <code>pgrep sshd</code> and <code>pkill -15 sshd</code>. They query the process table directly and cannot match themselves.' },

    // 48. MASTER PIPELINE 4
    { type: 'lesson', category: 'Master Pipeline', title: 'Master Pipeline: CSV Transform', subtitle: 'Data Swapping', desc: 'Swap two CSV columns using sed capture groups.', syntax: 'sed -E "s/([^,]*),([^,]*)/\\2,\\1/"', term: [{p:'~', c:'echo "ajsacay,admin" | sed -E "s/([^,]*),([^,]*)/\\2,\\1/"'}, {o:'admin,ajsacay'}], explain: '<strong>Explanation:</strong> <code>([^,]*)</code> captures everything before the comma into group 1. The second captures everything after into group 2. <code>\\2,\\1</code> outputs them in reverse order.' },

    // 49. MASTER PIPELINE 5
    { type: 'lesson', category: 'Master Pipeline', title: 'Master Pipeline: Config Generation', subtitle: 'Automating Setup', desc: 'Extract active users, format them, and append to a new config file.', syntax: 'grep "bash" users.txt | sed "s/:.*//" > admins.txt', term: [{p:'/tmp/itp141', c:'grep "bash" users.txt | sed "s/:.*//" > admins.txt'}, {p:'/tmp/itp141', c:'cat admins.txt'}, {o:'admin'}, {o:'root'}], explain: '<strong>Explanation:</strong> Grep finds users with bash. Sed removes everything from the colon onwards (<code>:.*</code>), leaving only the username. The <code>&gt;</code> saves it to <code>admins.txt</code>.' },

    // 50. MASTER PIPELINE 6
    { type: 'lesson', category: 'Master Pipeline', title: 'Master Pipeline: Web Server Analysis', subtitle: 'Failed Requests', desc: 'Report exactly which pages returned an error, with the noise stripped away.', syntax: 'grep "404$" access.log | grep -oE "GET [^ ]+" | sed "s|GET ||"', term: [{p:'/tmp/itp141', c:'grep "404$" access.log | grep -oE "GET [^ ]+" | sed "s|GET ||"'}, {o:'/missing.html'}, {o:'/admin.php'}], explain: '<strong>Explanation:</strong> 1. <code>grep "404$"</code> keeps only failed requests. 2. <code>grep -oE "GET [^ ]+"</code> pulls out the verb and the path. 3. <code>sed</code> deletes the leading "GET ", using <code>|</code> as the delimiter so the slashes in the path need no escaping. The result is a clean list of the pages your users could not reach.' },

    // 51. FINAL TXT EXAMPLE SLIDE
    { type: 'lesson', category: 'Final Example', title: 'The Master Setup Script', subtitle: 'Generate All Data', desc: 'If you haven\'t run the setup script yet, copy this entire block and paste it into your Kali Linux terminal. It creates all the files needed for this lecture.', syntax: 'Copy and paste into terminal', term: [{raw:'<span class="cmd">mkdir -p /tmp/itp141 &amp;&amp; cd /tmp/itp141</span><br><span class="cmd">echo "192.168.1.10 - - GET /index.html 200" &gt; access.log</span><br><span class="cmd">echo "192.168.1.50 - - GET /missing.html 404" &gt;&gt; access.log</span><br><span class="cmd">echo "192.168.1.50 - - GET /admin.php 404" &gt;&gt; access.log</span><br><span class="cmd">echo "10.0.0.5 - - GET /style.css 200" &gt;&gt; access.log</span><br><span class="cmd">echo "admin:/bin/bash" &gt; users.txt</span><br><span class="cmd">echo "root:/bin/bash" &gt;&gt; users.txt</span><br><span class="cmd">echo "guest:/usr/sbin/nologin" &gt;&gt; users.txt</span><br><span class="cmd">echo "# SSH Config" &gt; sshd_config</span><br><span class="cmd">echo "Port 22" &gt;&gt; sshd_config</span><br><span class="cmd">echo "" &gt;&gt; sshd_config</span><br><span class="cmd">echo "PermitRootLogin no" &gt;&gt; sshd_config</span><br><span class="cmd">echo -e "Sacay,Ar-Jay\\tadmin" &gt; users.csv</span><br><span class="cmd">echo -e "Doe,John\\teditor" &gt;&gt; users.csv</span><br><span class="cmd">echo "" &gt;&gt; users.csv</span><br><span class="cmd">echo -e "Smith,Jane\\tviewer" &gt;&gt; users.csv</span><br><span class="cmd">echo "Setup complete!"</span><br><span class="out">Setup complete!</span>'}], explain: '<strong>Explanation:</strong> This creates a safe lab directory in <code>/tmp/itp141</code>. We populate <code>access.log</code>, <code>users.txt</code>, <code>sshd_config</code>, and <code>users.csv</code>. All examples and labs in this presentation use these files.' },

  {
    type: 'closing',
    header: 'MODULE 01 · TOPIC 02',
    tag: 'End of Topic 02',
    title: 'Text is the interface. <em>Automate</em> it.',
    quote: 'The best sysadmins do not edit files by hand. They write the command that edits the files for them.',
    leftCardNum: '§ grep',
    leftCardTitle: 'Filtering & Searching',
    leftCardDesc: 'From its origins in the ed editor, grep is the ultimate pattern matcher. Master flags like -i, -v, and -E to refine searches.',
    middleCardNum: '§ sed',
    middleCardTitle: 'Streams & Editing',
    middleCardDesc: 'sed automates text editing. Master the substitution command s/old/new/g and the in-place flag -i for mass configuration.',
    rightCardNum: '§ automation',
    rightCardTitle: 'Pipelines',
    rightCardDesc: 'Combine grep and sed in pipelines to transform raw log data into useful, actionable insight without manual editing.'
  }
];
