const slideConfigs = [
  // --- 1. COVER SLIDE ---
  {
    type: 'cover',
    moduleTitle: 'MODULE 01 · TOPIC 07 · PART 2',
    topicNum: '07',
    topicTag: 'T7',
    title: 'Dual-OS Installation<br>& Post-Config <em>Part 2</em>',
    subtitle: 'Completing the dual-OS environment: Installing Ubuntu Server 24.04 LTS, configuring Netplan networking, and verifying cross-VM SSH connectivity.',
    graphicText: 'Install <em>Ubuntu</em><br>Configure <em>Netplan</em><br>Connect both VMs.',
    miniObjectives: [
      'Install Ubuntu Server 24.04 LTS', 
      'Configure Netplan Static IP', 
      'Setup SSH & Hostname', 
      'Verify Ping & SSH Connectivity'
    ]
  },

  // --- 2. OBJECTIVES SLIDE ---
  {
    type: 'objectives',
    header: 'MODULE 01 · TOPIC 07',
    kicker: 'ITP 141 · M1 · T7',
    desc: 'In Part 1, we configured Windows Server 2022. Now, we will install Ubuntu Server, configure its network, and bridge the two operating systems together.',
    lede: 'A dual-OS lab is not complete until the servers can talk to each other. We will configure bridged networking and test SSH connectivity.',
    list: [
      'Install Ubuntu Server 24.04 LTS as a second VirtualBox VM.',
      'Post-configure Ubuntu hostname and timezone using hostnamectl.',
      'Configure a static IP address using Netplan YAML configuration.',
      'Verify and manage the SSH service (systemctl status ssh).',
      'Configure UFW firewall to allow SSH traffic securely.',
      'Ensure both VMs are on the same Bridged Network.',
      'Verify cross-OS SSH connectivity and file transfers (SCP).',
      'Complete Lab 1C: Dual-OS Installation and Post-Configuration.'
    ]
  },

  // 1. Topic Overview
  { type: 'lesson', category: 'Overview', title: 'Dual-OS: The Linux Side', subtitle: 'Topic Overview', desc: 'In Part 1, we set up Windows Server 2022 in VirtualBox. Now, we will install Ubuntu Server 24.04 LTS as our second VM and configure the network so both servers can communicate.', syntax: 'Windows Server: 192.168.1.10\nUbuntu Server:  192.168.1.20', term: [{raw: '<span class="out" style="color:#E8A07A">Dual-OS Lab Architecture</span><br><br><span class="out">[ Windows Host ]</span><br><span class="out">      |</span><br><span class="out">      |-- Bridged Adapter (LAN)</span><br><span class="out">      |</span><br><span class="out">      |-- [ WIN-SRV-01 (192.168.1.10) ]</span><br><span class="out">      |</span><br><span class="out">      |-- [ UBU-SRV-01 (192.168.1.20) ]</span>'}], explain: '<strong>Explanation:</strong> Both VirtualBox VMs must be configured to use "Bridged Adapter" in their network settings. This places them on your physical network, allowing them to talk to each other and the internet.' },
  
  // 2. VBox Setup for Ubuntu
  { type: 'lesson', category: 'VirtualBox', title: 'VirtualBox: Ubuntu Setup', subtitle: 'VM Specs', desc: 'Create a new VM in VirtualBox for Ubuntu Server 24.04 LTS. It requires fewer resources than Windows Server.', syntax: 'Name: UBU-SRV-01\nType: Linux\nVersion: Ubuntu (64-bit)\nRAM: 2048 MB (2GB)\nDisk: 25.00 GB', term: [{raw: '<span class="out" style="color:#E8A07A">VirtualBox Manager</span><br><span class="out">[ ] Name: UBU-SRV-01</span><br><span class="out">[ ] ISO Image: ubuntu-24.04-live-server-amd64.iso</span><br><span class="out">[ ] Base Memory: 2048 MB</span><br><span class="out">[ ] Processors: 2</span><br><span class="out">[ ] Disk Size: 25.00 GB</span><br><span class="out">(Ensure Network is set to Bridged)</span>'}], explain: '<strong>Explanation:</strong> Ubuntu Server is lightweight and runs well on 2GB of RAM. Ensure the network adapter is set to "Bridged" just like the Windows Server VM so they can share the same subnet.' },
  
  // 3. VBox Virtual Hard Disk
  { type: 'lesson', category: 'VirtualBox', title: 'VBox: Virtual Hard Disk', subtitle: 'Dynamic vs Fixed', desc: 'When creating the VM, choose a Virtual Hard Disk. You can select "Dynamically allocated" (grows as needed) or "Fixed size" (faster but uses full space immediately).', syntax: 'File Type: VDI (VirtualBox Disk Image)\nStorage: Dynamically allocated\nSize: 25.00 GB', term: [{raw: '<span class="out" style="color:#E8A07A">VirtualBox Disk Creation</span><br><span class="out">[X] Dynamically allocated</span><br><span class="out">[ ] Fixed size</span><br><br><span class="out">Location: UBU-SRV-01.vdi</span><br><span class="out">Size: 25.00 GB</span>'}], explain: '<strong>Explanation:</strong> For labs, "Dynamically allocated" is best because it only consumes physical disk space as the VM uses it. A fixed-size disk takes longer to create but offers slightly better read/write performance for production servers.' },
  
  // 4. Ubuntu Install: Boot & Network
  { type: 'lesson', category: 'Ubuntu Install', title: 'Ubuntu: Install', subtitle: 'Boot & Network', desc: 'Boot the VM from the Ubuntu ISO. The installer will attempt to auto-configure the network via DHCP. We will accept this now and set a static IP later via Netplan.', syntax: 'Language: English\nInstaller update available: Continue without updating\nNetwork: Auto (DHCP)', term: [{raw: '<span class="out" style="color:#E8A07A">Ubuntu Installer</span><br><span class="out">[x] English</span><br><span class="out">[x] Continue without updating</span><br><br><span class="out" style="color:#E8A07A">Network connections</span><br><span class="out">eth0: (Auto)</span><br><span class="out">DHCPv4 IP: 192.168.1.115</span><br><br><span class="out">(Press Enter to accept DHCP for now)</span>'}], explain: '<strong>Explanation:</strong> The Ubuntu installer uses a text-based menu (Subiquity). It will detect your bridged network adapter and attempt to get an IP. We will change this to a static IP after installation using Netplan.' },
  
  // 5. Ubuntu Install: Storage & Profile
  { type: 'lesson', category: 'Ubuntu Install', title: 'Ubuntu: Install', subtitle: 'Storage & Profile', desc: 'Use the guided storage setup to use the entire virtual disk. Then, create your standard Linux user account and hostname.', syntax: 'Storage: Use an entire disk (Set up as LVM)\nName: Ar-Jay Sacay\nServer Name: ubu-srv-01\nUsername: ajsacay', term: [{raw: '<span class="out" style="color:#E8A07A">Storage configuration</span><br><span class="out">[X] Use an entire disk</span><br><span class="out">[X] Set up this disk as an LVM group</span><br><br><span class="out" style="color:#E8A07A">Profile setup</span><br><span class="out">Your name: Ar-Jay Sacay</span><br><span class="out">Your server\'s name: ubu-srv-01</span><br><span class="out">Pick a username: ajsacay</span><br><span class="out">Choose a password: ********</span>'}], explain: '<strong>Explanation:</strong> LVM (Logical Volume Manager) allows you to resize partitions later. The server name becomes the hostname. Create a strong password for your admin account.' },
  
  // 6. Ubuntu Install: SSH Setup
  { type: 'lesson', category: 'Ubuntu Install', title: 'Ubuntu: Install', subtitle: 'SSH Server Setup', desc: 'On the Ubuntu Server feature selection screen, you MUST press the Spacebar to select the OpenSSH server package.', syntax: 'Press SPACEBAR to select: [X] Install OpenSSH server', term: [{raw: '<span class="out" style="color:#E8A07A">SSH Setup</span><br><span class="out">[X] Install OpenSSH server</span><br><span class="out">Import SSH identity: No</span><br><br><span class="out" style="color:#E8A07A">Featured Server Snaps</span><br><span class="out">[ ] Docker</span><br><span class="out">[ ] MicroK8s</span><br><br><span class="out">(Tab to \'Done\' and press Enter)</span>'}], explain: '<strong>Explanation:</strong> If you miss this step, you will not be able to SSH into the server remotely. Pressing Spacebar inserts an [X]. Do not select Docker here, as we will install it manually in a later module.' },
  
  // 7. Post-Config: Update
  { type: 'lesson', category: 'Post-Config', title: 'Ubuntu: Post-Config', subtitle: 'Update & Upgrade', desc: 'After installation and reboot, log in with your username and password. The first task is to update the package list and upgrade all software.', syntax: 'sudo apt update && sudo apt upgrade -y', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt update && sudo apt upgrade -y</span><br><span class="out">[sudo] password for ajsacay:</span><br><span class="out">Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease</span><br><span class="out">Reading package lists... Done</span><br><span class="out">Building dependency tree... Done</span><br><span class="out">The following packages will be upgraded:</span><br><span class="out">42 upgraded, 0 newly installed, 0 to remove.</span>'}], explain: '<strong>Explanation:</strong> The Ubuntu ISO might be slightly outdated. <code>apt update</code> refreshes the list of available packages, and <code>upgrade -y</code> installs any available updates automatically.' },
  
  // 8. Post-Config: Hostname & Timezone
  { type: 'lesson', category: 'Post-Config', title: 'Ubuntu: Post-Config', subtitle: 'Hostname & Timezone', desc: 'Verify your hostname is correct. Then, set the timezone to match your location (Asia/Manila).', syntax: 'hostnamectl set-hostname UBU-SRV-01\ntimedatectl set-timezone Asia/Manila', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">hostnamectl set-hostname UBU-SRV-01</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">timedatectl set-timezone Asia/Manila</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">timedatectl</span><br><span class="out">               Local time: Wed 2024-10-24 10:00:00 PST</span><br><span class="out">               Universal time: Wed 2024-10-24 02:00:00 UTC</span><br><span class="out">               Time zone: Asia/Manila (PST, +0800)</span>'}], explain: '<strong>Explanation:</strong> Setting the correct timezone ensures your log timestamps are accurate. <code>hostnamectl</code> and <code>timedatectl</code> are part of the systemd suite, which Ubuntu uses for system management.' },
  
  // 9. Post-Config: Time Sync (Chrony)
  { type: 'lesson', category: 'Post-Config', title: 'Ubuntu: Post-Config', subtitle: 'Time Sync (NTP)', desc: 'Active Directory and Kerberos require strict time synchronization. Ubuntu uses <code>chrony</code> or <code>systemd-timesyncd</code> to keep the clock accurate.', syntax: 'timedatectl set-ntp true', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo timedatectl set-ntp true</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">timedatectl status</span><br><span class="out">               Local time: Wed 2024-10-24 10:15:00 PST</span><br><span class="out">               Network time on: yes</span><br><span class="out">               NTP synchronized: yes</span><br><span class="out">               RTC in local TZ: no</span>'}], explain: '<strong>Explanation:</strong> If "NTP synchronized" is "no", the server is not syncing with internet time servers. This command enables the built-in NTP client, which is essential before joining the server to a Windows AD domain later.' },
  
  // 10. Netplan: Introduction
  { type: 'lesson', category: 'Networking', title: 'Netplan: Introduction', subtitle: 'Modern Linux Networking', desc: 'Ubuntu uses Netplan for network configuration. Configuration files are written in YAML format and located in <code>/etc/netplan/</code>.', syntax: 'cd /etc/netplan/\nls\n# Usually 01-netcfg.yaml or 50-cloud-init.yaml', term: [{raw: '<span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">cd /etc/netplan/</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">/etc/netplan</span>$</span> <span class="cmd">ls</span><br><span class="out">50-cloud-init.yaml</span>'}], explain: '<strong>Explanation:</strong> Netplan replaces the traditional <code>/etc/network/interfaces</code> file. You must use spaces (not tabs) for indentation in YAML files, or the configuration will fail.' },
  
  // 11. Netplan: Identify Interface
  { type: 'lesson', category: 'Networking', title: 'Netplan: Identify Interface', subtitle: 'ip a', desc: 'Before configuring a static IP, find the name of your network interface using the <code>ip a</code> command.', syntax: 'ip a | grep eth0\n# OR enp0s3', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ip a</span><br><span class="out">1: lo: &lt;LOOPBACK,UP,LOWER_UP&gt; mtu 65536...</span><br><span class="out">2: enp0s3: &lt;BROADCAST,MULTICAST,UP,LOWER_UP&gt; mtu 1500...</span><br><span class="out">    link/ether 08:00:27:a8:12:45 brd ff:ff:ff:ff:ff:ff</span><br><span class="out">    inet 192.168.1.115/24 metric 100 brd 192.168.1.255 scope global dynamic enp0s3</span>'}], explain: '<strong>Explanation:</strong> In VirtualBox, the network interface is usually named <code>enp0s3</code> or <code>eth0</code>. Note this name down, as you will need it for the Netplan configuration file.' },
  
  // 12. Netplan: YAML Syntax Rules
  { type: 'lesson', category: 'Networking', title: 'Netplan: YAML Syntax', subtitle: 'Strict Rules', desc: 'YAML is strict about formatting. A single mistake in spacing will cause the network to fail to apply. Follow these rules strictly.', syntax: '# 1. Use SPACES, never TABS\n# 2. Indentation must be consistent (2 spaces per level)\n# 3. Colons must be followed by a space', term: [{raw: '<span class="out" style="color:#E8A07A">YAML Rules</span><br><br><span class="out">CORRECT:</span><br><span class="out">network:</span><br><span class="out">  version: 2</span><br><span class="out">  ethernets:</span><br><span class="out">    enp0s3:</span><br><br><span class="err">INCORRECT (Tab used):</span><br><span class="out">network:</span><br><span class="out">[TAB]version: 2</span>'}], explain: '<strong>Explanation:</strong> If <code>netplan apply</code> fails, it is almost always a YAML syntax error. Nano does not show tabs vs spaces visually, so use the spacebar exclusively when editing Netplan files.' },
  
  // 13. Netplan: Creating the Config
  { type: 'lesson', category: 'Networking', title: 'Netplan: Static IP Config', subtitle: 'YAML Configuration', desc: 'Edit the Netplan YAML file using <code>nano</code>. Set the static IP to 192.168.1.20 for the Ubuntu server. Ensure DHCP is set to false.', syntax: 'network:\n  version: 2\n  ethernets:\n    enp0s3:\n      dhcp4: false\n      addresses: [192.168.1.20/24]\n      gateway4: 192.168.1.1\n      nameservers:\n        addresses: [8.8.8.8, 1.1.1.1]', term: [{editor: "/etc/netplan/50-cloud-init.yaml", code: "network:\n  version: 2\n  ethernets:\n    enp0s3:\n      dhcp4: false\n      addresses: [192.168.1.20/24]\n      gateway4: 192.168.1.1\n      nameservers:\n        addresses: [8.8.8.8, 1.1.1.1]"}], explain: '<strong>Explanation:</strong> We disable DHCP and assign the static IP <code>192.168.1.20</code>. The gateway is your router\'s IP. The nameservers are Google and Cloudflare DNS. Save the file with <code>Ctrl+O</code> and exit with <code>Ctrl+X</code>.' },
  
  // 14. Netplan: Apply Config
  { type: 'lesson', category: 'Networking', title: 'Netplan: Apply Config', subtitle: 'netplan apply', desc: 'Apply the new network configuration. If you make a mistake in the YAML, the command will fail and warn you.', syntax: 'sudo netplan apply\nip a show enp0s3', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo netplan apply</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ip a show enp0s3</span><br><span class="out">2: enp0s3: &lt;BROADCAST,MULTICAST,UP,LOWER_UP&gt; mtu 1500...</span><br><span class="out">    inet 192.168.1.20/24 brd 192.168.1.255 scope global enp0s3</span>'}], explain: '<strong>Explanation:</strong> The <code>netplan apply</code> command reads the YAML file and applies it to the system. The <code>ip a show</code> command confirms our Ubuntu server now has the static IP 192.168.1.20.' },
  
  // 15. Netplan: Troubleshooting
  { type: 'lesson', category: 'Networking', title: 'Netplan: Troubleshooting', subtitle: 'netplan try', desc: 'If you are worried about losing your SSH connection due to a bad configuration, use <code>netplan try</code>. It applies the config temporarily and reverts if you do not press Enter.', syntax: 'sudo netplan try', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo netplan try</span><br><span class="out">Warning: Stopping systemd-networkd, but it should still start up properly.</span><br><span class="out">Do you want to keep these settings?</span><br><span class="out">Press ENTER before the timeout to accept the new configuration</span><br><span class="out">Configuration accepted.</span>'}], explain: '<strong>Explanation:</strong> <code>netplan try</code> gives you 120 seconds to test the new configuration. If your SSH session drops and you cannot type Enter, it automatically reverts to the old configuration, preventing you from locking yourself out.' },
  
  // 16. SSH: Verify Service
  { type: 'lesson', category: 'Services', title: 'SSH: Verify Service', subtitle: 'systemctl status', desc: 'During installation, we selected the OpenSSH server. Let us verify the service is running and enabled to start on boot.', syntax: 'systemctl status ssh\nsystemctl enable ssh', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">systemctl status ssh</span><br><span class="out">● ssh.service - OpenBSD Secure Shell server</span><br><span class="out">     Loaded: loaded (/lib/systemd/system/ssh.service; enabled; preset: enabled)</span><br><span class="out">     Active: active (running) since Wed 2024-10-24 10:00:00 PST; 5min ago</span>'}], explain: '<strong>Explanation:</strong> If it shows <code>active (running)</code>, the SSH daemon is working. Ubuntu 24.04 enables it by default, but running <code>systemctl enable ssh</code> guarantees it will survive a reboot.' },
  
  // 17. SSH: Hardening
  { type: 'lesson', category: 'Security', title: 'SSH: Hardening', subtitle: 'sshd_config', desc: 'Once keys are working, disable password authentication and root login in the SSH daemon config. This stops all brute-force attacks instantly.', syntax: 'sudo nano /etc/ssh/sshd_config', term: [{editor: "/etc/ssh/sshd_config", code: "# Change these settings to NO\nPasswordAuthentication no\nChallengeResponseAuthentication no\nUsePAM no\n\n# Optional but good: Only allow specific users\nAllowUsers ajsacay dev_user\n\n# Disable root login over SSH\nPermitRootLogin no"}], explain: '<strong>Explanation:</strong> <strong>WARNING:</strong> Do not close your current SSH session until you have tested the key login in a second window. If you disable passwords and your key does not work, you will be permanently locked out of the server.' },
  
  // 18. SSH: Key-Based Auth
  { type: 'lesson', category: 'Security', title: 'SSH: Key-Based Auth', subtitle: 'Keys vs Passwords', desc: 'Passwords can be guessed. SSH keys are cryptographic tokens that are impossible to brute-force. They are the standard for secure server administration.', syntax: 'Password: 14 chars, complex (Can be guessed).\nKey: 256-bit ed25519 (Impossible to guess).', term: [{raw: '<span class="out" style="color:#E8A07A">How it works</span><br><span class="out">- Private Key: Stays on YOUR laptop. Never shared.</span><br><span class="out">- Public Key: Placed on the server in ~/.ssh/authorized_keys.</span><br><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">ssh-keygen -t ed25519</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">ssh-copy-id ajsacay@192.168.1.20</span>'}], explain: '<strong>Explanation:</strong> If you disable password authentication entirely, botnets can hammer your SSH port forever and never get in. They do not have the private key. This is the single most effective hardening step.' },
  
  // 19. UFW: Firewall Config
  { type: 'lesson', category: 'Security', title: 'UFW: Firewall Config', subtitle: 'Uncomplicated Firewall', desc: 'Ubuntu includes UFW (Uncomplicated Firewall). We must explicitly allow SSH traffic before enabling the firewall, or we will lock ourselves out.', syntax: 'sudo ufw allow ssh\nsudo ufw enable', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw allow ssh</span><br><span class="out">Rules updated</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw enable</span><br><span class="out">Command may disrupt existing ssh connections. Proceed with operation (y|n)? y</span><br><span class="out">Firewall is active and enabled on system startup</span>'}], explain: '<strong>Explanation:</strong> <code>ufw allow ssh</code> opens port 22 for TCP traffic. <code>ufw enable</code> turns the firewall on. It blocks all incoming traffic by default except for the rules we explicitly allow, securing the server.' },
  
  // 20. UFW: Status & Deleting
  { type: 'lesson', category: 'Security', title: 'UFW: Status & Deleting', subtitle: 'Managing Rules', desc: 'Verify your firewall rules and learn how to delete rules that are no longer needed to close unused ports.', syntax: 'sudo ufw status verbose\nsudo ufw delete allow http', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw status verbose</span><br><span class="out">Status: active</span><br><span class="out">Default: deny (incoming), allow (outgoing)</span><br><span class="out">22/tcp                     ALLOW IN   Anywhere</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw delete allow http</span><br><span class="out">Rule deleted</span>'}], explain: '<strong>Explanation:</strong> Leaving unused ports open is a major security risk. If you installed Apache for testing but no longer use it, delete the port 80 rule using <code>ufw delete</code> to close the attack surface.' },
  
  // 21. Cross-OS Topology Review
  { type: 'lesson', category: 'Connectivity', title: 'Cross-OS Topology', subtitle: 'The Network Map', desc: 'Both VMs should now be on the same physical network via VirtualBox Bridged Adapters. Let us review our IP addresses before testing connectivity.', syntax: 'WIN-SRV-01: 192.168.1.10 (Windows)\nUBU-SRV-01: 192.168.1.20 (Ubuntu)', term: [{raw: '<span class="out" style="color:#E8A07A">Local Area Network (192.168.1.0/24)</span><br><br><span class="out">Router (192.168.1.1)</span><br><span class="out">   |</span><br><span class="out">   +-- Host Machine (Windows 10/11)</span><br><span class="out">   |</span><br><span class="out">   +-- WIN-SRV-01 (192.168.1.10)  [VirtualBox Bridged]</span><br><span class="out">   |</span><br><span class="out">   +-- UBU-SRV-01 (192.168.1.20)  [VirtualBox Bridged]</span>'}], explain: '<strong>Explanation:</strong> Because both VMs are bridged, they act like physical machines on the router. They should be able to ping each other without any firewall port forwarding rules.' },
  
  // 22. Test: Ping Ubuntu to Windows
  { type: 'lesson', category: 'Connectivity', title: 'Testing: Ping (Ubuntu to Win)', subtitle: 'Step 1', desc: 'From the Ubuntu VM, ping the Windows Server IP address to verify basic network reachability.', syntax: 'ping -c 4 192.168.1.10', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ping -c 4 192.168.1.10</span><br><span class="out">PING 192.168.1.10 (192.168.1.10) 56(84) bytes of data.</span><br><span class="out">64 bytes from 192.168.1.10: icmp_seq=1 ttl=128 time=0.521 ms</span><br><span class="out">64 bytes from 192.168.1.10: icmp_seq=2 ttl=128 time=0.485 ms</span><br><br><span class="out">--- 192.168.1.10 ping statistics ---</span><br><span class="out">4 packets transmitted, 4 received, 0% packet loss</span>'}], explain: '<strong>Explanation:</strong> The <code>-c 4</code> flag tells Linux to send exactly 4 ping packets and then stop. A successful reply confirms Windows Server is reachable on the network layer.' },
  
  // 23. Test: Ping Windows to Ubuntu
  { type: 'lesson', category: 'Connectivity', title: 'Testing: Ping (Win to Ubuntu)', subtitle: 'Step 2', desc: 'From the Windows Server VM (or your Windows host), ping the Ubuntu Server IP address.', syntax: 'ping 192.168.1.20', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> ping 192.168.1.20</span><br><span class="out">Pinging 192.168.1.20 with 32 bytes of data:</span><br><span class="out">Reply from 192.168.1.20: bytes=32 time=1ms TTL=64</span><br><span class="out">Reply from 192.168.1.20: bytes=32 time=1ms TTL=64</span><br><br><span class="out">Ping statistics for 192.168.1.20:</span><br><span class="out">Packets: Sent = 4, Received = 4, Lost = 0 (0% loss)</span>'}], explain: '<strong>Explanation:</strong> Ubuntu allows ICMP echo requests (pings) by default via its UFW firewall configuration. A successful reply confirms bidirectional connectivity.' },
  
  // 24. Test: SSH from Windows to Ubuntu
  { type: 'lesson', category: 'Connectivity', title: 'Testing: SSH (Win to Ubuntu)', subtitle: 'Step 3', desc: 'Windows 10/11 and Windows Server 2022 have a built-in SSH client. You can use PowerShell to securely connect to the Ubuntu server.', syntax: 'ssh ajsacay@192.168.1.20', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> ssh ajsacay@192.168.1.20</span><br><span class="out">The authenticity of host \'192.168.1.20\' can\'t be established.</span><br><span class="out">Are you sure you want to continue connecting (yes/no)? yes</span><br><span class="out">ajsacay@192.168.1.20\'s password:</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">hostname</span><br><span class="out">UBU-SRV-01</span>'}], explain: '<strong>Explanation:</strong> The first time you connect, SSH asks you to verify the host key. Type <code>yes</code> and press Enter. After entering your password, your PowerShell prompt changes to a Linux Bash prompt. You are now remotely managing Linux from Windows!' },
  
  // 25. DNS: Windows Hosts File
  { type: 'lesson', category: 'DNS', title: 'Hostname Resolution', subtitle: 'Windows Hosts File', desc: 'Instead of memorizing IP addresses, edit the Windows <code>hosts</code> file to map the Ubuntu IP to a hostname.', syntax: '# File: C:\\Windows\\System32\\drivers\\etc\\hosts\n192.168.1.20 ubu-srv-01', term: [{editor: "C:\\Windows\\System32\\drivers\\etc\\hosts", code: "# localhost name resolution is handled within DNS itself.\n127.0.0.1       localhost\n::1             localhost\n\n# ITP 141 Lab VMs\n192.168.1.10    win-srv-01\n192.168.1.20    ubu-srv-01"}, {raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> ping ubu-srv-01</span><br><span class="out">Pinging ubu-srv-01 [192.168.1.20] with 32 bytes of data:</span><br><span class="out">Reply from 192.168.1.20: bytes=32 time=1ms TTL=64</span>'}], explain: '<strong>Explanation:</strong> The <code>hosts</code> file is a local DNS override. By adding the Ubuntu server\'s IP and hostname here, you can use <code>ping ubu-srv-01</code> or <code>ssh ajsacay@ubu-srv-01</code> instead of the IP. You must open Notepad as Administrator to save this file.' },
  
  // 26. DNS: Ubuntu Hosts File
  { type: 'lesson', category: 'DNS', title: 'Hostname Resolution', subtitle: 'Ubuntu Hosts File', desc: 'Do the same on the Ubuntu server so it can ping the Windows server by name.', syntax: '# File: /etc/hosts\n192.168.1.10 win-srv-01', term: [{editor: "/etc/hosts", code: "127.0.0.1 localhost\n127.0.1.1 ubu-srv-01\n\n# The following lines are desirable for IPv6 capable hosts\n::1     ip6-localhost ip6-loopback\nff02::1 ip6-allnodes\nff02::2 ip6-allrouters\n\n# ITP 141 Lab VMs\n192.168.1.10    win-srv-01\n192.168.1.20    ubu-srv-01"}, {raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ping -c 2 win-srv-01</span><br><span class="out">PING win-srv-01 (192.168.1.10) 56(84) bytes of data.</span><br><span class="out">64 bytes from win-srv-01 (192.168.1.10): icmp_seq=1 ttl=128 time=0.521 ms</span>'}], explain: '<strong>Explanation:</strong> Linux uses the same <code>/etc/hosts</code> file mechanism for static DNS resolution. Now both servers can resolve each other by name, which is highly useful for SSH and future AD/DNS configurations.' },
  
  // 27. Connectivity: SSH to Windows Server
  { type: 'lesson', category: 'Connectivity', title: 'SSH: Ubuntu to Windows', subtitle: 'OpenSSH Server on Win', desc: 'Windows Server 2022 includes an OpenSSH Server feature. You can enable it to allow the Ubuntu server to SSH into the Windows server.', syntax: '# In Windows PowerShell (Admin):\nAdd-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0\nStart-Service sshd', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0</span><br><span class="cmd">> Start-Service sshd</span><br><span class="cmd">> Set-Service -Name sshd -StartupType \'Automatic\'</span><br><br><span class="out" style="color:#E8A07A">From Ubuntu Server</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ssh administrator@192.168.1.10</span><br><span class="out">administrator@192.168.1.10\'s password: ********</span><br><span class="prompt" style="color:#27C93F">administrator@WIN-SRV-01 C:\\Users\\Administrator&gt;</span>'}], explain: '<strong>Explanation:</strong> Enabling the SSH server on Windows allows true bidirectional management. When you SSH into Windows, you drop into a PowerShell prompt (<code>cmd.exe</code> or <code>powershell.exe</code>), not a Bash shell.' },
  
  // 28. File Transfer: SCP (Files)
  { type: 'lesson', category: 'File Transfer', title: 'File Transfer: SCP', subtitle: 'Secure Copy Protocol', desc: 'SCP uses SSH to securely transfer files between the Windows and Linux VMs without needing a shared folder or USB drive.', syntax: '# Windows to Ubuntu:\nscp C:\\labs\\script.sh ajsacay@192.168.1.20:/home/ajsacay/', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> scp C:\\labs\\backup.sh ajsacay@192.168.1.20:/home/ajsacay/</span><br><span class="out">ajsacay@192.168.1.20\'s password:</span><br><span class="out">backup.sh                      100% 1024     1.0KB/s   00:00</span><br><br><span class="out" style="color:#E8A07A">Ubuntu Server</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ls -lh backup.sh</span><br><span class="out">-rw-r--r-- 1 ajsacay ajsacay 1.0K Oct 24 10:15 backup.sh</span>'}], explain: '<strong>Explanation:</strong> The syntax is <code>scp [source] [destination]</code>. You can copy from Windows to Linux or Linux to Windows. The transfer is encrypted over the SSH protocol (port 22).' },
  
  // 29. File Transfer: SCP (Directories)
  { type: 'lesson', category: 'File Transfer', title: 'File Transfer: SCP Directories', subtitle: 'Recursive Copy', desc: 'To copy an entire directory and all its contents, use the <code>-r</code> (recursive) flag with SCP.', syntax: 'scp -r C:\\labs\\ ajsacay@192.168.1.20:/home/ajsacay/', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> scp -r C:\\labs\\ ajsacay@192.168.1.20:/home/ajsacay/</span><br><span class="out">ajsacay@192.168.1.20\'s password:</span><br><span class="out">backup.sh                      100% 1024     1.0KB/s   00:00</span><br><span class="out">deploy.sh                      100% 2048     2.0KB/s   00:00</span><br><span class="out">logs/</span><br><span class="out">logs/syslog                    100% 5120     5.0KB/s   00:00</span>'}], explain: '<strong>Explanation:</strong> The <code>-r</code> flag tells SCP to descend into directories. This is highly useful for backing up configuration directories or transferring project folders between the two VMs in one command.' },
  
  // 30. VBox: Shared Folders
  { type: 'lesson', category: 'File Transfer', title: 'VBox: Shared Folders', subtitle: 'Alternative to SCP', desc: 'VirtualBox allows you to mount a directory from your physical Windows host directly into the Ubuntu VM. This requires VirtualBox Guest Additions.', syntax: 'sudo mount -t vboxsf shared_folder /mnt/shared', term: [{raw: '<span class="out" style="color:#E8A07A">VirtualBox Settings -> Shared Folders</span><br><span class="out">Folder Path: C:\\Users\\Admin\\Desktop\\shared</span><br><span class="out">Folder Name: shared_folder</span><br><span class="out">[X] Auto-mount</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo mount -t vboxsf shared_folder /mnt/shared</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ls /mnt/shared</span><br><span class="out">notes.txt  scripts.zip</span>'}], explain: '<strong>Explanation:</strong> Shared folders are very fast for moving large files between the host and VM. However, they require Guest Additions installed on Linux, and permissions can be tricky.' },
  
  // 31. VBox: Shared Folders Permissions
  { type: 'lesson', category: 'File Transfer', title: 'VBox: Permissions', subtitle: 'vboxsf Group', desc: 'By default, VirtualBox shared folders are owned by root. To allow your standard user to write to the folder, add your user to the <code>vboxsf</code> group.', syntax: 'sudo usermod -aG vboxsf $USER', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo usermod -aG vboxsf $USER</span><br><br><span class="out" style="color:#E8A07A">Why?</span><br><span class="out">If you try to create a file in the shared folder without this, you get "Permission denied".</span><br><br><span class="out" style="color:#E8A07A">Apply the change</span><br><span class="out">You must log out and log back in (or reboot the VM) for the group membership to take effect.</span>'}], explain: '<strong>Explanation:</strong> The <code>vboxsf</code> group has read/write access to VirtualBox shared folders. The <code>-aG</code> flags append your user to this group. This is a common stumbling block when using shared folders for development.' },
  
  // 32. Ubuntu: System Health Checks
  { type: 'lesson', category: 'Sysadmin Tools', title: 'Ubuntu: System Health', subtitle: 'Post-Install Checks', desc: 'After setting up the Ubuntu server, verify its health. Check system uptime, memory usage, and disk space.', syntax: 'uptime\nfree -h\ndf -h', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">uptime</span><br><span class="out"> 10:30:15 up  0:30,  1 user,  load average: 0.00, 0.01, 0.05</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">free -h</span><br><span class="out">               total        used        free      shared  buff/cache   available</span><br><span class="out">Mem:           2.0Gi       200Mi       1.5Gi        10Mi       300Mi       1.6Gi</span><br><span class="out">Swap:          2.0Gi          0B       2.0Gi</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">df -h</span><br><span class="out">Filesystem      Size  Used Avail Use% Mounted on</span><br><span class="out">/dev/sda2        24G  8.5G   14G  39% /</span>'}], explain: '<strong>Explanation:</strong> <code>uptime</code> shows how long the server has been running and its load average. <code>free -h</code> shows RAM usage in human-readable format. <code>df -h</code> shows disk space. Ensuring these metrics are healthy is the sysadmin\'s first post-installation check.' },
  
  // 33. Ubuntu: Checking Logs
  { type: 'lesson', category: 'Sysadmin Tools', title: 'Ubuntu: Checking Logs', subtitle: 'journalctl', desc: 'In Windows, we use Event Viewer. In Ubuntu, we use <code>journalctl</code> to view system logs and <code>tail</code> to monitor them in real-time.', syntax: 'journalctl -p err -u ssh.service\ntail -f /var/log/syslog', term: [{raw: '<span class="prompt"><span class="user">admin@ubu-lab</span>:<span class="path">~</span>$</span> <span class="cmd">journalctl -p err -u ssh.service</span><br><span class="out">-- Logs begin at Wed 2024-10-24 10:00:00 PST, end at 10:15:00. --</span><br><span class="out">Oct 24 10:00:00 ubu-lab systemd[1]: Started OpenBSD Secure Shell server.</span><br><br><span class="prompt"><span class="user">admin@ubu-lab</span>:<span class="path">~</span>$</span> <span class="cmd">tail -f /var/log/syslog</span><br><span class="out">Oct 24 10:15:01 ubu-lab systemd[1]: Started Daily apt download activities.</span>'}], explain: '<strong>Explanation:</strong> <code>journalctl -p err</code> filters logs to show only errors. The <code>-u</code> flag filters by a specific service (like SSH). <code>tail -f</code> streams new log entries live, which is essential for real-time troubleshooting.' },
  
  // 34. Dual-OS Workflow
  { type: 'lesson', category: 'Summary', title: 'Dual-OS Workflow', subtitle: 'How to use this lab', desc: 'Now that both servers are running and connected, you can use Windows as your primary desktop and manage the Linux server via SSH.', syntax: '# On Windows:\nssh admin@192.168.1.20\n# Or use VS Code Remote-SSH', term: [{raw: '<span class="out" style="color:#E8A07A">Recommended Workflow:</span><br><span class="out">1. Use Windows 10/11 as your host OS</span><br><span class="out">2. Use VirtualBox for Windows Server 2022 (RDP into it)</span><br><span class="out">3. Use VirtualBox for Ubuntu Server 24.04 (SSH into it)</span><br><span class="out">4. Use VS Code with the "Remote - SSH" extension to edit Linux files</span><br><br><span class="out">You rarely need to look at the VirtualBox console window!</span>'}], explain: '<strong>Explanation:</strong> By using RDP for Windows and SSH for Linux, you can minimize the VirtualBox windows and manage both servers from standard Windows applications. This is the standard industry workflow.' },
  
  // 35. Windows vs Linux: Identity Comparison
  { type: 'lesson', category: 'Summary', title: 'Windows vs Linux', subtitle: 'Identity Comparison', desc: 'Compare the tools and concepts used for identity management across both operating systems, setting the stage for Module 4.', syntax: 'Windows: AD DS, GPOs, Event Viewer\nLinux: /etc/passwd, PAM, auditd', term: [{raw: '<span class="out" style="color:#E8A07A">Feature Comparison</span><br><span class="out">1. Directory: AD (NTDS.dit) vs /etc/passwd (flat file)</span><br><span class="out">2. Hierarchy: OUs vs Groups</span><br><span class="out">3. Policy: GPOs vs PAM (pam.d/*)</span><br><span class="out">4. Privilege: Domain Admins vs sudoers</span><br><span class="out">5. Auditing: Event Viewer (Security) vs auditd (ausearch)</span><br><span class="out">6. Centralization: AD is centralized; Linux is local unless using realmd/SSSD to join AD.</span>'}], explain: '<strong>Explanation:</strong> Windows is designed for centralization from the start. Linux is designed for independence but can join AD via <code>realmd</code>. In hybrid environments, sysadmins often configure Linux to authenticate against AD so users have one password for both OSes.' },
  
  // 36. Network Bridging Verification
  { type: 'lesson', category: 'Verification', title: 'Network Verification', subtitle: 'Bridged MAC Addresses', desc: 'To ensure true bridging is working, check that the VMs have distinct MAC addresses visible on your physical router\'s DHCP lease table.', syntax: 'ip link show enp0s3', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ip link show enp0s3</span><br><span class="out">2: enp0s3: &lt;BROADCAST,MULTICAST,UP,LOWER_UP&gt; mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000</span><br><span class="out">    link/ether 08:00:27:a8:12:45 brd ff:ff:ff:ff:ff:ff</span><br><br><span class="out" style="color:#E8A07A">Why this matters</span><br><span class="out">If the MAC address starts with 08:00:27, it is the VirtualBox OUI. Your physical router should list this MAC as an active DHCP client, distinct from your host machine.</span>'}], explain: '<strong>Explanation:</strong> If both VMs use NAT, they share the host\'s MAC address. By checking the MAC, you confirm they are truly bridged and will appear as independent physical devices on the network, which is critical for AD and DNS.' },
  
  // 37. Topic Summary
  { type: 'lesson', category: 'Summary', title: 'Topic Summary', subtitle: 'Module 1 Complete', desc: 'We have successfully installed and configured a dual-OS environment. You can now manage Windows Server, Linux (Ubuntu and WSL), and route traffic between them.', syntax: 'wsl -l -v\nping 192.168.1.10\nssh admin@192.168.1.20', term: [{raw: '<span class="out" style="color:#E8A07A">Module 1 Checklist:</span><br>[x] Windows Server 2022 Installed (192.168.1.10)<br>[x] Ubuntu Server 24.04 Installed (192.168.1.20)<br>[x] WSL 2 Installed on Windows Host<br>[x] Netplan Configured on Ubuntu<br>[x] SSH verified across VMs<br><br><span class="out">Next: We will move to OS Maintenance, Patching, and Service Management.</span>'}], explain: '<strong>Explanation:</strong> This concludes the installation and configuration phase. In the next module, we will begin managing these servers—applying patches, configuring services, and analyzing logs.' },

  // --- 4. CLOSING SLIDE ---
  {
    type: 'closing',
    header: 'MODULE 01 · TOPIC 07',
    tag: 'End of Topic 07',
    title: 'Two OSes, <em>One</em> Network.',
    leftCardNum: '§ ubuntu',
    leftCardTitle: 'Netplan & SSH',
    leftCardDesc: 'Ubuntu Server relies on Netplan for modern YAML-based networking. SSH is installed by default, enabling secure remote administration from Windows.',
    rightCardNum: '§ connectivity',
    rightCardTitle: 'Bridged Networking',
    rightCardDesc: 'By placing both VMs on a Bridged Adapter, they receive IPs on your physical LAN, allowing seamless Ping and SSH tests between Windows and Linux.'
  }

];
