const slideConfigs = [
  // --- 1. COVER SLIDE ---
  {
    type: 'cover',
    moduleTitle: 'MODULE 05 · TOPIC 14',
    topicNum: '14',
    topicTag: 'T14',
    title: 'Infrastructure as Code<br>with <em>Terraform</em>',
    subtitle: 'Automating cloud infrastructure: Defining Azure resources in HashiCorp Configuration Language, the core workflow, and safe deployment.',
    graphicText: 'Define <em>Cloud</em><br>Automate <em>Deploy</em><br>Destroy.',
    miniObjectives: [
      'What Is IaC and Why It Helps',
      'Install Terraform & Providers',
      'Write a First main.tf',
      'Core Workflow: Init, Plan, Apply, Destroy'
    ]
  },

  // --- 2. OBJECTIVES SLIDE ---
  {
    type: 'objectives',
    header: 'MODULE 05 · TOPIC 14',
    kicker: 'ITP 141 · M5 · T14',
    desc: 'Manual cloud provisioning is tedious. You will learn to define your entire data center in text and deploy it repeatably with HashiCorp Terraform.',
    lede: 'A modern sysadmin defines infrastructure in code, not by clicking in a web portal.',
    list: [
      'Explain Infrastructure as Code (IaC) and why it replaces manual provisioning.',
      'Install Terraform on Ubuntu Server or use Azure Cloud Shell.',
      'Identify Terraform providers, resources, and variables.',
      'Write a main.tf configuration defining Azure resources.',
      'Execute the Terraform workflow: init, plan, apply, and destroy.',
      'Understand Terraform State and how terraform.tfstate tracks infrastructure.',
      'Use variables and outputs to make configurations reusable.',
      'Configure Azure authentication through the Azure CLI.',
      'Deploy an Azure Resource Group, Virtual Network, Subnet, and Linux VM.',
      'Review deployment plans and manage infrastructure changes safely.',
      'Understand state management and remote state concepts.'
    ]
  },

  // --- 3. LESSON SLIDES ---
    // 1. IaC Overview
    { type: 'lesson', category: 'Overview', title: 'IaC Overview', subtitle: 'Manual vs IaC', desc: 'Infrastructure as Code (IaC) is the process of managing data centers through machine-readable definition files, rather than physical hardware configuration or interactive configuration tools.', syntax: 'Manual: Click -> Wait -> Forget -> Error\nIaC: Code -> Repeat -> Version -> Automate', term: [{raw: '<span class="out" style="color:#E8A07A">Why IaC?</span><br><br><span class="out">1. Speed: Deploy 100 VMs in 2 minutes.</span><br><span class="out">2. Consistency: Every VM is identical. No human typos.</span><br><span class="out">3. Version Control: You can track changes in Git.</span><br><span class="out">4. Reusability: Share the code with other sysadmins.</span><br><br><span class="out" style="color:#E8A07A">Tools</span><br><span class="out">Azure ARM Templates (JSON)</span><br><span class="out">Terraform (HashiCorp)</span><br><span class="out">Azure Bicep (Microsoft)</span>'}], explain: '<strong>Explanation:</strong> Clicking through the Portal is fine for learning. In production, you never click. You write a script. If a server dies, you don\'t fix it; you run the script to build a new one. This is the DevOps mindset.' },
    
    // 2. Benefits of IaC
    { type: 'lesson', category: 'Overview', title: 'IaC Benefits', subtitle: 'Why it helps', desc: 'IaC provides idempotency, speed, consistency, and visibility into infrastructure changes.', syntax: 'Idempotency: Running the code twice yields the same result.', term: [{raw: '<span class="out" style="color:#E8A07A">Core Benefits</span><br><br><span class="out">1. Idempotency: If the VM exists, Terraform knows and doesn\'t create it again.</span><br><span class="out">2. Speed: What took hours in the Portal takes minutes in code.</span><br><span class="out">3. Consistency: No "it works on my cloud" problems.</span><br><span class="out">4. Cost Control: Easily destroy resources when done.</span><br><br><span class="out" style="color:#E8A07A">Immutable Infrastructure</span><br><span class="out">Instead of patching a live server, you destroy and rebuild it from code.</span>'}], explain: '<strong>Explanation:</strong> Terraform is declarative. You state what you want (e.g., "I want 1 Ubuntu VM"). Terraform figures out how to get there. If you change the code to say "2 VMs", Terraform creates the second one without touching the first.' },
    
    // 3. IaC Tool Landscape
    { type: 'lesson', category: 'Overview', title: 'IaC Tools', subtitle: 'Terraform vs ARM', desc: 'Azure supports ARM Templates (JSON) and Bicep (Microsoft). Terraform is cloud-agnostic and the industry standard for multi-cloud IaC.', syntax: 'Terraform: Cloud-agnostic (Azure, AWS, GCP).\nARM: Azure-only.', term: [{raw: '<span class="out" style="color:#E8A07A">Comparison</span><br><br><span class="out">1. Terraform: Uses HCL. Works across Azure, AWS, Google Cloud. Declarative.</span><br><span class="out">2. ARM Templates: Azure only. JSON. Very verbose.</span><br><span class="out">3. Bicep: Azure only. Simplified DSL. Cleaner than ARM.</span><br><span class="out">4. Ansible: Configuration Management. Not for provisioning.</span>'}], explain: '<strong>Explanation:</strong> We use Terraform because it is the industry standard. If you learn Terraform, you can deploy to Azure today and AWS tomorrow. ARM limits you to Microsoft.</span>' },
    
    // 4. Terraform Intro
    { type: 'lesson', category: 'Terraform', title: 'Terraform Intro', subtitle: 'HashiCorp', desc: 'Terraform is an open-source infrastructure as code software tool created by HashiCorp. Users define and provision data center infrastructure using a high-level configuration language known as HashiCorp Configuration Language (HCL).', syntax: 'Provider -> Resource -> Plan -> Apply', term: [{raw: '<span class="out" style="color:#E8A07A">Terraform Architecture</span><br><br><span class="out">1. Core: Terraform Engine (parses HCL).</span><br><span class="out">2. Providers: Plugins that talk to APIs (e.g., azurerm, aws).</span><br><span class="out">3. State: Tracks real infrastructure vs code.</span><br><br><span class="out" style="color:#E8A07A">Why it is declarative</span><br><span class="out">You write the END STATE. Terraform executes the steps to get there.</span>'}], explain: '<strong>Explanation:</strong> Terraform does not care how the infrastructure got to its current state. It only cares about the difference between your code and reality. If reality matches code, it does nothing.</span>' },
    
    // 5. HCL Language
    { type: 'lesson', category: 'Terraform', title: 'HCL Language', subtitle: 'HashiCorp Configuration Language', desc: 'HCL is a structured language designed for configuration. It is less verbose than JSON and more secure than YAML. It uses blocks and arguments.', syntax: '<block> <label> { key = value }', term: [{raw: '<span class="out" style="color:#E8A07A">HCL Syntax</span><br><br><span class="out">1. Block: A container for resources.</span><br><span class="out">2. Label: Identifies the block.</span><br><br><span class="out">resource "azurerm_resource_group" "rg" {</span><br><span class="out">  name = "ITP141-Lab-14"</span><br><span class="out">  location = "southeastasia"</span><br><span class="out">}</span><br><br><span class="out" style="color:#E8A07A">Rule</span><br><span class="out">1. = is assignment, not ==.</span><br><span class="out">2. Quotation marks for strings. No quotes for numbers.</span>'}], explain: '<strong>Explanation:</strong> HCL is designed to be readable by humans. You define a resource, name it, and give it arguments. Terraform reads this and tells Azure "Create a resource group named rg with these properties".' },
    
    // 6. Providers
    { type: 'lesson', category: 'Terraform', title: 'Providers', subtitle: 'Cloud Plugins', desc: 'A Provider is a plugin that Terraform uses to talk to APIs. To use Azure, you need the <code>azurerm</code> provider.', syntax: 'provider "azurerm" { features {} }', term: [{raw: '<span class="out" style="color:#E8A07A">Common Providers</span><br><br><span class="out">1. azurerm: Azure Resource Manager.</span><br><span class="out">2. aws: Amazon Web Services.</span><br><span class="out">3. google: Google Cloud Platform.</span><br><span class="out">4. docker: Docker container management.</span><br><span class="out">5. azurerm: Azure Resource Manager.</span><br><br><span class="out" style="color:#E8A07A">Code Example</span><br><span class="out">terraform { required_providers { azurerm = { source = "hashicorp/azurerm" version = "=3.0.0" } } }</span><br><span class="out">provider "azurerm" { features {} }</span>'}], explain: '<strong>Explanation:</strong> The provider block is the first thing in your main.tf. It tells Terraform how to authenticate to the cloud. Without it, Terraform cannot talk to Azure.</span>' },
    
    // 7. Resources
    { type: 'lesson', category: 'Terraform', title: 'Resources', subtitle: 'Infrastructure Objects', desc: 'A resource is a piece of infrastructure. It can be a Virtual Machine, a Resource Group, a Database, or a Network.', syntax: 'resource "azurerm_resource_group" "rg" { name = "ITP141" location = "southeastasia" }', term: [{raw: '<span class="out" style="color:#E8A07A">Resource Structure</span><br><br><span class="out">1. Type: "azurerm_resource_group"</span><br><span class="out">2. Name: "rg" (Local to Terraform)</span><br><span class="out">3. Arguments: <span class="cmd">name</span> and <span class="cmd">location</span>.</span><br><br><span class="out" style="color:#E8A07A">Why two names?</span><br><span class="out">1. Type: Tells Azure what to create.</span><br><span class="out">2. Name: Tells Terraform how to reference it in other blocks.</span>'}], explain: '<strong>Explanation:</strong> If you create a Resource Group named "rg", you can reference it later in a VM block as <code>azurerm_resource_group.rg.name</code>. This dependency makes IaC powerful.</span>' },
    
    // 8. Variables
    { type: 'lesson', category: 'Terraform', title: 'Variables', subtitle: 'Parameterization', desc: 'Variables allow you to write one template and deploy it to multiple environments (Dev, Test, Prod).', syntax: 'variable "location" { type = string default = "southeastasia" }', term: [{raw: '<span class="out" style="color:#E8A07A">Variable Usage</span><br><br><span class="out">variable "vm_name" { type = string }</span><br><br><span class="out" style="color:#E8A07A">Reference in Code</span><br><span class="out">name = var.vm_name</span><br><br><span class="out" style="color:#E8A07A">Override at Runtime</span><br><span class="cmd">> terraform apply -var "vm_name=prod-vm-01"</span>'}], explain: '<strong>Explanation:</strong> Hardcoding names is bad practice. Variables make your code reusable. You can define a default value, or require it at runtime using the command line.</span>' },
    
    // 9. Outputs
    { type: 'lesson', category: 'Terraform', title: 'Outputs', subtitle: 'Return Values', desc: 'Outputs are like return values in functions. After Terraform creates a VM, it can output the Public IP so you know how to connect to it.', syntax: 'output "public_ip" { value = azurerm_public_ip.ip.ip_address }', term: [{raw: '<span class="out" style="color:#E8A07A">Output Usage</span><br><br><span class="out">output "public_ip" { value = azurerm_public_ip.ip.ip_address }</span><br><br><span class="out" style="color:#E8A07A">Apply Command Result</span><br><span class="out">Apply complete! Resources: 1 added.</span><br><span class="out">Outputs:</span><br><span class="cmd">public_ip = "20.115.45.123"</span><br><br><span class="out" style="color:#E8A07A">Why use it?</span><br><span class="out">To get passwords, IP addresses, and connection strings for automated scripts.</span>'}], explain: '<strong>Explanation:</strong> If your deployment script runs Terraform, it needs the IP. The output allows the script to read it. Without outputs, you would have to go back to the Portal to find the IP.</span>' },
    
    // 10. Installation
    { type: 'lesson', category: 'Setup', title: 'Installation', subtitle: 'Ubuntu/WSL', desc: 'Install Terraform on Ubuntu Server or WSL 2. HashiCorp provides an official repository for easy installation.', syntax: 'curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -\nsudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"\nsudo apt update && sudo apt install terraform', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt update && sudo apt install terraform</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">terraform --version</span><br><span class="out">Terraform v1.9.8</span><br><span class="out">on linux_amd64</span>'}], explain: '<strong>Explanation:</strong> Terraform is a single binary. You can also download it as a zip file. If you do not want to install it, you can use it inside Azure Cloud Shell, which has it pre-installed.</span>' },
    
    // 11. Cloud Shell Alternative
    { type: 'lesson', category: 'Setup', title: 'Azure Cloud Shell', subtitle: 'No Install Required', desc: 'If you do not want to install Terraform locally, you can use Azure Cloud Shell directly from the browser. It comes pre-configured with Terraform and Azure CLI.', syntax: 'Click ">_" icon in Azure Portal -> Bash', term: [{raw: '<span class="out" style="color:#E8A07A">Cloud Shell Benefits</span><br><br><span class="out">1. Pre-installed: Terraform and Azure CLI are ready.</span><br><span class="out">2. Authenticated: Automatically uses your Azure login.</span><br><span class="out">3. Persistent: Stores your Terraform state in an Azure storage account.</span><br><br><span class="out" style="color:#E8A07A">Warning</span><br><span class="out">State is saved in Azure storage. Do not leave scripts there permanently.</span>'}], explain: '<strong>Explanation:</strong> For this course, installing Terraform locally on your Ubuntu VM is recommended for learning the full process. Cloud Shell is for quick, ad-hoc deployments.</span>' },
    
    // 12. Azure Authentication
    { type: 'lesson', category: 'Setup', title: 'Authentication', subtitle: 'Azure CLI Login', desc: 'Terraform needs permission to create resources. It uses your Azure CLI login session. You must run <code>az login</code> before running Terraform.', syntax: 'az login', term: [{raw: '<span class="out" style="color:#E8A07A">Local Authentication Flow</span><br><br><span class="out">1. Run <span class="cmd">az login</span> in terminal.</span><br><span class="out">2. Browser opens. Enter code.</span><br><span class="out">3. Azure CLI saves session token to ~/.azure/</span><br><span class="out">4. Terraform Provider "azurerm" reads this token automatically.</span><br><br><span class="out" style="color:#E8A07A">Service Principal (Production)</span><br><span class="out">In production, you create a Service Principal (App Registration) for automation. This gives a limited, non-interactive login for CI/CD.</span>'}], explain: '<strong>Explanation:</strong> You never put passwords in Terraform code. The provider reads the Azure CLI context. This is secure and keeps secrets out of Git.</span>' },
    
    // 13. Working Directory
    { type: 'lesson', category: 'Setup', title: 'Working Directory', subtitle: 'Project Setup', desc: 'Terraform runs in a specific directory. It creates state files and downloads providers into a <code>.terraform</code> folder.', syntax: 'mkdir ITP141-Lab-14 && cd ITP141-Lab-14\nnano main.tf', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">mkdir ITP141-Lab-14</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">cd ITP141-Lab-14</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/ITP141-Lab-14</span>$</span> <span class="cmd">nano main.tf</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/ITP141-Lab-14</span>$</span> <span class="cmd">ls -la</span><br><span class="out">drwxr-xr-x 2 ajsacay ajsacay 4096 Oct 24 10:00 .</span><br><span class="out">-rw-r--r-- 1 ajsacay ajsacay 0 Oct 24 10:00 main.tf</span><br><span class="out">-rw-r--r-- 1 ajsacay ajsacay 0 Oct 24 10:00 variables.tf</span>'}], explain: '<strong>Explanation:</strong> It is best practice to split Terraform code into separate files (main.tf, variables.tf, outputs.tf). Terraform reads all <code>.tf</code> files in the directory as one combined configuration.</span>' },
    
    // 14. main.tf: Provider Block
    { type: 'lesson', category: 'Writing main.tf', title: 'main.tf: Provider', subtitle: 'Step 1', desc: 'The top of main.tf defines the required provider version and configures the Azure provider.', syntax: 'terraform { required_providers { ... } }\nprovider "azurerm" { features {} }', term: [{editor: "main.tf", code: 'terraform {\n  required_providers {\n    azurerm = {\n      source  = "hashicorp/azurerm"\n      version = "=3.0.0"\n    }\n  }\n}\n\nprovider "azurerm" {\n  features {}\n}'}], explain: '<strong>Explanation:</strong> The <code>features {}</code> block is required for azurerm 3.0+. It allows you to customize Azure behaviors, but by default it uses safe values.</span>' },
    
    // 15. main.tf: Resource Group
    { type: 'lesson', category: 'Writing main.tf', title: 'main.tf: Resource Group', subtitle: 'Step 2', desc: 'Define the Resource Group. It will hold all other resources.', syntax: 'resource "azurerm_resource_group" "rg" { name = "ITP141-Lab-14" location = "southeastasia" }', term: [{editor: "main.tf", code: 'resource "azurerm_resource_group" "rg" {\n  name     = "ITP141-Lab-14"\n  location = "southeastasia"\n}'}], explain: '<strong>Explanation:</strong> We named the local label "rg". This means later we can reference it as <code>azurerm_resource_group.rg.name</code>. The location defines where the Azure Resource Group metadata is stored.</span>' },
    
    // 16. main.tf: VNet
    { type: 'lesson', category: 'Writing main.tf', title: 'main.tf: VNet', subtitle: 'Step 3', desc: 'Define a Virtual Network and Subnet inside the Resource Group.', syntax: 'resource "azurerm_virtual_network" "vnet" { ... }', term: [{editor: "main.tf", code: 'resource "azurerm_virtual_network" "vnet" {\n  name                = "vnet-tf-14"\n  address_space       = ["10.0.0.0/16"]\n  location            = azurerm_resource_group.rg.location\n  resource_group_name = azurerm_resource_group.rg.name\n}\n\nresource "azurerm_subnet" "subnet" {\n  name                 = "subnet-tf-14"\n  resource_group_name  = azurerm_resource_group.rg.name\n  virtual_network_name = azurerm_virtual_network.vnet.name\n  address_prefixes     = ["10.0.1.0/24"]\n}'}], explain: '<strong>Explanation:</strong> Notice the dependency. The subnet block uses <code>azurerm_resource_group.rg.name</code>. Terraform understands this and creates the Resource Group first, then the VNet, then the Subnet. This is the "Resource Graph".</span>' },
    
    // 17. main.tf: VM
    { type: 'lesson', category: 'Writing main.tf', title: 'main.tf: VM', subtitle: 'Step 4', desc: 'Define the Linux Virtual Machine, NIC, and Public IP.', syntax: 'resource "azurerm_linux_virtual_machine" "vm" { ... }', term: [{editor: "main.tf", code: 'resource "azurerm_linux_virtual_machine" "vm" {\n  name                  = "vm-tf-14"\n  resource_group_name   = azurerm_resource_group.rg.name\n  location              = azurerm_resource_group.rg.location\n  size                  = "Standard_B1s"\n  admin_username        = "azureuser"\n  network_interface_ids = [azurerm_network_interface.nic.id]\n  admin_ssh_key {\n    username   = "azureuser"\n    public_key = file("~/.ssh/id_ed25519.pub")\n  }\n  os_disk {\n    caching              = "ReadWrite"\n    storage_account_type = "Standard_LRS"\n  }\n  source_image_reference {\n    publisher = "Canonical"\n    offer     = "0001-com-ubuntu-server-jammy"\n    sku       = "24_04-lts-gen2"\n    version   = "latest"\n  }\n}'}], explain: '<strong>Explanation:</strong> <code>file("~/.ssh/id_ed25519.pub")</code> reads your local SSH public key and uploads it to Azure. You must have generated this key previously. B1s size is used for the free tier.</span>' },
    
    // 18. main.tf: NSG & IP
    { type: 'lesson', category: 'Writing main.tf', title: 'main.tf: NSG & IP', subtitle: 'Step 5', desc: 'Define Public IP and Network Security Group (NSG) to allow SSH.', syntax: 'resource "azurerm_network_security_group" "nsg" { ... }', term: [{editor: "main.tf", code: 'resource "azurerm_public_ip" "ip" {\n  name                = "ip-tf-14"\n  resource_group_name = azurerm_resource_group.rg.name\n  location            = azurerm_resource_group.rg.location\n  allocation_method   = "Dynamic"\n}\n\nresource "azurerm_network_security_group" "nsg" {\n  name                = "nsg-tf-14"\n  location            = azurerm_resource_group.rg.location\n  resource_group_name = azurerm_resource_group.rg.name\n\n  security_rule {\n    name                       = "SSH"\n    priority                   = 100\n    direction                  = "Inbound"\n    access                     = "Allow"\n    protocol                   = "Tcp"\n    source_port_range          = "*"\n    destination_port_range     = "22"\n    source_address_prefix      = "*"\n    destination_address_prefix = "*"\n  }\n}'}], explain: '<strong>Explanation:</strong> The NSG block includes a <code>security_rule</code> allowing SSH. You must attach this NSG to the NIC (Network Interface) block to make it effective.</span>' },
    
    // 19. main.tf: Full File Review
    { type: 'lesson', category: 'Writing main.tf', title: 'main.tf: Review', subtitle: 'Full Code', desc: 'Review the complete main.tf file defining the Provider, Resource Group, VNet, Subnet, Public IP, NSG, NIC, and VM.', syntax: '# Complete main.tf structure', term: [{editor: "main.tf", code: 'terraform {\n  required_providers {\n    azurerm = { source = "hashicorp/azurerm" version = "=3.0.0" }\n  }\n}\nprovider "azurerm" { features {} }\n\nresource "azurerm_resource_group" "rg" {\n  name = "ITP141-Lab-14"\n  location = "southeastasia"\n}\n\n# VNet, Subnet, Public IP, NSG, NIC...\n\nresource "azurerm_linux_virtual_machine" "vm" {\n  name = "vm-tf-14"\n  resource_group_name = azurerm_resource_group.rg.name\n  location = azurerm_resource_group.rg.location\n  size = "Standard_B1s"\n  admin_username = "azureuser"\n  network_interface_ids = [azurerm_network_interface.nic.id]\n  admin_ssh_key { username = "azureuser" public_key = file("~/.ssh/id_ed25519.pub") }\n  os_disk { caching = "ReadWrite" storage_account_type = "Standard_LRS" }\n  source_image_reference {\n    publisher = "Canonical" offer = "0001-com-ubuntu-server-jammy" sku = "24_04-lts-gen2" version = "latest"\n  }\n}'}], explain: '<strong>Explanation:</strong> This file replaces hours of clicking in the Portal. Once you have this file, you can deploy it 100 times in a row, and it will create the exact same environment every single time.</span>' },
    
    // 20. Workflow Intro
    { type: 'lesson', category: 'Core Workflow', title: 'Workflow Intro', subtitle: 'init -> plan -> apply -> destroy', desc: 'The core Terraform workflow consists of four commands that guide you from writing code to provisioning and ultimately destroying infrastructure.', syntax: 'terraform init\n terraform plan\n terraform apply\n terraform destroy', term: [{raw: '<span class="out" style="color:#E8A07A">The 4 Core Steps</span><br><br><span class="out">1. terraform init: Prepares the directory.</span><br><span class="out">2. terraform plan: Simulates deployment.</span><br><span class="out">3. terraform apply: Deploys the infrastructure.</span><br><span class="out">4. terraform destroy: Deletes the infrastructure.</span><br><br><span class="out" style="color:#E8A07A">Why this order matters</span><br><span class="out">Never run apply without planning first. Plan shows you exactly what will change.</span>'}], explain: '<strong>Explanation:</strong> This workflow is the heartbeat of Terraform. If you skip a step, you risk making unintended changes. Always follow the sequence.</span>' },
    
    // 21. terraform init
    { type: 'lesson', category: 'Core Workflow', title: 'terraform init', subtitle: 'Initialization', desc: 'The <code>terraform init</code> command initializes the working directory containing Terraform configuration files.', syntax: 'terraform init', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/ITP141-Lab-14</span>$</span> <span class="cmd">terraform init</span><br><span class="out">Initializing the backend...</span><br><span class="out">Initializing provider plugins...</span><br><span class="out">- Using previously-installed hashicorp/azurerm v3.0.0</span><br><span class="out">Terraform has been successfully initialized!</span>'}], explain: '<strong>Explanation:</strong> init is safe to run multiple times. It downloads the Azure Provider (azurerm) plugin. It also configures the backend for storing state. It does NOT create any resources in Azure.</span>' },
    
    // 22. terraform plan
    { type: 'lesson', category: 'Core Workflow', title: 'terraform plan', subtitle: 'Simulation', desc: 'The <code>terraform plan</code> command creates an execution plan, determining what actions are necessary to achieve the desired state.', syntax: 'terraform plan', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/ITP141-Lab-14</span>$</span> <span class="cmd">terraform plan</span><br><span class="out">Terraform used the selected providers to generate the following execution plan.</span><br><span class="out">Resource actions are indicated with the following symbols:</span><br><span class="out">  + create</span><br><span class="out">Terraform will perform the following actions:</span><br><span class="out">  # azurerm_resource_group.rg will be created</span><br><span class="out">  + resource "azurerm_resource_group" "rg" { name = "ITP141-Lab-14" }</span><br><span class="out">Plan: 7 to add, 0 to change, 0 to destroy.</span>'}], explain: '<strong>Explanation:</strong> plan does NOT modify infrastructure. It tells you exactly what will be created (+), changed (~), or destroyed (-). You should ALWAYS read the plan carefully before applying.</span>' },
    
    // 23. terraform apply
    { type: 'lesson', category: 'Core Workflow', title: 'terraform apply', subtitle: 'Execution', desc: 'The <code>terraform apply</code> command executes the actions proposed in a Terraform plan.', syntax: 'terraform apply', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/ITP141-Lab-14</span>$</span> <span class="cmd">terraform apply</span><br><span class="out">Do you want to perform these actions?</span><br><span class="out">  Terraform will perform the actions described above.</span><br><span class="out">  Only \'yes\' will be accepted to approve.</span><br><span class="out">  Enter a value: yes</span><br><br><span class="out">azurerm_resource_group.rg: Creating...</span><br><span class="out">azurerm_resource_group.rg: Creation complete after 1s [id=/subscriptions/.../rg]</span><br><span class="out">Apply complete! Resources: 7 added, 0 changed, 0 destroyed.</span>'}], explain: '<strong>Explanation:</strong> apply will prompt for confirmation. You type "yes". For CI/CD pipelines, you use <code>terraform apply -auto-approve</code> to skip the prompt. It reads your code, compares it to reality, and creates the resources in Azure.</span>' },
    
    // 24. terraform destroy
    { type: 'lesson', category: 'Core Workflow', title: 'terraform destroy', subtitle: 'Teardown', desc: 'The <code>terraform destroy</code> command destroys Terraform-managed infrastructure. It is the ultimate cleanup command.', syntax: 'terraform destroy', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/ITP141-Lab-14</span>$</span> <span class="cmd">terraform destroy</span><br><span class="out">Do you really want to destroy all resources?</span><br><span class="out">  Terraform will destroy all your managed infrastructure.</span><br><span class="out">  There is no undo. Only \'yes\' will be accepted to approve.</span><br><span class="out">  Enter a value: yes</span><br><br><span class="out">azurerm_resource_group.rg: Destruction complete after 1s</span><br><span class="out">Destroy complete! Resources: 7 destroyed.</span>'}], explain: '<strong>Explanation:</strong> destroy reads the state file, finds every resource you created with this template, and deletes it. This is critical for the Azure Free Tier to stop all charges instantly. No more manually clicking delete in the Portal.</span>' },
    
    // 25. Terraform State
    { type: 'lesson', category: 'State', title: 'Terraform State', subtitle: 'terraform.tfstate', desc: 'Terraform must track state to map real-world resources to your configuration. It keeps track of metadata in <code>terraform.tfstate</code>.', syntax: 'terraform.tfstate', term: [{raw: '<span class="out" style="color:#E8A07A">What is State?</span><br><br><span class="out">1. Mapping: Links code to real Azure resources.</span><br><span class="out">2. Performance: Only checks changed resources.</span><br><span class="out">3. Tracking: Knows what needs to be created (+) or destroyed (-).</span><br><br><span class="out" style="color:#E8A07A">Local vs Remote</span><br><span class="out">Local: Default. Saved in your directory. Never commit to Git.<br><span class="out">Remote: Saved in Azure Storage. Best practice for teams.</span>'}], explain: '<strong>Explanation:</strong> The state file is the source of truth. If you delete it, Terraform forgets what it created and cannot destroy it later. For teams, store it in Azure Blob Storage.</span>' },
    
    // 26. fmt & validate
    { type: 'lesson', category: 'Best Practices', title: 'fmt & validate', subtitle: 'Code Formatting', desc: 'Use <code>terraform fmt</code> to format code and <code>terraform validate</code> to check syntax without connecting to Azure.', syntax: 'terraform fmt\n terraform validate', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/ITP141-Lab-14</span>$</span> <span class="cmd">terraform fmt</span><br><span class="out">main.tf</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/ITP141-Lab-14</span>$</span> <span class="cmd">terraform validate</span><br><span class="out">Success! The configuration is valid.</span>'}], explain: '<strong>Explanation:</strong> fmt aligns your equal signs and indents. validate checks if your HCL syntax is correct (e.g., missing brackets). Both should be run before committing code to Git.</span>' },
    
    // 27. state list & show
    { type: 'lesson', category: 'State Management', title: 'state list', subtitle: 'Inspecting State', desc: 'You can query the state file to see exactly what resources Terraform is managing.', syntax: 'terraform state list', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/ITP141-Lab-14</span>$</span> <span class="cmd">terraform state list</span><br><span class="out">azurerm_resource_group.rg</span><br><span class="out">azurerm_virtual_network.vnet</span><br><span class="out">azurerm_subnet.subnet</span><br><span class="out">azurerm_linux_virtual_machine.vm</span><br><span class="out">azurerm_network_interface.nic</span><br><span class="out">azurerm_public_ip.ip</span><br><span class="out">azurerm_network_security_group.nsg</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/ITP141-Lab-14</span>$</span> <span class="cmd">terraform state show azurerm_linux_virtual_machine.vm</span><br><span class="out">id = /subscriptions/.../vm-tf-14</span><br><span class="out">name = vm-tf-14</span><br><span class="out">size = Standard_B1s</span>'}], explain: '<strong>Explanation:</strong> This is how you verify what Terraform thinks exists in Azure. If the state and reality diverge, you have "State Drift".</span>' },
    
    // 28. Variables Usage
    { type: 'lesson', category: 'Best Practices', title: 'Variables', subtitle: 'Overriding at Runtime', desc: 'You can override variables using the <code>-var</code> flag or a <code>.tfvars</code> file. This makes templates reusable across environments.', syntax: 'terraform apply -var="location=eastus"', term: [{raw: '<span class="out" style="color:#E8A07A">Using -var Flag</span><br><span class="cmd">> terraform plan -var "vm_name=dev-vm" -var "location=eastus"</span><br><br><span class="out" style="color:#E8A07A">Using dev.tfvars File</span><br><span class="out"># dev.tfvars</span><br><span class="out">vm_name = "dev-vm"</span><br><span class="out">location = "eastus"</span><br><span class="cmd">> terraform apply -var-file="dev.tfvars"</span>'}], explain: '<strong>Explanation:</strong> Hardcoding values in main.tf is bad. Use variables for environment-specific values like names, regions, and SKUs. You can have one main.tf and multiple tfvars files (dev.tfvars, prod.tfvars).</span>' },
    
    // 29. Modules
    { type: 'lesson', category: 'Advanced', title: 'Terraform Modules', subtitle: 'Code Reusability', desc: 'A Module is a container for multiple resources that are used together. It is like a function in programming.', syntax: 'module "web_server" { source = "./modules/vm" name = "web-01" }', term: [{raw: '<span class="out" style="color:#E8A07A">Module Structure</span><br><br><span class="out">1. Root Module: Your main.tf in the project root.</span><br><span class="out">2. Child Modules: Subdirectories with their own main.tf.</span><br><span class="out">3. Inputs: Variables passed to the module.</span><br><span class="out">4. Outputs: Values returned by the module.</span><br><br><span class="out" style="color:#E8A07A">Why use Modules?</span><br><span class="out">If you deploy 5 identical web servers, don\'t write the code 5 times. Write it once as a module, call it 5 times.</span>'}], explain: '<strong>Explanation:</strong> Modules enable code reuse. The Terraform Registry has pre-built modules for common architectures (e.g., Azure AKS Cluster, Azure VNet) that you can import into your code without writing from scratch.</span>' },
    
    // 30. Workspaces
    { type: 'lesson', category: 'Advanced', title: 'Terraform Workspaces', subtitle: 'Multiple Environments', desc: 'Workspaces allow you to use the same configuration to manage multiple distinct environments (e.g., Dev, Test, Prod) without duplicating code.', syntax: 'terraform workspace new dev', term: [{raw: '<span class="out" style="color:#E8A07A">Workspace Commands</span><br><span class="cmd">> terraform workspace new dev</span><br><span class="out">Created and switched to workspace "dev"!</span><br><span class="cmd">> terraform workspace list</span><br><span class="out">  default</span><br><span class="out">  dev</span><br><br><span class="out" style="color:#E8A07A">Why use Workspaces?</span><br><span class="out">Each workspace has its own state file. You deploy Dev with <span class="cmd">terraform apply</span> in the "dev" workspace, then switch to "prod" and deploy it there. Same code, different state.</span>'}], explain: '<strong>Explanation:</strong> Workspaces are powerful but can be risky if mismanaged. For beginners, separate directories are simpler. Workspaces keep one directory for multiple environments.</span>' },
    
    // 31. Remote State
    { type: 'lesson', category: 'State Management', title: 'Remote State', subtitle: 'Azure Storage', desc: 'Storing state locally is dangerous. If your laptop dies, Terraform forgets your infrastructure. Store it in an Azure Storage Account.', syntax: 'backend "azurerm" { resource_group_name = "rg-tf-state" storage_account_name = "statetf14" container_name = "tfstate" key = "terraform.tfstate" }', term: [{raw: '<span class="out" style="color:#E8A07A">Why Remote State?</span><br><br><span class="out">1. Security: State files can contain secrets (IPs, passwords). Do not commit to Git.</span><br><span class="out">2. Collaboration: Multiple sysadmins can run Terraform against the same state.</span><br><span class="out">3. Locking: Prevents two sysadmins from running apply at the same time.</span><br><br><span class="out" style="color:#E8A07A">Configuration in main.tf</span><br><span class="out">terraform { backend "azurerm" { ... } }</span><br><span class="out">resource_group_name = "rg-tf-state"</span><br><span class="out">storage_account_name = "statetf14"</span><br><span class="out">container_name = "tfstate"</span><br><span class="out">key = "terraform.tfstate"</span>'}], explain: '<strong>Explanation:</strong> You must create the Storage Account and Container manually first. Then, configure the backend block. Terraform will automatically save the state to Azure.</span>' },
    
    // 32. State Locking
    { type: 'lesson', category: 'State Management', title: 'State Locking', subtitle: 'Preventing Drift', desc: 'When using remote state (e.g., Azure Storage), Terraform automatically locks the state file during <code>apply</code>.', syntax: 'terraform apply\nState is already locked by another process.', term: [{raw: '<span class="out" style="color:#E8A07A">How Locking Works</span><br><br><span class="out">1. User A runs <span class="cmd">terraform apply</span>.</span><br><span class="out">2. Terraform places a lease on the blob in Azure.</span><br><span class="out">3. User B tries <span class="cmd">terraform apply</span>. They get an error: "State is locked".</span><br><span class="out">4. User A finishes. The lease is released.</span><br><span class="out">5. User B can now run apply.</span><br><br><span class="out" style="color:#E8A07A">Force Unlock</span><br><span class="cmd">> terraform force-unlock LOCK_ID</span><br><span class="out">(Use with extreme caution. It can corrupt state if another apply is still running.)</span>'}], explain: '<strong>Explanation:</strong> Locking is critical for team safety. If two people run apply at once, they will overwrite each other and corrupt the state, destroying resources by accident. Azure Storage provides native locking via Blob Leases.</span>' },
    
    // 33. Terraform Cloud
    { type: 'lesson', category: 'Enterprise', title: 'Terraform Cloud', subtitle: 'SaaS Platform', desc: 'HashiCorp offers Terraform Cloud (TFC) and Terraform Enterprise (TFE) for teams. It runs Terraform in a centralized environment, removing the need for local execution.', syntax: 'Local: You run code on your laptop.\nCloud: HashiCorp runs code on their servers.', term: [{raw: '<span class="out" style="color:#E8A07A">Terraform Cloud Features</span><br><br><span class="out">1. Remote Execution: Runs apply on HashiCorp servers.</span><br><span class="out">2. VCS Integration: Auto-deploys when you push to GitHub.</span><br><span class="out">3. Secure Variables: Store secrets safely in the cloud, not on your laptop.</span><br><span class="out">4. Cost Estimation: Shows how much the apply will cost before you run it.</span><br><br><span class="out" style="color:#E8A07A">Why use it?</span><br><span class="out">For teams, it provides audit trails and role-based access control (RBAC).</span>'}], explain: '<strong>Explanation:</strong> In enterprise, running Terraform on a laptop is rare. Code is pushed to Git, which triggers Terraform Cloud to run the plan and apply automatically. This enforces code reviews.</span>' },
    
    // 34. CI/CD Integration
    { type: 'lesson', category: 'Enterprise', title: 'CI/CD Integration', subtitle: 'Automation Pipeline', desc: 'Terraform is designed to be integrated into Continuous Integration/Continuous Deployment (CI/CD) pipelines like GitHub Actions or Azure DevOps.', syntax: 'on: [push]\nrun: terraform plan', term: [{raw: '<span class="out" style="color:#E8A07A">GitHub Actions Workflow</span><br><br><span class="out">1. Push code to GitHub.</span><br><span class="out">2. GitHub Actions runs <span class="cmd">terraform plan</span>.</span><br><span class="out">3. Human approves the plan.</span><br><span class="out">4. GitHub Actions runs <span class="cmd">terraform apply</span>.</span><br><br><span class="out" style="color:#E8A07A">Benefits</span><br><span class="out">1. Consistency: Everyone uses the same execution environment.</span><br><span class="out">2. Audit Trail: You know exactly who approved what, and when.</span><br><span class="out">3. Self-Service: Developers can deploy infrastructure safely.</span>'}], explain: '<strong>Explanation:</strong> Infrastructure as Code is only powerful if it is automated. In DevOps, you do not manually run apply. A pipeline runs it for you after tests pass.</span>' },
    
    // 35. Terraform vs Ansible
    { type: 'lesson', category: 'Comparison', title: 'Terraform vs Ansible', subtitle: 'Provisioning vs Configuration', desc: 'Terraform is for Provisioning (creating the server). Ansible is for Configuration (installing software on the server).', syntax: 'Terraform: Creates the VM in Azure.\nAnsible: Installs Nginx on the VM.', term: [{raw: '<span class="out" style="color:#E8A07A">Key Differences</span><br><br><span class="out">1. Terraform: Declarative. You state the end state.</span><br><span class="out">2. Ansible: Procedural. You write the steps to get there.</span><br><span class="out">3. Terraform: Destroys resources easily.</span><br><span class="out">4. Ansible: Immutable (no destroy, only reconfigure).</span><br><br><span class="out" style="color:#E8A07A">Hybrid Approach</span><br><span class="out">Use Terraform to create the VM, then use Ansible to configure it.</span>'}], explain: '<strong>Explanation:</strong> Terraform does not install Nginx or configure users. It builds the hardware. Ansible handles the OS configuration. They are complementary tools.</span>' },
    
    // 36. Best Practices
    { type: 'lesson', category: 'Best Practices', title: 'Best Practices', subtitle: 'Writing Clean Code', desc: 'Following best practices ensures your Terraform code is readable, secure, and maintainable.', syntax: '1. Use modules. 2. Remote state. 3. Validate code.', term: [{raw: '<span class="out" style="color:#E8A07A">Terraform Best Practices</span><br><br><span class="out">1. Remote State: Never store state locally or in Git.</span><br><span class="out">2. Variables: Parameterize your code with variables.</span><br><span class="out">3. Modules: Reuse code blocks for common patterns.</span><br><span class="out">4. Formatting: Run <span class="cmd">terraform fmt</span> before commit.</span><br><span class="out">5. Tags: Use tags on resources for billing visibility.</span><br><span class="out">6. Version Control: Pin provider versions to avoid breaking changes.</span><br><span class="out">7. Least Privilege: Use Service Principals, not your admin account.</span>'}], explain: '<strong>Explanation:</strong> Pinning the provider version (e.g., <code>version = "=3.0.0"</code>) prevents HashiCorp from pushing breaking changes to your code. Always use tags (e.g., <code>tags = { Environment = "Dev", Course = "ITP141" }</code>) to track costs.</span>' },
    
    // 37. Topic Summary
    { type: 'lesson', category: 'Summary', title: 'Topic Summary', subtitle: 'Module 5 Complete', desc: 'You have learned to deploy Azure resources by writing code instead of clicking in a portal. This is the foundation of modern DevOps.', syntax: 'terraform init\n terraform plan\n terraform apply', term: [{raw: '<span class="out" style="color:#E8A07A">Module 5 Checklist:</span><br>[x] Understood what Infrastructure as Code (IaC) is.<br>[x] Installed Terraform.<br>[x] Wrote a basic <span class="cmd">main.tf</span> file.<br>[x] Defined Providers, Resources, and Variables.<br>[x] Ran the core workflow: init, plan, apply, destroy.<br>[x] Explored state management and remote state.<br><br><span class="out">Next: We will explore Monitoring, Disaster Recovery, and Documentation.</span>'}], explain: '<strong>Explanation:</strong> Terraform changes the role of the sysadmin from a manual builder to a code author. Infrastructure becomes a software artifact. Mastering this workflow is the capstone of cloud administration.</span>' },

  // --- 4. CLOSING SLIDE ---
  {
    type: 'closing',
    header: 'MODULE 05 · TOPIC 14',
    tag: 'End of Topic 14',
    title: 'Infrastructure is <em>Code</em>.',
    quote: 'Manual provisioning is for testing. Infrastructure as Code is for production. If it’s not in code, it’s not infrastructure.',
    leftCardNum: '§ IaC',
    leftCardTitle: 'Declarative Automation',
    leftCardDesc: 'Terraform replaces manual portal operations with declarative HashiCorp Configuration Language (HCL). Infrastructure can be versioned in Git, shared, reviewed, and deployed repeatedly.',
    middleCardNum: '§ workflow',
    middleCardTitle: 'The Core Workflow',
    middleCardDesc: 'The init, plan, apply, and destroy commands allow administrators to initialize configurations, preview changes, provision resources, and remove infrastructure when no longer needed.',
    rightCardNum: '§ management',
    rightCardTitle: 'State & Reusability',
    rightCardDesc: 'Terraform state tracks managed resources, while variables and outputs improve configuration reuse and automation. Reviewing plans before applying changes helps prevent unintended deployments.'
  }
];