const slideConfigs = [
  {
    type: 'cover',
    moduleTitle: 'MODULE 04 · TOPIC 11',
    topicNum: '11',
    topicTag: 'T11',
    title: 'Storage, File Systems<br>& <em>Backup</em>',
    subtitle: 'Managing dynamic storage with LVM, sharing files with Samba, calculating backup strategies, and automating rsync backups.',
    graphicText: 'Expand <em>Storage</em><br>Share <em>Files</em><br>Automate Backups.',
    miniObjectives: [
      'LVM & Dynamic Volumes',
      'Samba File Sharing',
      '3-2-1 Backup Strategy',
      'Automated rsync & Cron'
    ]
  },

  {
    type: 'objectives',
    header: 'MODULE 04 · TOPIC 11',
    kicker: 'ITP 141 · M4 · T11',
    desc: 'Data is the lifeblood of an organization. You will learn to manage elastic storage, share it securely across OSes, and protect it with automated backups.',
    lede: 'A sysadmin who cannot restore a deleted file from backup is just a spectator to a disaster. Master storage and backup to ensure data survives.',
    list: [
      'Create and manage Logical Volumes using LVM.',
      'Extend an LV without downtime using lvextend and resize2fs.',
      'Understand file systems (mkfs) and mounting (/etc/fstab).',
      'Configure a Samba share on Ubuntu accessible from Windows Server 2022.',
      'Calculate four-week storage for full, incremental, and differential backups.',
      'Understand the 3-2-1 backup rule for disaster recovery.',
      'Automate rsync backup with a timestamped directory.',
      'Schedule backup scripts using cron.'
    ]
  },

  // --- 3. LESSON SLIDES ---
    { type: 'lesson', category: 'Overview', title: 'Storage Management', subtitle: 'Traditional vs LVM', desc: 'Traditionally, partitions are fixed in size on a single physical disk. Logical Volume Manager (LVM) abstracts the physical disks, allowing you to pool space and resize volumes dynamically.', syntax: 'Traditional: Disk -> Partition -> File System\nLVM: Disk(s) -> PV -> VG -> LV -> File System', term: [{raw: '<span class="out" style="color:#E8A07A">Storage Models</span><br><br><span class="out">1. Traditional Partitioning (fdisk)</span><br><span class="out">- Fixed size. Cannot easily span multiple disks.</span><br><span class="out">- Hard to resize. Risk of data loss.</span><br><br><span class="out">2. Logical Volume Manager (LVM)</span><br><span class="out">- Volumes can span multiple disks.</span><br><span class="out">- Can be resized online (without unmounting).</span><br><span class="out">- Snapshots allow point-in-time backups.</span>'}], explain: '<strong>Explanation:</strong> LVM is the enterprise standard for Linux storage. It acts like a virtualization layer for disks. You can add a new physical disk to a server and seamlessly add its space to an existing logical volume.' },
        
    // 2. LVM Architecture
    { type: 'lesson', category: 'LVM', title: 'LVM Architecture', subtitle: 'PV, VG, LV', desc: 'LVM has three main layers. Physical Volumes (PV) are the raw disks. Volume Groups (VG) pool the PVs. Logical Volumes (LV) are the slices you format with a file system.', syntax: 'PV (Physical Volume) -> VG (Volume Group) -> LV (Logical Volume)', term: [{raw: '<span class="out" style="color:#E8A07A">LVM Layers</span><br><br><span class="out">1. Physical Volume (PV): A raw disk or partition (e.g., /dev/sdb).</span><br><span class="out">2. Volume Group (VG): A pool of storage made from one or more PVs.</span><br><span class="out">3. Logical Volume (LV): A virtual partition carved out of a VG.</span><br><br><span class="out" style="color:#E8A07A">Analogy</span><br><span class="out">PV = Bricks. VG = Wall. LV = Rooms.</span>'}], explain: '<strong>Explanation:</strong> You cannot format a PV directly. You must assign it to a VG, and then create an LV from the VG. The OS sees the LV as a normal block device (e.g., /dev/vg_data/lv_data).' },

    // 3. LVM Components Detailed
    { type: 'lesson', category: 'LVM', title: 'LVM Components', subtitle: 'Detailed View', desc: 'Understand how space is allocated inside LVM. Physical Extents (PEs) are the smallest block of physical storage, and Logical Extents (LEs) map to PEs.', syntax: 'PE (Physical Extent) = LE (Logical Extent)', term: [{raw: '<span class="out" style="color:#E8A07A">How Space is Allocated</span><br><br><span class="out">- PVs are divided into small chunks called PEs (default 4MB).</span><br><span class="out">- LVs are divided into chunks called LEs.</span><br><span class="out">- When you create an LV, the LVM maps LEs to PEs in the VG.</span><br><br><span class="out" style="color:#E8A07A">Why this matters?</span><br><span class="out">If you add a new disk (PV) to the VG, the VG gets more PEs. You can then tell the LV to use the new PEs, growing the LV seamlessly.</span>'}], explain: '<strong>Explanation:</strong> This abstraction is why LVM is so powerful. The file system on the LV doesn\'t know or care which physical disk the data is actually written to. LVM handles the mapping.' },

    // 4. Preparing the Disk
    { type: 'lesson', category: 'LVM', title: 'LVM: Preparing Disks', subtitle: 'fdisk & pvcreate', desc: 'Before adding a disk to LVM, you should partition it and tag it as LVM type. Then, initialize it as a Physical Volume (PV).', syntax: 'sudo fdisk /dev/sdb\nsudo pvcreate /dev/sdb1', term: [{raw: '<span class="out" style="color:#E8A07A">Step 1: Partition the Disk</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo fdisk /dev/sdb</span><br><span class="out">Command (m for help): n (new partition)</span><br><span class="out">Command (m for help): t (change type)</span><br><span class="out">Hex code: 8e (Linux LVM)</span><br><span class="out">Command (m for help): w (write and save)</span><br><br><span class="out" style="color:#E8A07A">Step 2: Initialize as PV</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo pvcreate /dev/sdb1</span><br><span class="out">Physical volume "/dev/sdb1" successfully created.</span>'}], explain: '<strong>Explanation:</strong> The <code>8e</code> hex code in fdisk tags the partition as Linux LVM. While <code>pvcreate</code> can work on a whole disk without partitioning, creating a partition is best practice for alignment and compatibility.' },

    // 5. Creating Physical Volumes
    { type: 'lesson', category: 'LVM', title: 'LVM: Physical Volumes', subtitle: 'pvcreate & pvdisplay', desc: 'Verify the Physical Volume was created successfully and view its size and UUID.', syntax: 'sudo pvdisplay /dev/sdb1', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo pvdisplay /dev/sdb1</span><br><br><span class="out">--- Physical volume ---</span><br><span class="out">PV Name               /dev/sdb1</span><br><span class="out">VG Name               (not assigned yet)</span><br><span class="out">PV Size               10.00 GiB</span><br><span class="out">Allocatable           yes</span><br><span class="out">PE Size               4.00 MiB</span><br><span class="out">Total PE              2559</span><br><span class="out">Free PE               2559</span><br><span class="out">Allocated PE          0</span>'}], explain: '<strong>Explanation:</strong> <code>pvdisplay</code> shows the raw capacity of the disk. The "Free PE" (Physical Extents) shows how much space is available to be assigned to a Volume Group.' },

    // 6. Creating Volume Groups
    { type: 'lesson', category: 'LVM', title: 'LVM: Volume Groups', subtitle: 'vgcreate', desc: 'Combine one or more Physical Volumes into a Volume Group (VG). This creates the storage pool.', syntax: 'sudo vgcreate vg_data /dev/sdb1 /dev/sdc1', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo vgcreate vg_data /dev/sdb1</span><br><span class="out">Volume group "vg_data" successfully created</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo vgdisplay vg_data</span><br><span class="out">VG Name               vg_data</span><br><span class="out">VG Size               10.00 GiB</span><br><span class="out">Total PE              2559</span><br><span class="out">Alloc PE / Size       0 / 0</span><br><span class="out">Free  PE / Size       2559 / 10.00 GiB</span>'}], explain: '<strong>Explanation:</strong> Here we named the VG "vg_data". You can add multiple PVs to a single VG. If you add a 10GB disk and a 20GB disk to the VG, the VG will have 30GB of pooled space available for LVs.' },

    // 7. Creating Logical Volumes
    { type: 'lesson', category: 'LVM', title: 'LVM: Logical Volumes', subtitle: 'lvcreate', desc: 'Carve out a Logical Volume (LV) from the Volume Group. This LV acts like a virtual partition.', syntax: 'sudo lvcreate -L 5G -n lv_data vg_data', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo lvcreate -L 5G -n lv_data vg_data</span><br><span class="out">Logical volume "lv_data" created.</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo lvdisplay /dev/vg_data/lv_data</span><br><span class="out">LV Path                /dev/vg_data/lv_data</span><br><span class="out">LV Name                lv_data</span><br><span class="out">VG Name                vg_data</span><br><span class="out">LV Size                5.00 GiB</span>'}], explain: '<strong>Explanation:</strong> <code>-L 5G</code> specifies a fixed size of 5GB. <code>-n lv_data</code> names the volume. The device path is <code>/dev/vg_data/lv_data</code>. Even though the VG has 10GB, we only allocated 5GB to this LV, leaving 5GB free for future expansion.' },

    // 8. Creating the File System
    { type: 'lesson', category: 'File Systems', title: 'File System: mkfs', subtitle: 'Formatting the LV', desc: 'An LV is just raw storage. To store files, you must format it with a file system. We will use ext4, the Linux standard.', syntax: 'sudo mkfs.ext4 /dev/vg_data/lv_data', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo mkfs.ext4 /dev/vg_data/lv_data</span><br><span class="out">mke2fs 1.47.0 (5fa5f24)</span><br><span class="out">Creating filesystem with 1310720 4k blocks and 327680 inodes</span><br><span class="out">Filesystem UUID: 12345678-9abc-def0-1234-56789abcdef0</span><br><span class="out">Superblock backups stored on blocks:</span><br><span class="out">Writing inode tables: done</span><br><span class="out">Creating journal (32768 blocks): done</span><br><span class="out">Writing superblocks and filesystem accounting information: done</span>'}], explain: '<strong>Explanation:</strong> <code>mkfs.ext4</code> writes the file system structures (inodes, superblocks) onto the LV. Other options include <code>mkfs.xfs</code> (good for large files) or <code>mkfs.btrfs</code> (advanced features). Ext4 is the safest default for general server use.' },

    // 9. Mounting the File System
    { type: 'lesson', category: 'File Systems', title: 'File System: Mount', subtitle: 'Temporary vs Persistent', desc: 'To access the file system, you must mount it to a directory. The <code>mount</code> command is temporary. To make it survive a reboot, add it to <code>/etc/fstab</code>.', syntax: 'sudo mkdir /mnt/data\nsudo mount /dev/vg_data/lv_data /mnt/data\n# For persistence: /etc/fstab', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo mkdir /mnt/data</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo mount /dev/vg_data/lv_data /mnt/data</span><br><br><span class="out" style="color:#E8A07A">Verify it is mounted</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">df -h | grep mnt</span><br><span class="out">/dev/mapper/vg_data-lv_data  4.8G  20M  4.6G   1% /mnt/data</span>'}], explain: '<strong>Explanation:</strong> Mounting attaches the file system to the directory tree. However, if you reboot now, the mount is lost. You must add an entry to <code>/etc/fstab</code> to make it permanent.' },

    // 10. Persistent Mounts: /etc/fstab
    { type: 'lesson', category: 'File Systems', title: 'Persistent Mounts', subtitle: '/etc/fstab', desc: 'The File System Table (<code>/etc/fstab</code>) tells the OS which volumes to mount automatically during boot.', syntax: 'sudo nano /etc/fstab\n# Add: /dev/vg_data/lv_data /mnt/data ext4 defaults 0 2', term: [{editor: "/etc/fstab", code: "# /etc/fstab: static file system information.\n# <file system> <mount point> <type> <options> <dump> <pass>\n\nUUID=123...  /  ext4  errors=remount-ro  0  1\n\n# LVM Mount\n/dev/vg_data/lv_data  /mnt/data  ext4  defaults  0  2"}, {raw: '<span class="out" style="color:#E8A07A">Columns Explained</span><br><span class="out">1. Device path or UUID</span><br><span class="out">2. Mount point directory</span><br><span class="out">3. File system type (ext4)</span><br><span class="out">4. Options (defaults = rw, suid, dev, exec, auto)</span><br><span class="out">5. Dump (0 = do not backup via dump cmd)</span><br><span class="out">6. Pass (fsck order: 0=skip, 1=root, 2=others)</span>'}], explain: '<strong>Explanation:</strong> Always run <code>sudo mount -a</code> after editing fstab to test the syntax. If you make a typo in fstab and reboot, the server will drop into emergency mode and refuse to boot. Using UUID is safer than device paths.' },

    // 11. LVM Extension: Concept
    { type: 'lesson', category: 'LVM Extension', title: 'LVM Extension', subtitle: 'Zero Downtime', desc: 'The greatest benefit of LVM is the ability to extend a volume while it is mounted and actively being used. This is called "online resizing".', syntax: 'Add Disk -> vgextend -> lvextend -> resize2fs', term: [{raw: '<span class="out" style="color:#E8A07A">The Expansion Process</span><br><br><span class="out">1. Add a new physical disk to the server (/dev/sdc).</span><br><span class="out">2. vgextend: Add the new disk to the Volume Group.</span><br><span class="out">3. lvextend: Allocate the new space to the Logical Volume.</span><br><span class="out">4. resize2fs: Tell the ext4 file system to use the new space.</span><br><br><span class="out" style="color:#E8A07A">Result</span><br><span class="out">The /mnt/data directory grows instantly. No reboot, no unmounting, no service interruption.</span>'}], explain: '<strong>Explanation:</strong> This is impossible with traditional partitions. LVM separates the physical disk from the logical view, allowing the file system to be stretched to fill the new logical space.' },

    // 12. Extending the Volume Group
    { type: 'lesson', category: 'LVM Extension', title: 'LVM: vgextend', subtitle: 'Adding a Disk', desc: 'First, initialize the new disk as a PV. Then, add it to the existing Volume Group.', syntax: 'sudo pvcreate /dev/sdc1\nsudo vgextend vg_data /dev/sdc1', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo pvcreate /dev/sdc1</span><br><span class="out">Physical volume "/dev/sdc1" successfully created.</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo vgextend vg_data /dev/sdc1</span><br><span class="out">Volume group "vg_data" successfully extended</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo vgdisplay vg_data | grep Size</span><br><span class="out">VG Size               20.00 GiB  (Was 10GB, now 20GB)</span>'}], explain: '<strong>Explanation:</strong> The Volume Group now has 20GB of total space. However, the Logical Volume (lv_data) is still only 5GB. The file system has not changed yet. We must explicitly give the new space to the LV.' },

    // 13. Extending the Logical Volume
    { type: 'lesson', category: 'LVM Extension', title: 'LVM: lvextend', subtitle: 'Growing the Volume', desc: 'Use <code>lvextend</code> to expand the Logical Volume. You can specify an absolute size or a relative addition (e.g., +5G).', syntax: 'sudo lvextend -L +5G /dev/vg_data/lv_data\n# OR use 100% of remaining free space:\nsudo lvextend -l +100%FREE /dev/vg_data/lv_data', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo lvextend -L +5G /dev/vg_data/lv_data</span><br><span class="out">Size of logical volume vg_data/lv_data changed from 5.00 GiB to 10.00 GiB.</span><br><span class="out">Logical volume vg_data/lv_data successfully resized.</span><br><br><span class="out" style="color:#E8A07A">Check the LV size</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo lvdisplay /dev/vg_data/lv_data | grep Size</span><br><span class="out">LV Size                10.00 GiB</span>'}], explain: '<strong>Explanation:</strong> The Logical Volume is now 10GB. However, if you run <code>df -h</code>, the file system will still show 5GB. This is because LVM expanded the container, but the ext4 file system inside doesn\'t know about the new space yet.' },

    // 14. Resizing the File System
    { type: 'lesson', category: 'LVM Extension', title: 'LVM: resize2fs', subtitle: 'Online Resize', desc: 'Tell the ext4 file system to expand and use the newly allocated space in the LV. This happens live, without unmounting.', syntax: 'sudo resize2fs /dev/vg_data/lv_data', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo resize2fs /dev/vg_data/lv_data</span><br><span class="out">resize2fs 1.47.0 (5fa5f24)</span><br><span class="out">The filesystem on /dev/vg_data/lv_data is now 2621440 (4k) blocks long.</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">df -h | grep mnt</span><br><span class="out">/dev/mapper/vg_data-lv_data  9.8G  24M  9.3G   1% /mnt/data</span><br><br><span class="out" style="color:#E8A07A">Success!</span><br><span class="out">The file system now sees the full 10GB. No reboot, no downtime.</span>'}], explain: '<strong>Explanation:</strong> <code>resize2fs</code> is for ext4 file systems. If you used XFS, the command is <code>xfs_growfs /mnt/data</code>. This step bridges the gap between the LVM layer and the File System layer.' },

    // 15. LVM Verification
    { type: 'lesson', category: 'LVM', title: 'LVM: Verification', subtitle: 'pvs, vgs, lvs', desc: 'LVM provides shorthand commands to view the state of all layers in a compact table format.', syntax: 'sudo pvs\nsudo vgs\nsudo lvs', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo pvs</span><br><span class="out">PV         VG      Fmt  Attr PSize   PFree</span><br><span class="out">/dev/sdb1  vg_data lvm2 a--  10.00g  5.00g</span><br><span class="out">/dev/sdc1  vg_data lvm2 a--  10.00g 10.00g</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo lvs</span><br><span class="out">LV      VG      Attr       LSize</span><br><span class="out">lv_data vg_data -wi-ao---- 10.00g</span>'}], explain: '<strong>Explanation:</strong> <code>pvs</code> shows Physical Volumes. <code>vgs</code> shows Volume Groups. <code>lvs</code> shows Logical Volumes. These commands are highly useful for quickly assessing how much free space is available to allocate.' },

    // 16. Content Management Overview
    { type: 'lesson', category: 'Samba', title: 'Content Management', subtitle: 'Samba Overview', desc: 'Samba is the standard open-source implementation of the SMB/CIFS protocol. It allows Linux to share files and printers with Windows clients.', syntax: 'Linux Server -> Samba Daemon (smbd) -> Windows Client', term: [{raw: '<span class="out" style="color:#E8A07A">Samba Architecture</span><br><br><span class="out">1. smbd: The daemon that handles file sharing and authentication.</span><br><span class="out">2. nmbd: The daemon that handles NetBIOS name resolution.</span><br><span class="out">3. /etc/samba/smb.conf: The main configuration file.</span><br><br><span class="out" style="color:#E8A07A">Why Samba?</span><br><span class="out">Without Samba, Windows cannot natively mount a Linux NFS share. Samba translates Linux file permissions into Windows ACLs (Access Control Lists).</span>'}], explain: '<strong>Explanation:</strong> In a dual-OS environment, Samba is the bridge. We will create a share on Ubuntu Server that Windows Server 2022 can map as a network drive (e.g., Z: drive).' },

    // 17. Samba Installation
    { type: 'lesson', category: 'Samba', title: 'Samba Installation', subtitle: 'apt install', desc: 'Install Samba on the Ubuntu Server and verify the services are running.', syntax: 'sudo apt install samba samba-common-bin -y\nsystemctl status smbd', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt install samba samba-common-bin -y</span><br><span class="out">Setting up samba (2:4.15.13+dfsg-0ubuntu1)...</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">systemctl status smbd</span><br><span class="out">\u25cf smbd.service - Samba SMB Daemon</span><br><span class="out">     Active: active (running) since Wed 2024-10-24 10:00:00 PST</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw allow samba</span><br><span class="out">Rules updated</span>'}], explain: '<strong>Explanation:</strong> The <code>smbd</code> daemon listens on port 445 (and 139). We must open the firewall to allow traffic. The <code>samba-common-bin</code> package provides the <code>smbpasswd</code> utility needed to manage users.' },

    // 18. Samba Configuration Structure
    { type: 'lesson', category: 'Samba', title: 'Samba Config Structure', subtitle: '/etc/samba/smb.conf', desc: 'The Samba config file is divided into sections denoted by square brackets. The [global] section applies to the whole server. Share sections define individual folders.', syntax: '[global] -> Server settings\n[share_name] -> Individual folder settings', term: [{raw: '<span class="out" style="color:#E8A07A">smb.conf Sections</span><br><br><span class="out">[global]</span><br><span class="out">   workgroup = WORKGROUP</span><br><span class="out">   security = user</span><br><br><span class="out">[shared]</span><br><span class="out">   path = /srv/samba/shared</span><br><span class="out">   valid users = @developers</span><br><span class="out">   read only = no</span><br><br><span class="out" style="color:#E8A07A">Key Parameters</span><br><span class="out">security = user: Requires username/password.</span><br><span class="out">read only = no: Allows write access.</span>'}], explain: '<strong>Explanation:</strong> The <code>[global]</code> section sets the workgroup name (must match Windows). Each share gets its own section (e.g., <code>[shared]</code>). The name in brackets is what the Windows user sees in the network browser.' },

    // 19. Creating a Samba Share
    { type: 'lesson', category: 'Samba', title: 'Samba: Creating Share', subtitle: 'smb.conf', desc: 'Create a shared directory and add its configuration to the bottom of the Samba config file.', syntax: 'sudo mkdir -p /srv/samba/shared\nsudo nano /etc/samba/smb.conf', term: [{editor: "/etc/samba/smb.conf", code: "# Add to the bottom of /etc/samba/smb.conf\n\n[ITDept]\n   path = /srv/samba/shared\n   comment = IT Department Shared Drive\n   valid users = ajsacay, @developers\n   read only = no\n   browsable = yes\n   create mask = 0770\n   directory mask = 0770"}, {raw: '<span class="out" style="color:#E8A07A">Share Parameters</span><br><span class="out">path: The Linux folder being shared.</span><br><span class="out">valid users: Users/groups allowed to connect.</span><br><span class="out">create mask: Permissions for new files (rwxrwx---).</span>'}], explain: '<strong>Explanation:</strong> We named the share <code>[ITDept]</code>. The Windows client will see this name. We restrict access to the user <code>ajsacay</code> and the <code>developers</code> group. The mask ensures files created via Windows are writable by the group on Linux.' },

    // 20. Samba Users & Passwords
    { type: 'lesson', category: 'Samba', title: 'Samba: Users & Passwords', subtitle: 'smbpasswd', desc: 'Samba maintains its own password database. A user must exist as a Linux system user AND have a Samba password set to access the share.', syntax: 'sudo smbpasswd -a ajsacay', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo smbpasswd -a ajsacay</span><br><span class="out">New SMB password:</span><br><span class="out">Retype new SMB password:</span><br><span class="out">Added user ajsacay.</span><br><br><span class="out" style="color:#E8A07A">Important</span><br><span class="out">- The user "ajsacay" must already exist in /etc/passwd.</span><br><span class="out">- The Samba password does NOT have to match the Linux password, but usually does.</span><br><span class="out">- To enable a user: sudo smbpasswd -e ajsacay</span><br><span class="out">- To disable a user: sudo smbpasswd -d ajsacay</span>'}], explain: '<strong>Explanation:</strong> The <code>-a</code> flag adds the user to the Samba database. If you don\'t run this, the user will get "Access Denied" when trying to connect from Windows, even if they are listed in <code>valid users</code>.' },

    // 21. Samba Permissions
    { type: 'lesson', category: 'Samba', title: 'Samba: Permissions', subtitle: 'chown & chmod', desc: 'The Linux file system permissions must match the Samba config. If Samba says "valid users = @developers", the Linux directory must be owned by that group.', syntax: 'sudo chown -R :developers /srv/samba/shared\nsudo chmod -R 2770 /srv/samba/shared', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo chown -R :developers /srv/samba/shared</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo chmod -R 2770 /srv/samba/shared</span><br><br><span class="out" style="color:#E8A07A">Permission Breakdown</span><br><span class="out">chown -R :developers: Changes group ownership to developers.</span><br><span class="out">chmod -R 2770: rwx for owner, rwx for group, nothing for others.</span><br><span class="out">The "2" is the SetGID bit. New files created here inherit the group ownership.</span>'}], explain: '<strong>Explanation:</strong> The SetGID bit (2) is crucial for Samba shares. Without it, if user A creates a file, they become the owner. If user B tries to edit it, they get denied because they are not the owner. SetGID forces all new files to be owned by the group, allowing collaborative editing.' },

    // 22. Restarting Samba
    { type: 'lesson', category: 'Samba', title: 'Samba: Restart & Test', subtitle: 'systemctl restart smbd', desc: 'After changing the config or adding users, restart the Samba daemon and test the syntax of the config file.', syntax: 'testparm\nsudo systemctl restart smbd nmbd', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">testparm</span><br><span class="out">Load smb config files from /etc/samba/smb.conf</span><br><span class="out">Loaded services file OK.</span><br><span class="out">Server role: ROLE_STANDALONE</span><br><br><span class="out" style="color:#E8A07A">Press enter to see a dump of your service definitions</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl restart smbd nmbd</span><br><span class="out">(Changes are now live)</span>'}], explain: '<strong>Explanation:</strong> <code>testparm</code> parses the config file and reports syntax errors before you restart the service. This prevents you from breaking the Samba server with a typo. You must restart both <code>smbd</code> (file sharing) and <code>nmbd</code> (name resolution).' },

    // 23. Windows Firewall for Samba
    { type: 'lesson', category: 'Samba', title: 'Windows: Firewall', subtitle: 'File Sharing Rules', desc: 'Windows Server 2022 blocks inbound SMB traffic by default. We must enable the File and Printer Sharing firewall rule on the Windows client.', syntax: 'Enable-NetFirewallRule -DisplayGroup "File and Printer Sharing"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Enable-NetFirewallRule -DisplayGroup "File and Printer Sharing"</span><br><span class="out">Name : {a1b2...}</span><br><span class="out">DisplayName : File and Printer Sharing (SMB-In)</span><br><span class="out">Enabled : True</span><br><span class="out">Direction : Inbound</span><br><span class="out">Action : Allow</span><br><span class="out">Protocol : TCP</span><br><span class="out">LocalPort : 445</span>'}], explain: '<strong>Explanation:</strong> While Windows can connect to external SMB shares without this rule, enabling it ensures that the Windows Server can also act as a client and browse the network properly. Port 445 must be open.' },

    // 24. Accessing Samba from Windows
    { type: 'lesson', category: 'Samba', title: 'Windows: Access Share', subtitle: 'Map Network Drive', desc: 'On the Windows Server, map the Samba share as a network drive using PowerShell or File Explorer.', syntax: 'net use Z: \\\\192.168.1.20\\ITDept /user:ajsacay password', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> net use Z: \\\\192.168.1.20\\ITDept /user:ajsacay P@ssw0rd123!</span><br><span class="out">The command completed successfully.</span><br><br><span class="cmd">> dir Z:</span><br><span class="out">Volume in drive Z is ITDept</span><br><span class="out">Directory of Z:\\</span><br><br><span class="out">10/24/2024 10:30 AM &lt;DIR&gt; database_backups</span><br><span class="out">10/24/2024 10:35 AM 1024 notes.txt</span>'}], explain: '<strong>Explanation:</strong> The UNC path (Universal Naming Convention) uses backslashes. In PowerShell, you must escape them (\\\\). The drive is now mapped to Z:. Any files dropped here are instantly saved on the Ubuntu server in /srv/samba/shared.' },

    // 25. Backup Overview
    { type: 'lesson', category: 'Backup', title: 'Backup Overview', subtitle: 'The 3-2-1 Rule', desc: 'The golden rule of backup is the 3-2-1 strategy. It ensures data survives even if the entire building burns down.', syntax: '3 Copies, 2 Media, 1 Offsite', term: [{raw: '<span class="out" style="color:#E8A07A">The 3-2-1 Strategy</span><br><br><span class="out">3: Keep THREE copies of your data (1 primary, 2 backups).</span><br><span class="out">2: Store backups on TWO different types of media (e.g., HDD + Cloud).</span><br><span class="out">1: Keep ONE backup copy offsite (e.g., Azure, AWS, or another building).</span><br><br><span class="out" style="color:#E8A07A">Why?</span><br><span class="out">If your server dies, and your backup drive is plugged into the same server, you lose both. Ransomware also encrypts attached backups.</span>'}], explain: '<strong>Explanation:</strong> In this course, our server is the primary. We will create a backup to a local LVM mount (Media 1) and use rsync to push a copy to a remote server or cloud (Media 2 / Offsite).' },

    // 26. Backup Types
    { type: 'lesson', category: 'Backup', title: 'Backup Types', subtitle: 'Full vs Incremental vs Differential', desc: 'Choosing the right backup type balances storage space, backup speed, and restore speed.', syntax: 'Full -> Incremental -> Differential', term: [{raw: '<span class="out" style="color:#E8A07A">1. Full Backup</span><br><span class="out">Copies ALL selected data. Takes longest, uses most space. Fastest to restore.</span><br><br><span class="out" style="color:#E8A07A">2. Incremental Backup</span><br><span class="out">Copies only files changed SINCE THE LAST BACKUP (of any type). Fast, small. Slow to restore (must apply Full + every Incremental).</span><br><br><span class="out" style="color:#E8A07A">3. Differential Backup</span><br><span class="out">Copies files changed SINCE THE LAST FULL BACKUP. Medium speed/size. Restore requires only Full + latest Differential.</span>'}], explain: '<strong>Explanation:</strong> Incremental backups are great for daily backups because they are small. But if the server crashes on Friday, you must restore Sunday\'s Full, then Mon, Tue, Wed, Thu, Fri incrementals. Differential grows each day, but you only need the Full and Friday\'s Differential to restore.' },

    // 27. Calculating 4-Week Storage Strategy
    { type: 'lesson', category: 'Backup', title: 'Storage Calculation', subtitle: '4-Week Strategy', desc: 'Calculate storage requirements for a 4-week backup strategy. Assume 100GB data, 10% daily change. Strategy: 1 Full/week, Incrementals other days.', syntax: 'Week 1: Full (Sun) + 6 Incr (Mon-Sat)\nRepeat for 4 weeks', term: [{raw: '<span class="out" style="color:#E8A07A">Assumptions</span><br><span class="out">Total Data: 100 GB</span><br><span class="out">Daily Change: 10% (10 GB)</span><br><br><span class="out" style="color:#E8A07A">Weekly Calculation</span><br><span class="out">Sunday (Full): 100 GB</span><br><span class="out">Monday (Incr): 10 GB</span><br><span class="out">Tuesday (Incr): 10 GB</span><br><span class="out">...</span><br><span class="out">Saturday (Incr): 10 GB</span><br><span class="out">Total Week 1: 100 + (6 * 10) = 160 GB</span><br><br><span class="out" style="color:#E8A07A">Total 4 Weeks</span><br><span class="out">160 GB * 4 weeks = 640 GB total storage needed.</span>'}], explain: '<strong>Explanation:</strong> If we used Differential instead: Sunday (100GB) + Mon (10) + Tue (20) + Wed (30)... the storage grows faster. The choice depends on whether you prioritize storage space (Incremental) or restore speed (Differential).' },

    // 28. rsync Introduction
    { type: 'lesson', category: 'rsync', title: 'rsync Introduction', subtitle: 'Efficient Syncing', desc: '<code>rsync</code> (Remote Sync) is the standard Linux tool for backups. It only transfers the parts of files that have changed, saving massive amounts of time and bandwidth.', syntax: 'rsync -avz /source/ /destination/', term: [{raw: '<span class="out" style="color:#E8A07A">Why rsync is better than cp</span><br><br><span class="out">1. Delta Transfer: If a 1GB log file has 1MB of new text, rsync only sends the 1MB.</span><br><span class="out">2. Compression: Data is compressed during transit (-z).</span><br><span class="out">3. Permissions: Retains file ownership, timestamps, and permissions (-a).</span><br><span class="out">4. Verification: Checks file checksums to ensure integrity.</span>'}], explain: '<strong>Explanation:</strong> <code>cp</code> copies the whole file every time. If you have a 50GB database file and change 1 row, <code>cp</code> rewrites the entire 50GB. <code>rsync</code> calculates the differences and only transfers the changed blocks.' },

    // 29. rsync Syntax & Basic Usage
    { type: 'lesson', category: 'rsync', title: 'rsync: Basic Usage', subtitle: 'Local Copy', desc: 'Use rsync to copy files locally. The trailing slash on the source is crucial. A trailing slash copies contents; no slash copies the folder itself.', syntax: 'rsync -avz /source/ /destination/', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">rsync -avz /var/www/ /mnt/data/backup/</span><br><span class="out">sending incremental file list</span><br><span class="out">index.html</span><br><span class="out">images/</span><br><span class="out">images/logo.png</span><br><br><span class="out">sent 1.24M bytes  received 230 bytes  2.48M bytes/sec</span><br><span class="out">total size is 5.2M  speedup is 4.1</span><br><br><span class="out" style="color:#E8A07A">Trailing Slash Warning</span><br><span class="out">rsync /var/www /mnt/data -> Creates /mnt/data/www/</span><br><span class="out">rsync /var/www/ /mnt/data -> Copies contents INTO /mnt/data/</span>'}], explain: '<strong>Explanation:</strong> Always double-check your trailing slashes. <code>-v</code> is verbose. <code>-a</code> is archive mode (recursive, preserve permissions). <code>-z</code> is compress during transfer. This is the "holy trinity" of rsync flags.' },

    // 30. rsync Flags Explained
    { type: 'lesson', category: 'rsync', title: 'rsync: Flags Explained', subtitle: '-a, -v, -z, --delete', desc: 'Understand the key rsync flags to control how files are copied and synchronized.', syntax: '-a (archive) -v (verbose) -z (compress) --delete (mirror)', term: [{raw: '<span class="out" style="color:#E8A07A">Key rsync Flags</span><br><br><span class="out">-a (archive): Recurse into directories, preserve symlinks, permissions, times, group, owner.</span><br><span class="out">-v (verbose): Print out what is being copied.</span><br><span class="out">-z (compress): Compress file data during transfer (good for network, bad for local).</span><br><span class="out">--delete: Delete files in destination that no longer exist in source. (Creates a true mirror).</span><br><br><span class="out" style="color:#E8A07A">Local Backup Example</span><br><span class="cmd">rsync -a --delete /var/www/ /mnt/data/backup/www/</span>'}], explain: '<strong>Explanation:</strong> <code>--delete</code> is powerful but dangerous. If you run it with the wrong source path, it will delete everything in the destination. Always use <code>-n</code> (dry-run) first to see what would happen without actually deleting.' },

    // 31. rsync with Timestamps
    { type: 'lesson', category: 'rsync', title: 'rsync: Timestamped Backups', subtitle: 'Rotating Backups', desc: 'A single backup overwrites the previous one. To keep history, we create a new folder for each day using the <code>date</code> command.', syntax: 'DATE=$(date +%Y%m%d)\nrsync -a /source/ /backup/$DATE/', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">DATE=$(date +%Y%m%d)</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">mkdir -p /mnt/data/backup/$DATE</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">rsync -a /var/www/ /mnt/data/backup/$DATE/</span><br><span class="out">sent 5.2M bytes  received 230 bytes  10.4M bytes/sec</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ls /mnt/data/backup/</span><br><span class="out">20241024  20241023  20241022</span>'}], explain: '<strong>Explanation:</strong> The <code>$(date +%Y%m%d)</code> command substitution creates a folder named "20241024". This gives you a point-in-time snapshot for each day. However, this is not a true incremental backup; it copies everything every time. We need to add hard links for true incrementals.' },

    // 32. rsync: True Incremental with Hard Links
    { type: 'lesson', category: 'rsync', title: 'rsync: Hard Link Backups', subtitle: '--link-dest', desc: 'Use <code>--link-dest</code> to create a full backup that shares unchanged files with the previous backup via hard links. This looks like a full backup but takes almost zero space.', syntax: 'rsync -a --link-dest=/backup/yesterday /source/ /backup/today/', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">YESTERDAY=$(date -d "yesterday" +%Y%m%d)</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">TODAY=$(date +%Y%m%d)</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">rsync -a --link-dest=/backup/$YESTERDAY /var/www/ /backup/$TODAY/</span><br><br><span class="out" style="color:#E8A07A">How it works</span><br><span class="out">1. If file.txt exists in yesterday and hasn\'t changed, rsync creates a hard link in today\'s folder.</span><br><span class="out">2. A hard link points to the same inode (data on disk). Zero extra space used.</span><br><span class="out">3. If file.txt was changed, rsync copies the new version into today\'s folder.</span>'}], explain: '<strong>Explanation:</strong> This is the ultimate Linux backup trick. Each day\'s folder appears to contain every file, so you can browse or restore from any day. But unchanged files share the same disk blocks. You get the space savings of Incremental with the restore speed of Full.' },

    // 33. Automation: Backup Script
    { type: 'lesson', category: 'Automation', title: 'Automation: Backup Script', subtitle: 'backup.sh', desc: 'Combine LVM, rsync, and timestamp logic into a single robust Bash script to automate the backup process.', syntax: '#!/bin/bash\nset -e\ntrap cleanup EXIT', term: [{editor: "backup.sh", code: "#!/bin/bash\nset -e\nDATE=$(date +%Y%m%d)\nSRC=/var/www/\nDEST=/mnt/data/backup/$DATE/\nLOG=/var/log/backup.log\n\necho \"Starting backup for $DATE\" >> $LOG\nmkdir -p $DEST\n\n# Perform the rsync backup\nrsync -a $SRC $DEST\n\n# Clean up backups older than 7 days\nfind /mnt/data/backup/ -maxdepth 1 -type d -mtime +7 -exec rm -rf {} \\;\n\necho \"Backup complete.\" >> $LOG"}, {raw: '<span class="out" style="color:#E8A07A">Script Breakdown</span><br><span class="out">1. set -e: Stop if any command fails.</span><br><span class="out">2. mkdir -p: Creates the day\'s folder.</span><br><span class="out">3. rsync -a: Copies the data safely.</span><br><span class="out">4. find -mtime +7: Deletes folders older than 7 days. (Retention Policy).</span>'}], explain: '<strong>Explanation:</strong> This script is a complete backup solution. It creates a daily timestamped folder, copies the data, and automatically deletes old backups to prevent the disk from filling up. This satisfies the syllabus requirement for rsync automation.' },

    // 34. Scheduling with Cron
    { type: 'lesson', category: 'Automation', title: 'Automation: Scheduling', subtitle: 'crontab -e', desc: 'A script is useless if you must run it manually. Use <code>cron</code> to schedule the backup script to run automatically every night at 2:00 AM.', syntax: 'crontab -e\n# Add: 0 2 * * * /home/ajsacay/backup.sh', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">chmod +x backup.sh</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">crontab -e</span><br><br><span class="out" style="color:#E8A07A">Cron Entry (0 2 * * *)</span><br><span class="out"># m h  dom mon dow   command</span><br><span class="out">0   2   *   *   *   /home/ajsacay/backup.sh >> /var/log/backup.log 2>&1</span><br><br><span class="out" style="color:#E8A07A">Syntax</span><br><span class="out">m: Minute (0)</span><br><span class="out">h: Hour (2)</span><br><span class="out">dom: Day of Month (*)</span><br><span class="out">mon: Month (*)</span><br><span class="out">dow: Day of Week (*)</span>'}], explain: '<strong>Explanation:</strong> The <code>>> /var/log/backup.log 2>&1</code> part is crucial. It redirects the script\'s output to a log file. Because cron runs in the background without a terminal, you won\'t see errors unless you log them. The <code>2>&1</code> captures both standard output and errors.' },

    // 35. Restoring from Backup
    { type: 'lesson', category: 'Backup', title: 'Backup: Restoring', subtitle: 'The Final Test', desc: 'A backup is only as good as your ability to restore it. Practice restoring a file from the timestamped rsync backup.', syntax: 'rsync -a /backup/20241023/file.txt /var/www/', term: [{raw: '<span class="out" style="color:#E8A07A">Disaster Scenario</span><br><span class="out">A user accidentally deleted /var/www/index.html.</span><br><br><span class="out" style="color:#E8A07A">Step 1: Find the backup</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">ls /mnt/data/backup/</span><br><span class="out">20241024  20241023  20241022</span><br><br><span class="out" style="color:#E8A07A">Step 2: Restore from yesterday</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo rsync -a /mnt/data/backup/20241023/index.html /var/www/</span><br><span class="out">(File is instantly restored to its state from yesterday)</span>'}], explain: '<strong>Explanation:</strong> Because we used <code>rsync -a</code> to backup, the restored file retains its original permissions and timestamps. The restore command is just rsync in reverse (source and destination swapped).' },

    // 36. LVM Snapshots (Concept)
    { type: 'lesson', category: 'LVM', title: 'LVM: Snapshots', subtitle: 'Point-in-Time', desc: 'LVM can create snapshots. A snapshot is a frozen view of a volume at a specific moment. It allows you to backup a live database without corruption.', syntax: 'lvcreate -L 1G -s -n lv_snap /dev/vg_data/lv_data', term: [{raw: '<span class="out" style="color:#E8A07A">How LVM Snapshots Work</span><br><br><span class="out">1. You create a snapshot of lv_data (1GB space).</span><br><span class="out">2. The snapshot starts empty.</span><br><span class="out">3. When a file on lv_data is changed, the OLD version is copied to the snapshot volume.</span><br><span class="out">4. You mount the snapshot and backup the frozen state.</span><br><br><span class="out" style="color:#E8A07A">Why?</span><br><span class="out">If you rsync a live database, the files might change mid-copy, resulting in a corrupt backup. A snapshot ensures consistency.</span>'}], explain: '<strong>Explanation:</strong> Snapshots are a "Copy-on-Write" mechanism. They only store the changes (deltas). This allows you to take a consistent backup of a running virtual machine or database without taking it offline.' },

    // 37. Topic Summary
    { type: 'lesson', category: 'Summary', title: 'Topic Summary', subtitle: 'Module 4 Complete', desc: 'You have mastered dynamic storage (LVM), file sharing (Samba), and automated backups (rsync + cron). This is the core of data management.', syntax: 'lvextend -L +5G /dev/vg_data/lv_data\nsudo resize2fs /dev/vg_data/lv_data\nnet use Z: \\\\192.168.1.20\\ITDept\nrsync -a /var/www/ /backup/', term: [{raw: '<span class="out" style="color:#E8A07A">Module 4 Checklist:</span><br>[x] LVM Architecture understood (PV, VG, LV)<br>[x] LV extended online (lvextend + resize2fs)<br>[x] File systems created and mounted persistently<br>[x] Samba share configured and accessible from Windows<br>[x] Backup strategy calculated (Full vs Incremental)<br>[x] rsync automated with timestamps via cron<br><br><span class="out">Next: We will move to Security Management, System Hardening, and Compliance (CIS Benchmark).</span>'}], explain: '<strong>Explanation:</strong> Storage and backup are the sysadmin\'s safety net. LVM gives you flexibility, Samba gives you connectivity, and rsync gives you peace of mind. Automating these processes ensures you never have to do them manually at 2 AM.' },

  {
    type: 'closing',
    header: 'MODULE 04 · TOPIC 11',
    tag: 'End of Topic 11',
    title: 'Storage is <em>Elastic</em>. Backup is <em>Insurance</em>.',
    leftCardNum: '§ lvm & samba',
    leftCardTitle: 'Dynamic Storage & Sharing',
    leftCardDesc: 'LVM separates the physical disk from the logical volume, allowing sysadmins to extend storage without downtime. Samba bridges the gap, making Linux storage visible to Windows clients.',
    middleCardNum: '§ storage & recovery',
    middleCardTitle: 'System Resilience',
    middleCardDesc: 'The right storage layout and restore plan make a server resilient under pressure, growth, and failure conditions.',
    rightCardNum: '§ rsync & cron',
    rightCardTitle: 'Backup Automation',
    rightCardDesc: 'Understanding the storage trade-offs of Full, Differential, and Incremental backups is crucial. Automating rsync via cron ensures backups happen consistently, without relying on human memory.'
  }
];