const slideConfigs = [
  // --- 1. COVER SLIDE ---
  {
    type: 'cover',
    moduleTitle: 'MODULE 04 · TOPIC 12',
    topicNum: '12',
    topicTag: 'T12',
    title: 'Security, Hardening<br>& <em>Compliance</em>',
    subtitle: 'Locking down the dual-OS environment: Applying CIS Level 1 controls, configuring firewalls, preventing brute-force attacks, and generating compliance reports.',
    graphicText: 'Harden <em>Systems</em><br>Block <em>Attacks</em><br>Prove Compliance.',
    miniObjectives: [
      'CIS Benchmark Level 1',
      'UFW & Windows Firewall',
      'Fail2ban & SSH Keys',
      'Lynis HTML Report'
    ]
  },

  // --- 2. OBJECTIVES SLIDE ---
  {
    type: 'objectives',
    header: 'MODULE 04 · TOPIC 12',
    kicker: 'ITP 141 · M4 · T12',
    desc: 'Security is not a product, it is a process. You will learn to apply industry-standard baselines, restrict network access, and verify your security posture.',
    lede: 'An unpatched, open server is a liability. Master hardening and compliance to ensure your infrastructure meets security standards and survives attacks.',
    list: [
      'Understand the CIS Benchmark Level 1 and NIST 800-53 frameworks.',
      'Apply ten CIS Benchmark Level 1 controls on Ubuntu Server 24.04 LTS.',
      'Configure UFW (Uncomplicated Firewall) on Ubuntu using default-deny.',
      'Configure Windows Firewall using PowerShell with explicit allow rules.',
      'Install and configure Fail2ban to verify SSH brute-force protection.',
      'Configure SSH Key Authentication and disable password login.',
      'Run Lynis to audit the system and generate a hardening index.',
      'Generate an HTML compliance summary report through a Bash script.'
    ]
  },

  // --- 3. LESSON SLIDES ---
  { type: 'lesson', category: 'Overview', title: 'Security Overview', subtitle: 'The CIA Triad', desc: 'Security management ensures the Confidentiality, Integrity, and Availability (CIA) of data. Hardening is the process of reducing a system\'s attack surface.', syntax: 'Confidentiality: Only authorized users can read.\nIntegrity: Only authorized users can write.\nAvailability: System is accessible when needed.', term: [{raw: '<span class="out" style="color:#E8A07A">The Security Lifecycle</span><br><br><span class="out">1. Baseline: Apply CIS Level 1 controls.</span><br><span class="out">2. Restrict: Configure Firewalls (UFW/Windows).</span><br><span class="out">3. Protect: Stop brute-force (Fail2ban) & use SSH Keys.</span><br><span class="out">4. Audit: Run Lynis and generate compliance reports.</span>'}], explain: '<strong>Explanation:</strong> You cannot secure a system completely, but you can make it harder to attack than the next target. Hardening removes unnecessary services and locks down the necessary ones.' },
    
  { type: 'lesson', category: 'Overview', title: 'Hardening Concept', subtitle: 'Least Privilege', desc: 'The Principle of Least Privilege (PoLP) means giving a user or process only the minimum access rights needed to perform its job, and no more.', syntax: 'User -> Needs to read log -> Grant READ ONLY (not write)', term: [{raw: '<span class="out" style="color:#E8A07A">Applying PoLP to Sysadmin Tasks</span><br><br><span class="out">1. Do not log in as root. Use sudo for specific commands.</span><br><span class="out">2. Do not run web servers as root. Use a dedicated user (e.g., www-data).</span><br><span class="out">3. Do not open port 22 (SSH) to the whole internet. Restrict to specific IPs.</span><br><span class="out">4. If a service does not need internet access, do not allow it outbound.</span>'}], explain: '<strong>Explanation:</strong> If a web server runs as root and an attacker exploits a vulnerability in the web app, the attacker gets root access. If the web server runs as a limited user, the attacker is trapped in that user\'s context.' },
  
  { type: 'lesson', category: 'Frameworks', title: 'Security Frameworks', subtitle: 'CIS vs NIST', desc: 'Frameworks provide structured, documented security controls. CIS focuses on configuration baselines, while NIST focuses on processes and documentation.', syntax: 'CIS: How to configure the OS.\nNIST: How to manage the security program.', term: [{raw: '<span class="out" style="color:#E8A07A">CIS (Center for Internet Security)</span><br><span class="out">- Provides specific, step-by-step configuration guides.</span><br><span class="out">- Example: "Ensure password length is 14 chars."</span><br><br><span class="out" style="color:#E8A07A">NIST 800-53</span><br><span class="out">- Provides a catalog of security controls for US federal agencies.</span><br><span class="out">- Example: "Implement an access control policy."</span><br><br><span class="out" style="color:#E8A07A">For this course</span><br><span class="out">We will apply CIS Level 1 controls and align them with NIST control families.</span>'}], explain: '<strong>Explanation:</strong> CIS tells you exactly what to type into the terminal. NIST tells you why you are doing it and how to document it for an auditor. Both are essential for enterprise compliance.' },
  
  { type: 'lesson', category: 'CIS Benchmark', title: 'CIS Benchmark', subtitle: 'Introduction', desc: 'A CIS Benchmark is a set of consensus-based secure configuration guidelines for over 100 technologies. It is the industry standard for hardening.', syntax: 'OS: Ubuntu 24.04 LTS\nLevel: Level 1 (Basic Security)', term: [{raw: '<span class="out" style="color:#E8A07A">CIS Benchmark Scope</span><br><br><span class="out">1. Initial Setup: Ensure filesystem integrity, secure boot.</span><br><span class="out">2. Services: Disable unnecessary daemons.</span><br><span class="out">3. Network Configuration: Restrict IPv6, disable IP forwarding.</span><br><span class="out">4. Logging: Configure rsyslog, install auditd.</span><br><span class="out">5. Access: Configure SSH, PAM, and user accounts.</span>'}], explain: '<strong>Explanation:</strong> The Ubuntu 24.04 LTS benchmark contains over 200 specific recommendations. In this module, we will focus on the ten most critical Level 1 controls to secure the server against common attacks.' },
  
  { type: 'lesson', category: 'CIS Benchmark', title: 'CIS Levels', subtitle: 'Level 1 vs Level 2', desc: 'CIS Benchmarks are divided into Level 1 (basic) and Level 2 (high security). Level 1 applies to most enterprise environments.', syntax: 'Level 1: Basic Security\nLevel 2: High Security', term: [{raw: '<span class="out" style="color:#E8A07A">Level 1 (Basic Security)</span><br><span class="out">- Minimal impact on business operations.</span><br><span class="out">- Stops common attacks and misconfigurations.</span><br><span class="out">- Applicable to 90% of servers.</span><br><br><span class="out" style="color:#E8A07A">Level 2 (High Security)</span><br><span class="out">- Strict settings that may break some applications.</span><br><span class="out">- Requires extensive testing before deployment.</span><br><span class="out">- Used in defense, finance, and healthcare.</span>'}], explain: '<strong>Explanation:</strong> Jumping straight to Level 2 can break services. For example, Level 2 might require disabling all outbound traffic except port 443. If your server needs to pull updates from a custom port, it will fail. We will stick to Level 1.' },
  
  { type: 'lesson', category: 'CIS Benchmark', title: 'CIS Ubuntu Controls', subtitle: 'Examples', desc: 'Examples of CIS Level 1 controls for Ubuntu Server. These target the most common vulnerabilities in default Linux installations.', syntax: 'sudo sysctl -w net.ipv4.ip_forward=0\nsudo sysctl -w net.ipv4.conf.all.send_redirects=0', term: [{raw: '<span class="out" style="color:#E8A07A">CIS Ubuntu 24.04 Control Examples</span><br><br><span class="out">1. Ensure mounting of cramfs, freevxfs, jffs2, hfs, hfsplus, squashfs, udf filesystems is disabled.</span><br><span class="out">2. Ensure IP forwarding is disabled (Prevent the server from routing traffic).</span><br><span class="out">3. Ensure password creation requirements are configured in /etc/pam.d/common-password.</span><br><span class="out">4. Ensure permissions on /etc/passwd are configured (644).</span>'}], explain: '<strong>Explanation:</strong> Disabling IP forwarding is critical. If a server is compromised and IP forwarding is on, the attacker can use your server as a router to bypass network security boundaries. PAM rules enforce strong passwords.' },
  
  { type: 'lesson', category: 'CIS Benchmark', title: 'CIS Windows Controls', subtitle: 'Examples', desc: 'Examples of CIS Level 1 controls for Windows Server 2022. These focus on account lockout, network access, and event logging.', syntax: 'net accounts /lockoutthreshold:5\nnet accounts /maxpwage:60', term: [{raw: '<span class="out" style="color:#E8A07A">CIS Windows Server 2022 Control Examples</span><br><br><span class="out">1. Ensure Account Lockout Duration is set to 15 minutes or more.</span><br><span class="out">2. Ensure Force audit policy subcategory settings is set to Enabled.</span><br><span class="out">3. Ensure Windows Firewall: Domain Profile is set to On.</span><br><span class="out">4. Ensure Network security: LAN Manager authentication level is set to Send NTLMv2 only.</span>'}], explain: '<strong>Explanation:</strong> Account lockout stops brute-force attacks. Requiring NTLMv2 prevents older, vulnerable authentication protocols from being used. Default Windows settings are too permissive for a server facing the internet.' },
  
  { type: 'lesson', category: 'NIST', title: 'NIST 800-53', subtitle: 'Control Families', desc: 'NIST Special Publication 800-53 provides a catalog of security controls for federal information systems. It focuses on the process, not just the configuration.', syntax: 'Family: Access Control (AC)\nControl: AC-2: Account Management', term: [{raw: '<span class="out" style="color:#E8A07A">Key NIST Control Families</span><br><br><span class="out">AC: Access Control (Who can log in? Who can read files?)</span><br><span class="out">AU: Audit and Accountability (Are we logging actions?)</span><br><span class="out">SC: System and Communications Protection (Firewalls, encryption)</span><br><span class="out">IA: Identification and Authentication (Passwords, MFA)</span><br><br><span class="out" style="color:#E8A07A">How it aligns</span><br><span class="out">Configuring UFW satisfies SC-7 (Boundary Protection).</span>'}], explain: '<strong>Explanation:</strong> When you run Lynis at the end of this module, it will output a list of warnings and suggestions. These map directly to NIST control families. The HTML report you generate serves as the "Audit and Accountability" (AU) evidence for compliance.' },
  
  { type: 'lesson', category: 'UFW', title: 'UFW Introduction', subtitle: 'Uncomplicated Firewall', desc: 'UFW (Uncomplicated Firewall) is the default firewall configuration tool for Ubuntu. It wraps the complex <code>iptables</code> rules into simple commands.', syntax: 'sudo ufw status\nsudo ufw enable', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw status</span><br><span class="out">Status: inactive</span><br><br><span class="out" style="color:#E8A07A">Why UFW?</span><br><span class="out">iptables -A INPUT -p tcp --dport 22 -j ACCEPT</span><br><span class="out">That is the iptables command to allow SSH.</span><br><br><span class="out">sudo ufw allow ssh</span><br><span class="out">This is the UFW equivalent. Much simpler and less prone to errors.</span>'}], explain: '<strong>Explanation:</strong> UFW is a frontend for iptables. It does not provide new security; it just makes configuring iptables easier. A misconfigured firewall can lock you out of your server, so simplicity is a security feature.' },
  
  { type: 'lesson', category: 'UFW', title: 'UFW: Default Policy', subtitle: 'Default Deny', desc: 'The safest firewall policy is "Default Deny". Block all incoming traffic by default, and explicitly allow only what is needed.', syntax: 'sudo ufw default deny incoming\nsudo ufw default allow outgoing', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw default deny incoming</span><br><span class="out">Default incoming policy changed to deny</span><br><span class="out">(be sure to update your rules to allow SSH)</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw default allow outgoing</span><br><span class="out">Default outgoing policy changed to allow</span><br><br><span class="out" style="color:#E8A07A">CIS Control Mapping</span><br><span class="out">This satisfies SC-7 (Boundary Protection) by default.</span>'}], explain: '<strong>Explanation:</strong> If you enable UFW with a "deny all" policy WITHOUT allowing SSH first, your SSH connection will drop immediately, and you will be locked out. Always add the SSH rule before enabling.' },
  
  { type: 'lesson', category: 'UFW', title: 'UFW: Allow Services', subtitle: 'SSH & HTTP', desc: 'Allow essential services through the firewall. Always allow SSH (port 22) and, if it is a web server, ports 80 and 443.', syntax: 'sudo ufw allow ssh\nsudo ufw allow http\nsudo ufw allow https', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw allow ssh</span><br><span class="out">Rules updated</span><br><span class="out">Rules updated (v6)</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw allow 8083/tcp</span><br><span class="out">Rules updated</span><br><br><span class="out" style="color:#E8A07A">Naming vs Ports</span><br><span class="out">UFW knows ssh, http, https. For custom ports, use the number (8083/tcp).</span>'}], explain: '<strong>Explanation:</strong> By default, UFW rules allow traffic from any IP address to the specified port. Later, we will restrict SSH to only your office IP address for tighter security.' },
  
  { type: 'lesson', category: 'UFW', title: 'UFW: Enable', subtitle: 'Turning it On', desc: 'Once the default policy and SSH rule are in place, enable the firewall. This applies the rules to the kernel via iptables.', syntax: 'sudo ufw enable', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw enable</span><br><span class="out">Command may disrupt existing ssh connections. Proceed with operation (y|n)? y</span><br><span class="out">Firewall is active and enabled on system startup</span><br><br><span class="out" style="color:#E8A07A">Persistence</span><br><span class="out">UFW rules are saved in /etc/ufw/user.rules and survive a reboot.</span>'}], explain: '<strong>Explanation:</strong> UFW warns you about SSH disruption because if your current IP is not allowed, it will drop your session. Since we added "allow ssh", it should be fine. The rules are immediately active and will load on boot.' },
  
  { type: 'lesson', category: 'UFW', title: 'UFW: Status', subtitle: 'Verifying Rules', desc: 'Verify the firewall rules are active and correct. Use the verbose flag to see the default policies.', syntax: 'sudo ufw status verbose', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw status verbose</span><br><span class="out">Status: active</span><br><span class="out">Logging: on (low)</span><br><span class="out">Default: deny (incoming), allow (outgoing), disabled (routed)</span><br><span class="out">New profiles: skip</span><br><br><span class="out">To                         Action      From</span><br><span class="out">--                         ------     ----</span><br><span class="out">22/tcp                     ALLOW IN   Anywhere</span><br><span class="out">80/tcp                     ALLOW IN   Anywhere</span><br><span class="out">22/tcp (v6)                ALLOW IN   Anywhere (v6)</span>'}], explain: '<strong>Explanation:</strong> The status shows the default policy, followed by the specific allow rules. You can see both IPv4 and IPv6 rules. If a rule is missing, it means traffic to that port will be dropped.' },
  
  { type: 'lesson', category: 'UFW', title: 'UFW: Deleting Rules', subtitle: 'Removing Access', desc: 'If a service is decommissioned, you must remove its firewall rule. This closes the port and reduces the attack surface.', syntax: 'sudo ufw delete allow http', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw status</span><br><span class="out">80/tcp                     ALLOW IN   Anywhere</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw delete allow http</span><br><span class="out">Rule deleted</span><span class="out">Rule deleted (v6)</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw status</span><br><span class="out">(Port 80 is no longer listed)</span>'}], explain: '<strong>Explanation:</strong> Leaving unused ports open is a major security risk. Automated scanners constantly probe the internet for open ports. If you installed Apache for testing but no longer use it, delete the port 80 rule and stop the service.' },
  
  { type: 'lesson', category: 'Windows Firewall', title: 'Windows Firewall', subtitle: 'Introduction', desc: 'Windows Firewall (now Windows Defender Firewall) blocks unauthorized incoming traffic by default. It is managed via GUI or the <code>netsh</code> and PowerShell cmdlets.', syntax: 'Get-NetFirewallProfile', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Get-NetFirewallProfile</span><br><br><span class="out">Name                            : Domain</span><br><span class="out">Enabled                         : True</span><br><span class="out">Default Inbound Action          : Block</span><br><span class="out">Default Outbound Action         : Allow</span><br><br><span class="out">Name                            : Private</span><br><span class="out">Enabled                         : True</span><br><span class="out">Default Inbound Action          : Block</span>'}], explain: '<strong>Explanation:</strong> Windows Firewall is enabled by default and blocks inbound connections unless explicitly allowed. This is equivalent to Ubuntu\'s UFW default deny policy.' },
  
  { type: 'lesson', category: 'Windows Firewall', title: 'Windows Firewall Profiles', subtitle: 'Domain, Private, Public', desc: 'Windows uses network profiles to apply different firewall rules based on the network you are connected to.', syntax: 'Set-NetFirewallProfile -Profile Public -Enabled True', term: [{raw: '<span class="out" style="color:#E8A07A">The Three Profiles</span><br><br><span class="out">1. Domain: Used when the computer is joined to an AD domain (e.g., dorsu.lab).</span><br><span class="out">2. Private: Used for trusted home or office networks.</span><br><span class="out">3. Public: Used for untrusted networks (e.g., airports, cafes).</span><br><br><span class="out" style="color:#E8A07A">Why profiles matter</span><br><span class="out">A laptop might allow File Sharing on Private, but block it on Public to prevent strangers from accessing files.</span>'}], explain: '<strong>Explanation:</strong> A server in a data center is usually on the Domain profile. A sysadmin\'s laptop uses Public when traveling and Private at home. The firewall rules adapt automatically based on the network classification.' },
  
  { type: 'lesson', category: 'Windows Firewall', title: 'Windows Firewall: Rules', subtitle: 'PowerShell', desc: 'Use PowerShell to create explicit allow rules. The syntax defines the display name, direction, protocol, local port, and action.', syntax: 'New-NetFirewallRule -DisplayName "HTTP 8083" -Direction Inbound -Protocol TCP -LocalPort 8083 -Action Allow', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> New-NetFirewallRule -DisplayName "Docker Web" -Direction Inbound -Protocol TCP -LocalPort 8083 -Action Allow</span><br><br><span class="out">Name : {a1b2...}</span><br><span class="out">DisplayName : Docker Web</span><br><span class="out">Enabled : True</span><br><span class="out">Direction : Inbound</span><br><span class="out">Action : Allow</span><br><span class="out">Protocol : TCP</span><br><span class="out">LocalPort : 8083</span>'}], explain: '<strong>Explanation:</strong> This command opens port 8083 for the Docker Web stack we deployed in Topic 9. Without this rule, traffic to http://localhost:8083 from another computer would be silently dropped by the Windows Firewall.' },
  
  { type: 'lesson', category: 'Windows Firewall', title: 'Windows Firewall: Block', subtitle: 'Explicit Deny', desc: 'You can create explicit block rules to deny traffic to specific ports or applications, overriding any broad allow rules.', syntax: 'New-NetFirewallRule -DisplayName "Block Telnet" -Direction Inbound -Protocol TCP -LocalPort 23 -Action Block', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> New-NetFirewallRule -DisplayName "Block Telnet" -Direction Inbound -Protocol TCP -LocalPort 23 -Action Block</span><br><br><span class="out">Name : {c3d4...}</span><br><span class="out">DisplayName : Block Telnet</span><br><span class="out">Enabled : True</span><br><span class="out">Direction : Inbound</span><br><span class="out">Action : Block</span><br><span class="out">LocalPort : 23</span><br><br><span class="out" style="color:#E8A07A">CIS Control</span><br><span class="out">Blocking legacy protocols (Telnet, FTP) is a CIS Level 1 requirement.</span>'}], explain: '<strong>Explanation:</strong> Even if an administrator accidentally enables the Telnet service, this firewall rule ensures no one can connect to it. Block rules take precedence over allow rules in Windows Firewall.' },
  
  { type: 'lesson', category: 'Fail2ban', title: 'Fail2ban', subtitle: 'Introduction', desc: 'Fail2ban is an intrusion prevention software framework that protects Linux servers from brute-force attacks. It reads log files and bans IPs that show malicious signs.', syntax: 'sudo apt install fail2ban', term: [{raw: '<span class="out" style="color:#E8A07A">The Brute-Force Problem</span><br><br><span class="out">Attackers run scripts that try thousands of SSH passwords (admin, root, password123) against your server.</span><br><br><span class="out" style="color:#E8A07A">The Fail2ban Solution</span><br><br><span class="out">1. Monitors /var/log/auth.log for failed SSH logins.</span><br><span class="out">2. If an IP fails 5 times in 10 minutes, it bans the IP.</span><br><span class="out">3. The ban is implemented via an iptables rule (firewall drop).</span><br><span class="out">4. The ban lasts 1 hour by default.</span>'}], explain: '<strong>Explanation:</strong> Fail2ban is essential for any Linux server exposed to the internet. Without it, botnets will constantly hammer your SSH port, filling your logs and potentially guessing a weak password.' },
  
  { type: 'lesson', category: 'Fail2ban', title: 'Fail2ban Architecture', subtitle: 'How It Works', desc: 'Fail2ban uses filters (regex patterns) to find bad IPs in log files, and actions (iptables rules) to block them.', syntax: 'Filter: /etc/fail2ban/filter.d/sshd.conf\nAction: /etc/fail2ban/action.d/iptables.conf', term: [{raw: '<span class="out" style="color:#E8A07A">Components</span><br><br><span class="out">1. Jail: A combination of a filter and an action (e.g., sshd jail).</span><br><span class="out">2. Filter: A regex that matches "Failed password for root from 10.0.0.5".</span><br><span class="out">3. Action: The command to run when the filter matches (iptables -A INPUT -s 10.0.0.5 -j DROP).</span><br><br><span class="out" style="color:#E8A07A">Default Jails</span><br><span class="out">- sshd: Protects SSH.</span><br><span class="out">- apache-auth: Protects Apache HTTP auth.</span><br><span class="out">- nginx-http-auth: Protects Nginx.</span>'}], explain: '<strong>Explanation:</strong> Fail2ban is modular. You can write custom filters for any application that logs failed login attempts. The "jail" binds it all together and defines how many failures trigger a ban and for how long.' },
  
  { type: 'lesson', category: 'Fail2ban', title: 'Fail2ban: Install', subtitle: 'apt install', desc: 'Install Fail2ban on the Ubuntu Server. The default configuration protects SSH out of the box.', syntax: 'sudo apt install fail2ban -y\nsudo systemctl status fail2ban', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt install fail2ban -y</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl status fail2ban</span><br><span class="out">\u25cf fail2ban.service - Fail2Ban Service</span><br><span class="out">     Active: active (running) since Wed 2024-10-24 10:00:00 PST</span><br><br><span class="out" style="color:#E8A07A">Is it protecting SSH?</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo fail2ban-client status sshd</span><br><span class="out">Status for the jail: sshd</span><br><span class="out">Currently failed: 0</span><br><span class="out">Currently banned: 0</span>'}], explain: '<strong>Explanation:</strong> Fail2ban starts immediately upon installation and begins monitoring SSH logs. The <code>fail2ban-client status</code> command shows how many IPs are currently banned. It is an instant security upgrade.' },
  
  { type: 'lesson', category: 'Fail2ban', title: 'Fail2ban: jail.local', subtitle: 'Configuration', desc: 'Never edit <code>jail.conf</code> directly. Create a <code>jail.local</code> file to override settings. Your settings survive package upgrades.', syntax: 'sudo nano /etc/fail2ban/jail.local', term: [{editor: "/etc/fail2ban/jail.local", code: "[DEFAULT]\n# Ban for 1 hour\nbantime = 3600\n# 5 failures in 10 minutes triggers a ban\nfindtime = 600\nmaxretry = 5\n\n# Enable SSH protection\n[sshd]\nenabled = true\n# Ignore your own office IP\nignoreip = 127.0.0.1/8 ::1 192.168.1.50"}, {raw: '<span class="out" style="color:#E8A07A">Key Settings</span><br><span class="out">bantime: How long the IP is blocked (3600s = 1hr).</span><br><span class="out">maxretry: Number of failures before ban.</span><br><span class="out">ignoreip: Whitelist. Your office IP should be here so you don\'t ban yourself.</span>'}], explain: '<strong>Explanation:</strong> If you lock yourself out by typing the wrong password 5 times, Fail2ban will ban your IP for an hour. Adding your IP to <code>ignoreip</code> prevents this. Always test SSH in a second terminal before closing the first one when configuring Fail2ban.' },
  
  { type: 'lesson', category: 'Fail2ban', title: 'Fail2ban: Restart & Test', subtitle: 'Verifying', desc: 'Restart the service to apply the new <code>jail.local</code> configuration and test it by failing to log in 5 times.', syntax: 'sudo systemctl restart fail2ban\nsudo fail2ban-client status sshd', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl restart fail2ban</span><br><br><span class="out" style="color:#E8A07A">(From a test machine, try to SSH with wrong passwords 5 times)</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo fail2ban-client status sshd</span><br><span class="out">Status for the jail: sshd</span><br><span class="out">|- Filter</span><br><span class="out">|  |- Currently failed: 5</span><br><span class="out">|  |- Total failed: 5</span><br><span class="out">|- Actions</span><br><span class="out">   |- Currently banned: 1</span><br><span class="out">   |- Banned IP list: 192.168.1.51</span>'}], explain: '<strong>Explanation:</strong> The test machine is now banned for 1 hour. UFW will drop all packets from 192.168.1.51. This proves the integration between Fail2ban and the firewall is working correctly.' },
  
  { type: 'lesson', category: 'Fail2ban', title: 'Fail2ban: Unban', subtitle: 'Releasing an IP', desc: 'If you accidentally ban a legitimate user (or yourself), you can unban the IP manually without waiting for the timer to expire.', syntax: 'sudo fail2ban-client set sshd unbanip 192.168.1.51', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo fail2ban-client set sshd unbanip 192.168.1.51</span><br><br><span class="out" style="color:#E8A07A">Alternative: Use fail2ban-client unban</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo fail2ban-client unban 192.168.1.51</span><br><br><span class="out" style="color:#E8A07A">View all active bans across all jails</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo fail2ban-client banned</span><br><span class="out">[{"sshd": ["192.168.1.51"]}]</span>'}], explain: '<strong>Explanation:</strong> The <code>unbanip</code> command removes the iptables rule immediately. If a user complains they cannot access the server, check Fail2ban first. It is a common issue for users who forget their password and keep trying.' },
  
  { type: 'lesson', category: 'SSH Keys', title: 'SSH Keys: Introduction', subtitle: 'Keys vs Passwords', desc: 'Passwords can be guessed. SSH keys are cryptographic tokens that are impossible to brute-force. They are the standard for secure server administration.', syntax: 'Password: 14 chars, complex (Can be guessed by botnets).\nKey: 256-bit ed25519 (Mathematically impossible to guess).', term: [{raw: '<span class="out" style="color:#E8A07A">Why use SSH Keys?</span><br><br><span class="out">1. Security: Immune to brute-force attacks.</span><br><span class="out">2. Automation: Scripts can connect without a human typing a password.</span><br><span class="out">3. Convenience: Once configured, you log in instantly.</span><br><br><span class="out" style="color:#E8A07A">How it works</span><br><span class="out">- Private Key: Stays on YOUR laptop. Never shared.</span><br><span class="out">- Public Key: Placed on the server in ~/.ssh/authorized_keys.</span><br><span class="out">- The server issues a challenge only the private key can answer.</span>'}], explain: '<strong>Explanation:</strong> If you disable password authentication entirely, botnets can hammer your SSH port forever and never get in. They do not have the private key. This is the single most effective hardening step for a Linux server.' },
  
  { type: 'lesson', category: 'SSH Keys', title: 'SSH Keys: Generate', subtitle: 'ssh-keygen', desc: 'Generate an SSH key pair on your local machine (Windows or Linux). We recommend the modern ed25519 algorithm.', syntax: 'ssh-keygen -t ed25519 -C "ajsacay@dorsu.edu"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> ssh-keygen -t ed25519 -C "ajsacay@dorsu.edu"</span><br><span class="out">Generating public/private ed25519 key pair.</span><br><span class="out">Enter file in which to save the key (C:\\Users\\Admin/.ssh/id_ed25519):</span><br><span class="out">Enter passphrase (empty for no passphrase):</span><br><span class="out">Your identification has been saved in id_ed25519</span><br><span class="out">Your public key has been saved in id_ed25519.pub</span><br><br><span class="out" style="color:#E8A07A">Key Types</span><br><span class="out">- ed25519: Best practice, short, secure.</span><br><span class="out">- rsa: Legacy, requires 4096 bits to be secure.</span>'}], explain: '<strong>Explanation:</strong> The <code>-C</code> flag adds a comment (usually your email) so you know who the key belongs to. A passphrase protects the private key if your laptop is stolen. If you leave it empty, you can log in without typing anything, but anyone with your laptop file can log in too.' },
  
  { type: 'lesson', category: 'SSH Keys', title: 'SSH Keys: Copy', subtitle: 'ssh-copy-id', desc: 'Copy the public key to the Ubuntu server. This appends it to the <code>~/.ssh/authorized_keys</code> file.', syntax: 'ssh-copy-id ajsacay@192.168.1.20', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> ssh-copy-id ajsacay@192.168.1.20</span><br><span class="out">/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s)</span><br><span class="out">ajsacay@192.168.1.20 s password: ********</span><br><span class="out">Number of key(s) added: 1</span><br><br><span class="out">Now try logging into the machine, with: "ssh ajsacay@192.168.1.20"</span><br><br><span class="out" style="color:#E8A07A">Test it</span><br><span class="cmd">> ssh ajsacay@192.168.1.20</span><br><span class="out">Welcome to Ubuntu 24.04 LTS</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="out">(No password required!)</span>'}], explain: '<strong>Explanation:</strong> <code>ssh-copy-id</code> is a convenience script. It logs in with your password once, copies the public key, and logs out. From then on, you use the key. If <code>ssh-copy-id</code> is not available on Windows, you must manually append the key to the file using SSH commands.' },
  
  { type: 'lesson', category: 'SSH Keys', title: 'SSH Keys: Disable Passwords', subtitle: 'sshd_config', desc: 'Once keys are working, disable password authentication in the SSH daemon config. This stops all brute-force attacks instantly.', syntax: 'sudo nano /etc/ssh/sshd_config', term: [{editor: "/etc/ssh/sshd_config", code: "# Change these settings to NO\nPasswordAuthentication no\nChallengeResponseAuthentication no\nUsePAM no\n\n# Optional but good: Only allow specific users\nAllowUsers ajsacay dev_user\n\n# Disable root login over SSH\nPermitRootLogin no"}, {raw: '<span class="out" style="color:#E8A07A">Critical Security Settings</span><br><span class="out">PasswordAuthentication no: Stops password logins.</span><br><span class="out">PermitRootLogin no: Stops direct root login. You must log in as a user and sudo.</span><br><span class="out">AllowUsers: Whitelist. Only these users can even attempt to connect.</span>'}], explain: '<strong>Explanation:</strong> <strong>WARNING:</strong> Do not close your current SSH session until you have tested the key login in a second window. If you disable passwords and your key does not work, you will be permanently locked out of the server.' },
  
  { type: 'lesson', category: 'SSH Keys', title: 'SSH Keys: Restart & Verify', subtitle: 'systemctl restart sshd', desc: 'Restart the SSH daemon to apply the new security settings. Verify that password login is rejected.', syntax: 'sudo systemctl restart ssh\nssh ajsacay@192.168.1.20', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl restart ssh</span><br><br><span class="out" style="color:#E8A07A">From a test machine without the key:</span><br><span class="prompt"><span class="user">dev_user@kali</span>:<span class="path">~</span>$</span> <span class="cmd">ssh ajsacay@192.168.1.20</span><br><span class="out">ajsacay@192.168.1.20: Permission denied (publickey).</span><br><span class="err">Connection closed by 192.168.1.20 port 22</span><br><br><span class="out" style="color:#E8A07A">From your machine with the key:</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">ssh ajsacay@192.168.1.20</span><br><span class="out">Welcome to Ubuntu 24.04 LTS</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span>'}], explain: '<strong>Explanation:</strong> The error "Permission denied (publickey)" means the server only accepts keys, not passwords. The attacker\'s script cannot guess a key. Your server is now secured against the most common internet threat.' },
  
  { type: 'lesson', category: 'Lynis', title: 'Lynis: Introduction', subtitle: 'Security Auditing', desc: 'Lynis is an open-source security auditing tool. It scans the system for configuration issues, weak permissions, and missing patches.', syntax: 'sudo apt install lynis', term: [{raw: '<span class="out" style="color:#E8A07A">Why Lynis?</span><br><br><span class="out">1. Compliance: It maps findings to CIS benchmarks.</span><br><span class="out">2. Readable: Color-coded output and a hardening index score.</span><br><span class="out">3. Non-destructive: It only reads and tests; it does not change the system.</span><br><br><span class="out" style="color:#E8A07A">How it works</span><br><span class="out">It runs hundreds of test modules checking kernel params, services, file permissions, and SSH config.</span>'}], explain: '<strong>Explanation:</strong> Manually verifying 200 CIS controls takes hours. Lynis does it in 2 minutes. It does not fix issues; it reports them so the sysadmin can decide what to change.' },
  
  { type: 'lesson', category: 'Lynis', title: 'Lynis: Install & Run', subtitle: 'audit system', desc: 'Install Lynis and execute a full system audit. The output will show warnings (critical) and suggestions (recommended improvements).', syntax: 'sudo apt install lynis\nsudo lynis audit system', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo lynis audit system</span><br><br><span class="out">[+] Initializing program</span><br><span class="out">------------------------------------</span><br><span class="out">  - Detecting OS...           [ DONE ]</span><br><span class="out">  - Checking profiles...      [ DONE ]</span><br><span class="out">  Program version:            3.0.8</span><br><span class="out">  Operating system:          Linux</span><br><span class="out">  Operating system name:    Ubuntu Linux</span><br><span class="out">  Kernel version:           6.8.0</span><br><span class="out">  Hardware platform:         x86_64</span>'}], explain: '<strong>Explanation:</strong> The audit takes 1-2 minutes. It scrolls rapidly through checks. The most important output is at the very end, summarizing warnings and suggestions. It also generates a log file in <code>/var/log/lynis.log</code>.' },
  
  { type: 'lesson', category: 'Lynis', title: 'Lynis: Output Analysis', subtitle: 'Warnings & Suggestions', desc: 'Lynis outputs W (Warnings) and S (Suggestions). Fixing warnings increases your hardening index.', syntax: 'W: [Critical] Ensure permissions on /etc/passwd are 644\nS: [Recommended] Disable USB storage', term: [{raw: '<span class="out" style="color:#E8A07A">Example Lynis Findings</span><br><br><span class="out">W: [AUTH-9286] Two or more administrators found in group "sudo" (Minimize admin count)</span><br><span class="out">S: [SSH-7408] Consider disabling root login (PermitRootLogin no)</span><br><span class="out">S: [FIRE-4590] Check iptables rules for unused ports</span><br><br><span class="out" style="color:#E8A07A">Hardening Index</span><br><span class="out">Lynis outputs a score out of 100.</span><br><span class="out">Initial Score: 65</span><br><span class="out">Target Score: 85+</span>'}], explain: '<strong>Explanation:</strong> A warning (W) means a critical security issue. A suggestion (S) is a best practice. Fixing these issues is the hardening process. Each fix raises the hardening index score.' },
  
  { type: 'lesson', category: 'Lynis', title: 'Lynis: Hardening Index', subtitle: 'Compliance Score', desc: 'The hardening index is a score out of 100 representing the security posture. A score of 85+ is considered enterprise-ready.', syntax: 'sudo lynis audit system --quiet', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo lynis audit system | grep Hardening</span><br><span class="out">Hardening index : 72 [##########..........]</span><br><span class="out">Hardening strength : 72%</span><br><br><span class="out" style="color:#E8A07A">Score Interpretation</span><br><span class="out">0-50: Weak. Vulnerable to common attacks.</span><br><span class="out">50-70: Fair. Basic security in place.</span><br><span class="out">70-85: Good. Meets most compliance standards.</span><br><span class="out">85+: Strong. Enterprise-grade hardening.</span>'}], explain: '<strong>Explanation:</strong> The <code>--quiet</code> flag suppresses the verbose output and just shows the summary. Management and auditors love this score. It provides a quantifiable metric to prove the server has been hardened.' },
  
  { type: 'lesson', category: 'Compliance Report', title: 'HTML Compliance Report', subtitle: 'Concept', desc: 'Auditors require reports. We will write a Bash script that runs Lynis, captures the score, and wraps it in an HTML file for easy viewing.', syntax: '#!/bin/bash\n# Generate compliance_report.html', term: [{raw: '<span class="out" style="color:#E8A07A">Why an HTML Report?</span><br><br><span class="out">1. Readability: HTML is easier to read than raw terminal output.</span><br><span class="out">2. Archive: The file can be saved to a web server or emailed.</span><br><span class="out">3. Compliance Evidence: Auditors need a snapshot of the system state on a specific date.</span><br><br><span class="out" style="color:#E8A07A">Script Logic</span><br><span class="out">1. Run Lynis, grep the Hardening Index.</span><br><span class="out">2. Run UFW status, Fail2ban status.</span><br><span class="out">3. Wrap outputs in HTML tags.</span><br><span class="out">4. Save as compliance_2024-10-24.html.</span>'}], explain: '<strong>Explanation:</strong> Automation is key. A sysadmin should not manually copy-paste terminal output into Word documents. A script ensures the report is standardized and reproducible every time it is run.' },
  
  { type: 'lesson', category: 'Compliance Report', title: 'HTML Compliance Report', subtitle: 'The Script', desc: 'The Bash script collects security states and formats them into a clean HTML file. It uses standard command substitution <code>$()</code>.', syntax: '#!/bin/bash\nREPORT="compliance_$(date +%F).html"', term: [{editor: "generate_report.sh", code: "#!/bin/bash\nDATE=$(date +%F)\nFILE=\"compliance_$DATE.html\"\n\n# Capture System Status\nLYNIS=$(sudo lynis audit system --quiet | grep -E 'Hardening|Warnings|Suggestions')\nUFW=$(sudo ufw status)\nFAIL2BAN=$(sudo fail2ban-client status)\n\n# Generate HTML\necho \"<html><head><title>Security Report $DATE</title></head><body>\" > $FILE\necho \"<h1>DOrSU IT Compliance Report - $DATE</h1>\" >> $FILE\necho \"<h2>System Auditing (Lynis)</h2><pre>$LYNIS</pre>\" >> $FILE\necho \"<h2>Firewall Status (UFW)</h2><pre>$UFW</pre>\" >> $FILE\necho \"<h2>Intrusion Prevention (Fail2ban)</h2><pre>$FAIL2BAN</pre>\" >> $FILE\necho \"</body></html>\" >> $FILE\n\necho \"Report generated: $FILE\""}, {raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">chmod +x generate_report.sh && ./generate_report.sh</span>'}], explain: '<strong>Explanation:</strong> This script uses basic HTML tags (<code>&lt;h1&gt;</code>, <code>&lt;pre&gt;</code>) to structure the data. The <code>&lt;pre&gt;</code> tag is crucial for terminal output because it preserves spaces and line breaks, making it readable.' },
  
  { type: 'lesson', category: 'Compliance Report', title: 'HTML Report Output', subtitle: 'Verification', desc: 'Run the script and view the generated HTML file. It provides a single-page summary of the server\'s security posture.', syntax: './generate_report.sh\nls -l compliance_*.html', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">./generate_report.sh</span><br><span class="out">Report generated: compliance_2024-10-24.html</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">cat compliance_2024-10-24.html | grep -A2 "Lynis"</span><br><span class="out">&lt;h2&gt;System Auditing (Lynis)&lt;/h2&gt;</span><br><span class="out">  Hardening index : 85 [##################..]</span><br><span class="out">  Tests performed : 187</span><br><span class="out">  Warnings : 2</span>'}], explain: '<strong>Explanation:</strong> The generated file can be opened in a web browser or sent to the IT Manager. It proves that on 2024-10-24, the server had a hardening index of 85 and the firewall was active. This satisfies the NIST Audit and Accountability (AU) family.' },
  
  { type: 'lesson', category: 'Summary', title: 'Topic Summary', subtitle: 'Module 4 Complete', desc: 'You have secured the dual-OS lab. Firewalls block unauthorized traffic, Fail2ban stops brute-force, SSH keys replace passwords, and Lynis proves compliance.', syntax: 'sudo ufw enable\nsudo fail2ban-client status sshd\nsudo lynis audit system', term: [{raw: '<span class="out" style="color:#E8A07A">Module 4 Checklist:</span><br>[x] CIS Level 1 controls applied to Ubuntu<br>[x] UFW configured with Default Deny<br>[x] Windows Firewall rules created via PowerShell<br>[x] Fail2ban installed and protecting SSH<br>[x] SSH Key Authentication enabled, passwords disabled<br>[x] Lynis audit run, score improved<br>[x] HTML Compliance Report generated via Bash script<br><br><span class="out">Next: We will move to Cloud Computing and Microsoft Azure.</span>'}], explain: '<strong>Explanation:</strong> Security is not a one-time setup. It is a continuous loop of auditing, hardening, and reporting. By automating the report generation, you have created a repeatable compliance process. This concludes Module 4.' },

  // --- 4. CLOSING SLIDE ---
  {
    type: 'closing',
    header: 'MODULE 04 · TOPIC 12',
    tag: 'End of Topic 12',
    title: 'Security is a <em>Process</em>, not a Product.',
    quote: 'The only truly secure system is one that is powered off, cast in a block of concrete, and submerged in a sea. Everything else is a compromise.',
    leftCardNum: '§ frameworks',
    leftCardTitle: 'CIS & NIST',
    leftCardDesc: 'Applying CIS Level 1 baselines reduces the attack surface while aligning with NIST compliance requirements.',
    middleCardNum: '§ firewalls',
    middleCardTitle: 'UFW & Windows',
    middleCardDesc: 'Configuring UFW and Windows Firewall ensures only explicitly allowed traffic can reach the server.',
    rightCardNum: '§ compliance',
    rightCardTitle: 'Lynis & Auditing',
    rightCardDesc: 'Fail2ban and SSH Keys stop brute-force attacks, while Lynis provides the hardening index needed to prove compliance.'
  }
];
