const slideConfigs = [
  // --- 1. COVER SLIDE ---
  {
    type: 'cover',
    moduleTitle: 'MODULE 03 · TOPIC 09',
    topicNum: '09',
    topicTag: 'T9',
    title: 'Application Mgmt<br>& Server <em>Deployment</em>',
    subtitle: 'Bridging traditional web hosting and modern containerization: Deploying IIS, Nginx, and multi-container Docker Compose stacks with automated scripts.',
    graphicText: 'Host <em>Websites</em><br>Deploy <em>Containers</em><br>Automate Everything.',
    miniObjectives: [
      'IIS on Windows Server',
      'Nginx on Ubuntu',
      'Docker CE & Compose',
      'Automated deploy.sh'
    ]
  },

  // --- 2. OBJECTIVES SLIDE ---
  {
    type: 'objectives',
    header: 'MODULE 03 · TOPIC 09',
    kicker: 'ITP 141 · M3 · T9',
    desc: 'This topic transitions from OS management to application delivery. You will learn to host websites natively and via Docker containers.',
    lede: 'A modern sysadmin must know both traditional web servers (IIS/Apache) and containerized deployments (Docker Compose) to support diverse application stacks.',
    list: [
      'Install and configure IIS on Windows Server 2022.',
      'Configure IIS Virtual Directories and App Pools.',
      'Install and configure Nginx on Ubuntu Server.',
      'Configure Nginx as a Reverse Proxy.',
      'Install Docker Community Edition (CE) on Ubuntu.',
      'Understand Docker images, layers, and Dockerfiles.',
      'Write a docker-compose.yml deploying Nginx, PHP-FPM, and MariaDB.',
      'Automate deployment with a deploy.sh script using strict error handling.'
    ]
  },

  // --- 3. LESSON SLIDES ---
  { type: 'lesson', category: 'Overview', title: 'App Deployment', subtitle: 'Traditional vs Modern', desc: 'Traditionally, web servers (IIS, Apache) are installed directly onto the OS. Modern deployment uses containers (Docker) to package the app and its dependencies together, ensuring consistency across environments.', syntax: 'Traditional: OS -> Web Server -> App\nContainer:   OS -> Docker Engine -> Container (Web Server + App)', term: [{raw: '<span class="out" style="color:#E8A07A">Deployment Models</span><br><br><span class="out">1. Traditional (IIS/Nginx direct)</span><br><span class="out">   - Pros: Simple, low overhead</span><br><span class="out">   - Cons: Dependency hell, hard to scale</span><br><br><span class="out">2. Containerized (Docker Compose)</span><br><span class="out">   - Pros: Isolated, portable, reproducible</span><br><span class="out">   - Cons: Slight performance overhead</span>'}], explain: '<strong>Explanation:</strong> In this module, we learn both. We install IIS on Windows and Nginx on Ubuntu to understand the traditional model. Then we use Docker Compose on Ubuntu to deploy a full LEMP stack (Linux, Nginx, MariaDB, PHP) in containers.' },
    
  { type: 'lesson', category: 'Windows IIS', title: 'Windows: IIS Install', subtitle: 'PowerShell', desc: 'Internet Information Services (IIS) is Windows\' native web server. It can be installed via Server Manager GUI or PowerShell. We use PowerShell for automation.', syntax: 'Install-WindowsFeature -Name Web-Server -IncludeManagementTools', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Install-WindowsFeature -Name Web-Server -IncludeManagementTools</span><br><br><span class="out">Success Restart Needed Exit Code      Feature Result</span><br><span class="out">------- -------------- ---------      --------------</span><br><span class="out">True    No             Success        {Web-Server, Web-WebServer...</span><br><br><span class="cmd">> Import-Module WebAdministration</span><br><span class="out">(Loads the IIS PowerShell cmdlets)</span>'}], explain: '<strong>Explanation:</strong> This command installs the IIS web server role and the management tools (like IIS Manager). Once installed, navigating to <code>http://localhost</code> on the server will show the default IIS welcome page.' },
  
  { type: 'lesson', category: 'Windows IIS', title: 'Windows: IIS App Pools', subtitle: 'Isolation', desc: 'IIS uses Application Pools (App Pools) to isolate web applications. If one app crashes, its app pool recycles without affecting other sites on the server.', syntax: 'Get-IISAppPool\nNew-AppPool -Name "TestSitePool"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> New-WebAppPool -Name "TestSitePool"</span><br><span class="out">Name                 State       Applications</span><br><span class="out">----                 -----       ------------</span><br><span class="out">TestSitePool         Started</span><br><br><span class="out" style="color:#E8A07A">Concept</span><br><span class="out">App Pool (Worker Process) -> executes code (PHP/ASP.NET)</span><br><span class="out">Website -> Listens on a port (80/8080) and routes to App Pool</span>'}], explain: '<strong>Explanation:</strong> The App Pool defines the identity (user) and memory limits for the web application. Creating a dedicated App Pool for each site is a standard security and stability practice.' },
  
  { type: 'lesson', category: 'Windows IIS', title: 'Windows: IIS Virtual Dirs', subtitle: 'Path Mapping', desc: 'A Virtual Directory maps a URL path to a physical folder on the server or a network share. This allows you to serve files from outside the default wwwroot folder.', syntax: 'New-WebVirtualDirectory -Site "TestSite" -Name "Assets" -PhysicalPath "D:\\WebsiteAssets"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> New-WebVirtualDirectory -Site "TestSite" -Name "Assets" -PhysicalPath "D:\\WebsiteAssets"</span><br><span class="out">Name             : Assets</span><br><span class="out">PhysicalPath     : D:\\WebsiteAssets</span><br><br><span class="out" style="color:#E8A07A">URL Mapping</span><br><span class="out">http://localhost:8080/Assets/image.jpg</span><br><span class="out">-> Serves from D:\\WebsiteAssets\\image.jpg</span>'}], explain: '<strong>Explanation:</strong> Virtual Directories are useful for serving static content (like images or videos) from a separate, larger disk drive without moving the entire website. They can also point to UNC paths (\\servername\\share) for network storage.' },
  
  { type: 'lesson', category: 'Windows IIS', title: 'Windows: IIS Test Site', subtitle: 'Port 8080', desc: 'By default, IIS binds to port 80. To create a test site without conflicting with the default site, we will bind a new site to port 8080.', syntax: 'New-Website -Name "TestSite" -Port 8080 -PhysicalPath "C:\\inetpub\\testsite" -ApplicationPool "TestSitePool"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> mkdir C:\\inetpub\\testsite</span><br><span class="cmd">> echo "&lt;h1&gt;Hello from IIS 8080&lt;/h1&gt;" > C:\\inetpub\\testsite\\index.html</span><br><span class="cmd">> New-Website -Name "TestSite" -Port 8080 -PhysicalPath "C:\\inetpub\\testsite" -ApplicationPool "TestSitePool"</span><br><br><span class="cmd">> Invoke-WebRequest -Uri http://localhost:8080 -UseBasicParsing</span><br><span class="out">StatusCode : 200</span><br><span class="out">Content     : &lt;h1&gt;Hello from IIS 8080&lt;/h1&gt;</span>'}], explain: '<strong>Explanation:</strong> We create a directory, add a basic HTML file, and bind the site to port 8080. Using <code>Invoke-WebRequest</code> in PowerShell is a quick way to verify the server responds with a 200 OK status.' },
  
  { type: 'lesson', category: 'Windows IIS', title: 'Windows: IIS Firewall', subtitle: 'Open Port 8080', desc: 'Windows Firewall blocks incoming connections by default. To allow external users to access the test site on port 8080, we must open the port.', syntax: 'New-NetFirewallRule -DisplayName "HTTP 8080" -Direction Inbound -Protocol TCP -LocalPort 8080 -Action Allow', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> New-NetFirewallRule -DisplayName "HTTP 8080" -Direction Inbound -Protocol TCP -LocalPort 8080 -Action Allow</span><br><span class="out">Name : {a1b2c3...}</span><br><span class="out">DisplayName : HTTP 8080</span><br><span class="out">Enabled : True</span><br><span class="out">Direction : Inbound</span><br><span class="out">Action : Allow</span>'}], explain: '<strong>Explanation:</strong> Without this firewall rule, browsing to <code>http://192.168.1.10:8080</code> from another machine will time out. This command opens TCP port 8080 for inbound traffic.' },
  
  { type: 'lesson', category: 'Ubuntu Nginx', title: 'Apache vs Nginx', subtitle: 'Web Server Choice', desc: 'Apache is process-based (spawns a thread per request), while Nginx is event-driven (handles thousands of concurrent connections in a single thread). Nginx is preferred for high-traffic reverse proxying.', syntax: 'Apache: Process/Thread Model\nNginx: Event-Driven Model', term: [{raw: '<span class="out" style="color:#E8A07A">Comparison</span><br><br><span class="out">1. Apache: Uses .htaccess for directory-level config. Heavy memory usage per connection.</span><br><span class="out">2. Nginx: No .htaccess. Centralized config. Extremely lightweight. Excellent for serving static files and proxying to Node/Python apps.</span><br><br><span class="out" style="color:#E8A07A">In this course</span><br><span class="out">We use Nginx for its modern architecture and Docker compatibility.</span>'}], explain: '<strong>Explanation:</strong> While Apache dominated the 90s and 2000s, Nginx has become the standard for modern deployments due to its ability to handle C10k (10,000 concurrent connections) efficiently. It is the default in most Docker LEMP stacks.' },
  
  { type: 'lesson', category: 'Ubuntu Nginx', title: 'Ubuntu: Nginx Install', subtitle: 'apt install', desc: 'Nginx is a high-performance, open-source web server. It is known for its low memory footprint and ability to handle thousands of concurrent connections.', syntax: 'sudo apt install nginx -y\nsystemctl status nginx', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt install nginx -y</span><br><span class="out">Reading package lists... Done</span><br><span class="out">Setting up nginx (1.24.0-2ubuntu7) ...</span><br><span class="out">Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service.</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">systemctl status nginx</span><br><span class="out">● nginx.service - The nginx HTTP and reverse proxy web server</span><br><span class="out">     Active: active (running) since Wed 2024-10-24 10:00:00 PST</span>'}], explain: '<strong>Explanation:</strong> The <code>nginx</code> package installs and starts the service automatically. It creates a default website in <code>/var/www/html</code>. Navigating to the Ubuntu server\'s IP in a browser will show the "Welcome to nginx" page.' },
  
  { type: 'lesson', category: 'Ubuntu Nginx', title: 'Ubuntu: Nginx Config', subtitle: 'Server Blocks', desc: 'Nginx uses "Server Blocks" (similar to Apache Virtual Hosts) to host multiple websites on one server. The config files are stored in <code>/etc/nginx/sites-available/</code>.', syntax: 'sudo nano /etc/nginx/sites-available/testsite', term: [{editor: "/etc/nginx/sites-available/testsite", code: "server {\n    listen 80;\n    server_name testsite.local;\n    root /var/www/testsite;\n    index index.html;\n\n    location / {\n        try_files $uri $uri/ =404;\n    }\n}"}, {raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ln -s /etc/nginx/sites-available/testsite /etc/nginx/sites-enabled/</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo nginx -t</span><br><span class="out">nginx: configuration file /etc/nginx/nginx.conf test is successful</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl reload nginx</span>'}], explain: '<strong>Explanation:</strong> We define a new server block listening on port 80. We create a symlink in <code>sites-enabled</code> to activate it. <code>nginx -t</code> tests the configuration for syntax errors before we gracefully reload the service.' },
  
  { type: 'lesson', category: 'Ubuntu Nginx', title: 'Ubuntu: Nginx Test', subtitle: 'curl localhost', desc: 'Use <code>curl</code> to test the Nginx configuration directly from the command line without needing a web browser.', syntax: 'curl -I http://localhost\n# or\nsudo tail -f /var/log/nginx/access.log', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">curl -I http://localhost</span><br><span class="out">HTTP/1.1 200 OK</span><br><span class="out">Server: nginx/1.24.0 (Ubuntu)</span><br><span class="out">Date: Wed, 24 Oct 2024 10:15:00 GMT</span><br><span class="out">Content-Type: text/html</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo tail -f /var/log/nginx/access.log</span><br><span class="out">192.168.1.50 - - "HEAD / HTTP/1.1" 200 0 "-" "curl/8.5.0"</span>'}], explain: '<strong>Explanation:</strong> The <code>-I</code> flag fetches only the HTTP headers. A "200 OK" response confirms the server is working. Checking the <code>access.log</code> verifies that Nginx is recording the request, which proves logging is functioning.' },
  
  { type: 'lesson', category: 'Ubuntu Nginx', title: 'Nginx Reverse Proxy', subtitle: 'proxy_pass', desc: 'A reverse proxy sits in front of a web application (like Node.js or Python) and forwards client requests to it. Nginx handles SSL and static files, while the backend handles logic.', syntax: 'location /api {\n    proxy_pass http://127.0.0.1:3000;\n}', term: [{editor: "/etc/nginx/sites-available/api", code: "server {\n    listen 80;\n    server_name api.dorsu.lab;\n\n    location / {\n        proxy_pass http://127.0.0.1:3000;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n    }\n}"}, {raw: '<span class="out" style="color:#E8A07A">Why use a Reverse Proxy?</span><br><span class="out">1. SSL Termination: Nginx handles HTTPS, backend handles HTTP.</span><br><span class="out">2. Load Balancing: Distribute traffic across multiple Node/Python instances.</span><br><span class="out">3. Security: Hides the backend server IP and ports from the internet.</span>'}], explain: '<strong>Explanation:</strong> The <code>proxy_pass</code> directive forwards any request starting with <code>/</code> to the Node.js app running on port 3000. The headers ensure the backend knows the original client\'s IP address, not the proxy\'s IP.' },
  
  { type: 'lesson', category: 'Docker', title: 'Docker CE: Introduction', subtitle: 'Containerization', desc: 'Docker Community Edition (CE) is the standard platform for building, running, and managing containers. A container packages the application code, libraries, and tools into one immutable artifact.', syntax: 'Image -> Docker Engine -> Running Container', term: [{raw: '<span class="out" style="color:#E8A07A">Docker Architecture</span><br><br><span class="out">1. Docker Engine: The background service managing containers</span><br><span class="out">2. Image: A read-only template (e.g., nginx:latest)</span><br><span class="out">3. Container: A running instance of an image</span><br><span class="out">4. Volume: Persistent storage independent of the container</span>'}], explain: '<strong>Explanation:</strong> Unlike Nginx installed via <code>apt</code> (which modifies the host OS), a Docker container is isolated. If you delete the container, the host OS remains perfectly clean. This solves dependency conflicts.' },
  
  { type: 'lesson', category: 'Docker', title: 'Docker CE: Installation', subtitle: 'Ubuntu Setup', desc: 'Install Docker CE using the official convenience script, then add your user to the docker group so you don\'t need <code>sudo</code> for every command.', syntax: 'curl -fsSL https://get.docker.com | sh\nsudo usermod -aG docker $USER', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">curl -fsSL https://get.docker.com | sh</span><br><span class="out"># Executing docker install script</span><br><span class="out">+ sudo apt-get update</span><br><span class="out">+ sudo apt-get install docker-ce docker-ce-cli containerd.io</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo usermod -aG docker $USER</span><br><span class="out">(You must log out and log back in for this to take effect)</span>'}], explain: '<strong>Explanation:</strong> The script adds the Docker repository and installs the engine. Adding your user to the <code>docker</code> group is highly recommended; otherwise, you must prefix every docker command with <code>sudo</code>.' },
  
  { type: 'lesson', category: 'Docker', title: 'Docker Images & Layers', subtitle: 'Architecture', desc: 'A Docker image is a read-only template made of multiple layers. Each layer corresponds to an instruction in the Dockerfile. Containers add a writable layer on top.', syntax: 'docker pull nginx\nThe image is built in layers. Layers are cached for speed.', term: [{raw: '<span class="out" style="color:#E8A07A">Image Layers</span><br><br><span class="out">Layer 1: Ubuntu Base Image (read-only)</span><br><span class="out">Layer 2: apt install nginx (read-only)</span><br><span class="out">Layer 3: COPY index.html (read-only)</span><br><br><span class="out" style="color:#E8A07A">Container Layer</span><br><span class="out">Layer 4: Writable layer (created on `docker run`). Deleted when container is removed.</span><br><br><span class="out" style="color:#E8A07A">Why layers?</span><br><span class="out">Efficiency. If you change index.html, Docker only rebuilds Layer 3, reusing Layers 1 and 2 from cache.</span>'}], explain: '<strong>Explanation:</strong> This layering system is what makes Docker so fast. Pulling a new version of an app only downloads the layers that changed, not the entire OS image. This is crucial for CI/CD pipelines.' },
  
  { type: 'lesson', category: 'Docker', title: 'Dockerfile Basics', subtitle: 'Building Images', desc: 'A Dockerfile is a text file containing instructions to build a custom Docker image. It defines the base OS, packages, and the command to run when the container starts.', syntax: 'docker build -t my-nginx .', term: [{editor: "Dockerfile", code: "# Base Image\nFROM ubuntu:24.04\n\n# Install packages\nRUN apt update && apt install -y nginx\n\n# Copy local files\nCOPY index.html /var/www/html/\n\n# Expose port\nEXPOSE 80\n\n# Start command\nCMD [\"nginx\", \"-g\", \"daemon off;\"]"}, {raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/myapp</span>$</span> <span class="cmd">docker build -t my-nginx:latest .</span><br><span class="out">Step 1/4 : FROM ubuntu:24.04</span><br><span class="out">Step 2/4 : RUN apt update && apt install -y nginx</span><br><span class="out">Step 3/4 : COPY index.html /var/www/html/</span><br><span class="out">Successfully tagged my-nginx:latest</span>'}], explain: '<strong>Explanation:</strong> The <code>Dockerfile</code> is the blueprint. <code>FROM</code> sets the base image. <code>RUN</code> executes shell commands during the build. <code>COPY</code> moves files from your host into the image. <code>CMD</code> is the process that runs when the container starts.' },
  
  { type: 'lesson', category: 'Docker', title: 'Docker: Run Command', subtitle: 'First Container', desc: 'The <code>docker run</code> command downloads an image (if not present) and starts a container. Let\'s run a simple Nginx web server.', syntax: 'docker run -d -p 8081:80 --name my-web nginx:latest', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">docker run -d -p 8081:80 --name my-web nginx:latest</span><br><span class="out">Unable to find image \'nginx:latest\' locally</span><br><span class="out">latest: Pulling from library/nginx</span><br><span class="out">Status: Downloaded newer image for nginx:latest</span><br><span class="out">a1b2c3d4e5f6...7a8b9c0d1e2f</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">curl -I http://localhost:8081</span><br><span class="out">HTTP/1.1 200 OK</span><br><span class="out">Server: nginx/1.27.2</span>'}], explain: '<strong>Explanation:</strong> <code>-d</code> runs it in the background. <code>-p 8081:80</code> maps host port 8081 to the container\'s port 80. <code>--name</code> gives it a friendly name. The host OS only sees port 8081; Nginx inside the container listens on 80.' },
  
  { type: 'lesson', category: 'Docker', title: 'Docker: Port Mapping', subtitle: '-p host:container', desc: 'Understanding port mapping is critical. The left side is the host, the right side is the container. They do not have to match.', syntax: 'Host Port -> Container Port\n8081      -> 80', term: [{raw: '<span class="out" style="color:#E8A07A">Port Mapping Logic</span><br><br><span class="out">Host Machine (Ubuntu Server)</span><br><span class="out">  |-- Port 8081 (Open on host)</span><br><span class="out">        |</span><br><span class="out">        +--> [ Docker Container: my-web ]</span><br><span class="out">               |-- Port 80 (Nginx listening here)</span><br><br><span class="out" style="color:#E8A07A">Why?</span><br><span class="out">- Host port 80 is already used by native Nginx.</span><br><span class="out">- We map to 8081 to avoid a conflict.</span><br><span class="out">- Inside the container, Nginx still defaults to 80.</span>'}], explain: '<strong>Explanation:</strong> If you try to map to a host port that is already in use (like 80, which we used earlier), Docker will throw an error. Mapping to a high port (8081, 8082) is the standard workaround for running multiple web apps on one server.' },
  
  { type: 'lesson', category: 'Docker', title: 'Docker: Volumes', subtitle: 'Persistent Data', desc: 'Containers are ephemeral (temporary). If a container is deleted, all data inside it is lost. Volumes map host directories into the container to persist data.', syntax: 'docker run -d -p 8082:80 -v /var/www/html:/usr/share/nginx/html nginx', term: [{raw: '<span class="out" style="color:#E8A07A">Without Volumes (Ephemeral)</span><br><span class="out">- Delete container = Website HTML is gone.</span><br><br><span class="out" style="color:#E8A07A">With Volumes (Persistent)</span><br><span class="out">- Delete container = HTML is safe on host /var/www/html</span><br><br><span class="out" style="color:#E8A07A">Docker Compose Syntax</span><br><span class="out">volumes:</span><br><span class="out">  - ./website:/usr/share/nginx/html</span>'}], explain: '<strong>Explanation:</strong> The <code>-v</code> flag creates a bridge. The left side is the directory on the Ubuntu host. The right side is the path inside the container. Changes made on the host are instantly reflected in the container.' },
  
  { type: 'lesson', category: 'Docker', title: 'Docker: Networks', subtitle: 'Container Isolation', desc: 'By default, containers can talk to each other on a bridge network. You can create custom networks to isolate groups of containers (e.g., web tier vs db tier).', syntax: 'docker network create app_net\ndocker run --network app_net --name db mariadb', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">docker network create app_net</span><br><span class="out">a1b2c3... network created</span><br><br><span class="out" style="color:#E8A07A">Why Custom Networks?</span><br><span class="out">1. DNS Resolution: Containers can ping each other by name (e.g., db:3306).</span><br><span class="out">2. Isolation: Prevents the web container from accessing other databases on the host.</span>'}], explain: '<strong>Explanation:</strong> In a Docker Compose stack, a custom network is created automatically. This is how the Nginx container can proxy requests to the PHP-FPM container using the hostname <code>php:9000</code> without knowing its IP address.' },
  
  { type: 'lesson', category: 'Docker Compose', title: 'Docker Compose: Intro', subtitle: 'Multi-Container Apps', desc: 'Running single containers with <code>docker run</code> is tedious for complex apps. Docker Compose uses a single YAML file to define and run multi-container applications.', syntax: 'sudo apt install docker-compose-plugin\nnano docker-compose.yml', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt install docker-compose-plugin -y</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">mkdir lemp-stack && cd lemp-stack</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/lemp-stack</span>$</span> <span class="cmd">nano docker-compose.yml</span><br><span class="out">(Opens nano to define the application stack)</span>'}], explain: '<strong>Explanation:</strong> Compose allows you to define a complete stack (like Nginx + PHP + MariaDB) in one file. You can start the entire architecture with one command: <code>docker compose up -d</code>.' },
  
  { type: 'lesson', category: 'Docker Compose', title: 'Compose: Nginx Service', subtitle: 'The Web Server', desc: 'Define the Nginx container. It will serve the website and proxy PHP requests to the PHP-FPM container.', syntax: 'services:\n  nginx:\n    image: nginx:latest\n    ports:\n      - "8083:80"', term: [{editor: "docker-compose.yml", code: "services:\n  nginx:\n    image: nginx:latest\n    container_name: web_server\n    ports:\n      - \"8083:80\"\n    volumes:\n      - ./html:/usr/share/nginx/html\n      - ./nginx.conf:/etc/nginx/conf.d/default.conf\n    depends_on:\n      - php"}, {raw: '<span class="out" style="color:#E8A07A">Key concepts:</span><br><span class="out">1. ports: Maps host 8083 to container 80</span><br><span class="out">2. volumes: Mounts local code and custom config</span><br><span class="out">3. depends_on: Starts PHP before Nginx</span>'}], explain: '<strong>Explanation:</strong> We mount a custom <code>nginx.conf</code> to tell Nginx to pass <code>.php</code> files to the PHP container instead of trying to serve them as static text. The <code>depends_on</code> key ensures PHP-FPM is running before Nginx starts.' },
  
  { type: 'lesson', category: 'Docker Compose', title: 'Compose: PHP-FPM Service', subtitle: 'The Code Engine', desc: 'PHP-FPM (FastCGI Process Manager) is the service that actually executes the PHP code. Nginx just hands it the request.', syntax: '  php:\n    image: php:8.2-fpm\n    volumes:\n      - ./html:/var/www/html', term: [{editor: "docker-compose.yml", code: "  php:\n    image: php:8.2-fpm\n    container_name: php_engine\n    volumes:\n      - ./html:/var/www/html\n    environment:\n      - DB_HOST=mariadb_db\n      - DB_USER=root\n      - DB_PASS=secret"}, {raw: '<span class="out" style="color:#E8A07A">Key concepts:</span><br><span class="out">1. image: php:8.2-fpm (FastCGI version)</span><br><span class="out">2. volumes: Must share the SAME html folder as Nginx</span><br><span class="out">3. environment: Injects DB credentials securely</span>'}], explain: '<strong>Explanation:</strong> Both Nginx and PHP must have access to the website files. Therefore, we mount the same <code>./html</code> directory to both. The environment variables will be read by the PHP application to connect to the database.' },
  
  { type: 'lesson', category: 'Docker Compose', title: 'Compose: MariaDB Service', subtitle: 'The Database', desc: 'MariaDB is a popular open-source database. It needs persistent storage (a volume) so data survives container restarts.', syntax: '  mariadb:\n    image: mariadb:latest\n    environment:\n      - MYSQL_ROOT_PASSWORD=secret', term: [{editor: "docker-compose.yml", code: "  mariadb:\n    image: mariadb:latest\n    container_name: mariadb_db\n    environment:\n      - MARIADB_ROOT_PASSWORD=secret\n    volumes:\n      - db_data:/var/lib/mysql\n\nvolumes:\n  db_data:"}, {raw: '<span class="out" style="color:#E8A07A">Key concepts:</span><br><span class="out">1. environment: Sets the root password</span><br><span class="out">2. volumes: Maps to a named volume \'db_data\'</span><br><span class="out">3. Named volumes are managed by Docker Engine</span>'}], explain: '<strong>Explanation:</strong> We define <code>MARIADB_ROOT_PASSWORD</code> to initialize the database. We use a Docker-managed named volume (<code>db_data</code>) for the database files. If the container is deleted and recreated, Docker reattaches this volume, and the data remains intact.' },
  
  { type: 'lesson', category: 'Docker Compose', title: 'Compose: Env Variables', subtitle: '.env file', desc: 'Hardcoding passwords in <code>docker-compose.yml</code> is insecure if committed to Git. Use a <code>.env</code> file to inject secrets at runtime.', syntax: '# .env file\nDB_ROOT_PASSWORD=S3cr3t!', term: [{editor: ".env", code: "# Database Credentials\nDB_ROOT_PASSWORD=S3cr3t!\nDB_NAME=itp141_db\nDB_USER=app_user"}, {editor: "docker-compose.yml", code: "  mariadb:\n    image: mariadb:latest\n    environment:\n      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}\n      - MARIADB_DATABASE=${DB_NAME}\n      - MARIADB_USER=${DB_USER}"}], explain: '<strong>Explanation:</strong> Docker Compose automatically reads a <code>.env</code> file in the same directory. You reference variables using <code>${VARIABLE_NAME}</code>. This keeps your YAML file clean and your secrets out of version control.' },
  
  { type: 'lesson', category: 'Docker Compose', title: 'Compose: Full YAML Review', subtitle: 'The Complete Stack', desc: 'Review the complete <code>docker-compose.yml</code> file defining the Nginx, PHP-FPM, and MariaDB stack.', syntax: '# The 3-container LEMP Stack', term: [{editor: "docker-compose.yml", code: "services:\n  nginx:\n    image: nginx:latest\n    ports:\n      - \"8083:80\"\n    volumes:\n      - ./html:/usr/share/nginx/html\n      - ./nginx.conf:/etc/nginx/conf.d/default.conf\n    depends_on:\n      - php\n\n  php:\n    image: php:8.2-fpm\n    volumes:\n      - ./html:/var/www/html\n    environment:\n      - DB_HOST=mariadb\n\n  mariadb:\n    image: mariadb:latest\n    environment:\n      - MARIADB_ROOT_PASSWORD=secret\n    volumes:\n      - db_data:/var/lib/mysql\n\nvolumes:\n  db_data:"}], explain: '<strong>Explanation:</strong> This single file replaces the need to manually install Nginx, configure PHP-FPM, and install MariaDB on the host OS. The whole environment is reproducible and can be version-controlled with the application code.' },
  
  { type: 'lesson', category: 'Docker Compose', title: 'Compose: Up & Down', subtitle: 'Lifecycle', desc: 'Start the entire stack in the background (detached mode) with one command. Stop it without deleting data with another.', syntax: 'docker compose up -d\ndocker compose down', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/lemp-stack</span>$</span> <span class="cmd">docker compose up -d</span><br><span class="out">[+] Running 4/4</span><br><span class="out"> ✔ Network lemp-stack_default    Created</span><br><span class="out"> ✔ Container mariadb_db           Started</span><br><span class="out"> ✔ Container php_engine           Started</span><br><span class="out"> ✔ Container web_server           Started</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/lemp-stack</span>$</span> <span class="cmd">docker compose down</span><br><span class="out">[+] Running 4/4</span><br><span class="out"> ✔ Container web_server           Removed</span><br><span class="out"> ✔ Container php_engine           Removed</span><br><span class="out"> ✔ Container mariadb_db           Removed</span><br><span class="out"> ✔ Network lemp-stack_default    Removed</span>'}], explain: '<strong>Explanation:</strong> <code>up -d</code> builds, creates, and starts all containers in the background. <code>down</code> stops and removes the containers and networks, but leaves the <code>db_data</code> volume intact so your database data survives.' },
  
  { type: 'lesson', category: 'Docker Compose', title: 'Compose: Rebuilding', subtitle: 'Updating Code', desc: 'If you change your Dockerfile or application code, you must force Compose to rebuild the images before starting the stack.', syntax: 'docker compose up -d --build', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/lemp-stack</span>$</span> <span class="cmd">docker compose up -d --build</span><br><span class="out">Building php</span><br><span class="out">Step 1/5 : FROM php:8.2-fpm</span><br><span class="out">Step 2/5 : RUN docker-php-ext-install pdo_mysql</span><br><span class="out">[+] Running 3/3</span><br><span class="out"> ✔ Container php_engine           Started</span>'}], explain: '<strong>Explanation:</strong> By default, <code>docker compose up</code> uses existing images. Adding <code>--build</code> tells Compose to look for Dockerfiles in the build context and rebuild the images if the files have changed, then restart the containers with the new code.' },
  
  { type: 'lesson', category: 'Docker Compose', title: 'Compose: Checking Status', subtitle: 'docker compose ps', desc: 'Verify that all containers in the stack are running and healthy using the <code>ps</code> command.', syntax: 'docker compose ps', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/lemp-stack</span>$</span> <span class="cmd">docker compose ps</span><br><span class="out">NAME          IMAGE           STATUS                      PORTS</span><br><span class="out">web_server    nginx:latest    Up 2 minutes                0.0.0.0:8083->80/tcp</span><br><span class="out">php_engine    php:8.2-fpm    Up 2 minutes                9000/tcp</span><br><span class="out">mariadb_db    mariadb:latest  Up 2 minutes (healthy)      3306/tcp</span>'}], explain: '<strong>Explanation:</strong> The <code>ps</code> command shows the container names, images, and status. If a container shows "Exited", you need to check the logs to see why it crashed. The "healthy" status for MariaDB means the built-in healthcheck passed.' },
  
  { type: 'lesson', category: 'Docker Compose', title: 'Compose: Viewing Logs', subtitle: 'docker compose logs', desc: 'When a container fails, you must read its logs. You can tail logs for a specific service or the whole stack.', syntax: 'docker compose logs -f\ndocker compose logs nginx\n# or specific container\ndocker logs web_server', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/lemp-stack</span>$</span> <span class="cmd">docker compose logs nginx</span><br><span class="out">web_server | 192.168.1.50 - - [24/Oct/2024:10:20:01 +0000] "GET / HTTP/1.1" 200</span><br><span class="out">web_server | 192.168.1.50 - - [24/Oct/2024:10:20:05 +0000] "GET /info.php HTTP/1.1" 200</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/lemp-stack</span>$</span> <span class="cmd">docker compose logs -f php</span><br><span class="out">php_engine | [24-Oct-2024 10:20:05] NOTICE: fpm is running, pid 1</span><br><span class="out">php_engine | [24-Oct-2024 10:20:05] NOTICE: ready to handle connections</span>'}], explain: '<strong>Explanation:</strong> The <code>-f</code> flag follows the logs live. This is invaluable for debugging. If Nginx returns a 502 Bad Gateway, checking the PHP logs will usually reveal that PHP-FPM failed to start due to a syntax error in the code.' },
  
  { type: 'lesson', category: 'Automation', title: 'Automation: deploy.sh', subtitle: 'Why Script It?', desc: 'Manually running <code>docker compose up</code> is fine for testing, but in production, deployments must be automated, repeatable, and include safety checks.', syntax: '#!/bin/bash\nset -e\ntrap cleanup EXIT', term: [{raw: '<span class="out" style="color:#E8A07A">Why use a deploy script?</span><br><br><span class="out">1. Reproducibility: Same result every time.</span><br><span class="out">2. Error Handling: Stop immediately if something fails.</span><br><span class="out">3. Cleanup: Automatically clean up partial deployments on failure.</span><br><span class="out">4. Health Checks: Verify the app is actually responding before declaring success.</span>'}], explain: '<strong>Explanation:</strong> A good deployment script does not just run commands; it anticipates failure. We will use Bash features like <code>set -e</code> and <code>trap</code> to make our Docker Compose deployment robust and safe.' },
  
  { type: 'lesson', category: 'Automation', title: 'Automation: set -e', subtitle: 'Exit on Error', desc: 'By adding <code>set -e</code> at the top of your script, Bash will immediately abort if any command returns a non-zero exit status (failure).', syntax: '#!/bin/bash\nset -e\necho "Pulling images..."\ndocker compose pull\necho "Starting stack..."', term: [{editor: "deploy.sh", code: "#!/bin/bash\nset -e\necho \"Starting deployment...\"\ndocker compose pull\necho \"Images pulled successfully.\"\ndocker compose up -d\necho \"Stack started.\""}, {raw: '<span class="out" style="color:#E8A07A">Behavior</span><br><span class="out">If \'docker compose pull\' fails (e.g., no internet), the script stops instantly.</span><br><span class="out">It will NOT proceed to \'docker compose up -d\', preventing a broken deployment.</span>'}], explain: '<strong>Explanation:</strong> Without <code>set -e</code>, Bash will happily continue running commands even if previous ones failed. This leads to half-deployed applications and confusing errors. <code>set -e</code> ensures fail-fast behavior.' },
  
  { type: 'lesson', category: 'Automation', title: 'Automation: trap', subtitle: 'Cleanup on Exit', desc: 'The <code>trap</code> command catches signals (like Ctrl+C or errors) and runs a cleanup function before the script exits. This prevents orphaned containers or locked files.', syntax: 'trap cleanup EXIT\n\ncleanup() {\n  echo "Cleaning up..."\n  docker compose down\n}', term: [{editor: "deploy.sh", code: "#!/bin/bash\nset -e\n\ntrap cleanup EXIT\n\ncleanup() {\n  echo \"Script exiting. Cleaning up...\"\n  # Do not stop running containers on success, only on failure\n  if [ $? -ne 0 ]; then\n    docker compose down\n  fi\n}\n\necho \"Starting deployment...\""}, {raw: '<span class="out" style="color:#E8A07A">How it works</span><br><span class="out">1. Script starts.</span><br><span class="out">2. If a command fails (set -e), script prepares to exit.</span><br><span class="out">3. trap catches the EXIT signal.</span><br><span class="out">4. cleanup() function runs, tearing down partial stack.</span>'}], explain: '<strong>Explanation:</strong> The <code>EXIT</code> trap fires whenever the script terminates, whether successfully or due to <code>set -e</code>. We check <code>$?</code> (the exit status of the last command). If it is not 0, it means an error occurred, so we safely tear down the stack to avoid leaving broken containers running.' },
  
  { type: 'lesson', category: 'Automation', title: 'Automation: Strict Mode', subtitle: 'set -euo pipefail', desc: 'For enterprise-grade scripts, use <code>set -euo pipefail</code>. This catches undefined variables and failures inside pipes, which <code>set -e</code> misses.', syntax: 'set -euo pipefail', term: [{editor: "deploy.sh", code: "#!/bin/bash\nset -euo pipefail\n\n# -e: Exit on error\n# -u: Treat unset variables as an error\n# -o pipefail: Return value of a pipeline is the status of the last command to exit with non-zero status\n\necho \"Deploying ${APP_NAME}...\""}, {raw: '<span class="out" style="color:#E8A07A">Why Pipefail?</span><br><span class="out">If you run: false | true</span><br><span class="out">- With set -e: Script continues (because \'true\' succeeded).</span><br><span class="out">- With pipefail: Script stops (because \'false\' failed in the pipe).</span><br><br><span class="out" style="color:#E8A07A">Why -u?</span><br><span class="out">Prevents typos like ${APP_NAM} from deploying empty strings.</span>'}], explain: '<strong>Explanation:</strong> A pipeline (<code>cmd1 | cmd2</code>) returns the exit code of the last command (<code>cmd2</code>). If <code>cmd1</code> fails but <code>cmd2</code> succeeds, <code>set -e</code> won\'t catch it. <code>pipefail</code> fixes this, making scripts much safer for CI/CD pipelines.' },
  
  { type: 'lesson', category: 'Automation', title: 'Automation: Health Check', subtitle: 'curl verification', desc: 'After starting the containers, the script should verify the web server is actually responding before reporting success. We use <code>curl</code> for this.', syntax: 'sleep 5\ncurl -f http://localhost:8083 || exit 1\necho "Deployment Successful!"', term: [{editor: "deploy.sh", code: "#!/bin/bash\nset -euo pipefail\ntrap cleanup EXIT\n\n# (Cleanup function defined here)\n\necho \"Pulling and starting containers...\"\ndocker compose pull\ndocker compose up -d\n\necho \"Waiting for containers to initialize...\"\nsleep 5\n\necho \"Performing health check...\"\ncurl -f http://localhost:8083 || exit 1\n\necho \"Deployment successful!\"\nexit 0"}, {raw: '<span class="out" style="color:#E8A07A">Health Check Logic</span><br><span class="out">1. sleep 5: Give Nginx/PHP time to start.</span><br><span class="out">2. curl -f: Returns 0 if HTTP 200, 1 if 404/500.</span><br><span class="out">3. || exit 1: If curl fails, force exit 1 (error).</span><br><span class="out">4. trap catches the error, runs cleanup (docker compose down).</span>'}], explain: '<strong>Explanation:</strong> The <code>-f</code> flag in curl makes it return a non-zero exit code if the HTTP response is an error (like 404 or 500). If curl fails, <code>|| exit 1</code> triggers an error, which <code>set -e</code> catches, which triggers the <code>trap</code>, which cleans up the failed deployment.' },
  
  { type: 'lesson', category: 'Automation', title: 'Automation: Full Script', subtitle: 'Complete deploy.sh', desc: 'The complete deployment script combining robustness (<code>set -e</code>), safety (<code>trap</code>), and validation (<code>curl</code>).', syntax: './deploy.sh', term: [{editor: "deploy.sh", code: "#!/bin/bash\nset -euo pipefail\n\ncleanup() {\n  if [ $? -ne 0 ]; then\n    echo \"Error detected! Cleaning up...\"\n    docker compose down\n  fi\n}\ntrap cleanup EXIT\n\necho \"[1/4] Pulling latest images...\"\ndocker compose pull\n\necho \"[2/4] Starting the stack...\"\ndocker compose up -d\n\necho \"[3/4] Waiting for services to boot...\"\nsleep 5\n\necho \"[4/4] Verifying health...\"\ncurl -f http://localhost:8083 || exit 1\n\necho \"Success! Application is live.\""}, {raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/lemp-stack</span>$</span> <span class="cmd">chmod +x deploy.sh</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~/lemp-stack</span>$</span> <span class="cmd">./deploy.sh</span>'}], explain: '<strong>Explanation:</strong> This is an industry-standard pattern for deployment scripts. It ensures that if any step fails, the system is not left in a broken state. The script either succeeds completely, or cleans up after itself.' },
  
  { type: 'lesson', category: 'Orchestration', title: 'Orchestration', subtitle: 'Beyond Compose', desc: 'Docker Compose runs on a single host. In enterprise environments, you need Orchestration tools to manage containers across multiple servers, handling scaling and self-healing.', syntax: 'Docker Swarm / Kubernetes', term: [{raw: '<span class="out" style="color:#E8A07A">Compose vs Orchestration</span><br><br><span class="out">1. Docker Compose: Single node. If the server dies, the app dies.</span><br><span class="out">2. Kubernetes (K8s): Multi-node. If one server dies, K8s restarts the container on another server automatically.</span><br><br><span class="out" style="color:#E8A07A">Key Orchestration Features</span><br><span class="out">- Self-Healing: Restarts failed containers.</span><br><span class="out">- Scaling: Runs 10 copies of Nginx to handle traffic spikes.</span><br><span class="out">- Rolling Updates: Updates containers one by one with zero downtime.</span>'}], explain: '<strong>Explanation:</strong> Compose is the stepping stone. Once you understand how to define a multi-container app in YAML, the next step is learning Kubernetes, which uses similar concepts (Pods, Deployments, Services) but across a cluster of machines.' },
  
  { type: 'lesson', category: 'Summary', title: 'Topic Summary', subtitle: 'Module 3 Complete', desc: 'You have learned to deploy applications natively (IIS, Nginx) and using modern containerization (Docker Compose), wrapped in a robust automation script.', syntax: 'Install-WindowsFeature Web-Server\ndocker compose up -d\n./deploy.sh', term: [{raw: '<span class="out" style="color:#E8A07A">Module 3 Checklist:</span><br>[x] Installed IIS on Windows Server 2022<br>[x] Hosted site on Port 8080 with custom App Pool<br>[x] Installed Nginx on Ubuntu Server<br>[x] Configured Nginx Reverse Proxy<br>[x] Installed Docker CE<br>[x] Wrote docker-compose.yml (Nginx + PHP + MariaDB)<br>[x] Verified health with docker compose ps & logs<br>[x] Automated deployment with deploy.sh (set -euo, trap)<br><br><span class="out">Next: We will move to Identity Management (AD DS & RBAC).</span>'}], explain: '<strong>Explanation:</strong> This module bridges the gap between OS administration and DevOps. You can now deliver applications reliably. In the next module, we will secure these servers by managing users and access controls.' },

  // --- 4. CLOSING SLIDE ---
  {
    type: 'closing',
    header: 'MODULE 03 · TOPIC 09',
    tag: 'End of Topic 09',
    title: 'From Servers to <em>Containers</em>.',
    leftCardNum: '§ traditional',
    leftCardTitle: 'IIS & Nginx',
    leftCardDesc: 'Traditional web servers install the application directly onto the OS. They are easy to understand but can suffer from dependency conflicts and "works on my machine" syndromes.',
    rightCardNum: '§ modern',
    rightCardTitle: 'Docker & Automation',
    rightCardDesc: 'Docker Compose packages Nginx, PHP, and MariaDB into isolated containers. Wrapping this in a deploy.sh script with trap ensures reliable, repeatable deployments.'
  }
];