const slideConfigs = [
  // --- 1. COVER SLIDE ---
  {
    type: 'cover',
    moduleTitle: 'MODULE 05 · TOPIC 13',
    topicNum: '13',
    topicTag: 'T13',
    title: 'Getting Started with<br><em>Microsoft Azure</em>',
    subtitle: 'Cloud computing fundamentals, navigating the Azure Portal, deploying a free-tier Linux VM, and managing resources to avoid charges.',
    graphicText: 'Understand <em>Cloud</em><br>Deploy <em>Azure VMs</em><br>Manage Costs.',
    miniObjectives: [
      'Cloud Fundamentals (IaaS/PaaS)',
      'Azure Portal & Resource Groups',
      'Deploy Free-Tier Linux VM',
      'SSH & Resource Cleanup'
    ]
  },

  // --- 2. OBJECTIVES SLIDE ---
  {
    type: 'objectives',
    header: 'MODULE 05 · TOPIC 13',
    kicker: 'ITP 141 · M5 · T13',
    desc: 'Cloud administration moves the data center from the campus to the internet. You will learn to deploy servers without buying hardware, while strictly managing costs.',
    lede: 'A sysadmin who cannot deploy a server in the cloud is restricted to local hardware. Master Azure to scale infrastructure globally in minutes.',
    list: [
      'Explain what cloud computing is and how IaaS, PaaS, and SaaS differ.',
      'Create a free Microsoft Azure for Students account without paid billing.',
      'Understand Azure Subscriptions, Tenants, and Resource Groups.',
      'Navigate the Azure Portal to locate services and regions.',
      'Deploy a free-eligible Standard_B1s Linux Virtual Machine.',
      'Configure Network Security Groups (NSG) to allow SSH on port 22.',
      'Connect to an Azure Linux VM over SSH.',
      'Stop and deallocate virtual machines to manage costs.',
      'Delete unused Azure resources to prevent unexpected charges.',
      'Explore Azure CLI commands for basic infrastructure management.'
    ]
  },

  // --- 3. LESSON SLIDES ---
  // 1. Cloud Computing Overview
    { type: 'lesson', category: 'Overview', title: 'Cloud Computing', subtitle: 'The Shift', desc: 'Cloud computing is the delivery of computing services over the internet. Instead of buying and maintaining physical servers, you rent virtual servers, storage, and software on demand.', syntax: 'Traditional: Buy physical hardware -> Wait weeks -> Install OS -> Maintain.\nCloud: Click a button -> Get a server in 2 minutes -> Pay by the minute.', term: [{raw: '<span class="out" style="color:#E8A07A">The Cloud Model</span><br><br><span class="out">1. On-Demand: You provision resources when you need them.</span><br><span class="out">2. Elastic: Scale up during traffic spikes, scale down at night.</span><br><span class="out">3. Metered: You only pay for CPU/RAM seconds you actually use.</span><br><span class="out">4. Global: Deploy in Manila, Tokyo, or New York with a dropdown.</span>'}], explain: '<strong>Explanation:</strong> Cloud computing changes the sysadmin\'s job. You no longer hold a screwdriver; you hold a web browser or CLI. The focus shifts from hardware maintenance to configuration, security, and cost optimization.' },

    // 2. IaaS vs PaaS vs SaaS
    { type: 'lesson', category: 'Overview', title: 'Cloud Models', subtitle: 'IaaS vs PaaS vs SaaS', desc: 'Cloud services are categorized by how much you manage versus what the provider manages. The three main models are IaaS, PaaS, and SaaS.', syntax: 'IaaS: You manage OS.\nPaaS: Provider manages OS.\nSaaS: Provider manages everything.', term: [{raw: '<span class="out" style="color:#E8A07A">Service Models</span><br><br><span class="out">1. IaaS (Infrastructure as a Service): Virtual Machines. You manage the OS, patches, and apps. (e.g., Azure VM)</span><br><span class="out">2. PaaS (Platform as a Service): Managed databases or web hosting. You only manage your code. (e.g., Azure SQL, App Service)</span><br><span class="out">3. SaaS (Software as a Service): Finished apps. You just log in and use it. (e.g., Office 365, Gmail)</span>'}], explain: '<strong>Explanation:</strong> In this course, we focus on IaaS (Virtual Machines) because it directly maps to the dual-OS administration skills we learned. You rent the hardware, but you are still the sysadmin for the OS.' },

    // 3. Public, Private, Hybrid
    { type: 'lesson', category: 'Overview', title: 'Cloud Deployment', subtitle: 'Public, Private, Hybrid', desc: 'Cloud environments can be public (owned by Microsoft/AWS), private (owned by the university), or a hybrid mix of both.', syntax: 'Public: Shared hardware owned by Microsoft.\nPrivate: Exclusive hardware owned by you.\nHybrid: Both connected together.', term: [{raw: '<span class="out" style="color:#E8A07A">Deployment Models</span><br><br><span class="out">1. Public Cloud: Microsoft owns the servers. You rent virtual slices. Cheapest and most common.</span><br><span class="out">2. Private Cloud: DOrSU owns and runs its own data center. Complete control, high cost.</span><br><span class="out">3. Hybrid Cloud: Keep sensitive databases in the private data center, put the public website in Azure.</span>'}], explain: '<strong>Explanation:</strong> Most enterprises use Hybrid. A university might keep the student records database on a private server (for privacy) but host the public website on Azure (to handle traffic spikes during enrollment).' },

    // 4. Microsoft Azure Intro
    { type: 'lesson', category: 'Azure', title: 'Microsoft Azure', subtitle: 'Introduction', desc: 'Microsoft Azure is the second-largest public cloud provider globally. It offers over 200 services, with strong integration for Windows Server and hybrid environments.', syntax: 'Azure: 60+ Regions\nAzure: IaaS, PaaS, SaaS', term: [{raw: '<span class="out" style="color:#E8A07A">Why Azure?</span><br><br><span class="out">1. Free Tier: $100 credit + 12 months of free services for students.</span><br><span class="out">2. Microsoft Ecosystem: Perfect match for Windows Server 2022 and AD DS.</span><br><span class="out">3. Hybrid Tools: Azure Arc lets you manage on-prem servers from the Azure Portal.</span><br><span class="out">4. Open Source: First-class support for Ubuntu, Red Hat, and Docker.</span>'}], explain: '<strong>Explanation:</strong> Azure is heavily used in enterprise environments because it integrates perfectly with Active Directory and Office 365. If a company uses Windows, they usually use Azure.' },

    // 5. Azure Regions & Availability Zones
    { type: 'lesson', category: 'Azure', title: 'Azure Regions', subtitle: 'Global Infrastructure', desc: 'Azure is divided into Regions (geographies). Each Region has one or more Availability Zones (separate data centers with independent power).', syntax: 'Region: e.g., East US, Southeast Asia\nAvailability Zone: Separate data center in a Region.', term: [{raw: '<span class="out" style="color:#E8A07A">Global Infrastructure</span><br><br><span class="out">1. Region: A specific geographic location (e.g., East US, West Europe).</span><br><span class="out">2. Availability Zone (AZ): A distinct physical location within a region. If one AZ floods, the other keeps running.</span><br><br><span class="out" style="color:#E8A07A">Why it matters</span><br><span class="out">Choose a region close to your users to reduce latency. For this course, choose Southeast Asia (Singapore) for the DOrSU lab.</span>'}], explain: '<strong>Explanation:</strong> Latency is the time it takes for a packet to travel. If you deploy a VM in "East US" but users are in Mati City, the website will feel slow. Choosing the closest region (Southeast Asia) is critical for performance.' },

    // 6. Azure Free Tier & Student Account (GUI Mockup)
    { type: 'lesson', category: 'Free Tier', title: 'Azure Free Tier', subtitle: 'Student Account', desc: 'Azure offers a free tier for students that provides a $100 credit and free services for 12 months, without requiring a credit card. This is strictly enforced in this course.', syntax: 'Free Tier: $100 Credit + Free Services\nNo credit card required for students.', term: [{raw: '<div class="az-portal"><div class="az-topbar"><div class="az-logo">Microsoft Azure</div><div class="az-search">Search...</div></div><div class="az-body"><div class="az-sidebar"><div class="az-icon"></div><div class="az-icon"></div></div><div class="az-main"><div class="az-blade"><div class="az-blade-header">Azure for Students - Sign Up <span>x</span></div><div class="az-blade-body"><div class="az-form-row"><div class="az-label">Academic Email</div><div class="az-input">ajsacay@dorsu.edu</div></div><div class="az-form-row"><div class="az-label">Verification</div><div class="az-input">Verify your academic status</div></div><button class="az-btn">Sign up and get $100 credit</button><br><span style="font-size:10px; color:#605e5c;">No credit card required.</span></div></div></div></div></div>'}], explain: '<strong>Explanation:</strong> The free tier is designed for learning. The B1s VM is small (1 CPU, 1GB RAM) but enough to run Ubuntu Server and test Apache/Docker. If you exceed the 750 hours in a month, the VM stops automatically.' },

    // 7. Cost Management
    { type: 'lesson', category: 'Free Tier', title: 'Cost Management', subtitle: 'Staying Free', desc: 'The biggest risk in cloud administration is accidental charges. A VM left running over the weekend burns your credit. You must manage resources strictly.', syntax: 'Stop (Deallocate): Stops billing for CPU/RAM.\nDelete: Permanently removes the resource.', term: [{raw: '<span class="out" style="color:#E8A07A">Cost Control Rules</span><br><br><span class="out">1. Deallocate: When done for the day, click "Stop". This detaches the CPU/RAM. You stop paying for compute.</span><br><span class="out">2. Delete Resource Group: At the end of the lab, delete the entire resource group. This deletes the VM, disk, and IP, stopping all charges.</span><br><span class="out">3. Set Alerts: Configure Azure to email you if spending exceeds $1.</span>'}], explain: '<strong>Explanation:</strong> "Deallocate" is the key word. If you just "Shut down" the OS from inside the VM, Azure still reserves the hardware for you and charges you. You must click "Stop" in the Azure Portal to deallocate and stop billing.' },

    // 8. Creating an Azure Account (GUI Dashboard)
    { type: 'lesson', category: 'Setup', title: 'Azure Account', subtitle: 'Portal Dashboard', desc: 'Creating an Azure account requires a valid university email address. You do not need a credit card for the Student tier. Once logged in, you are greeted by the Portal Dashboard.', syntax: 'portal.azure.com', term: [{raw: '<div class="az-portal"><div class="az-topbar"><div class="az-logo">Microsoft Azure</div><div class="az-search">Search resources, services, and docs</div></div><div class="az-body"><div class="az-sidebar"><div class="az-icon"></div><div class="az-icon"></div><div class="az-icon"></div><div class="az-icon"></div></div><div class="az-main"><h3 style="margin-bottom: 10px; color: #0078d4; font-size: 16px;">Azure services</h3><div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;"><div class="az-blade"><div class="az-blade-body"><div class="az-label">Virtual machines</div>Create and run VMs in the cloud</div></div><div class="az-blade"><div class="az-blade-body"><div class="az-label">Resource groups</div>Group resources together</div></div><div class="az-blade"><div class="az-blade-body"><div class="az-label">Storage accounts</div>Store data securely</div></div><div class="az-blade"><div class="az-blade-body"><div class="az-label">Cost Management</div>Track spending</div></div></div></div></div></div>'}], explain: '<strong>Explanation:</strong> The top search bar is the most important tool. Type "Virtual Machines" to find the service instantly. The Portal is a graphical front-end for the Azure Resource Manager (ARM). Behind the scenes, it is all code.' },

    // 9. Azure Portal Tour
    { type: 'lesson', category: 'Portal', title: 'Azure Portal', subtitle: 'Navigation', desc: 'The Azure Portal is the web-based control plane. Everything you do in Azure (create, delete, monitor) starts here.', syntax: 'portal.azure.com', term: [{raw: '<span class="out" style="color:#E8A07A">Portal Layout</span><br><br><span class="out">1. Top Search Bar: The most important tool. Type "Virtual Machines" to find the service instantly.</span><br><span class="out">2. Left Menu: Navigation for Resource Groups, VMs, etc.</span><br><span class="out">3. Dashboard: Customizable tiles for your most-used resources.</span><br><span class="out">4. Notifications (Bell Icon): Alerts when a deployment finishes or fails.</span><br><br><span class="out" style="color:#E8A07A">Pro Tip</span><br><span class="out">Use the search bar. The left menu is too long to scroll through.</span>'}], explain: '<strong>Explanation:</strong> The Portal is a graphical front-end for the Azure Resource Manager (ARM). When you click "Create VM", the Portal sends an API request to Azure to build it. Behind the scenes, it is all code.' },

    // 10. Subscriptions & Tenants
    { type: 'lesson', category: 'Portal', title: 'Subscriptions & Tenants', subtitle: 'Hierarchy', desc: 'Azure has a strict hierarchy: Tenant -> Subscription -> Resource Group -> Resource. Understanding this prevents billing disasters.', syntax: 'Tenant -> Subscription -> Resource Group -> VM', term: [{raw: '<span class="out" style="color:#E8A07A">Azure Hierarchy</span><br><br><span class="out">1. Tenant (Azure AD): Your organization identity (e.g., dorsu.edu).</span><br><span class="out">2. Subscription: The billing boundary. "Free Trial" is one subscription. "Pay-As-You-Go" is another.</span><br><span class="out">3. Resource Group: A logical container for resources that share a lifecycle (e.g., "WebApp-Production").</span><br><span class="out">4. Resource: The actual VM, database, or network.</span>'}], explain: '<strong>Explanation:</strong> You cannot create a VM without putting it in a Resource Group. The Resource Group is the unit of management. If you delete the Resource Group, every resource inside it is deleted automatically. This is how you clean up a lab.' },

    // 11. Resource Groups Concept
    { type: 'lesson', category: 'Portal', title: 'Resource Groups', subtitle: 'Logical Containers', desc: 'A Resource Group is a folder that holds related resources. It is the fundamental unit of organization and billing in Azure.', syntax: 'Resource Group: "ITP141-Lab-07"\nContains: VM, Disk, IP, NSG', term: [{raw: '<span class="out" style="color:#E8A07A">Why use Resource Groups?</span><br><br><span class="out">1. Lifecycle: You can deploy, monitor, and delete an entire application as one unit.</span><br><span class="out">2. Billing: You can export the cost of a single Resource Group to see how much "Lab 7" cost.</span><br><span class="out">3. Access Control (RBAC): You can give a student "Contributor" access to one Resource Group without giving them access to the whole subscription.</span><br><br><span class="out" style="color:#E8A07A">Naming Convention</span><br><span class="out">Use: [Course]-[Lab]-[Environment] (e.g., ITP141-Lab07-Dev)</span>'}], explain: '<strong>Explanation:</strong> Never mix Production and Dev resources in the same Resource Group. If you do, and you delete the Resource Group to clean up Dev, you accidentally delete Production.' },

    // 12. Azure Resource Manager (ARM)
    { type: 'lesson', category: 'Portal', title: 'Azure Resource Manager', subtitle: 'The Control Plane', desc: 'Behind the Portal is the Azure Resource Manager (ARM). It validates, authenticates, and routes every request to create or modify resources.', syntax: 'User -> Portal -> ARM API -> Azure Data Centers', term: [{raw: '<span class="out" style="color:#E8A07A">How ARM Works</span><br><br><span class="out">1. You click "Create VM" in the Portal.</span><br><span class="out">2. The Portal sends a JSON request to the ARM API.</span><br><span class="out">3. ARM checks: Do you have permission? Is the region valid?</span><br><span class="out">4. ARM routes the request to a physical server in the region.</span><br><span class="out">5. The server allocates CPU/RAM and boots the VM.</span><br><br><span class="out" style="color:#E8A07A">Infrastructure as Code (IaC)</span><br><span class="out">Because everything is an API call, you can automate deployments using JSON templates (ARM Templates) or Terraform.</span>'}], explain: '<strong>Explanation:</strong> ARM is why cloud is "software-defined". The Portal is just a pretty UI. Real sysadmins use Azure CLI or Terraform to send these JSON requests via scripts, enabling them to deploy 1000 VMs in 5 minutes.' },

    // 13. Virtual Machines (IaaS)
    { type: 'lesson', category: 'Virtual Machines', title: 'Azure Virtual Machines', subtitle: 'IaaS Concept', desc: 'An Azure VM is a virtual server running in a Microsoft data center. You have full control over the OS, exactly like your VirtualBox VM.', syntax: 'Azure VM = VirtualBox VM (Conceptually)\nBut hardware is managed by Microsoft.', term: [{raw: '<span class="out" style="color:#E8A07A">Azure VM vs VirtualBox VM</span><br><br><span class="out">Similarities:</span><br><span class="out">- Both run Ubuntu/Windows.</span><br><span class="out">- Both have a virtual disk.</span><br><br><span class="out">Differences:</span><br><span class="out">- VirtualBox runs on your laptop. Azure runs in a data center.</span><br><span class="out">- VirtualBox is free. Azure bills per second.</span><br><span class="out">- Azure VM has a public IP accessible from the internet.</span><br><span class="out">- Azure VM can scale to 96 CPUs. VirtualBox is limited by your laptop.</span>'}], explain: '<strong>Explanation:</strong> The skills you learned in Module 1 (SSH, Netplan, LVM) apply exactly the same to an Azure VM. The only difference is where the hardware physically sits.' },

    // 14. Free-Tier VM Size (B1s)
    { type: 'lesson', category: 'Virtual Machines', title: 'VM Sizes', subtitle: 'Free-Tier B1s', desc: 'Azure categorizes VMs by Size (CPU/RAM). To stay in the free tier, you must use the Standard_B1s size. Do not select D-series or F-series.', syntax: 'Standard_B1s: 1 vCPU, 1 GB RAM\nFree for 750 hours/month.', term: [{raw: '<span class="out" style="color:#E8A07A">VM Size Tiers</span><br><br><span class="out">1. B-Series (Burstable): Cheap, for testing. B1s is free.</span><br><span class="out">2. D-Series (General Purpose): 4+ CPUs, used for web servers. Costs money.</span><br><span class="out">3. F-Series (Compute Optimized): For heavy processing. Very expensive.</span><br><br><span class="out" style="color:#E8A07A">Warning</span><br><span class="out">Selecting "D2s_v3" will drain your $100 credit in a few days. Always select "Standard_B1s" for this course.</span>'}], explain: '<strong>Explanation:</strong> B-series VMs are "burstable". They have a baseline CPU performance but can burst to 100% for a short time. This is perfect for labs. 1GB RAM is enough for Ubuntu CLI but will struggle with a GUI Desktop.' },

    // 15. VM Images (Ubuntu 24.04 LTS)
    { type: 'lesson', category: 'Virtual Machines', title: 'VM Images', subtitle: 'Ubuntu 24.04 LTS', desc: 'An Image is the OS template. Azure has a marketplace of pre-configured images. We will use the official Ubuntu Server 24.04 LTS image.', syntax: 'Image: Ubuntu Server 24.04 LTS - x64 Gen2', term: [{raw: '<span class="out" style="color:#E8A07A">Azure Marketplace</span><br><br><span class="out">1. Ubuntu Server 24.04 LTS: The standard Linux server image.</span><br><span class="out">2. Windows Server 2022 Datacenter: Available but consumes 30GB of disk and 4GB RAM. Too heavy for free tier.</span><br><span class="out">3. CentOS, Red Hat, Debian: Other free options.</span><br><br><span class="out" style="color:#E8A07A">Why Ubuntu?</span><br><span class="out">It is free, lightweight, and matches the dual-OS lab from Module 1. We can SSH into it and run Docker.</span>'}], explain: '<strong>Explanation:</strong> Images are provided by Canonical (the company behind Ubuntu) and vetted by Microsoft. They contain the OS and essential drivers, but no applications. You install Nginx/Docker yourself after booting.' },

    // 16. VM Authentication (SSH Keys)
    { type: 'lesson', category: 'Virtual Machines', title: 'VM Authentication', subtitle: 'SSH Keys vs Password', desc: 'Azure strongly discourages password authentication for Linux VMs exposed to the internet. You should use SSH public keys.', syntax: 'Generate SSH Key -> Upload Public Key to Azure -> Azure injects it into the VM', term: [{raw: '<span class="out" style="color:#E8A07A">Why SSH Keys?</span><br><br><span class="out">1. Internet Exposure: Azure VMs have public IPs. Bots scan port 22 within seconds of creation.</span><br><span class="out">2. Passwords fail: Brute-force attacks will guess weak passwords.</span><br><span class="out">3. Automation: You cannot script a password prompt. Keys allow CI/CD pipelines to connect.</span><br><br><span class="out" style="color:#E8A07A">Azure Portal Option</span><br><span class="out">When creating the VM, select "SSH public key" and paste your id_ed25519.pub content.</span>'}], explain: '<strong>Explanation:</strong> You can generate an SSH key on your Windows host using <code>ssh-keygen -t ed25519</code>. Paste the public key into the Azure Portal. Azure will inject it into the <code>~/.ssh/authorized_keys</code> file of the admin user during VM provisioning.' },

    // 17. Network Security Groups (NSG)
    { type: 'lesson', category: 'Virtual Machines', title: 'Network Security', subtitle: 'NSG', desc: 'A Network Security Group (NSG) is the Azure equivalent of UFW/Windows Firewall. It filters traffic at the virtual network interface.', syntax: 'NSG Rule: Allow Inbound Port 22 (SSH) from My IP', term: [{raw: '<span class="out" style="color:#E8A07A">Default NSG Rules</span><br><br><span class="out">1. Deny All Inbound: By default, nothing can reach the VM.</span><br><span class="out">2. Allow VNet: The VM can talk to other VMs in the same virtual network.</span><br><span class="out">3. Allow Outbound: The VM can connect to the internet.</span><br><br><span class="out" style="color:#E8A07A">Best Practice</span><br><span class="out">Instead of allowing SSH from "Any", restrict it to your home/office IP address (e.g., 192.168.1.50/32). This stops bots.</span>'}], explain: '<strong>Explanation:</strong> When you create a VM, Azure automatically creates an NSG and attaches it to the network interface. If you select port 22 as open, it adds the rule. If you forget to open port 22, your SSH connection will time out.' },

    // 18. Create VM Portal: Basics (GUI Mockup)
    { type: 'lesson', category: 'Deployment', title: 'Deploy VM: Basics', subtitle: 'Portal Step 1', desc: 'The first step in the VM creation wizard sets the name, region, image, and size. This is the "Basics" tab in the Azure Portal.', syntax: 'Resource Group: ITP141-Lab07\nVM Name: ubu-azure-01\nRegion: Southeast Asia\nImage: Ubuntu 24.04 LTS\nSize: Standard_B1s', term: [{raw: '<div class="az-portal"><div class="az-topbar"><div class="az-logo">Microsoft Azure</div><div class="az-search">Search resources</div></div><div class="az-body"><div class="az-sidebar"><div class="az-icon"></div></div><div class="az-main"><div class="az-blade"><div class="az-blade-header">Create a virtual machine <span>x</span></div><div class="az-blade-body"><div class="az-tabs"><span class="az-tab active">Basics</span><span class="az-tab">Disks</span><span class="az-tab">Networking</span><span class="az-tab">Review + create</span></div><div class="az-form-row"><div class="az-label">Project details</div><div class="az-input">Resource group: ITP141-Lab07 [Create new]</div></div><div class="az-form-row"><div class="az-label">Instance details</div><div class="az-input">Virtual machine name: ubu-azure-01</div></div><div class="az-form-row"><div class="az-input">Region: Southeast Asia</div></div><div class="az-form-row"><div class="az-input">Image: Ubuntu Server 24.04 LTS - x64 Gen2</div></div><div class="az-form-row"><div class="az-input">Size: Standard_B1s [See all sizes]</div></div></div></div></div></div></div>'}], explain: '<strong>Explanation:</strong> The username is always "azureuser" for Ubuntu images in Azure. You cannot use "root" for SSH login. You will use <code>sudo</code> for admin tasks. Ensure you select "SSH public key" for authentication.' },

    // 19. Create VM Portal: Disks & Networking (GUI Mockup)
    { type: 'lesson', category: 'Deployment', title: 'Deploy VM: Disks & Net', subtitle: 'Portal Step 2', desc: 'The Disks tab configures the OS disk type. The Networking tab sets up the IP and ports. This is the "Disks" and "Networking" tab in the Azure Portal.', syntax: 'OS Disk: Standard SSD\nPublic IP: Yes\nInbound Port: SSH (22)', term: [{raw: '<div class="az-portal"><div class="az-topbar"><div class="az-logo">Microsoft Azure</div><div class="az-search">Search</div></div><div class="az-body"><div class="az-sidebar"><div class="az-icon"></div></div><div class="az-main"><div class="az-blade"><div class="az-blade-header">Create a virtual machine <span>x</span></div><div class="az-blade-body"><div class="az-tabs"><span class="az-tab">Basics</span><span class="az-tab active">Disks</span><span class="az-tab active">Networking</span><span class="az-tab">Review + create</span></div><div class="az-form-row"><div class="az-label">OS disk type</div><div class="az-input">Standard SSD (Locally-redundant storage)</div></div><div class="az-form-row"><div class="az-label">Networking (Preview)</div><div class="az-input">Virtual network: vnet-ITP141</div></div><div class="az-form-row"><div class="az-input">Public IP: 20.115.45.123</div></div><div class="az-form-row"><div class="az-input">NIC network security group: Advanced</div></div><div class="az-form-row"><div class="az-input">Inbound ports: SSH (22)</div></div></div></div></div></div></div>'}], explain: '<strong>Explanation:</strong> The Public IP is dynamic but assigned to you as long as the VM exists. If you stop and start the VM (without deleting it), the IP might change. For production, you would buy a "Static IP" resource, but that costs money.' },

    // 20. Create VM Portal: Review & Create (GUI Mockup)
    { type: 'lesson', category: 'Deployment', title: 'Deploy VM: Review', subtitle: 'Portal Step 3', desc: 'The final tab validates your configuration and runs a security check. Click "Create" to deploy. This is the "Review + create" tab in the Azure Portal.', syntax: 'Click "Review + create"\nWait 2-3 minutes for deployment.', term: [{raw: '<div class="az-portal"><div class="az-topbar"><div class="az-logo">Microsoft Azure</div><div class="az-search">Search</div></div><div class="az-body"><div class="az-sidebar"><div class="az-icon"></div></div><div class="az-main"><div class="az-blade"><div class="az-blade-header">Create a virtual machine <span>x</span></div><div class="az-blade-body"><div class="az-tabs"><span class="az-tab">Basics</span><span class="az-tab">Disks</span><span class="az-tab">Networking</span><span class="az-tab active">Review + create</span></div><div class="az-validation-box">Validation passed. Click Create to deploy.</div><div class="az-form-row"><div class="az-label">Estimated cost</div><div class="az-input">$8.00/month (Free for 750 hours)</div></div><button class="az-btn" style="background: #0078d4;">Create</button></div></div></div></div></div></div>'}], explain: '<strong>Explanation:</strong> Azure uses "cloud-init" to inject your SSH keys and set the hostname during boot. This replaces the manual setup we did in VirtualBox. The whole process is automated.' },

    // 21. Finding the Public IP (GUI Mockup)
    { type: 'lesson', category: 'Access', title: 'Finding Public IP', subtitle: 'Overview Page', desc: 'Once deployed, the VM Overview page displays the Public IP Address. You use this to connect via SSH. This is the "Overview" blade in the Azure Portal.', syntax: 'Go to VM -> Overview -> Public IP Address', term: [{raw: '<div class="az-portal"><div class="az-topbar"><div class="az-logo">Microsoft Azure</div><div class="az-search">Search</div></div><div class="az-body"><div class="az-sidebar"><div class="az-icon"></div></div><div class="az-main"><div class="az-blade"><div class="az-blade-header">ubu-azure-01 | Virtual Machine <span>x</span></div><div class="az-blade-body"><div style="display: flex; align-items: center; gap: 8px; margin-bottom: 15px;"><span class="az-status-dot"></span> Status: Running</div><div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;"><div class="az-form-row"><div class="az-label">Public IP address</div><div class="az-input">20.115.45.123</div></div><div class="az-form-row"><div class="az-label">Virtual network/subnet</div><div class="az-input">vnet/default</div></div><div class="az-form-row"><div class="az-label">DNS name</div><div class="az-input">ubu-azure-01.southeastasia.cloudapp.azure.com</div></div><div class="az-form-row"><div class="az-label">Size</div><div class="az-input">Standard_B1s</div></div></div></div></div></div></div></div>'}], explain: '<strong>Explanation:</strong> Copy the Public IP Address. This is the address you will use to SSH into the VM. Never share this IP in public forums, as it identifies a running server that could be targeted.' },

    // 22. Connecting via SSH
    { type: 'lesson', category: 'Access', title: 'Connecting via SSH', subtitle: 'PowerShell/Terminal', desc: 'From your Windows host, open PowerShell or Terminal and use the SSH command with the public IP and the private key.', syntax: 'ssh -i ~/.ssh/id_ed25519 azureuser@20.115.45.123', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell</span><br><span class="cmd">> ssh -i C:\\Users\\Admin\\.ssh\\id_ed25519 azureuser@20.115.45.123</span><br><span class="out">The authenticity of host \'20.115.45.123\' can\'t be established.</span><br><span class="out">Are you sure you want to continue connecting (yes/no)? yes</span><br><br><span class="out" style="color:#E8A07A">Welcome to Ubuntu 24.04.1 LTS</span><br><span class="prompt"><span class="user">azureuser@ubu-azure-01</span>:<span class="path">~</span>$</span> <span class="cmd">hostname</span><br><span class="out">ubu-azure-01</span>'}], explain: '<strong>Explanation:</strong> The <code>-i</code> flag specifies the private key file. The username is "azureuser". If you did not protect your key with a passphrase, you will log in instantly. If you did, you will be prompted for it.' },

    // 23. Azure Cloud Shell
    { type: 'lesson', category: 'Access', title: 'Azure Cloud Shell', subtitle: 'Browser CLI', desc: 'If you do not have a local SSH client, you can use Azure Cloud Shell directly from the browser to connect to the VM.', syntax: 'Click ">_" icon in Azure Portal -> Bash', term: [{raw: '<span class="out" style="color:#E8A07A">Azure Cloud Shell</span><br><br><span class="out">1. Browser-based: No local SSH client needed.</span><br><span class="out">2. Authenticated: Automatically uses your Azure login.</span><br><br><span class="out" style="color:#E8A07A">Commands</span><br><span class="out">az vm show --name ubu-azure-01 --resource-group ITP141-Lab07</span><br><span class="out">ssh azureuser@20.115.45.123</span><br><br><span class="out" style="color:#E8A07A">Why use it?</span><br><span class="out">It persists your files in an Azure storage account. If your laptop breaks, your scripts are safe in the cloud.</span>'}], explain: '<strong>Explanation:</strong> Cloud Shell is a pre-configured Ubuntu environment with Azure CLI installed. It is excellent for quick administrative tasks. However, it times out after 20 minutes of inactivity.' },

    // 24. Azure Bastion
    { type: 'lesson', category: 'Access', title: 'Azure Bastion', subtitle: 'Secure RDP/SSH', desc: 'Azure Bastion provides secure, browser-based RDP and SSH access to VMs without exposing public IPs. It is the enterprise standard for secure access.', syntax: 'VM -> Connect -> Bastion -> Browser Window', term: [{raw: '<span class="out" style="color:#E8A07A">Azure Bastion</span><br><br><span class="out">1. Zero Public IP: VMs do not need a public IP, making them invisible to the internet.</span><br><span class="out">2. Browser Only: Connect from any computer without installing PuTTY or SSH.</span><br><span class="out">3. TLS Encryption: Traffic passes through the Bastion host over port 443.</span><br><br><span class="out" style="color:#E8A07A">Cost Warning</span><br><span class="out">Bastion is a PaaS service that charges ~$0.15/hour. Do not leave it running in the free tier unless necessary.</span>'}], explain: '<strong>Explanation:</strong> Bastion is the most secure way to access VMs in Azure. It sits in a special subnet called "AzureBastionSubnet" and brokers connections. It eliminates the need for NSG port 22 rules.' },

    // 25. Stop vs Deallocate
    { type: 'lesson', category: 'Cost', title: 'Stop vs Deallocate', subtitle: 'Billing Difference', desc: 'This is the most critical distinction in Azure. "Stopping" a VM from inside the OS does not stop billing. You must "Deallocate" from the Portal.', syntax: 'Portal Stop = Deallocate (Stops billing)\nVM OS Shutdown = Stopped (Still billing)', term: [{raw: '<span class="out" style="color:#E8A07A">The Deallocate Difference</span><br><br><span class="out">1. Stopped (OS Shutdown): The VM is off, but Azure reserves the CPU/RAM for you. You pay for the reserved hardware.</span><br><br><span class="out">2. Deallocated (Portal Stop): The VM is off, and Azure returns the CPU/RAM to the pool. You stop paying for compute. You only pay for the disk.</span><br><br><span class="out" style="color:#E8A07A">How to Deallocate</span><br><span class="out">Click "Stop" in the Azure Portal. The status will change to "Stopped (Deallocated)".</span>'}], explain: '<strong>Explanation:</strong> Always deallocate your VMs when the lab is done. A B1s VM left "Stopped" (not deallocated) costs about $8/month. Left running for a weekend, it burns your free credit.' },

    // 26. Deleting Resources
    { type: 'lesson', category: 'Cost', title: 'Deleting Resources', subtitle: 'Full Cleanup', desc: 'To completely stop all charges, you must delete the Resource Group. This deletes the VM, disk, and public IP.', syntax: 'Resource Group -> Delete', term: [{raw: '<span class="out" style="color:#E8A07A">Deletion Steps</span><br><br><span class="out">1. Search for "Resource Groups" in the Portal.</span><br><span class="out">2. Click "ITP141-Lab07".</span><br><span class="out">3. Click "Delete resource group".</span><br><span class="out">4. Type the resource group name to confirm.</span><br><span class="out">5. Click "Delete".</span><br><br><span class="out" style="color:#E8A07A">Why delete?</span><br><span class="out">Even a deallocated VM has a 30GB OS disk that costs $0.07/GB/month ($2.10/month). The public IP costs $0.004/hour. Deleting stops all these charges.</span>'}], explain: '<strong>Explanation:</strong> Deallocating is for temporary pauses. Deleting is for permanent cleanup. After Lab 7, you must delete the resource group. Syllabus Rule 2: Free tier only.' },

    // 27. Infrastructure as Code (IaC)
    { type: 'lesson', category: 'IaC', title: 'Infrastructure as Code', subtitle: 'Concept', desc: 'Infrastructure as Code (IaC) is the process of managing data centers through machine-readable definition files, rather than clicking in a GUI.', syntax: 'Manual: Click -> Wait -> Forget -> Error.\nIaC: Code -> Repeat -> Version -> Automate.', term: [{raw: '<span class="out" style="color:#E8A07A">Why IaC?</span><br><br><span class="out">1. Speed: Deploy 100 VMs in 2 minutes.</span><br><span class="out">2. Consistency: Every VM is identical. No human typos.</span><br><span class="out">3. Version Control: You can track changes in Git.</span><br><span class="out">4. Reusability: Share the code with other sysadmins.</span><br><br><span class="out" style="color:#E8A07A">Tools</span><br><span class="out">Azure ARM Templates (JSON)</span><br><span class="out">Terraform (HashiCorp)</span><br><span class="out">Azure Bicep (Microsoft)</span>'}], explain: '<strong>Explanation:</strong> Clicking through the Portal is fine for learning. In production, you never click. You write a script. If a server dies, you don\'t fix it; you run the script to build a new one. This is the DevOps mindset.' },

    // 28. Azure CLI Overview
    { type: 'lesson', category: 'IaC', title: 'Azure CLI', subtitle: 'Command Line Interface', desc: 'The Azure CLI is a cross-platform command-line tool to manage Azure resources. It is the easiest way to start with IaC.', syntax: 'az group create --name ITP141 --location southeastasia', term: [{raw: '<span class="out" style="color:#E8A07A">Azure CLI Commands</span><br><br><span class="out">1. az login: Opens browser to authenticate.</span><br><span class="out">2. az group create: Creates a Resource Group.</span><br><span class="out">3. az vm create: Deploys a VM in one line.</span><br><br><span class="out" style="color:#E8A07A">Installation</span><br><span class="out">Available on Windows (MSI), macOS (Homebrew), and Linux (apt).</span><br><span class="out">Or use it inside Azure Cloud Shell (no install needed).</span>'}], explain: '<strong>Explanation:</strong> The Azure CLI uses the same ARM API as the Portal, but via terminal. It is perfect for sysadmins who are already comfortable with Bash. The commands start with <code>az</code> followed by the resource type (e.g., <code>vm</code>).' },

    // 29. Azure PowerShell vs CLI
    { type: 'lesson', category: 'IaC', title: 'PowerShell vs CLI', subtitle: 'Tool Choice', desc: 'Azure provides two main scripting tools: Azure PowerShell (Az module) and Azure CLI. Choose based on your background.', syntax: 'CLI: az vm create\nPS: New-AzVM', term: [{raw: '<span class="out" style="color:#E8A07A">Comparison</span><br><br><span class="out">1. Azure PowerShell (Az): Native to Windows. Object-oriented. Cmdlets like New-AzVM.</span><br><span class="out">2. Azure CLI: Cross-platform (Linux/Mac/Win). Text-based. Commands like az vm create.</span><br><br><span class="out" style="color:#E8A07A">Which to use?</span><br><span class="out">- Windows sysadmins usually prefer PowerShell.</span><br><span class="out">- Linux sysadmins usually prefer CLI.</span><br><span class="out">- Both can do 100% of the tasks.</span>'}], explain: '<strong>Explanation:</strong> In this course, we focus on Azure CLI because it integrates well with WSL 2 and Ubuntu. You can run <code>az</code> commands directly from your WSL Bash shell.' },

    // 30. Installing Azure CLI
    { type: 'lesson', category: 'IaC', title: 'Install Azure CLI', subtitle: 'Ubuntu/WSL', desc: 'Install the Azure CLI on your Ubuntu Server or WSL 2 environment to manage cloud resources from the terminal.', syntax: 'curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash</span><br><span class="out">Executing script...</span><br><span class="out">Installing azure-cli...</span><br><span class="out">Setting up azure-cli (2.65.0-1~jammy)...</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">az --version</span><br><span class="out">azure-cli 2.65.0</span><br><span class="out">core 2.65.0</span>'}], explain: '<strong>Explanation:</strong> This script adds the Microsoft repository and installs the <code>az</code> command. Once installed, you can manage Azure from your Ubuntu terminal without opening a browser.' },

    // 31. Logging in via CLI
    { type: 'lesson', category: 'IaC', title: 'CLI: Login', subtitle: 'az login', desc: 'To manage resources, you must authenticate the CLI to your Azure account. This opens a browser window for a one-time login.', syntax: 'az login', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">az login</span><br><span class="out">To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code A1B2C3D4 to authenticate.</span><br><span class="out">[</span><br><span class="out">  {</span><br><span class="out">    "cloudName": "AzureCloud",</span><br><span class="out">    "name": "Free Trial",</span><br><span class="out">    "state": "Enabled",</span><br><span class="out">    "user": { "name": "ajsacay@dorsu.edu" }</span><br><span class="out">  }</span><br><span class="out">]</span>'}], explain: '<strong>Explanation:</strong> The CLI generates a device code. You open a browser on any device, enter the code, and log in. The CLI stores the session token locally. You stay logged in until the token expires or you run <code>az logout</code>.' },

    // 32. CLI: Create Resource Group
    { type: 'lesson', category: 'IaC', title: 'CLI: Resource Group', subtitle: 'az group create', desc: 'Before creating a VM via CLI, you must create a Resource Group in a specific region.', syntax: 'az group create --name ITP141-Lab07 --location southeastasia', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">az group create --name ITP141-Lab07 --location southeastasia</span><br><span class="out">{</span><br><span class="out">  "id": "/subscriptions/12345/resourceGroups/ITP141-Lab07",</span><br><span class="out">  "location": "southeastasia",</span><br><span class="out">  "name": "ITP141-Lab07",</span><br><span class="out">  "properties": { "provisioningState": "Succeeded" }</span><br><span class="out">}</span>'}], explain: '<strong>Explanation:</strong> The <code>--location</code> parameter determines where the Resource Group metadata is stored. "southeastasia" is the Singapore region. You can list all regions with <code>az account list-locations</code>.' },

    // 33. CLI: Create VM
    { type: 'lesson', category: 'IaC', title: 'CLI: Create VM', subtitle: 'az vm create', desc: 'Deploy a full Ubuntu VM with one command. The CLI generates SSH keys automatically if you do not provide them.', syntax: 'az vm create --resource-group ITP141-Lab07 --name ubu-cli-01 --image UbuntuLTS --size Standard_B1s --generate-ssh-keys', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">az vm create -g ITP141-Lab07 -n ubu-cli-01 --image UbuntuLTS --size Standard_B1s --generate-ssh-keys</span><br><span class="out">{</span><br><span class="out">  "fqdns": "",</span><br><span class="out">  "id": "/subscriptions/.../ubu-cli-01",</span><br><span class="out">  "location": "southeastasia",</span><br><span class="out">  "macAddress": "00-0D-3A-1B-2C-3D",</span><br><span class="out">  "publicIpAddress": "20.115.45.200",</span><br><span class="out">  "privateIpAddress": "10.0.0.5",</span><br><span class="out">  "resourceGroup": "ITP141-Lab07",</span><br><span class="out">  "vmSize": "Standard_B1s"</span><br><span class="out">}</span>'}], explain: '<strong>Explanation:</strong> This single command replaces the entire Portal wizard. It creates the VM, network interface, public IP, and disk. The <code>--generate-ssh-keys</code> flag creates a new key pair and saves it in <code>~/.ssh/</code>.' },

    // 34. CLI: List & Manage VMs
    { type: 'lesson', category: 'IaC', title: 'CLI: Manage VMs', subtitle: 'az vm list', desc: 'The CLI allows you to list all VMs in a subscription, stop them, or delete them without opening a browser.', syntax: 'az vm list --output table\naz vm stop --name ubu-cli-01 -g ITP141-Lab07', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">az vm list --output table</span><br><span class="out">Name          ResourceGroup    Location      Status</span><br><span class="out">------------  ---------------  ------------  --------</span><br><span class="out">ubu-cli-01    ITP141-Lab07     southeastasia  VM running</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">az vm deallocate -g ITP141-Lab07 -n ubu-cli-01</span><br><span class="out">(Stops the VM and releases the compute resources to stop billing)</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">az group delete --name ITP141-Lab07</span><br><span class="out">(Deletes everything inside the resource group)</span>'}], explain: '<strong>Explanation:</strong> <code>az vm deallocate</code> is the CLI equivalent of clicking "Stop" in the Portal. It is the critical command to stop billing. <code>az group delete</code> is the ultimate cleanup command, destroying everything permanently.' },

    // 35. Azure Monitor & Metrics
    { type: 'lesson', category: 'Monitoring', title: 'Azure Monitor', subtitle: 'Metrics', desc: 'Azure Monitor collects metrics and logs from Azure resources. You can view CPU usage, network traffic, and disk I/O without installing agents.', syntax: 'VM -> Metrics -> Select "Percentage CPU"', term: [{raw: '<span class="out" style="color:#E8A07A">Azure Monitor Features</span><br><br><span class="out">1. Platform Metrics: Automatically collected. No agent needed. (e.g., CPU, Network).</span><br><span class="out">2. Guest OS Metrics: Requires Azure Monitor Agent. (e.g., Memory, Disk Space).</span><br><span class="out">3. Alerts: Send an email or trigger a webhook if CPU > 90% for 5 minutes.</span><br><br><span class="out" style="color:#E8A07A">Why use it?</span><br><span class="out">If your free tier VM is slow, check the CPU metric. B1s VMs are burstable. If you run out of CPU credits, performance drops to 10%.</span>'}], explain: '<strong>Explanation:</strong> B1s VMs have a "Credit" system. When idle, they build up CPU credits. When busy, they spend them. When credits are zero, the VM is throttled. Azure Monitor shows the credit balance.' },

    // 36. Azure Cost Analysis
    { type: 'lesson', category: 'Monitoring', title: 'Cost Analysis', subtitle: 'Tracking Spend', desc: 'The Cost Management tool tracks how much you are spending. It is the dashboard you check daily in the cloud.', syntax: 'Cost Management -> Cost Analysis', term: [{raw: '<span class="out" style="color:#E8A07A">Cost Management</span><br><br><span class="out">1. Cost by Resource: Shows which VM/Database is burning your credit.</span><br><span class="out">2. Cost by Service: Shows if you are paying for Virtual Machines, Storage, or Bandwidth.</span><br><span class="out">3. Budgets: Set a $1 budget. Azure emails you when you hit it.</span><br><br><span class="out" style="color:#E8A07A">Free Tier Rule</span><br><span class="out">If your "Actual Cost" line goes up before the 30th day, you forgot to deallocate a VM.</span>'}], explain: '<strong>Explanation:</strong> Cost Analysis is the most important screen for a student. It shows your burn rate. If the graph is flat at $0, you are correctly using the free tier. If it spikes, you need to find and delete the resource immediately.' },

    // 37. Topic Summary
    { type: 'lesson', category: 'Summary', title: 'Topic Summary', subtitle: 'Module 5 Complete', desc: 'You have deployed a server in the cloud without buying hardware, connected to it over the internet, and learned the discipline of cost management.', syntax: 'az login\naz vm create\naz group delete', term: [{raw: '<span class="out" style="color:#E8A07A">Module 5 Checklist:</span><br>[x] Created Azure Free Student Account<br>[x] Navigated Portal and Resource Groups<br>[x] Deployed Free-Tier B1s Ubuntu VM<br>[x] Connected via SSH<br>[x] Stopped (Deallocated) VM to stop billing<br>[x] Deleted Resource Group for cleanup<br>[x] Explored Azure CLI for IaC<br><br><span class="out">Next: We will explore Infrastructure as Code with Terraform.</span>'}], explain: '<strong>Explanation:</strong> Cloud administration is about abstraction. You no longer care about the physical server; you care about the API call that creates it. Mastering the Azure Portal and CLI is the first step into cloud computing.' },

  // --- 4. CLOSING SLIDE ---
  {
    type: 'closing',
    header: 'MODULE 05 · TOPIC 13',
    tag: 'End of Topic 13',
    title: 'The Data Center is now <em>Software</em>.',
    quote: 'Cloud is not just a place to put your servers; it is a financial model where you pay for what you use. The free tier teaches you the discipline of cleanup.',
    leftCardNum: '§ cloud',
    leftCardTitle: 'Azure & IaaS',
    leftCardDesc: 'Cloud computing replaces physical hardware with virtual resources billed according to usage. Azure Portal and Resource Groups become the sysadmin’s control panel.',
    middleCardNum: '§ free tier',
    middleCardTitle: 'VMs & Cost Control',
    middleCardDesc: 'Deploying a Standard_B1s Linux VM and connecting over SSH demonstrates cloud infrastructure. Deallocating and deleting unused resources helps prevent unnecessary charges.',
    rightCardNum: '§ administration',
    rightCardTitle: 'SSH & Resource Management',
    rightCardDesc: 'Azure Portal and CLI simplify deployment, while secure SSH access and proper resource cleanup support effective cloud administration.'
  }
];