const slideConfigs = [
  // --- 1. COVER SLIDE ---
  {
    type: 'cover',
    moduleTitle: 'MODULE 06 · TOPIC 15',
    topicNum: '15',
    topicTag: 'T15',
    title: 'IT Automation,<br>Monitoring &amp; <em>DR</em>',
    subtitle: 'Observability with Prometheus and Grafana, alert rule design, IT Run Books, and Change Request templates: the sysadmin’s defensive perimeter against downtime.',
    graphicText: 'Observe <em>Metrics</em><br>Alert <em>Early</em><br>Document.',
    miniObjectives: [
      'Prometheus + Grafana + Node Exporter',
      'Alert Rules & 5-Panel Dashboard',
      'IT Run Book Template',
      'Change Request & ITIL'
    ]
  },

  // --- 2. OBJECTIVES SLIDE ---
  {
    type: 'objectives',
    header: 'MODULE 06 · TOPIC 15',
    kicker: 'ITP 141 · M6 · T15',
    desc: 'A server without monitoring is a black box. You will learn to install the Prometheus observability stack, build dashboards, write alert rules, and codify operational knowledge in run books.',
    lede: 'Visibility, alerting, and documentation transform a fragile system into a resilient one.',
    list: [
      'Explain the three pillars of observability: metrics, logs, and traces.',
      'Install Prometheus, Node Exporter, and Grafana on Ubuntu Server 24.04 LTS.',
      'Configure Prometheus to scrape Node Exporter metrics every 15 seconds.',
      'Connect Grafana to Prometheus and verify the data source using the up query.',
      'Build a five-panel Grafana dashboard for CPU, memory, disk, uptime, and network.',
      'Write PromQL queries using rate(), avg by(), and arithmetic operators.',
      'Create Prometheus alert rules for CPU utilization above 80% and disk utilization above 85%.',
      'Understand Alertmanager features, including routing, grouping, deduplication, and silencing.',
      'Configure Grafana notification channels and notification policies.',
      'Automate routine administrative tasks using Bash scripts and cron.',
      'Create a self-healing script that checks and restarts the Prometheus service.',
      'Understand Recovery Point Objective (RPO) and Recovery Time Objective (RTO).',
      'Create an IT Run Book containing service information, health checks, and incident procedures.',
      'Prepare an ITIL Change Request with risk, impact, approval, and rollback details.',
      'Differentiate Standard, Normal, and Emergency changes.',
      'Identify the essential components of a Disaster Recovery network diagram.'
    ]
  },

  // --- 3. LESSON SLIDES ---
    // 1. Monitoring Overview
    { type: 'lesson', category: 'Monitoring', title: 'Monitoring Overview: Why', subtitle: 'Situational Awareness', desc: 'Monitoring is not surveillance. It is situational awareness: the system tells you it is hurting before the user files a ticket. Detect early, diagnose fast, demonstrate SLA compliance with hard data.', syntax: 'Detect -> Diagnose -> Demonstrate', term: [{raw: '<span class="out" style="color:#E8A07A">Why Monitor?</span><br><br><span class="out">1. Detect: Catch a memory leak at 03:00 before the 09:00 outage.</span><br><span class="out">2. Diagnose: Correlate CPU, disk, and network to pinpoint root cause.</span><br><span class="out">3. Demonstrate: Prove SLA compliance with graphs, not vibes.</span><br><br><span class="out" style="color:#E8A07A">The Ops Mindset</span><br><span class="out">Hope is not a strategy. Logs are not monitoring.</span><br><span class="out">A dashboard nobody looks at is worthless.</span>'}], explain: '<strong>Explanation:</strong> A ticket from a user is the most expensive form of monitoring. By the time they complain, the damage is done. We instrument the system to whisper to us before it screams.' },
    
    // 2. Observability Pillars
    { type: 'lesson', category: 'Monitoring', title: 'Observability: Pillars', subtitle: 'Metrics, Logs, Traces', desc: 'Observability asks "why is it broken, and what else is affected?" It rests on three pillars: metrics (cheap, time-series), logs (expensive, contextual), and traces (request-scoped journeys).', syntax: 'Metrics: numeric, sampled\nLogs: discrete events\nTraces: request journeys', term: [{raw: '<span class="out" style="color:#E8A07A">The Three Pillars</span><br><br><span class="out">1. Metrics: Numeric, time-series. Cheap. CPU%, mem_used, disk_io.</span><br><span class="out">2. Logs: Discrete events with timestamps. journalctl, auth.log.</span><br><span class="out">3. Traces: Request-scoped journeys. OpenTelemetry, Jaeger.</span><br><br><span class="out" style="color:#E8A07A">Topic 15 Scope</span><br><span class="out">We focus on Metrics (Prometheus).</span><br><span class="out">Logs were covered in Module 2 (journalctl, Event Viewer).</span>'}], explain: '<strong>Explanation:</strong> Metrics answer "is it broken?" Logs answer "why?" Traces answer "where in the call chain?" For a single Ubuntu host, metrics are sufficient. Traces become essential in microservices.' },
    
    // 3. Stack Overview
    { type: 'lesson', category: 'Stack', title: 'Stack Overview: The 3', subtitle: 'Prometheus + Exporter + Grafana', desc: 'Three components, one job: visibility. Node Exporter runs on the host and exposes /metrics. Prometheus pulls and stores in a TSDB. Grafana queries Prometheus and renders dashboards.', syntax: 'Node Exporter -> Prometheus -> Grafana\n:9100           :9090          :3000', term: [{raw: '<span class="out" style="color:#E8A07A">Data Flow</span><br><br><span class="out">1. Node Exporter (port 9100) exposes /metrics endpoint.</span><br><span class="out">2. Prometheus (port 9090) scrapes /metrics every 15s.</span><br><span class="out">3. Prometheus stores samples in TSDB on local disk.</span><br><span class="out">4. Grafana (port 3000) queries Prometheus via PromQL.</span><br><span class="out">5. Grafana renders panels and evaluates alert rules.</span><br><br><span class="out" style="color:#E8A07A">Pull Model</span><br><span class="out">Prometheus pulls. Not push. Easier firewall reasoning.</span>'}], explain: '<strong>Explanation:</strong> The pull model means Prometheus decides when to fetch. If a target is down, Prometheus marks it as "up == 0". With push, a silent agent could die and you would never know.' },
    
    // 4. Prometheus Intro
    { type: 'lesson', category: 'Prometheus', title: 'Prometheus: Intro', subtitle: 'The TSDB that pulls', desc: 'Prometheus is a time-series database built at SoundCloud (2012), graduated by CNCF in 2016 as the second project after Kubernetes. It pulls metrics from targets, stores them locally, and evaluates alert rules.', syntax: 'Pull -> Store (TSDB) -> Query (PromQL) -> Alert', term: [{raw: '<span class="out" style="color:#E8A07A">Prometheus Core</span><br><br><span class="out">1. Retrieval: Scrapes targets at scrape_interval (default 15s).</span><br><span class="out">2. TSDB: Local on-disk storage, ~1.3 bytes per sample.</span><br><span class="out">3. PromQL: Purpose-built query language.</span><br><span class="out">4. HTTP: Query API for Grafana and ad-hoc use.</span><br><span class="out">5. Alerting: Rules evaluated by server, routed by Alertmanager.</span><br><br><span class="out" style="color:#E8A07A">Origin</span><br><span class="out">SoundCloud, 2012. CNCF graduated 2016.</span>'}], explain: '<strong>Explanation:</strong> Prometheus does not install software. It only reads metrics. It is not a log aggregator. It is a numeric time-series database with a query language and an alerting engine bolted on.' },
    
    // 5. Prometheus Architecture
    { type: 'lesson', category: 'Prometheus', title: 'Prometheus: Architecture', subtitle: 'Components', desc: 'The Prometheus server sits at the center. It scrapes exporters and instrumented apps, stores samples in a TSDB, evaluates recording and alerting rules, and exposes an HTTP API for Grafana.', syntax: 'Exporters -> Prometheus Server -> Grafana\n            (TSDB + Rules)', term: [{raw: '<span class="out" style="color:#E8A07A">Architecture</span><br><br><span class="out">1. Pushgateway: For short-lived jobs that cannot be scraped.</span><br><span class="out">2. Exporters: Node Exporter, mysqld_exporter, blackbox_exporter.</span><br><span class="out">3. Prometheus Server: TSDB + PromQL + Rules engine.</span><br><span class="out">4. Alertmanager: Routes, dedupes, silences alerts.</span><br><span class="out">5. Grafana: Visualization + dashboard + alerting UI.</span><br><br><span class="out" style="color:#E8A07A">Service Discovery</span><br><span class="out">Static configs for lab. File, DNS, or cloud for production.</span>'}], explain: '<strong>Explanation:</strong> In our lab, all three components run on one Ubuntu host. In production, Prometheus runs on a dedicated server, Node Exporter on every monitored host, and Grafana behind a reverse proxy with TLS.' },
    
    // 6. Data Model
    { type: 'lesson', category: 'Prometheus', title: 'Data Model: Metrics', subtitle: 'Name + Labels + Samples', desc: 'Every metric is a name plus a set of labels plus a numeric sample with a timestamp. Labels enable slicing: filter by instance, mode, device, mountpoint, or any dimension you exposed.', syntax: 'metric_name{label="value"} 1234 1700000000', term: [{raw: '<span class="out" style="color:#E8A07A">Metric Anatomy</span><br><br><span class="out">node_cpu_seconds_total{</span><br><span class="out">  cpu="0",</span><br><span class="out">  mode="idle",</span><br><span class="out">  instance="localhost:9100",</span><br><span class="out">  job="node"</span><br><span class="out">} 1234567.89 1700000000</span><br><br><span class="out" style="color:#E8A07A">Four Metric Types</span><br><span class="out">counter: only goes up (bytes sent)</span><br><span class="out">gauge: goes up and down (mem free)</span><br><span class="out">histogram: bucketed observations</span><br><span class="out">summary: precomputed quantiles</span>'}], explain: '<strong>Explanation:</strong> A counter that only grows is useless until you compute its rate of change. That is what <code>rate()</code> does. Gauges (like free memory) can be read directly. Histograms and summaries are for latency distributions.' },
    
    // 7. PromQL Basics
    { type: 'lesson', category: 'Prometheus', title: 'PromQL: Basics', subtitle: 'Query Language', desc: 'PromQL slices time-series by labels and time windows. An instant vector returns the current value. A range vector returns samples over a time window like [5m]. Aggregations like avg by(instance) group results.', syntax: 'avg by (instance) (rate(metric[5m]))', term: [{raw: '<span class="out" style="color:#E8A07A">PromQL Building Blocks</span><br><br><span class="out"># instant vector - current value</span><br><span class="out">node_memory_MemAvailable_bytes</span><br><br><span class="out"># filter by label</span><br><span class="out">node_cpu_seconds_total{mode="idle"}</span><br><br><span class="out"># range vector - last 5 minutes</span><br><span class="out">node_memory_MemAvailable_bytes[5m]</span><br><br><span class="out"># aggregation</span><br><span class="out">avg by(instance)(rate(node_cpu_seconds_total[5m]))</span><br><br><span class="out"># arithmetic</span><br><span class="out">100 * (1 - avg(idle_rate))</span>'}], explain: '<strong>Explanation:</strong> PromQL reads left to right. <code>rate(...[5m])</code> computes per-second increase over 5 minutes. <code>avg by(instance)</code> groups by host. Arithmetic operators combine series. The result is what Grafana plots.' },
    
    // 8. Node Exporter
    { type: 'lesson', category: 'Exporter', title: 'Node Exporter', subtitle: 'Host metrics agent', desc: 'Node Exporter is a single Go binary that exposes hardware and OS metrics on port 9100. It is read-only, has no dependencies, and is the standard way to instrument a Linux host for Prometheus.', syntax: 'Listens on :9100/metrics\nRead-only. Safe to run anywhere.', term: [{raw: '<span class="out" style="color:#E8A07A">What Node Exporter Exposes</span><br><br><span class="out">1. CPU: node_cpu_seconds_total (per mode)</span><br><span class="out">2. Memory: node_memory_MemAvailable_bytes</span><br><span class="out">3. Disk: node_filesystem_avail_bytes (per mount)</span><br><span class="out">4. Network: node_network_receive_bytes_total</span><br><span class="out">5. Uptime: node_boot_time_seconds</span><br><span class="out">6. Load: node_load1, node_load5, node_load15</span><br><br><span class="out" style="color:#E8A07A">Test Endpoint</span><br><span class="cmd">> curl http://localhost:9100/metrics | head</span>'}], explain: '<strong>Explanation:</strong> Node Exporter never modifies the system. It reads /proc and /sys and exposes them as Prometheus metrics. Safe to install on production. Default port 9100, plain HTTP, no auth.' },
    
    // 9. Grafana Intro
    { type: 'lesson', category: 'Grafana', title: 'Grafana: Intro', subtitle: 'Visualization layer', desc: 'Grafana is a multi-datasource visualization tool. It queries Prometheus (and Loki, InfluxDB, PostgreSQL, Azure Monitor) and renders dashboards, stat panels, gauges, and alerts. Default port 3000.', syntax: 'Multi-datasource. Default port 3000.\nDefault login: admin/admin', term: [{raw: '<span class="out" style="color:#E8A07A">Grafana Strengths</span><br><br><span class="out">1. Multi-datasource: Prometheus, Loki, InfluxDB, PostgreSQL.</span><br><span class="out">2. Panel types: graph, stat, gauge, table, heatmap, geomap.</span><br><span class="out">3. Dashboards: composable, templated, shareable as JSON.</span><br><span class="out">4. Alerting: Grafana-managed or Prometheus rules.</span><br><span class="out">5. RBAC: Enterprise adds SSO, audit, reporting.</span><br><br><span class="out" style="color:#E8A07A">Why not Prometheus UI?</span><br><span class="out">Prometheus UI is for ad-hoc debugging. Grafana is for ops.</span>'}], explain: '<strong>Explanation:</strong> Prometheus has a basic UI good for testing PromQL. Grafana is purpose-built for operations: dashboards, annotations, alerting channels, role-based access, snapshots. We use OSS edition — fully featured for our lab.' },
    
    // 10. Dashboard Anatomy
    { type: 'lesson', category: 'Grafana', title: 'Dashboard: Anatomy', subtitle: 'Hierarchy', desc: 'A Grafana dashboard is a container for rows. A row contains panels. A panel has a datasource, one or more queries, a visualization type, thresholds, and overrides. Variables parameterize the whole dashboard.', syntax: 'Dashboard -> Row -> Panel -> Query', term: [{raw: '<span class="out" style="color:#E8A07A">Dashboard Hierarchy</span><br><br><span class="out">L1 Dashboard: name, tags, time range, refresh, variables.</span><br><span class="out">L2 Row: visual grouping, collapsible.</span><br><span class="out">L3 Panel: datasource + queries + viz type + thresholds.</span><br><span class="out">L4 Query: PromQL expression returning instant or range vector.</span><br><br><span class="out" style="color:#E8A07A">Panel Anatomy</span><br><span class="out">A Title: "CPU Utilization %"</span><br><span class="out">B Query: PromQL expression</span><br><span class="out">C Visualization: time series / stat / gauge</span><br><span class="out">D Thresholds: Warn 70% / Crit 85%</span><br><span class="out">E Legend: per-series labels</span>'}], explain: '<strong>Explanation:</strong> A panel can have multiple queries stacked or overlaid. Thresholds color the panel when values cross limits. Variables (like $instance) let you switch the dashboard between hosts without editing queries.' },
    
    // 11. Install Prometheus
    { type: 'lesson', category: 'Installation', title: 'Install: Prometheus', subtitle: 'Binary + systemd', desc: 'Prometheus is a single Go binary. Download from GitHub releases, create a dedicated user, set up directories, write a minimal prometheus.yml, and create a systemd service unit.', syntax: 'wget -> tar -> useradd -> systemd unit -> enable', term: [{raw: '<span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo useradd --no-create-home --shell /usr/sbin/nologin prometheus</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo mkdir -p /etc/prometheus /var/lib/prometheus</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">wget https://github.com/prometheus/prometheus/releases/download/v2.55.0/prometheus-2.55.0.linux-amd64.tar.gz</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">tar xvf prometheus-2.55.0.linux-amd64.tar.gz</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">cd prometheus-2.55.0.linux-amd64</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~/prometheus-2.55.0</span>$</span> <span class="cmd">sudo mv prometheus promtool /usr/local/bin/</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~/prometheus-2.55.0</span>$</span> <span class="cmd">sudo mv consoles console_libraries /etc/prometheus/</span>'}], explain: '<strong>Explanation:</strong> We create a non-login user so Prometheus runs with least privilege. The binary goes to /usr/local/bin. Configs live in /etc/prometheus. The TSDB data lives in /var/lib/prometheus.' },
    
    // 12. Prometheus systemd
    { type: 'lesson', category: 'Installation', title: 'Prometheus: systemd', subtitle: 'Service unit', desc: 'Create /etc/systemd/system/prometheus.service with the Prometheus user, config file path, storage path, and listen address. Then daemon-reload, enable, and start.', syntax: '[Service] User=prometheus ExecStart=/usr/local/bin/prometheus --config.file=...', term: [{editor: "/etc/systemd/system/prometheus.service", code: '[Unit]\nDescription=Prometheus\nWants=network-online.target\nAfter=network-online.target\n\n[Service]\nUser=prometheus\nGroup=prometheus\nType=simple\nExecStart=/usr/local/bin/prometheus \\\n  --config.file=/etc/prometheus/prometheus.yml \\\n  --storage.tsdb.path=/var/lib/prometheus \\\n  --web.listen-address=0.0.0.0:9090\n\n[Install]\nWantedBy=multi-user.target'}], explain: '<strong>Explanation:</strong> systemd ensures Prometheus starts on boot and restarts on crash. After editing the service file, run <code>sudo systemctl daemon-reload</code> then <code>sudo systemctl enable --now prometheus</code>. Verify with <code>systemctl status prometheus</code>.' },
    
    // 13. prometheus.yml
    { type: 'lesson', category: 'Configuration', title: 'prometheus.yml', subtitle: 'Scrape config', desc: 'The prometheus.yml file defines the global scrape interval, evaluation interval, and the list of scrape_configs (jobs). Each job has a name and one or more targets.', syntax: 'global: scrape_interval: 15s\nscrape_configs: - job_name: ...', term: [{editor: "/etc/prometheus/prometheus.yml", code: 'global:\n  scrape_interval:     15s\n  evaluation_interval: 15s\n\nscrape_configs:\n  - job_name: "prometheus"\n    static_configs:\n      - targets: ["localhost:9090"]\n\n  - job_name: "node"\n    static_configs:\n      - targets: ["localhost:9100"]'}], explain: '<strong>Explanation:</strong> Prometheus scrapes itself (job "prometheus") to track its own health. The "node" job scrapes Node Exporter on port 9100. To add more hosts, append their IPs to the targets list. After editing, run <code>sudo systemctl reload prometheus</code>.' },
    
    // 14. Install Node Exporter
    { type: 'lesson', category: 'Installation', title: 'Install: Node Exporter', subtitle: 'Binary + systemd', desc: 'Download the Node Exporter binary from GitHub releases, create a dedicated user, and create a systemd service unit. Verify by curling /metrics on port 9100.', syntax: 'wget -> tar -> useradd -> systemd unit', term: [{raw: '<span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">wget https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">tar xvf node_exporter-1.8.2.linux-amd64.tar.gz</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo mv node_exporter-1.8.2.linux-amd64/node_exporter /usr/local/bin/</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo useradd --no-create-home --shell /usr/sbin/nologin node_exporter</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl enable --now node_exporter</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">curl http://localhost:9100/metrics | head</span><br><span class="out"># HELP node_cpu_seconds_total Seconds the CPUs spent in each mode.</span><br><span class="out"># TYPE node_cpu_seconds_total counter</span><br><span class="out">node_cpu_seconds_total{cpu="0",mode="idle"} 12345.67</span>'}], explain: '<strong>Explanation:</strong> Node Exporter is even simpler than Prometheus. The systemd unit has no flags — defaults are sensible. Verify the endpoint responds with curl. Then check <code>http://server-ip:9090/targets</code> in Prometheus UI to confirm the scrape is healthy.' },
    
    // 15. Install Grafana
    { type: 'lesson', category: 'Installation', title: 'Install: Grafana', subtitle: 'APT repository', desc: 'Add the official Grafana APT repository, install the package, and enable the systemd service. Default login is admin/admin. Change the password on first login.', syntax: 'add GPG key -> add repo -> apt install -> enable', term: [{raw: '<span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo mkdir -p /etc/apt/keyrings/</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">wget -q -O /etc/apt/keyrings/grafana.key https://apt.grafana.com/gpg.key</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">echo "deb [signed-by=/etc/apt/keyrings/grafana.key] https://apt.grafana.com stable main" | sudo tee /etc/apt/sources.list.d/grafana.list</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt update && sudo apt install -y grafana</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl enable --now grafana-server</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl status grafana-server</span><br><span class="out">Active: active (running) since...</span>'}], explain: '<strong>Explanation:</strong> Using the APT repo means Grafana updates with <code>apt upgrade</code>. Browse to <code>http://server-ip:3000</code>. Default credentials admin/admin. You will be forced to change the password. For production, put Grafana behind nginx with TLS.' },
    
    // 16. Firewall Config
    { type: 'lesson', category: 'Installation', title: 'Firewall: UFW Rules', subtitle: 'Open ports', desc: 'Open ports 3000 (Grafana), 9090 (Prometheus), and 9100 (Node Exporter) in UFW. In production, restrict these to a management subnet or VPN — never expose to the public internet.', syntax: 'sudo ufw allow 3000/tcp', term: [{raw: '<span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw allow 3000/tcp</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw allow 9090/tcp</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw allow 9100/tcp</span><br><span class="prompt"><span class="user">ajsacay@dorsu</span>:<span class="path">~</span>$</span> <span class="cmd">sudo ufw status</span><br><span class="out">Status: active</span><br><span class="out">To                Action   From</span><br><span class="out">3000/tcp          ALLOW    Anywhere</span><br><span class="out">9090/tcp          ALLOW    Anywhere</span><br><span class="out">9100/tcp          ALLOW    Anywhere</span><br><br><span class="out" style="color:#E8A07A">Production Note</span><br><span class="out">Never expose 3000/9090/9100 to the internet. Use a reverse proxy</span><br><span class="out">with TLS, or restrict to a VPN or SSH tunnel.</span>'}], explain: '<strong>Explanation:</strong> For the lab, opening to Anywhere is fine because the VM is on a private VirtualBox network. In production, restrict with <code>sudo ufw allow from 10.0.0.0/24 to any port 3000</code>. Grafana supports OAuth and SSO for access control.' },
    
    // 17. Grafana Datasource
    { type: 'lesson', category: 'Grafana', title: 'Grafana: Datasource', subtitle: 'Wire to Prometheus', desc: 'In Grafana: Connections -> Data Sources -> Add -> Prometheus. Set URL to http://localhost:9090. Leave Auth empty for lab. Save and Test. Verify with the Explore panel.', syntax: 'Connections -> Data Sources -> Prometheus -> Save & Test', term: [{raw: '<span class="out" style="color:#E8A07A">Datasource Setup Steps</span><br><br><span class="out">1. Hamburger menu -> Connections -> Data Sources.</span><br><span class="out">2. Click "Add data source".</span><br><span class="out">3. Choose "Prometheus" from the list.</span><br><span class="out">4. URL: http://localhost:9090</span><br><span class="out">5. Auth: leave empty (lab only).</span><br><span class="out">6. Click "Save & Test".</span><br><span class="out">7. Green banner: "Data source is working".</span><br><br><span class="out" style="color:#E8A07A">Test Query in Explore</span><br><span class="cmd">> up</span><br><span class="out">Should return {instance="localhost:9090", job="prometheus"} value=1</span>'}], explain: '<strong>Explanation:</strong> If <code>up == 1</code>, the scrape is healthy. If <code>up == 0</code>, the target is down or unreachable. Check firewall, check the service is running, check the URL. The Explore panel is your playground for testing PromQL before building panels.' },
    
    // 18. Panel 1: CPU
    { type: 'lesson', category: 'Dashboard', title: 'Panel 1: CPU %', subtitle: 'Utilization', desc: 'CPU utilization = 100 * (1 - idle rate). Use <code>rate(node_cpu_seconds_total{mode="idle"}[5m])</code> to compute per-second idle time, average by instance, invert, and multiply by 100.', syntax: '100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])))', term: [{raw: '<span class="out" style="color:#E8A07A">Panel Settings</span><br><br><span class="out">Visualization: Time series</span><br><span class="out">Unit: Percent (0-100)</span><br><span class="out">Decimals: 2</span><br><span class="out">Thresholds: Warning 70%, Critical 85%</span><br><span class="out">Legend: {{instance}}</span><br><span class="out">Fill: 10% opacity</span><br><br><span class="out" style="color:#E8A07A">Why rate(...[5m])?</span><br><br><span class="out">Counters only grow. rate() computes the per-second increase</span><br><span class="out">over a 5-minute window. This converts a counter into a</span><br><span class="out">meaningful per-second value (like CPU % used).</span>'}], explain: '<strong>Explanation:</strong> The CPU metric is a counter of seconds spent in each mode (idle, user, system, iowait). We isolate idle, compute its rate, average across cores, invert (1 - idle = busy), and multiply by 100 for a percentage.' },
    
    // 19. Panel 2: Memory
    { type: 'lesson', category: 'Dashboard', title: 'Panel 2: Memory %', subtitle: 'RAM usage', desc: 'Memory usage % = (1 - MemAvailable / MemTotal) * 100. Use MemAvailable (not MemFree) because Linux aggressively caches files in RAM — "free" looks low but is actually healthy.', syntax: '100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))', term: [{raw: '<span class="out" style="color:#E8A07A">Panel Settings</span><br><br><span class="out">Visualization: Gauge (single value)</span><br><span class="out">Unit: Percent (0-100)</span><br><span class="out">Thresholds: Warning 75%, Critical 90%</span><br><span class="out">Color mode: background</span><br><br><span class="out" style="color:#E8A07A">Why MemAvailable, not MemFree?</span><br><br><span class="out">Linux caches files in RAM to speed up reads.</span><br><span class="out">"Free" memory looks low but is actually healthy.</span><br><span class="out">MemAvailable is the kernel estimate of memory truly</span><br><span class="out">available for new allocations, accounting for</span><br><span class="out">reclaimable cache.</span>'}], explain: '<strong>Explanation:</strong> If you plot MemFree, you will panic every time you see 100MB free. Use MemAvailable — it subtracts reclaimable cache. A healthy Ubuntu server might show 200MB free but 4GB available.' },
    
    // 20. Panel 3: Disk
    { type: 'lesson', category: 'Dashboard', title: 'Panel 3: Disk %', subtitle: 'Filesystem usage', desc: 'Disk usage per mount = (1 - avail / size) * 100. Filter out pseudo-filesystems (tmpfs, overlay, squashfs) with <code>fstype!~"tmpfs|overlay|squashfs"</code> to avoid phantom entries.', syntax: '100 * (1 - (node_filesystem_avail_bytes{fstype!~"..."} / node_filesystem_size_bytes{fstype!~"..."}))', term: [{raw: '<span class="out" style="color:#E8A07A">Panel Settings</span><br><br><span class="out">Visualization: Bar gauge (per mount)</span><br><span class="out">Unit: Percent (0-100)</span><br><span class="out">Thresholds: Warning 80%, Critical 90%</span><br><span class="out">Orientation: horizontal</span><br><span class="out">Display mode: gradient</span><br><br><span class="out" style="color:#E8A07A">Filter Pseudo-filesystems</span><br><br><span class="out">fstype!~"tmpfs|overlay|squashfs"</span><br><br><span class="out">Without this filter, Grafana shows phantom 0% or 100%</span><br><span class="out">entries for tmpfs, overlayfs, and snap loop mounts.</span><br><span class="out">These have no real capacity and clutter the panel.</span>'}], explain: '<strong>Explanation:</strong> The filesystem metric is a gauge with labels for mountpoint and device. The regex filter excludes pseudo-filesystems. The bar gauge is perfect for showing multiple mounts side by side.' },
    
    // 21. Panel 4: Uptime
    { type: 'lesson', category: 'Dashboard', title: 'Panel 4: Uptime', subtitle: 'System uptime', desc: 'Uptime = current time minus boot time. Use <code>time() - node_boot_time_seconds</code>. Grafana can format the seconds into a human-readable duration (days, hours, minutes).', syntax: 'time() - node_boot_time_seconds', term: [{raw: '<span class="out" style="color:#E8A07A">Panel Settings</span><br><br><span class="out">Visualization: Stat</span><br><span class="out">Unit: Time -> seconds (d/h/m/s)</span><br><span class="out">Color mode: value</span><br><span class="out">Thresholds: none, or "good" > 86400 (1 day)</span><br><span class="out">Decimals: 0</span><br><span class="out">Graph mode: none</span><br><br><span class="out" style="color:#E8A07A">What This Tells You</span><br><br><span class="out">A sudden reset to 0 = unexpected reboot.</span><br><span class="out">Track over weeks: servers should never silently reboot.</span><br><span class="out">A bouncing uptime graph is the loudest silent alarm.</span><br><br><span class="out" style="color:#E8A07A">Bonus</span><br><span class="out">Track node_uname_info to display hostname + kernel version.</span>'}], explain: '<strong>Explanation:</strong> <code>time()</code> is a PromQL function returning the current Unix timestamp. Subtracting the boot time gives seconds since boot. Grafana formats this as "3d 4h 12m". A reboot resets the value to 0 — investigate immediately.' },
    
    // 22. Panel 5: Network
    { type: 'lesson', category: 'Dashboard', title: 'Panel 5: Network', subtitle: 'Throughput per NIC', desc: 'Network throughput per NIC = rate of receive and transmit bytes. Exclude loopback (lo), Docker bridges (veth*), and docker* interfaces to keep the panel focused on real NICs.', syntax: 'rate(node_network_receive_bytes_total{device!~"lo|veth.*|docker.*"}[5m])', term: [{raw: '<span class="out" style="color:#E8A07A">Panel Settings</span><br><br><span class="out">Visualization: Time series</span><br><span class="out">Unit: bytes/sec (SI)</span><br><span class="out">Legend: {{device}} {{direction}}</span><br><span class="out">Fill: 5% opacity</span><br><span class="out">Connect nulls: off</span><br><br><span class="out" style="color:#E8A07A">Why Exclude Interfaces?</span><br><br><span class="out">lo: loopback, internal traffic only.</span><br><span class="out">veth*: Docker virtual bridges.</span><br><span class="out">docker*: Docker networking.</span><br><br><span class="out">Without filtering, the panel drowns in virtual NICs and</span><br><span class="out">the real traffic on eth0 / ens18 is invisible.</span>'}], explain: '<strong>Explanation:</strong> Add two queries to the same panel: one for receive (rx), one for transmit (tx). Stack them or plot separately. The <code>device!~"lo|veth.*|docker.*"</code> regex excludes virtual interfaces. Real NICs are usually named eth0, ens18, or enp0s3.' },
    
    // 23. Dashboard Layout
    { type: 'lesson', category: 'Dashboard', title: 'Dashboard: Layout', subtitle: '5 panels + refresh', desc: 'The recommended layout: three stat panels (uptime, memory %, disk %) on the top row, two time-series graphs (CPU %, network) on the bottom. Set auto-refresh to 5s and time range to "last 1 hour".', syntax: 'Top: 3 stat panels | Bottom: 2 graphs\nRefresh: 5s', term: [{raw: '<span class="out" style="color:#E8A07A">Recommended Layout</span><br><br><span class="out">Row 1 (stat panels):</span><br><span class="out">  [ Uptime ]  [ Memory % ]  [ Disk % ]</span><br><br><span class="out">Row 2 (time series):</span><br><span class="out">  [ CPU Utilization % ]</span><br><span class="out">  [ Network I/O ]</span><br><br><span class="out" style="color:#E8A07A">Dashboard Settings</span><br><br><span class="out">Name: "ITP 141 - Host Health"</span><br><span class="out">Refresh: Every 5 seconds</span><br><span class="out">Time range: Last 1 hour</span><br><span class="out">Tags: itp141, monitoring</span><br><span class="out">Variables: $instance (for multi-host)</span><br><br><span class="out" style="color:#E8A07A">Lab Deliverable</span><br><span class="out">Screenshot of working 5-panel dashboard is required.</span>'}], explain: '<strong>Explanation:</strong> Stat panels give you a glance — are we red or green? Time series graphs give you trend — are we getting worse? Five panels on one screen, refreshed every 5 seconds, gives you a live pulse of the host. Export the dashboard as JSON for backup.' },
    
    // 24. Alerting Intro
    { type: 'lesson', category: 'Alerting', title: 'Alerting: Intro', subtitle: 'Metrics become action', desc: 'A dashboard nobody looks at is worthless. Alerts transform silent graphs into paged humans. Three parts: threshold (numeric boundary), duration (avoid flapping), and routing (who gets paged).', syntax: 'Threshold -> Duration -> Route', term: [{raw: '<span class="out" style="color:#E8A07A">Alert Lifecycle</span><br><br><span class="out">A Pending: Condition met, duration not yet elapsed.</span><br><span class="out">B Firing: Condition met + duration elapsed -> routed.</span><br><span class="out">C Resolved: Condition clears -> resolution notification sent.</span><br><br><span class="out" style="color:#E8A07A">Three Pillars of an Alert</span><br><br><span class="out">1. Threshold: Define a numeric boundary. "Disk > 85%".</span><br><span class="out">2. Duration: "For 5 minutes." Avoids flapping.</span><br><span class="out">3. Routing: Who gets paged? Email, Slack, PagerDuty, webhook.</span><br><br><span class="out" style="color:#E8A07A">Golden Rule</span><br><span class="out">If a page does not require human action, it is noise.</span>'}], explain: '<strong>Explanation:</strong> A 1-second CPU spike is not an incident. A 5-minute sustained CPU spike probably is. The <code>for:</code> clause in a Prometheus alert rule enforces duration. Without it, every transient blip pages someone — and they learn to ignore alerts.' },
    
    // 25. Alert Rules YAML
    { type: 'lesson', category: 'Alerting', title: 'Alert Rules: YAML', subtitle: 'rules.yml', desc: 'Prometheus alert rules live in a separate YAML file referenced from prometheus.yml via <code>rule_files:</code>. Each rule has an alert name, an expression, a duration, labels, and annotations.', syntax: 'groups: - name: ... rules: - alert: ...', term: [{editor: "/etc/prometheus/rules.yml", code: 'groups:\n  - name: node_alerts\n    rules:\n      - alert: HighCpuUtilization\n        expr: |\n          100 - (avg by (instance) (\n            rate(node_cpu_seconds_total{\n              mode="idle"\n            }[5m]) * 100\n          )) > 80\n        for: 5m\n        labels:\n          severity: warning\n        annotations:\n          summary: "CPU > 80% on {{ $labels.instance }}"\n          description: "CPU has been above 80% for 5 min."'}], explain: '<strong>Explanation:</strong> The <code>expr</code> is a PromQL expression that must return true (non-zero) for the alert to fire. <code>for: 5m</code> means the condition must persist for 5 minutes. Labels are used for routing. Annotations are templated messages shown in notifications.' },
    
    // 26. Alert Disk Rule
    { type: 'lesson', category: 'Alerting', title: 'Alert: Disk > 85%', subtitle: 'Critical rule', desc: 'The second required alert rule: disk usage above 85% for 10 minutes. Severity critical. The annotation includes the mountpoint so the operator knows which filesystem is filling up.', syntax: 'expr: ... > 85 for: 10m severity: critical', term: [{editor: "/etc/prometheus/rules.yml", code: '      - alert: HighDiskUtilization\n        expr: |\n          100 * (1 - (\n            node_filesystem_avail_bytes\n            {fstype!~"tmpfs|overlay"}\n            / node_filesystem_size_bytes\n            {fstype!~"tmpfs|overlay"}\n          )) > 85\n        for: 10m\n        labels:\n          severity: critical\n        annotations:\n          summary: "Disk > 85% on {{ $labels.instance }}"\n          description: "Mount {{ $labels.mountpoint }} is at {{ $value }}%."\n\n# After saving, reload Prometheus:\n# sudo systemctl reload prometheus\n# Verify at http://server-ip:9090/alerts'}], explain: '<strong>Explanation:</strong> The <code>{{ $labels.mountpoint }}</code> template variable is replaced at runtime with the actual mountpoint (e.g., "/" or "/var"). <code>{{ $value }}</code> shows the current value. This makes the notification actionable — you know which disk to clean.' },
    
    // 27. Alertmanager
    { type: 'lesson', category: 'Alerting', title: 'Alertmanager', subtitle: 'Routing & dedup', desc: 'Alertmanager receives firing alerts from Prometheus, deduplicates them, groups them, inhibits lower-severity alerts when higher-severity fire, and routes to receivers (email, Slack, PagerDuty, webhook).', syntax: 'Prometheus -> Alertmanager -> Receiver', term: [{raw: '<span class="out" style="color:#E8A07A">Alertmanager Features</span><br><br><span class="out">1. Deduplication: 50 instances firing -> 1 notification.</span><br><span class="out">2. Grouping: Bundle alerts by alertname + cluster.</span><br><span class="out">3. Inhibition: If datacenter is down, suppress host alerts.</span><br><span class="out">4. Silencing: Mute for a maintenance window.</span><br><span class="out">5. Receivers: email, Slack, PagerDuty, webhook, OpsGenie.</span><br><br><span class="out" style="color:#E8A07A">Severity Levels</span><br><br><span class="out">info: Informational, no action. Daily digest email.</span><br><span class="out">warning: Action needed soon (<4h). Slack #ops.</span><br><span class="out">critical: Action needed now. PagerDuty / SMS.</span>'}], explain: '<strong>Explanation:</strong> For the lab, Alertmanager is optional — Grafana has built-in alerting that can route directly to email or webhook. We mention Alertmanager for production awareness. In production, Alertmanager is mandatory for deduplication.' },
    
    // 28. Notification Channels
    { type: 'lesson', category: 'Alerting', title: 'Notifications', subtitle: 'Grafana channels', desc: 'In Grafana: Alerting -> Contact points -> Add. Choose type (Email, Slack, Webhook, Discord, Telegram). Configure destination. Test. Then create a Notification Policy to route alerts by label to the contact point.', syntax: 'Contact point -> Test -> Notification policy', term: [{raw: '<span class="out" style="color:#E8A07A">Slack Webhook (Simplest for Lab)</span><br><br><span class="out">1. In Slack: Apps -> Incoming Webhooks -> Add to Slack.</span><br><span class="out">2. Choose channel (e.g., #ops-alerts).</span><br><span class="out">3. Copy Webhook URL.</span><br><span class="out">4. In Grafana: Contact point type: Slack.</span><br><span class="out">5. URL: https://hooks.slack.com/services/T.../B.../...</span><br><span class="out">6. Channel: #ops-alerts</span><br><span class="out">7. Title: [{{ .Status }}] {{ .CommonLabels.alert }}</span><br><span class="out">8. Test -> verify message arrives in Slack.</span><br><br><span class="out" style="color:#E8A07A">Email (Requires Postfix or SMTP relay)</span><br><span class="out">Configure [smtp] in /etc/grafana/grafana.ini</span>'}], explain: '<strong>Explanation:</strong> Slack webhooks are free and instant. Email requires a working SMTP relay (Postfix or external like Gmail with an app password). For the lab, a webhook to a free service like Discord or ntfy.sh is also fine.' },
    
    // 29. Automation Intro
    { type: 'lesson', category: 'Automation', title: 'Automation: Intro', subtitle: 'Automate the boring', desc: 'Everything you do twice should be scripted. Everything you do once should be written down. Automate backups, deployment, patching, log rotation, and health checks. Do NOT automate DR failover or incident response.', syntax: 'Automate: backups, deploy, patch\nDocument: DR, incidents, first-setup', term: [{raw: '<span class="out" style="color:#E8A07A">What to Automate</span><br><br><span class="out">1. Backups: rsync + cron, log rotation (Topic 5)</span><br><span class="out">2. Deployment: deploy.sh with set -e, trap (Topic 9)</span><br><span class="out">3. Patching: unattended-upgrades, scheduled reboots</span><br><span class="out">4. Log rotation: logrotate.d configs</span><br><span class="out">5. Health checks: curl + jq + alert on JSON change</span><br><br><span class="out" style="color:#E8A07A">What NOT to Automate</span><br><br><span class="out">1. DR failover: too consequential, needs human judgment</span><br><span class="out">2. Security incident response: needs forensics</span><br><span class="out">3. First-time setup of a new service: manual, then automate</span><br><span class="out">4. Anything destructive without --dry-run first</span>'}], explain: '<strong>Explanation:</strong> Automate to reduce error, not to remove thought. A bad script run by cron at 3am is worse than a tired human at 3am. Always test scripts manually first, then schedule them. Always include <code>--dry-run</code> or <code>echo</code> before the real command.' },
    
    // 30. Self-heal Script
    { type: 'lesson', category: 'Automation', title: 'Automation: Self-heal', subtitle: 'Cron + script', desc: 'Monitor your monitoring. If Prometheus silently dies, alerts stop firing. A self-heal script checks the service, restarts it if down, and logs the event. Schedule with cron every 5 minutes.', syntax: 'cron: */5 * * * * /usr/local/bin/check-prom.sh', term: [{editor: "/usr/local/bin/check-prom.sh", code: '#!/usr/bin/env bash\nset -euo pipefail\n\nLOG=/var/log/prom-check.log\nTS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")\n\nif systemctl is-active --quiet prometheus; then\n  echo "$TS OK prometheus running" >> $LOG\n  exit 0\nelse\n  echo "$TS WARN prometheus down - restarting" >> $LOG\n  sudo systemctl restart prometheus\n  sleep 3\n  if systemctl is-active --quiet prometheus; then\n    echo "$TS OK restart succeeded" >> $LOG\n  else\n    echo "$TS CRIT restart failed - page oncall" >> $LOG\n  fi\nfi'}], explain: '<strong>Explanation:</strong> Idempotent — running it when Prometheus is healthy changes nothing. Idempotency is what separates automation from destruction. Schedule with <code>sudo crontab -e</code>: <code>*/5 * * * * /usr/local/bin/check-prom.sh</code>. Rotate the log weekly with logrotate.' },
    
    // 31. DR Intro
    { type: 'lesson', category: 'Disaster Recovery', title: 'DR: Intro', subtitle: 'Plan for the worst', desc: 'Disaster Recovery is rehearsed rehearsal. RPO (Recovery Point Objective) = how much data can you lose. RTO (Recovery Time Objective) = how long until service is restored. Topic 16 covers DR planning in depth.', syntax: 'RPO: data loss tolerance\nRTO: downtime tolerance', term: [{raw: '<span class="out" style="color:#E8A07A">DR Vocabulary</span><br><br><span class="out">RPO (Recovery Point Objective):</span><br><span class="out">  How much data can you afford to lose? Measured in time.</span><br><span class="out">  Example: "4 hours" = backups every 4 hours.</span><br><br><span class="out">RTO (Recovery Time Objective):</span><br><span class="out">  How long until service is restored? Measured in time.</span><br><span class="out">  Example: "2 hours" = failover completes within 2 hours.</span><br><br><span class="out">DR Plan:</span><br><span class="out">  The documented, rehearsed steps to fail over. Lives in a run book.</span><br><br><span class="out">Change Request:</span><br><span class="out">  ITIL process for safely modifying production.</span>'}], explain: '<strong>Explanation:</strong> RPO and RTO drive backup frequency and failover design. An RPO of 4 hours means you need backups every 4 hours. An RTO of 2 hours means you cannot restore from tape — you need a hot standby. Topic 16 covers VirtualBox snapshot restore and full DR planning.' },
    
    // 32. Run Book
    { type: 'lesson', category: 'Documentation', title: 'IT Run Book', subtitle: 'Operational manual', desc: 'An IT Run Book codifies operational knowledge. If you got hit by a bus, could we run this? Structure: service overview, architecture, SLA, owners, health checks, common incidents, backup/restore, post-incident review.', syntax: 'Run Book = contract between today & tomorrow', term: [{raw: '<span class="out" style="color:#E8A07A">Run Book Structure</span><br><br><span class="out">1. Service overview - what it does, who depends on it.</span><br><span class="out">2. Architecture diagram - components, data flow.</span><br><span class="out">3. Service hours & SLA - when is downtime acceptable.</span><br><span class="out">4. Owner & escalation - who, in what order.</span><br><span class="out">5. Health checks - URLs, commands, expected output.</span><br><span class="out">6. Common incidents - symptom -> diagnosis -> fix.</span><br><span class="out">7. Backup & restore - what, where, how often, verify.</span><br><span class="out">8. Post-incident review - template for post-mortem.</span>'}], explain: '<strong>Explanation:</strong> A run book is not documentation for the original author — it is documentation for the next engineer. Written on a calm day, read during an incident at 3am. Clarity over cleverness. Step-by-step over prose.' },
    
    // 33. Run Book Example
    { type: 'lesson', category: 'Documentation', title: 'Run Book: Example', subtitle: 'Prometheus service', desc: 'A sample run book entry for the Prometheus monitoring service: what it does, how to check health, and what to do when the dashboard shows no data.', syntax: 'Service: Prometheus on dorsu-mon-01', term: [{editor: "runbook-prometheus.md", code: '## Service Overview\nPrometheus scrapes Node Exporter on dorsu-mon-01\n(10.0.0.20) every 15s. Stores 15d of metrics locally.\n\n## Health Check\n  curl http://10.0.0.20:9090/-/healthy\n  -> expected: "Prometheus is Healthy."\n\n## Common Incident: Empty Dashboard\nSymptom: Grafana panels show "No data"\nDiagnosis:\n  1. Check prometheus.service status\n  2. Check /targets in Prometheus UI\n  3. Check node_exporter.service\nFix:\n  sudo systemctl restart node_exporter\n  sudo systemctl restart prometheus\n  Verify /-/healthy endpoint responds.\n\n## Escalation\n  1. On-call sysadmin (24/7)\n  2. Ar-Jay Sacay (course instructor)\n  3. IT Manager'}], explain: '<strong>Explanation:</strong> This is the lab deliverable for the run book. Written in Markdown so it can be versioned in Git alongside the Prometheus config. Every monitored service should have a run book entry. The "Common Incidents" section grows over time as the team learns.' },
    
    // 34. Change Request
    { type: 'lesson', category: 'Documentation', title: 'Change Request', subtitle: 'ITIL template', desc: 'Every change to production is a contract. The Change Request template captures: what changes, what could break, how to undo it, who approved it, and when it is scheduled. ITIL defines three change types.', syntax: 'CR-ID, type, risk, rollback, approver, schedule', term: [{editor: "change-request-template.md", code: 'CR-ID:        CR-2026-0142\nTitle:        Update Prometheus to v2.56.0\nRequester:    arjay.sacay@dorsu.edu.ph\nDate raised:  2026-11-12\n\nChange type:  [ ] Standard  [x] Normal  [ ] Emergency\nRisk:         Low\nImpact:       Monitoring unavailable ~5min during restart\n\nAffected services:\n  - Prometheus  (dorsu-mon-01)\n  - Grafana dashboards (read-only disruption)\n\nRollback plan:\n  1. sudo apt install prometheus=2.55.0-1\n  2. sudo systemctl restart prometheus\n  3. Verify /-/healthy endpoint\n\nApprover:     Dony Dongiapon (IT Manager)\nScheduled:    2026-11-15 22:00 PHT\nVerified by:  ___________________\nClosed:       ___________________'}], explain: '<strong>Explanation:</strong> The four questions every change must answer: What will change? What could break? How do we undo it? Who has approved it? Without these, a change is gambling. ITIL Standard changes are pre-approved (e.g., patching). Normal goes to a Change Advisory Board. Emergency is verbal approval during an outage.' },
    
    // 35. ITIL Change Types
    { type: 'lesson', category: 'Documentation', title: 'ITIL: Change Types', subtitle: 'Standard / Normal / Emergency', desc: 'ITIL defines three change types. Standard changes are pre-approved and repeatable. Normal changes require CAB approval. Emergency changes are for outages and require verbal approval from ECAB.', syntax: 'Standard: pre-approved\nNormal: CAB approval\nEmergency: verbal ECAB', term: [{raw: '<span class="out" style="color:#E8A07A">ITIL Change Types</span><br><br><span class="out">1. Standard Change:</span><br><span class="out">   Pre-approved, repeatable, low risk.</span><br><span class="out">   Example: applying security patches, restarting a service.</span><br><span class="out">   No approval needed (pre-authorized).</span><br><br><span class="out">2. Normal Change:</span><br><span class="out">   Planned, low to medium risk.</span><br><span class="out">   Requires Change Advisory Board (CAB) approval.</span><br><span class="out">   Example: upgrading Prometheus major version.</span><br><br><span class="out">3. Emergency Change:</span><br><span class="out">   Outage, security incident, critical fix.</span><br><span class="out">   Requires verbal approval from ECAB (Emergency CAB).</span><br><span class="out">   Documented retroactively.</span>'}], explain: '<strong>Explanation:</strong> The change type determines the approval process. Standard changes have a documented run book — anyone can execute them. Normal changes need a CR with rollback plan. Emergency changes happen during incidents — the priority is restoring service, paperwork follows.' },
    
    // 36. Draw.io DR Diagram
    { type: 'lesson', category: 'Documentation', title: 'Draw.io: DR Diagram', subtitle: 'Network diagram', desc: 'A labeled Draw.io IT infrastructure and DR network diagram is a Topic 16 deliverable. It shows: primary site, DR site, network links, failover paths, and component dependencies. Use clear icons and consistent colors.', syntax: 'Primary site -> WAN -> DR site\nFailover path: dashed red line', term: [{raw: '<span class="out" style="color:#E8A07A">DR Diagram Elements</span><br><br><span class="out">1. Primary Site: Production servers, network, storage.</span><br><span class="out">2. DR Site: Standby servers, replicated storage.</span><br><span class="out">3. Network Links: WAN, VPN, replication links.</span><br><span class="out">4. Failover Path: Dashed red line, labeled with RTO.</span><br><span class="out">5. Components: VMs, databases, load balancers, firewalls.</span><br><span class="out">6. Labels: IP addresses, hostnames, ports.</span><br><br><span class="out" style="color:#E8A07A">Draw.io Tips</span><br><br><span class="out">1. Use the "Network" shape library.</span><br><span class="out">2. Group related components in containers.</span><br><span class="out">3. Color: green = primary, blue = DR, red = failover.</span><br><span class="out">4. Export as PNG or SVG for the run book.</span>'}], explain: '<strong>Explanation:</strong> The DR diagram is a contract. It shows what fails over, in what order, and how long each step takes. Without it, the DR plan is prose that nobody reads. Draw.io is free and exports to multiple formats. The diagram lives in the run book.' },
    
    // 37. Topic Summary
    { type: 'lesson', category: 'Summary', title: 'Topic Summary', subtitle: 'Module 6 so far', desc: 'You have installed the Prometheus observability stack, built a five-panel dashboard, written alert rules, and produced operational documentation templates. This is the defensive perimeter against downtime.', syntax: 'Prometheus -> Grafana -> Alerts -> Run Book', term: [{raw: '<span class="out" style="color:#E8A07A">Topic 15 Checklist</span><br><br><span class="out">[x] Understood the three pillars of observability.</span><br><span class="out">[x] Installed Prometheus, Node Exporter, and Grafana.</span><br><span class="out">[x] Configured prometheus.yml scrape targets.</span><br><span class="out">[x] Wired Grafana datasource to Prometheus.</span><br><span class="out">[x] Built 5-panel dashboard (CPU, mem, disk, uptime, net).</span><br><span class="out">[x] Wrote alert rules for CPU > 80% and Disk > 85%.</span><br><span class="out">[x] Produced IT Run Book template.</span><br><span class="out">[x] Produced ITIL Change Request template.</span><br><br><span class="out" style="color:#E8A07A">Next: Topic 16</span><br><span class="out">DR planning, VirtualBox snapshot restore, Draw.io diagram.</span>'}], explain: '<strong>Explanation:</strong> A well-monitored system tells you it is sick. A well-documented system lets the next engineer cure it. A well-rehearsed DR plan lets you survive the cure failing. Topic 16 picks up with RPO/RTO targets and snapshot restore practice.' },

  // --- 4. CLOSING SLIDE ---
  {
    type: 'closing',
    header: 'MODULE 06 · TOPIC 15',
    tag: 'End of Topic 15',
    title: 'Monitor. <em>Alert.</em><br>Document.',
    quote: 'A well-monitored system tells you it is sick. A well-documented system lets the next engineer cure it. A well-rehearsed DR plan lets you survive the cure failing.',
    leftCardNum: '§ observability',
    leftCardTitle: 'Prometheus + Grafana',
    leftCardDesc: 'Prometheus scrapes Node Exporter metrics every 15 seconds and stores them in a time-series database. Grafana visualizes CPU, memory, disk, uptime, and network activity in a unified dashboard.',
    middleCardNum: '§ operations',
    middleCardTitle: 'Alerts & Run Books',
    middleCardDesc: 'CPU and disk threshold alerts turn monitoring data into actionable notifications. Run Books document health checks, troubleshooting steps, escalation paths, and service recovery procedures.',
    rightCardNum: '§ automation',
    rightCardTitle: 'Automation & ITIL',
    rightCardDesc: 'Bash scripts and cron automate routine checks, while ITIL Change Requests document risks, approvals, and rollback plans. RPO, RTO, and disaster recovery diagrams support operational resilience.'
  }
];