const slideConfigs = [
  // --- 1. COVER SLIDE ---
  {
    type: 'cover',
    moduleTitle: 'MODULE 06 · TOPIC 16',
    topicNum: '16',
    topicTag: 'T16',
    title: 'DR Planning,<br>Snapshot Restore & <em>IT Docs</em>',
    subtitle: 'Recovering from failure: defining RPO/RTO, executing VirtualBox and Azure snapshot restores, building DR network diagrams, and managing ITIL change requests.',
    graphicText: 'Define <em>RPO/RTO</em><br>Restore <em>Snapshots</em><br>Document.',
    miniObjectives: [
      'RPO / RTO & VirtualBox Snapshot Restore',
      'Draw.io DR Network Diagram',
      'IT Project Proposal & ITIL Change Management',
      'Lab Exercise 8 Deliverables'
    ]
  },

  // --- 2. OBJECTIVES SLIDE ---
  {
    type: 'objectives',
    header: 'MODULE 06 · TOPIC 16',
    kicker: 'ITP 141 · M6 · T16',
    desc: 'A system without a recovery plan is a liability. You will learn to define acceptable data loss, perform point-in-time restores, and diagram the entire failover process.',
    lede: 'Hope is not a strategy. Rehearsed recovery is.',
    list: [
      'Define RPO (Recovery Point Objective) and RTO (Recovery Time Objective).',
      'Design a disaster recovery plan with an RPO of 4 hours or less and an RTO of 2 hours or less.',
      'Identify and document the five required failover steps in a disaster recovery scenario.',
      'Perform a VirtualBox snapshot restore and verify service recovery within the defined RTO.',
      'Understand Azure VM snapshot restoration workflows for cloud infrastructure.',
      'Create a labeled Draw.io IT infrastructure and disaster recovery network diagram.',
      'Structure an IT Project Proposal for disaster recovery infrastructure investment.',
      'Apply ITIL Change Management principles to disaster recovery scenarios.'
    ]
  },

  // --- 3. LESSON SLIDES ---
    // 1. DR Overview
    { type: 'lesson', category: 'DR Planning', title: 'DR Overview: Why', subtitle: 'Plan for the worst', desc: 'Disaster Recovery (DR) is the process of resuming normal operations following a disruption. It is not just backups; it is the rehearsed plan to bring systems back online within acceptable time and data loss limits.', syntax: 'Disruption -> Response -> Recovery -> Restoration', term: [{raw: '<span class="out" style="color:#E8A07A">Why DR Matters</span><br><br><span class="out">1. Hardware fails: Hard drives die, PSUs burn out.</span><br><span class="out">2. Human error: Accidental rm -rf / or bad config.</span><br><span class="out">3. Environment: Power outages, fires, floods.</span><br><span class="out">4. Cyberattacks: Ransomware encrypts your data.</span><br><br><span class="out" style="color:#E8A07A">The Goal</span><br><span class="out">Minimize downtime (RTO) and data loss (RPO).</span>'}], explain: '<strong>Explanation:</strong> A backup is a copy of your data. Disaster Recovery is the entire plan to restore service using that backup. Without a DR plan, a backup is just a pile of files on a shelf.' },
    
    // 2. DR Core Concepts: RPO & RTO
    { type: 'lesson', category: 'DR Planning', title: 'DR Concepts: RPO/RTO', subtitle: 'The golden metrics', desc: 'RPO (Recovery Point Objective) defines acceptable data loss measured in time. RTO (Recovery Time Objective) defines acceptable downtime. These metrics drive the entire DR architecture and budget.', syntax: 'RPO = Data Loss Tolerance\nRTO = Downtime Tolerance', term: [{raw: '<span class="out" style="color:#E8A07A">Recovery Point Objective (RPO)</span><br><br><span class="out">How much data can you afford to lose?</span><br><span class="out">If backups run every 4 hours, your RPO is 4 hours.</span><br><span class="out">You could lose up to 4 hours of work.</span><br><br><span class="out" style="color:#E8A07A">Recovery Time Objective (RTO)</span><br><br><span class="out">How long can the system be down?</span><br><span class="out">If RTO is 2 hours, the system must be back online</span><br><span class="out">within 2 hours of the disaster declaration.</span>'}], explain: '<strong>Explanation:</strong> RPO dictates your backup frequency. RTO dictates your recovery speed. A lower RPO/RTO costs more money (requires redundant hardware, cloud replication, or faster restore media).' },
    
    // 3. Calculating RPO & RTO
    { type: 'lesson', category: 'DR Planning', title: 'Calculating RPO & RTO', subtitle: 'Business impact', desc: 'To calculate RPO/RTO, assess the business impact of downtime and data loss. If a business loses $10,000/hour of downtime, an RTO of 4 hours costs $40,000 per incident.', syntax: 'Impact = Downtime * Cost/Hour', term: [{raw: '<span class="out" style="color:#E8A07A">Business Impact Analysis (BIA)</span><br><br><span class="out">1. Criticality: Is this system mission-critical?</span><br><span class="out">2. Cost of Downtime: Lost revenue, SLA penalties.</span><br><span class="out">3. Cost of Data Loss: Re-entering data, lost transactions.</span><br><br><span class="out" style="color:#E8A07A">Decision Matrix</span><br><br><span class="out">High Cost -> Low RTO (Hot Site, 0-1h)</span><br><span class="out">Med Cost -> Med RTO (Warm Site, 4-8h)</span><br><span class="out">Low Cost -> High RTO (Cold Site, 24h+)</span>'}], explain: '<strong>Explanation:</strong> A university registration system during enrollment has a very low RTO (must be up immediately). An internal HR portal might have a 48-hour RTO. Match the technology to the business need.' },
    
    // 4. Setting DR Objectives
    { type: 'lesson', category: 'DR Planning', title: 'Setting DR Objectives', subtitle: '4h RPO, 2h RTO', desc: 'For this course, the DR plan must achieve an RPO of 4 hours or less (backups/snapshots every 4h) and an RTO of 2 hours or less (service restored within 2h of failure).', syntax: 'RPO <= 4 hours\nRTO <= 2 hours', term: [{raw: '<span class="out" style="color:#E8A07A">Course Requirements</span><br><br><span class="out">Target RPO: 4 hours</span><br><span class="out">-> Take VirtualBox snapshots every 4 hours.</span><br><span class="out">-> Schedule cron rsync backups every 4 hours.</span><br><br><span class="out">Target RTO: 2 hours</span><br><span class="out">-> Restore snapshot within 10 minutes.</span><br><span class="out">-> Boot VM, verify services (5 minutes).</span><br><span class="out">-> Re-route traffic / update DNS (5 minutes).</span><br><span class="out">-> Total recovery well within 2h RTO.</span>'}], explain: '<strong>Explanation:</strong> VirtualBox snapshots allow near-instant RTOs because they save the full system state (including RAM). If we relied only on reinstalling the OS and restoring from rsync, our RTO would be 4+ hours.' },
    
    // 5. DR Strategies
    { type: 'lesson', category: 'DR Planning', title: 'DR Strategies', subtitle: 'Active vs Passive', desc: 'Active-Active: both sites run simultaneously, zero downtime. Active-Passive: one site runs, the other stands by. Choice depends on budget and RTO requirements.', syntax: 'Active-Active: 0 RTO\nActive-Passive: >0 RTO', term: [{raw: '<span class="out" style="color:#E8A07A">DR Site Types</span><br><br><span class="out">1. Hot Site (Active-Active): Live replication. 0 RTO.</span><br><span class="out">2. Warm Site (Active-Passive): Replicated hourly. 1-4h RTO.</span><br><span class="out">3. Cold Site (Passive): Hardware ready, data restored from tape. 24h+ RTO.</span><br><br><span class="out" style="color:#E8A07A">VirtualBox Lab Strategy</span><br><span class="out">We use "Snapshot-based Recovery" (Warm Site model).</span>'}], explain: '<strong>Explanation:</strong> A hot site is expensive (requires duplicate hardware/cloud costs). A cold site is cheap but slow. Our VirtualBox snapshot strategy mimics a Warm Site — data is captured periodically (RPO) and restored quickly (RTO).' },
    
    // 6. The 5 Failover Steps: Intro
    { type: 'lesson', category: 'Failover', title: '5 Failover Steps: Intro', subtitle: 'The DR sequence', desc: 'A successful failover follows five distinct steps: Detection, Declaration, Execution, Verification, and Failback. Skipping any step risks data loss or extended downtime.', syntax: 'Detect -> Declare -> Execute -> Verify -> Failback', term: [{raw: '<span class="out" style="color:#E8A07A">The 5-Step Failover Process</span><br><br><span class="out">1. Detection: Monitoring alerts the team of failure.</span><br><span class="out">2. Declaration: Incident commander declares a disaster.</span><br><span class="out">3. Execution: The DR plan is executed (restore snapshot).</span><br><span class="out">4. Verification: Confirm services are working for users.</span><br><span class="out">5. Failback: Return to the primary site when safe.</span><br><br><span class="out" style="color:#E8A07A">Course Requirement</span><br><span class="out">Your DR plan must document all 5 steps.</span>'}], explain: '<strong>Explanation:</strong> A DR plan is not just "restore the backup." It is a coordinated sequence. If you execute a restore before verifying the primary is truly dead, you risk split-brain (both servers writing data simultaneously).' },
    
    // 7. Failover Step 1: Detection
    { type: 'lesson', category: 'Failover', title: 'Failover 1: Detection', subtitle: 'Identifying the issue', desc: 'Monitoring alerts the team of a critical failure. The issue is triaged to determine if it is a transient outage (restart service) or a disaster requiring failover.', syntax: 'Alert -> Triage -> Classify', term: [{raw: '<span class="out" style="color:#E8A07A">Step 1: Detection</span><br><br><span class="out">Tools: Prometheus alerts, Grafana, user reports.</span><br><br><span class="out">Actions:</span><br><span class="out">1. Acknowledge the alert.</span><br><span class="out">2. Attempt standard service restart (systemctl restart).</span><br><span class="out">3. Check logs (journalctl) for root cause.</span><br><br><span class="out">Decision:</span><br><span class="out">If restart fixes it -> Incident closed.</span><br><span class="out">If OS is unbootable/corrupted -> Move to Declaration.</span>'}], explain: '<strong>Explanation:</strong> Not every alert is a disaster. A full memory leak might just need a service restart. Detection is about determining the scope: "Is this a minor blip or a catastrophic failure requiring our DR plan?"' },
    
    // 8. Failover Step 2: Declaration
    { type: 'lesson', category: 'Failover', title: 'Failover 2: Declaration', subtitle: 'Calling the disaster', desc: 'The Incident Commander officially declares a disaster. This triggers the DR plan, notifies stakeholders, and authorizes the failover execution team to proceed.', syntax: 'Declare -> Notify -> Authorize', term: [{raw: '<span class="out" style="color:#E8A07A">Step 2: Declaration</span><br><br><span class="out">Who: Incident Commander (e.g., IT Manager).</span><br><br><span class="out">Actions:</span><br><span class="out">1. Formally declare "Disaster Condition" via ITIL.</span><br><span class="out">2. Notify stakeholders (Management, Users).</span><br><span class="out">3. Authorize DR team to begin restore.</span><br><span class="out">4. Open Emergency Change Request (ECAB).</span><br><br><span class="out">Why formal?</span><br><span class="out">Failover is destructive. It requires approval.</span>'}], explain: '<strong>Explanation:</strong> Declaring a disaster means accepting data loss (up to RPO). It also means spending money (activating cloud failover resources). It must be done by someone with authority, not just the on-call engineer.' },
    
    // 9. Failover Step 3: Execution
    { type: 'lesson', category: 'Failover', title: 'Failover 3: Execution', subtitle: 'Switching traffic', desc: 'The standby environment is brought online. For our lab, this means restoring the VirtualBox snapshot. DNS or load balancers are updated to route traffic to the DR site.', syntax: 'Restore -> Boot -> Route', term: [{raw: '<span class="out" style="color:#E8A07A">Step 3: Execution</span><br><br><span class="out">VirtualBox Lab Execution:</span><br><span class="out">1. Power off the broken primary VM (force stop).</span><br><span class="out">2. Select the last known good snapshot.</span><br><span class="out">3. Click "Restore Snapshot".</span><br><span class="out">4. Boot the VM.</span><br><br><span class="out">Network Execution (Prod):</span><br><span class="out">1. Update DNS A-record to point to DR IP.</span><br><span class="out">2. Activate load balancer pool member.</span>'}], explain: '<strong>Explanation:</strong> This is the mechanical step. The DR team follows the run book. In our lab, it takes 2 minutes. In production, restoring a 1TB database from cloud snapshots might take 30 minutes — which is why RTO must account for restore time.' },
    
    // 10. Failover Step 4: Verification
    { type: 'lesson', category: 'Failover', title: 'Failover 4: Verification', subtitle: 'Is it working?', desc: 'The system is tested to ensure it is functional. Health checks pass, databases are connected, and user logins succeed. Only then is the failover considered complete and the RTO clock stops.', syntax: 'Health Check -> Test -> Confirm', term: [{raw: '<span class="out" style="color:#E8A07A">Step 4: Verification</span><br><br><span class="out">1. Ping the restored VM.</span><br><span class="out">2. SSH into the server.</span><br><span class="out">3. Check systemctl status of critical services.</span><br><span class="out">4. Curl localhost to test web server.</span><br><span class="out">5. Check database connectivity.</span><br><br><span class="out" style="color:#E8A07A">RTO Clock Stops Here</span><br><span class="out">If verification takes 10 minutes, and restore took 5 minutes,</span><br><span class="out">total RTO is 15 minutes (well under 2 hours).</span>'}], explain: '<strong>Explanation:</strong> A booted server is not a recovered server. The application might be up, but the database connection string might be broken. Verification proves the system is actually serving users, not just powered on.' },
    
    // 11. Failover Step 5: Failback
    { type: 'lesson', category: 'Failover', title: 'Failover 5: Failback', subtitle: 'Returning home', desc: 'Once the primary site is repaired, data is synced back, and traffic is routed back to the primary site. This is often the riskiest step and must be planned carefully.', syntax: 'Sync -> Route Back -> Verify', term: [{raw: '<span class="out" style="color:#E8A07A">Step 5: Failback</span><br><br><span class="out">When: After the primary site disaster is resolved</span><br><span class="out">      (e.g., hardware replaced, fire put out).</span><br><br><span class="out">Actions:</span><br><span class="out">1. Sync data from DR site back to Primary.</span><br><span class="out">2. Schedule maintenance window (ITIL Change).</span><br><span class="out">3. Switch DNS/Load Balancer back to Primary.</span><br><span class="out">4. Power down DR site.</span><br><br><span class="out" style="color:#E8A07A">Risk</span><br><span class="out">Failback causes a second brief downtime.</span>'}], explain: '<strong>Explanation:</strong> Failback is optional in a real disaster. Sometimes, the "DR site" becomes the new "Primary site" because it is cheaper. But if you failback, you must sync the data that changed during the outage back to the primary.' },
    
    // 12. Backups vs. Snapshots
    { type: 'lesson', category: 'Backups', title: 'Backups vs Snapshots', subtitle: 'The difference', desc: 'A backup is a copy of data stored elsewhere. A snapshot is a point-in-time state of a system/volume. Snapshots are fast for rollbacks but tied to the host. Backups are portable.', syntax: 'Backup = Portable Data\nSnapshot = System State', term: [{raw: '<span class="out" style="color:#E8A07A">Definitions</span><br><br><span class="out">Backup:</span><br><span class="out">Copies files (rsync) or disk images to external storage.</span><br><span class="out">Survives host hardware failure. Slow to restore.</span><br><br><span class="out">Snapshot:</span><br><span class="out">Saves VM state (RAM, disk diffs) on the same host.</span><br><span class="out">Fast to restore. Dies if host dies.</span><br><br><span class="out" style="color:#E8A07A">Rule</span><br><span class="out">Snapshots are for quick rollbacks.</span><br><span class="out">Backups are for true disasters.</span>'}], explain: '<strong>Explanation:</strong> If your VirtualBox host catches fire, snapshots are useless. You need an off-host backup. But for "I installed a bad patch and need to undo it," snapshots are 100x faster than restoring from backup.' },
    
    // 13. VirtualBox Snapshots: Overview
    { type: 'lesson', category: 'VirtualBox', title: 'VirtualBox Snapshots', subtitle: 'Point-in-time state', desc: 'VirtualBox snapshots save the exact state of a VM (RAM, disk, settings) at a specific moment. They allow non-destructive rollback during testing or before risky updates.', syntax: 'Snapshot = VM State + Disk State', term: [{raw: '<span class="out" style="color:#E8A07A">How VBox Snapshots Work</span><br><br><span class="out">1. Base Disk: The original VDI file (immutable).</span><br><span class="out">2. Snapshot File: Saves changes in a differencing disk.</span><br><span class="out">3. Saved State: Dumps RAM to disk so VM resumes instantly.</span><br><br><span class="out" style="color:#E8A07A">Use Cases</span><br><br><span class="out">- Before applying OS patches (Lab 2).</span><br><span class="out">- Before CIS hardening (Lab 6).</span><br><br><span class="out">- Before Docker Compose deployment (Lab 3).</span>'}], explain: '<strong>Explanation:</strong> When you take a snapshot, VirtualBox stops writing to the main VDI and starts writing to a new file. If you restore, it deletes that new file and resumes from the base. This is why snapshots consume disk space over time.' },
    
    // 14. VirtualBox Snapshot Types
    { type: 'lesson', category: 'VirtualBox', title: 'Snapshot Types', subtitle: 'Standard vs Live', desc: 'Standard snapshots power off the VM briefly. Live snapshots (saved state) capture the VM while running, including RAM. Live snapshots are resource-intensive.', syntax: 'Standard = Powered Off\nLive = Running (RAM)', term: [{raw: '<span class="out" style="color:#E8A07A">Snapshot Options</span><br><br><span class="out">1. Standard Snapshot:</span><br><span class="out">   - Takes snapshot of disk only.</span><br><span class="out">   - Safer. VM must be powered off or we risk crash-consistency.</span><br><br><span class="out">2. Live Snapshot (with Saved State):</span><br><span class="out">   - Dumps RAM to disk.</span><br><span class="out">   - VM resumes exactly where it left off.</span><br><span class="out">   - Requires enough free disk space for RAM dump.</span>'}], explain: '<strong>Explanation:</strong> For databases, a live snapshot might capture the DB in an inconsistent state (mid-write). It is safer to stop the DB service, take a standard snapshot, then restart. For web servers, live snapshots are usually fine.' },
    
    // 15. Creating a VirtualBox Snapshot
    { type: 'lesson', category: 'VirtualBox', title: 'Creating Snapshots', subtitle: 'The pre-update ritual', desc: 'Before any patch, config change, or destructive command, take a snapshot. Name it with a timestamp and description (e.g., "Pre-Patch-2026-11-20").', syntax: 'Machine -> Tools -> Snapshots -> Take', term: [{raw: '<span class="out" style="color:#E8A07A">Creating a Snapshot (GUI)</span><br><br><span class="out">1. Select the VM in VirtualBox Manager.</span><br><span class="out">2. Click the "Snapshots" icon (camera).</span><br><span class="out">3. Click "Take".</span><br><span class="out">4. Name: Pre-CIS-Hardening-20261120</span><br><span class="out">5. Description: Baseline before applying Lynis controls.</span><br><span class="out">6. Include RAM state: Checked (if VM is running).</span><br><span class="out">7. Click OK.</span>'}], explain: '<strong>Explanation:</strong> Naming is critical. "Snapshot 1" tells you nothing in 3 months. Use a standard naming convention like [State]-[Action]-[Date]. The description field should explain exactly what you were about to do.' },
    
    // 16. VirtualBox Snapshot Restore
    { type: 'lesson', category: 'VirtualBox', title: 'Snapshot Restore', subtitle: 'The rollback', desc: 'To restore, power off the VM, select the snapshot, and click "Restore." The VM disk and state are reverted. Any changes made after the snapshot are lost.', syntax: 'Power Off -> Select Snapshot -> Restore', term: [{raw: '<span class="out" style="color:#E8A07A">Restoring a Snapshot (GUI)</span><br><br><span class="out">1. Power off the VM (if running).</span><br><span class="out">2. Go to Snapshots tab.</span><br><span class="out">3. Right-click the target snapshot.</span><br><span class="out">4. Select "Restore Snapshot".</span><br><span class="out">5. Wait for merge/revert process.</span><br><span class="out">6. Start the VM.</span><br><br><span class="out" style="color:#E8A07A">Warning</span><br><span class="out">All data written to disk AFTER the snapshot is permanently lost.</span>'}], explain: '<strong>Explanation:</strong> This is the RTO mechanic. If a patch breaks the OS, restoring the snapshot brings it back to a working state in 30 seconds. This satisfies our RTO of 2 hours with a massive safety margin.' },
    
    // 17. Verifying Recovery in VBox
    { type: 'lesson', category: 'VirtualBox', title: 'Verifying Recovery', subtitle: 'Did it work?', desc: 'After restore, boot the VM. Check if the issue is resolved, services are running, and data is intact. Verify against the RTO: did recovery happen within 2 hours?', syntax: 'Boot -> Check Services -> Verify RTO', term: [{raw: '<span class="out" style="color:#E8A07A">Post-Restore Checklist</span><br><br><span class="out">1. Boot VM. Watch for kernel panics or boot errors.</span><br><span class="out">2. Login. Check IP address (ip a).</span><br><span class="out">3. systemctl status nginx (or target service).</span><br><span class="out">4. df -h (verify disk space is restored).</span><br><br><span class="out" style="color:#E8A07A">DR Plan Verification</span><br><br><span class="out">- Snapshot Timestamp: 10:00 AM</span><br><span class="out">- Disaster struck: 11:30 AM</span><br><span class="out">- Restore complete: 11:35 AM</span><br><span class="out">- Verification passed: 11:40 AM -> RTO Met!</span>'}], explain: '<strong>Explanation:</strong> The verification step is part of the RTO. If the restore takes 5 minutes but verifying takes 2 hours, your RTO is 2 hours. Automate health checks (a script that curls endpoints) to shrink verification time.' },
    
    // 18. VBox Snapshot Best Practices
    { type: 'lesson', category: 'VirtualBox', title: 'Snapshot Best Practices', subtitle: 'Safe usage', desc: 'Do not use snapshots as permanent backups; they degrade performance. Delete old snapshots. Consolidate when done. Always document what the snapshot represents.', syntax: 'Not for backups. Temporary only.', term: [{raw: '<span class="out" style="color:#E8A07A">Best Practices</span><br><br><span class="out">1. Delete Unused: Old snapshots chain together, slowing disk I/O.</span><br><span class="out">2. Consolidate: Merges snapshot data back to base disk.</span><br><span class="out">3. Document: Record why snapshot was taken in description.</span><br><span class="out">4. Limit Chain Length: Max 3-4 snapshots deep.</span><br><br><span class="out" style="color:#E8A07A">Danger</span><br><span class="out">If the base VDI file is corrupted or deleted, the entire</span><br><span class="out">snapshot chain is useless.</span>'}], explain: '<strong>Explanation:</strong> Snapshots are not backups. They rely on the base disk. If you leave 20 snapshots active, the VM will crawl because every read/write has to check 20 differencing files. Clean up your snapshots.' },
    
    // 19. Azure VM Snapshots: Overview
    { type: 'lesson', category: 'Azure Cloud', title: 'Azure VM Snapshots', subtitle: 'Cloud point-in-time', desc: 'Azure snapshots are point-in-time copies of managed disks. They are stored in Standard Storage by default. They are used to restore a VM or clone a disk for testing.', syntax: 'Managed Disk -> Snapshot -> Blob', term: [{raw: '<span class="out" style="color:#E8A07A">Azure Snapshots</span><br><br><span class="out">1. Source: Azure Managed Disk (OS or Data disk).</span><br><span class="out">2. Storage: Standard (HDD) or Premium (SSD).</span><br><span class="out">3. Incremental: Azure only stores changes since last snapshot.</span><br><span class="out">4. Access: Stored in Resource Group, accessible via Portal.</span><br><br><span class="out" style="color:#E8A07A">Lab 7 Context</span><br><span class="out">In Lab 7, we deployed an Azure Linux VM. We can snapshot its</span><br><span class="out">OS disk to preserve the IaC deployment state.</span>'}], explain: '<strong>Explanation:</strong> Azure snapshots are incredibly robust. Because they are incremental, taking a snapshot every 4 hours (our RPO) is cheap — you only pay for the changed blocks. They survive host failures, unlike VirtualBox snapshots.' },
    
    // 20. Creating an Azure VM Snapshot
    { type: 'lesson', category: 'Azure Cloud', title: 'Creating Azure Snapshots', subtitle: 'Portal steps', desc: 'In Azure Portal, select the VM, click "Snapshots" under Disks. Create a new snapshot. This captures the disk state instantly and stores it in a resource group.', syntax: 'VM -> Disks -> Create Snapshot', term: [{raw: '<span class="out" style="color:#E8A07A">Portal Steps</span><br><br><span class="out">1. Go to Azure Portal -> Virtual Machines.</span><br><span class="out">2. Select your VM (e.g., vm-tf-14).</span><br><span class="out">3. Scroll to "Disks" in the left menu.</span><br><span class="out">4. Click "Create Snapshot".</span><br><span class="out">5. Name: snap-vm-tf-14-20261120.</span><br><span class="out">6. Resource Group: rg-tf-14.</span><br><span class="out">7. Storage type: Standard HDD (cheaper).</span><br><span class="out">8. Click "Review + Create".</span>'}], explain: '<strong>Explanation:</strong> This takes a few seconds to initiate, but the actual data copy happens in the background. Azure ensures the snapshot is crash-consistent. You can continue using the VM while the snapshot finalizes.' },
    
    // 21. Restoring an Azure VM from Snapshot
    { type: 'lesson', category: 'Azure Cloud', title: 'Azure VM Restore', subtitle: 'Creating a new disk', desc: 'To restore, create a new managed disk from the snapshot. Stop the VM, swap the OS disk to the newly created disk, and start the VM.', syntax: 'Snapshot -> New Disk -> Swap OS Disk', term: [{raw: '<span class="out" style="color:#E8A07A">Restore Workflow</span><br><br><span class="out">1. Select Snapshot -> "Create Disk".</span><br><span class="out">2. Name: disk-restore-20261120.</span><br><span class="out">3. Wait for disk creation (2-5 mins).</span><br><span class="out">4. Stop (deallocate) the target VM.</span><br><span class="out">5. VM -> Disks -> "Swap OS Disk".</span><br><span class="out">6. Select the new disk. Click OK.</span><br><span class="out">7. Start the VM.</span>'}], explain: '<strong>Explanation:</strong> Azure cannot restore a disk while the VM is running (file locks). You must stop the VM, swap the disk, and restart. This RTO is longer than VirtualBox (could be 10-15 minutes), but still well within our 2-hour target.' },
    
    // 22. On-Prem vs Cloud Snapshots
    { type: 'lesson', category: 'Snapshots', title: 'On-Prem vs Cloud', subtitle: 'Comparing tools', desc: 'VirtualBox snapshots are local and fast but manual. Azure snapshots are durable, can be automated, and survive host failure. Both achieve RPO goals if scheduled.', syntax: 'VBox: Local/Manual\nAzure: Cloud/Automated', term: [{raw: '<span class="out" style="color:#E8A07A">Comparison</span><br><br><span class="out">VirtualBox:</span><br><span class="out">- Survives host failure? NO.</span><br><span class="out">- Can automate? Difficult (CLI only).</span><br><span class="out">- RTO: Seconds (RAM state).</span><br><br><span class="out">Azure:</span><br><span class="out">- Survives host failure? YES (Cloud).</span><br><span class="out">- Can automate? YES (Azure Backup / Automation Runbooks).</span><br><span class="out">- RTO: Minutes (Disk swap).</span>'}], explain: '<strong>Explanation:</strong> In a real business, you use both. VirtualBox snapshots for rapid lab/testing rollback. Azure snapshots for production DR. Never rely on VirtualBox snapshots for production data.' },
    
    // 23. The Role of Documentation
    { type: 'lesson', category: 'Documentation', title: 'Role of Documentation', subtitle: 'The run book', desc: 'During a disaster, stress is high and memory fails. Documentation (Run Books, DR Plans) provides step-by-step instructions so any engineer can execute the recovery.', syntax: 'Document = Survive the stress', term: [{raw: '<span class="out" style="color:#E8A07A">Why Document?</span><br><br><span class="out">1. Stress: At 3 AM, nobody remembers IP addresses.</span><br><span class="out">2. Turnover: The person who built it might not be there.</span><br><span class="out">3. Audit: Prove to management that a plan exists.</span><br><br><span class="out" style="color:#E8A07A">Required DR Documents</span><br><br><span class="out">1. DR Plan Template (The 5 steps).</span><br><span class="out">2. Network Diagram (Draw.io).</span><br><span class="out">3. IT Project Proposal (Funding).</span><br><span class="out">4. ITIL Change Request (Approval).</span>'}], explain: '<strong>Explanation:</strong> A DR plan unwritten is just an opinion. Writing it down forces you to think through the steps, identify missing links (do we have the backup credentials?), and validate the RTO math.' },
    
    // 24. Draw.io: The Tool
    { type: 'lesson', category: 'Documentation', title: 'Draw.io: The Tool', subtitle: 'Visual IT docs', desc: 'Draw.io (diagrams.net) is a free, open-source tool for creating network and IT infrastructure diagrams. It uses clear icons and supports export to PNG, SVG, and XML.', syntax: 'Diagrams -> Visual -> Clear', term: [{raw: '<span class="out" style="color:#E8A07A">Draw.io Features</span><br><br><span class="out">1. Free: No license required. Web or Desktop.</span><br><span class="out">2. Shape Libraries: AWS, Azure, Cisco, Generic Network.</span><br><span class="out">3. Export: PNG, SVG, PDF, XML.</span><br><span class="out">4. Collaboration: Integrates with Google Drive / OneDrive.</span><br><br><span class="out" style="color:#E8A07A">Lab Requirement</span><br><span class="out">You must submit a labeled Draw.io DR network diagram for Lab 8.</span>'}], explain: '<strong>Explanation:</strong> Visio is the enterprise standard but costs money. Draw.io is the open-source equivalent used by most modern DevOps teams. It produces clean, professional diagrams that can be embedded in run books.' },
    
    // 25. DR Network Diagrams
    { type: 'lesson', category: 'Documentation', title: 'DR Network Diagrams', subtitle: 'Visualizing failover', desc: 'A DR network diagram shows primary and secondary sites, network routes, and failover paths. It must be labeled with IPs, hostnames, and RTO/RPO metrics for each segment.', syntax: 'Primary <-> DR Site', term: [{raw: '<span class="out" style="color:#E8A07A">Diagram Requirements</span><br><br><span class="out">1. Primary Site: Servers, firewalls, load balancers.</span><br><span class="out">2. DR Site: Standby servers, network gear.</span><br><span class="out">3. Connection: WAN/VPN link between sites.</span><br><span class="out">4. Failover Path: Dashed line showing traffic reroute.</span><br><span class="out">5. Labels: IP addresses, ports, service names.</span><br><br><span class="out" style="color:#E8A07A">Goal</span><br><span class="out">A new hire should understand the topology in 60 seconds.</span>'}], explain: '<strong>Explanation:</strong> The diagram is the map. During an outage, engineers reference it to find "where is the firewall?" or "what is the DR IP?". If it is unlabeled, it is wall art.' },
    
    // 26. Creating a Labeled Diagram
    { type: 'lesson', category: 'Documentation', title: 'Labeled Diagrams', subtitle: 'Requirements', desc: 'Use standard icons for servers, firewalls, and load balancers. Label all connections with IPs and ports. Use color: Green for primary, Blue for DR, Red for failover route.', syntax: 'Icons -> Labels -> Colors', term: [{raw: '<span class="out" style="color:#E8A07A">Drawing Standards</span><br><br><span class="out">1. Shapes:</span><br><span class="out">   - Rectangle: Server/VM</span><br><span class="out">   - Hexagon: Firewall</span><br><span class="out">   - Cloud: Internet/WAN</span><br><br><span class="out">2. Colors:</span><br><span class="out">   - Green Outline: Primary (Production)</span><br><span class="out">   - Blue Outline: DR (Standby)</span><br><span class="out">   - Red Line: Failover traffic</span><br><br><span class="out">3. Text:</span><br><span class="out">   Hostname, IP, OS, Service (e.g., "web-01 | 10.0.0.5 | Nginx")</span>'}], explain: '<strong>Explanation:</strong> Consistency is key. If green means primary in one diagram, it should mean primary in all diagrams. Labeling both the IP and the service means the engineer does not have to look up what 10.0.0.5 is during an outage.' },
    
    // 27. Sample DR Diagram Structure
    { type: 'lesson', category: 'Documentation', title: 'Sample DR Structure', subtitle: 'Layout', desc: 'Draw two distinct sites connected by a WAN link. Primary site has App/DB servers. DR site has standby App/DB. Draw a dashed red line indicating failover traffic.', syntax: 'Primary (Green) ---WAN--- DR (Blue)', term: [{raw: '<span class="out" style="color:#E8A07A">Visual Layout</span><br><br><span class="out">   [Internet Cloud]</span><br><span class="out">        |</span><br><span class="out">   [Load Balancer] -------------- [DR Load Balancer]</span><br><span class="out">        |                              |</span><br><span class="out">   [Primary Site]                [DR Site]</span><br><span class="out">   - Web-01 (10.0.0.5)          - Web-DR (10.1.0.5)</span><br><span class="out">   - DB-01  (10.0.0.6)          - DB-DR  (10.1.0.6)</span><br><br><span class="out" style="color:#E8A07A">Legend</span><br><span class="out">Green = Active / Primary</span><br><span class="out">Blue = Standby / DR</span><br><span class="out">Red Dashed = Failover Path</span>'}], explain: '<strong>Explanation:</strong> The diagram visually answers "what happens if Web-01 dies?". The red dashed line shows traffic rerouting to Web-DR. This is the deliverable for the Draw.io portion of Lab 8.' },
    
    // 28. IT Project Proposal
    { type: 'lesson', category: 'IT Management', title: 'IT Project Proposal', subtitle: 'Pitching the DR plan', desc: 'An IT Project Proposal justifies the cost of DR infrastructure to management. It outlines current risks, proposed solutions (RPO/RTO), timeline, and budget.', syntax: 'Problem -> Solution -> Cost -> Timeline', term: [{raw: '<span class="out" style="color:#E8A07A">Proposal Structure</span><br><br><span class="out">1. Executive Summary: Why we need DR.</span><br><span class="out">2. Problem Statement: Current RPO/RTO is infinite (no plan).</span><br><span class="out">3. Proposed Solution: Azure backups + Draw.io runbooks.</span><br><span class="out">4. Budget: Cloud costs, engineer hours.</span><br><span class="out">5. Timeline: 3-month implementation plan.</span><br><br><span class="out" style="color:#E8A07A">Audience</span><br><span class="out">Management. Focus on risk reduction and ROI, not tech specs.</span>'}], explain: '<strong>Explanation:</strong> Management speaks in dollars. If the proposal says "We need $5,000 for Azure snapshots," it will be rejected. If it says "An outage costs us $20,000/hour; this $5,000 solution limits downtime to 2 hours," it will be approved.' },
    
    // 29. IT Proposal: DR Component
    { type: 'lesson', category: 'IT Management', title: 'IT Proposal: DR', subtitle: 'The DR ask', desc: 'The DR component of the proposal defines the target RPO/RTO, required hardware/cloud resources, and the expected ROI (money saved during an outage).', syntax: 'RPO/RTO -> Resources -> ROI', term: [{raw: '<span class="out" style="color:#E8A07A">DR Proposal Section</span><br><br><span class="out">Target RPO: 4 Hours (Hourly Azure snapshots)</span><br><span class="out">Target RTO: 2 Hours (Automated disk swap)</span><br><br><span class="out">Required Resources:</span><br><span class="out">- Azure Storage Account (for snapshots)</span><br><span class="out">- 1x Standby VM (Standard_B1s)</span><br><span class="out">- Draw.io licenses (Free)</span><br><br><span class="out">ROI:</span><br><span class="out">Cost: $50/month. Risk Mitigated: $20,000/hour of downtime.</span>'}], explain: '<strong>Explanation:</strong> This section translates technical concepts (snapshots, B1s VMs) into business value. It proves that the DR plan is not just an IT exercise, but a financial safeguard for the university.' },
    
    // 30. ITIL Change Management
    { type: 'lesson', category: 'IT Management', title: 'ITIL Change Management', subtitle: 'Coordinating chaos', desc: 'ITIL Change Management ensures DR execution (or failback) is coordinated. While emergencies bypass normal approval, they must still be documented and reviewed.', syntax: 'Request -> Approve -> Execute -> Review', term: [{raw: '<span class="out" style="color:#E8A07A">Why ITIL in DR?</span><br><br><span class="out">1. Coordination: Ensure DBAs and Network teams sync during failover.</span><br><span class="out">2. Audit Trail: Record who flipped the switch and when.</span><br><span class="out">3. Post-Mortem: Review what went wrong and update the DR plan.</span><br><br><span class="out" style="color:#E8A07A">Process</span><br><br><span class="out">Disaster = Emergency Change (ECAB approval).</span><br><span class="out">Failback = Normal Change (CAB approval).</span>'}], explain: '<strong>Explanation:</strong> ITIL prevents "cowboy sysadmins" from randomly rebooting servers. Even in a disaster, the Incident Commander authorizes the change. After the disaster, a post-incident review (PIR) updates the run book.' },
    
    // 31. ITIL Change Types
    { type: 'lesson', category: 'IT Management', title: 'ITIL Change Types', subtitle: 'Standard, Normal, Emergency', desc: 'Standard changes are pre-approved (patching). Normal changes require CAB approval (upgrades). Emergency changes bypass CAB for verbal approval during an outage.', syntax: 'Standard -> Normal -> Emergency', term: [{raw: '<span class="out" style="color:#E8A07A">Change Types</span><br><br><span class="out">1. Standard Change:</span><br><span class="out">   Pre-approved, repeatable, low risk.</span><br><span class="out">   Example: Taking a VirtualBox snapshot.</span><br><br><span class="out">2. Normal Change:</span><br><span class="out">   Requires CAB approval. Medium to high risk.</span><br><span class="out">   Example: Upgrading Ubuntu Server OS.</span><br><br><span class="out">3. Emergency Change:</span><br><span class="out">   Verbal approval during outage. Documented retroactively.</span><br><span class="out">   Example: Executing DR failover.</span>'}], explain: '<strong>Explanation:</strong> The DR execution is an Emergency Change. You do not have time to fill out a CR and wait for the weekly CAB meeting. You call the IT Manager (ECAB), get verbal approval, execute, and fill out the paperwork the next day.' },
    
    // 32. The Change Advisory Board (CAB)
    { type: 'lesson', category: 'IT Management', title: 'The CAB', subtitle: 'Approving changes', desc: 'The CAB reviews Normal changes. It includes IT, business, and security stakeholders. They assess risk, rollback plans, and impact before approving a change.', syntax: 'Review -> Assess -> Approve/Reject', term: [{raw: '<span class="out" style="color:#E8A07A">CAB Composition</span><br><br><span class="out">1. IT Manager (Chair)</span><br><span class="out">2. Network Engineer</span><br><span class="out">3. System Admin</span><br><span class="out">4. Security Officer</span><br><span class="out">5. Business Stakeholder (User Rep)</span><br><br><span class="out" style="color:#E8A07A">Review Criteria</span><br><br><span class="out">1. Is the rollback plan tested?</span><br><span class="out">2. What is the impact on users?</span><br><span class="out">3. Can we do this during off-hours?</span>'}], explain: '<strong>Explanation:</strong> The CAB exists to prevent unilateral decisions by one sysadmin that could break the company. For a DR failback (Normal Change), the CAB verifies the primary site is truly fixed before allowing traffic to return.' },
    
    // 33. DR & ITIL Coordination
    { type: 'lesson', category: 'IT Management', title: 'DR & ITIL', subtitle: 'Working together', desc: 'DR plans must align with ITIL. A disaster is an Emergency Change. The Incident Commander acts as the CAB chair temporarily, approving the failover execution.', syntax: 'Disaster = Emergency Change', term: [{raw: '<span class="out" style="color:#E8A07A">DR / ITIL Workflow</span><br><br><span class="out">1. Monitoring detects failure (Detection).</span><br><span class="out">2. Incident Commander convenes ECAB (Declaration).</span><br><br><span class="out">3. Emergency Change approved: "Execute Failover" (Execution).</span><br><br><span class="out">4. Services restored (Verification).</span><br><br><span class="out">5. Post-Incident Review (PIR) scheduled.</span><br><span class="out">6. Failback scheduled as Normal Change for next week.</span>'}], explain: '<strong>Explanation:</strong> This bridges technical DR (snapshots) with process ITIL (changes). It ensures that even during chaos, there is a record of decisions. The PIR is crucial — it updates the DR plan for the next disaster.' },
    
    // 34. Designing the DR Plan
    { type: 'lesson', category: 'DR Plan', title: 'Designing the DR Plan', subtitle: 'The template', desc: 'The DR Plan document includes: Objectives (RPO/RTO), Roles & Contacts, Infrastructure Inventory, Failover Steps, and Recovery Verification procedures.', syntax: 'Objectives -> Roles -> Steps -> Verify', term: [{editor: "dr-plan-template.md", code: '## 1. Objectives\n- RPO: 4 Hours (Snapshots every 4h)\n- RTO: 2 Hours (Restore within 2h)\n\n## 2. Roles & Contacts\n- Incident Cmd: Dony Dongiapon (x123)\n- Sysadmin: Ar-Jay Sacay (x456)\n\n## 3. Infrastructure\n- Primary: ubu-srv-01 (10.0.0.5)\n- Snapshot: Pre-Patch-20261120\n\n## 4. Failover Steps\n1. Power off ubu-srv-01\n2. Restore Snapshot via VBox GUI\n3. Boot VM\n\n## 5. Verification\n- systemctl status nginx\n- curl http://localhost'}], explain: '<strong>Explanation:</strong> This is the core deliverable for Lab 8. The template must be filled out completely. It is not a generic document; it must reference the specific VM names, IP addresses, and snapshot names used in your lab environment.' },
    
    // 35. Completing the DR Plan
    { type: 'lesson', category: 'DR Plan', title: 'Completing the Plan', subtitle: 'The lab deliverable', desc: 'For the lab, complete the DR plan template with a target RPO of 4h and RTO of 2h. Include 5 failover steps and reference the Draw.io diagram.', syntax: 'RPO <= 4h, RTO <= 2h, 5 Steps', term: [{raw: '<span class="out" style="color:#E8A07A">Lab 8 DR Plan Checklist</span><br><br><span class="out">[ ] RPO stated as <= 4 hours.</span><br><span class="out">[ ] RTO stated as <= 2 hours.</span><br><span class="out">[ ] 5 Failover steps documented.</span><br><span class="out">[ ] Roles assigned (Cmd, Sysadmin).</span><br><span class="out">[ ] VM names and IPs listed.</span><br><span class="out">[ ] Verification commands included.</span><br><span class="out">[ ] Reference to Draw.io diagram attached.</span><br><br><span class="out" style="color:#E8A07A">Submission</span><br><span class="out">Submit as PDF with diagram embedded.</span>'}], explain: '<strong>Explanation:</strong> If you leave a section blank, the plan fails. "Restore the snapshot" is not a step. "Right-click Pre-Patch snapshot in VirtualBox and select Restore" is a step. Be specific enough that a non-expert could follow it.' },
    
    // 36. Testing the DR Plan
    { type: 'lesson', category: 'DR Plan', title: 'Testing the DR Plan', subtitle: 'Tabletop vs Live', desc: 'A DR plan is useless if untested. Tabletop tests are walkthroughs. Live tests (like snapshot restores) prove the plan works. Schedule tests at least quarterly.', syntax: 'Tabletop -> Live Test -> Update', term: [{raw: '<span class="out" style="color:#E8A07A">Testing Types</span><br><br><span class="out">1. Tabletop Exercise:</span><br><span class="out">   Team sits in a room and talks through the plan.</span><br><span class="out">   Safe. Catches obvious gaps.</span><br><br><span class="out">2. Live Test (Disaster Simulation):</span><br><span class="out">   Actually delete a file and try to restore it.</span><br><br><span class="out">3. Chaos Engineering:</span><br><br><span class="out">   Randomly kill VMs in production (Netflix Chaos Monkey).</span><br><br><span class="out" style="color:#E8A07A">Lab 8 Test</span><br><br><span class="out">We perform a live test by restoring a snapshot.</span>'}], explain: '<strong>Explanation:</strong> A DR plan that has never been tested will fail when you need it most. Snapshots make testing safe and easy. If the restore fails, you haven\'t lost anything. Always update the plan based on test results.' },
    
    // 37. Topic Summary
    { type: 'lesson', category: 'Summary', title: 'Topic Summary', subtitle: 'Module 6 complete', desc: 'You have defined RPO/RTO, designed a 5-step failover plan, performed snapshot restores in VirtualBox and Azure, and created DR documentation using Draw.io and ITIL principles.', syntax: 'Plan -> Snapshot -> Document -> Test', term: [{raw: '<span class="out" style="color:#E8A07A">Topic 16 Checklist</span><br><br><span class="out">[x] Defined RPO (4h) and RTO (2h).</span><br><span class="out">[x] Documented 5 failover steps.</span><br><span class="out">[x] Performed VirtualBox snapshot restore.</span><br><span class="out">[x] Explored Azure VM snapshot restore.</span><br><span class="out">[x] Created Draw.io DR network diagram.</span><br><span class="out">[x] Understood IT Project Proposal structure.</span><br><span class="out">[x] Applied ITIL Change Management to DR.</span><br><br><span class="out" style="color:#E8A07A">Module 06 Complete!</span><br><span class="out">Next: Final Examinations.</span>'}], explain: '<strong>Explanation:</strong> This completes the operational lifecycle. You can now build (M1-M4), automate in the cloud (M5), and recover from disasters (M6). These skills define a professional systems administrator.' },

  // --- 4. CLOSING SLIDE ---
  {
    type: 'closing',
    header: 'MODULE 06 · TOPIC 16',
    tag: 'End of Topic 16',
    title: 'Plan. <em>Restore.</em><br>Document.',
    quote: 'Failing to plan is planning to fail. In systems administration, we don’t just plan to recover — we rehearse it, document it, and diagram it.',
    leftCardNum: '§ recovery',
    leftCardTitle: 'Snapshots & RTO/RPO',
    leftCardDesc: 'VirtualBox and Azure snapshots provide point-in-time recovery capabilities. Defining an RPO of 4 hours and an RTO of 2 hours establishes measurable limits for acceptable data loss and service downtime.',
    middleCardNum: '§ operations',
    middleCardTitle: 'Diagrams & ITIL',
    middleCardDesc: 'Draw.io disaster recovery diagrams communicate infrastructure layouts and failover paths, while ITIL Change Management ensures recovery changes are coordinated, documented, approved when required, and reviewed after an incident.',
    rightCardNum: '§ documentation',
    rightCardTitle: 'Planning & Proposals',
    rightCardDesc: 'A structured disaster recovery plan, IT Project Proposal, and documented recovery procedures help administrators prepare for failures, allocate resources, and restore critical services within established recovery objectives.'
  }
];