const slideConfigs = [
  // --- 1. COVER SLIDE ---
  {
    type: 'cover',
    moduleTitle: 'MODULE 02 · TOPIC 08',
    topicNum: '08',
    topicTag: 'T8',
    title: 'OS Maintenance<br>& Service <em>Management</em>',
    subtitle: 'Keeping systems secure, stable, and operational: Patching OSes, managing services across Windows and Linux, and analyzing system logs.',
    graphicText: 'Patch <em>Systems</em><br>Manage <em>Services</em><br>Analyze Logs.',
    miniObjectives: [
      'Windows & Ubuntu Patching',
      'Systemctl & Service Control',
      'Event Viewer & Journalctl',
      '4-Step ITIL Patching SOP'
    ]
  },

  // --- 2. OBJECTIVES SLIDE ---
  {
    type: 'objectives',
    header: 'MODULE 02 · TOPIC 08',
    kicker: 'ITP 141 · M2 · T8',
    desc: 'This topic covers the daily maintenance loop of a sysadmin. You will learn to apply patches, manage background services, and diagnose issues using logs.',
    lede: 'A system that is never patched is a liability. A service that fails silently is a mystery. Master maintenance to ensure 99.9% uptime.',
    list: [
      'Apply OS patching on Windows Server 2022 (sconfig / Windows Update).',
      'Apply OS patching on Ubuntu Server using apt and unattended-upgrades.',
      'Manage services on Windows using services.msc and PowerShell.',
      'Manage services on Linux using systemctl (start, stop, enable, status).',
      'Analyze logs with Windows Event Viewer.',
      'Analyze logs with journalctl -p err and tail -f.',
      'Configure a service to restart automatically upon failure.',
      'Write a 4-step OS Maintenance SOP following ITIL principles.'
    ]
  },

  // --- 3. LESSON SLIDES ---
  { type: 'lesson', category: 'Overview', title: 'OS Maintenance', subtitle: 'The Lifecycle', desc: 'OS maintenance is a continuous loop. It involves applying security patches, updating software, managing background services, and analyzing logs to predict failures before they happen.', syntax: 'Assess -> Test -> Deploy -> Verify -> Monitor', term: [{raw: '<span class="out" style="color:#E8A07A">The Sysadmin Maintenance Loop</span><br><br><span class="out">1. Assess: Check for available updates</span><br><span class="out">2. Test: Deploy in a staging environment</span><br><span class="out">3. Deploy: Roll out to production servers</span><br><span class="out">4. Verify: Check service status and logs</span><br><span class="out">5. Monitor: Watch for anomalies post-patch</span>'}], explain: '<strong>Explanation:</strong> This cycle is the core of ITIL (Information Technology Infrastructure Library) service management. It ensures patches do not break production systems by enforcing a testing phase before deployment.' },
    
  { type: 'lesson', category: 'Windows Patching', title: 'Windows: Patching', subtitle: 'sconfig', desc: 'On Windows Server Core or when using PowerShell, the <code>sconfig</code> utility provides a text-based menu to search for, download, and install Windows Updates.', syntax: 'sconfig\n# Option 6: Download and install updates', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> sconfig</span><br><br><span class="out" style="color:#E8A07A">Server Configuration</span><br><span class="out">1) Domain/Workgroup: Workgroup: WORKGROUP</span><br><span class="out">2) Computer Name:     WIN-SRV-01</span><br><span class="out">6) Windows Update:    Automatic</span><br><br><span class="out">Enter number to select an option: 6</span><br><span class="out">(A) Download and install all updates</span>'}], explain: '<strong>Explanation:</strong> <code>sconfig</code> is the easiest way to patch Windows Server without a GUI. Option 6 allows you to search Microsoft Update, download patches, and install them, followed by an automatic reboot.' },
  
  { type: 'lesson', category: 'Windows Patching', title: 'Windows: Patching', subtitle: 'PowerShell', desc: 'For full automation, use the <code>PSWindowsUpdate</code> module in PowerShell. It allows you to script the entire patching process.', syntax: 'Install-Module PSWindowsUpdate\nGet-WindowsUpdate\nInstall-WindowsUpdate -AcceptAll -AutoReboot', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Install-Module PSWindowsUpdate -Force</span><br><span class="cmd">> Get-WindowsUpdate</span><br><span class="out">ComputerName Status  KB       Size  Title</span><br><span class="out">WIN-SRV-01    -D----  KB500... 12MB  2024-10 Cumulative Update</span><br><span class="cmd">> Install-WindowsUpdate -AcceptAll -AutoReboot</span><br><span class="out">Installing KB500... Complete. Rebooting...</span>'}], explain: '<strong>Explanation:</strong> <code>Install-Module</code> downloads the community-maintained PSWindowsUpdate tool. <code>Install-WindowsUpdate -AcceptAll</code> applies all available patches, and <code>-AutoReboot</code> restarts the server automatically if required.' },
  
  { type: 'lesson', category: 'Windows Patching', title: 'Windows: Update Settings', subtitle: 'Group Policy', desc: 'In an enterprise, you control Windows Update via Group Policy Objects (GPOs). You can defer feature updates, set active hours, and target specific update rings.', syntax: 'GPO -> Computer Configuration -> Administrative Templates -> Windows Components -> Windows Update', term: [{raw: '<span class="out" style="color:#E8A07A">Key GPO Settings</span><br><span class="out">1. Configure Automatic Updates: Enabled, Auto download and notify for install.</span><br><span class="out">2. Turn off auto-restart for updates during active hours: Enabled (8 AM - 5 PM).</span><br><span class="out">3. Select when Preview Builds and Feature Updates are received: 365 days deferment.</span>'}], explain: '<strong>Explanation:</strong> Blindly installing the latest Windows update can break legacy apps. GPOs allow sysadmins to delay feature updates (like 24H2) while still allowing security patches to install automatically.' },
  
  { type: 'lesson', category: 'Ubuntu Patching', title: 'Ubuntu: Patching', subtitle: 'apt update & upgrade', desc: 'Linux distributions use package managers to fetch patches from central repositories. Ubuntu uses <code>apt</code>.', syntax: 'sudo apt update\nsudo apt upgrade -y\nsudo apt autoremove -y', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt update</span><br><span class="out">Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease</span><br><span class="out">42 packages can be upgraded. Run \'apt list --upgradable\' to see them.</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt upgrade -y</span><br><span class="out">Reading package lists... Done</span><br><span class="out">The following packages will be upgraded:</span><br><span class="out">42 upgraded, 0 newly installed, 0 to remove.</span>'}], explain: '<strong>Explanation:</strong> <code>apt update</code> refreshes the local package index (does NOT install anything). <code>apt upgrade -y</code> installs all available updates automatically. <code>autoremove</code> cleans up old dependencies.' },
  
  { type: 'lesson', category: 'Ubuntu Patching', title: 'Linux Patching', subtitle: 'APT vs DNF/YUM', desc: 'Ubuntu uses APT. Red Hat, CentOS, and Rocky Linux use YUM or DNF. The concepts are identical, but the commands differ.', syntax: 'Ubuntu (APT): sudo apt upgrade\nRHEL (DNF): sudo dnf upgrade', term: [{raw: '<span class="out" style="color:#E8A07A">Package Manager Comparison</span><br><br><span class="out">1. Update repo: apt update / dnf check-update</span><br><span class="out">2. Install pkg: apt install nginx / dnf install nginx</span><br><span class="out">3. Search pkg: apt search nginx / dnf search nginx</span><br><span class="out">4. Remove pkg: apt remove nginx / dnf remove nginx</span><br><br><span class="out" style="color:#E8A07A">Why it matters</span><br><span class="out">In a dual-OS lab, you might manage an Ubuntu web server and a Red Hat database server. You must be fluent in both package managers.</span>'}], explain: '<strong>Explanation:</strong> While APT is standard for Debian-based systems, DNF is the modern replacement for YUM on Red Hat-based systems. Both handle dependency resolution automatically.' },
  
  { type: 'lesson', category: 'Ubuntu Patching', title: 'Ubuntu: Patching History', subtitle: 'apt history', desc: 'When a patch breaks a service, you need to know exactly what was installed. Ubuntu logs all APT transactions in <code>/var/log/apt/history.log</code>.', syntax: 'cat /var/log/apt/history.log', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">cat /var/log/apt/history.log</span><br><span class="out">Start-Date: 2024-10-24  10:00:00</span><br><span class="out">Commandline: apt upgrade -y</span><br><span class="out">Upgrade: libssl3:amd64 (3.0.13-0ubuntu6, 3.0.13-0ubuntu7)</span><br><span class="out">End-Date: 2024-10-24  10:02:15</span>'}], explain: '<strong>Explanation:</strong> If a web app stops working right after a routine patch, check this log. It shows the exact timestamp and version numbers of what changed, allowing you to use <code>apt downgrade</code> or roll back the broken package.' },
  
  { type: 'lesson', category: 'Ubuntu Patching', title: 'Ubuntu: Patching', subtitle: 'Unattended Upgrades', desc: 'For automatic security patching, Ubuntu uses the <code>unattended-upgrades</code> package. It installs critical security updates daily without admin intervention.', syntax: 'sudo apt install unattended-upgrades\nsudo dpkg-reconfigure -plow unattended-upgrades', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt install unattended-upgrades -y</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo dpkg-reconfigure -plow unattended-upgrades</span><br><br><span class="out" style="color:#E8A07A">Configuring unattended-upgrades</span><br><span class="out">Automatically download and install stable updates?</span><br><span class="out">&lt;Yes&gt;          &lt;No&gt;</span><br><br><span class="out">(Selecting Yes enables automatic security patches)</span>'}], explain: '<strong>Explanation:</strong> This opens a text-based dialog. Selecting <code>Yes</code> enables a daily cron job that downloads and installs security updates automatically. This ensures your server is protected even if you forget to log in.' },
  
  { type: 'lesson', category: 'Services', title: 'Service Management', subtitle: 'Concepts', desc: 'A service (or daemon in Linux) is a program that runs in the background without user interaction. Sysadmins must start, stop, and configure them to run on boot.', syntax: 'Windows: services.msc\nLinux: systemctl', term: [{raw: '<span class="out" style="color:#E8A07A">Service States</span><br><span class="out">1. Running: Currently active in memory</span><br><span class="out">2. Stopped: Not running, but can be started</span><br><span class="out">3. Disabled: Will NOT start on boot</span><br><span class="out">4. Enabled: Will start automatically on boot</span>'}], explain: '<strong>Explanation:</strong> A common sysadmin task is ensuring critical services (like SSH or Web servers) are both "Running" and "Enabled" so they survive a server reboot. If a service is running but disabled, a reboot will take your application offline.' },
  
  { type: 'lesson', category: 'Windows Services', title: 'Windows: Services', subtitle: 'services.msc', desc: 'The GUI tool for managing Windows services is <code>services.msc</code>. It shows the service name, status, and startup type.', syntax: 'services.msc', term: [{raw: '<span class="out" style="color:#E8A07A">Services (Local)</span><br><br><span class="out">Name                   Status   Startup Type</span><br><span class="out">Active Directory...    Running  Automatic</span><br><span class="out">DNS Server             Running  Automatic</span><br><span class="out">Print Spooler          Running  Manual</span><br><span class="out">Remote Desktop...     Running  Automatic</span><br><br><span class="out">(Right-click a service to Start, Stop, or Restart)</span>'}], explain: '<strong>Explanation:</strong> <code>services.msc</code> is great for visual inspection. If a service hangs, you can right-click and select "Restart" to force it to reload its configuration and clear its memory.' },
  
  { type: 'lesson', category: 'Windows Services', title: 'Windows: Services', subtitle: 'PowerShell', desc: 'PowerShell provides precise control over services for automation scripts.', syntax: 'Get-Service\nStop-Service -Name "Spooler"\nStart-Service -Name "Spooler"\nSet-Service -Name "Spooler" -StartupType Automatic', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Get-Service -Name "Spooler"</span><br><span class="out">Status   Name               DisplayName</span><br><span class="out">Running  Spooler            Print Spooler</span><br><br><span class="cmd">> Stop-Service -Name "Spooler"</span><br><span class="cmd">> Set-Service -Name "Spooler" -StartupType Automatic</span><br><span class="cmd">> Start-Service -Name "Spooler"</span>'}], explain: '<strong>Explanation:</strong> <code>Stop-Service</code> halts the process. <code>Set-Service -StartupType Automatic</code> ensures it starts on the next boot. <code>Start-Service</code> brings it back online immediately.' },
  
  { type: 'lesson', category: 'Windows Services', title: 'Windows: Dependencies', subtitle: 'sc qc', desc: 'If a service fails to start, it might be waiting for a dependency. Use <code>sc qc</code> to view what services must start before this one can.', syntax: 'sc qc "W3SVC"', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> sc qc "W3SVC"</span><br><span class="out">[SC] QueryServiceConfig SUCCESS</span><br><span class="out">SERVICE_NAME: W3SVC</span><br><span class="out">        DEPENDENCIES   : HTTP</span><br><span class="out">                       RpcSs</span><br><br><span class="out" style="color:#E8A07A">Result</span><br><span class="out">The IIS Web Service (W3SVC) depends on the HTTP.sys driver and the RPC Service. If either is stopped, IIS cannot start.</span>'}], explain: '<strong>Explanation:</strong> Dependency failures are a common cause of service crashes. If IIS won\'t start, checking dependencies tells you to look at the RPC Service or the Windows Firewall (which uses the HTTP driver) instead of reinstalling IIS.' },
  
  { type: 'lesson', category: 'Linux Services', title: 'Linux: Services', subtitle: 'systemctl', desc: 'Ubuntu uses <code>systemd</code> to manage services. The <code>systemctl</code> command is your primary tool for controlling daemons.', syntax: 'systemctl status ssh\nsystemctl stop ssh\nsystemctl start ssh\nsystemctl restart ssh', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl status ssh</span><br><span class="out">● ssh.service - OpenBSD Secure Shell server</span><br><span class="out">     Loaded: loaded (/lib/systemd/system/ssh.service; enabled)</span><br><span class="out">     Active: active (running) since Wed 2024-10-24 10:00:00 PST</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl restart ssh</span><br><span class="out">(Stops and immediately starts the SSH daemon)</span>'}], explain: '<strong>Explanation:</strong> <code>status</code> shows if the service is running. <code>stop</code> halts it. <code>start</code> launches it. <code>restart</code> does both. Always use <code>sudo</code> when managing system services.' },
  
  { type: 'lesson', category: 'Linux Services', title: 'Linux: Services', subtitle: 'Enable on Boot', desc: 'To ensure a service starts automatically when the server boots, you must <code>enable</code> it.', syntax: 'sudo systemctl enable nginx\nsudo systemctl disable nginx', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl enable nginx</span><br><span class="out">Synchronizing state of nginx.service with SysV service script...</span><br><span class="out">Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl disable nginx</span><br><span class="out">Removed /etc/systemd/system/multi-user.target.wants/nginx.service.</span>'}], explain: '<strong>Explanation:</strong> <code>enable</code> creates a symlink in the systemd target directory, telling the OS to start the service during boot. <code>disable</code> removes that link, preventing it from starting.' },
  
  { type: 'lesson', category: 'Linux Services', title: 'Linux: Masking Services', subtitle: 'systemctl mask', desc: 'Some services are insecure or unnecessary (e.g., Bluetooth on a server). Disabling them is not enough; another service might start them. Use <code>mask</code>.', syntax: 'systemctl mask bluetooth.service', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl mask bluetooth.service</span><br><span class="out">Created symlink /etc/systemd/system/bluetooth.service -> /dev/null.</span><br><br><span class="out" style="color:#E8A07A">Mask vs Disable</span><br><span class="out">- disable: Stops auto-start, but manual start or dependency start still works.</span><br><span class="out">- mask: Completely blocks the service from starting, even manually.</span>'}], explain: '<strong>Explanation:</strong> Masking links the service file to <code>/dev/null</code>, effectively destroying it for systemd. This is a hardening step required by CIS benchmarks for unnecessary services on servers.' },
  
  { type: 'lesson', category: 'Linux Services', title: 'Linux: systemd Targets', subtitle: 'Runlevels', desc: 'Linux uses systemd targets (equivalent to old runlevels) to manage the system state. <code>graphical.target</code> is the GUI, <code>multi-user.target</code> is CLI.', syntax: 'systemctl get-default\nsystemctl set-default multi-user.target', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">systemctl get-default</span><br><span class="out">multi-user.target</span><br><br><span class="out" style="color:#E8A07A">Common Targets</span><br><span class="out">1. multi-user.target: CLI only (Standard for servers).</span><br><span class="out">2. graphical.target: Full GUI (Ubuntu Desktop).</span><br><span class="out">3. rescue.target: Single-user mode for recovery.</span>'}], explain: '<strong>Explanation:</strong> Servers should always boot into <code>multi-user.target</code> to save RAM and reduce the attack surface. If a GUI is installed but not needed, changing the default target stops it from loading on boot.' },
  
  { type: 'lesson', category: 'Log Analysis', title: 'Windows: Event Viewer', subtitle: 'eventvwr.msc', desc: 'Windows Event Viewer is the central log repository. It logs application crashes, security events, and system errors.', syntax: 'eventvwr.msc\n# Windows Logs -> System', term: [{raw: '<span class="out" style="color:#E8A07A">Event Viewer (Local)</span><br><br><span class="out">Windows Logs</span><br><span class="out">  Application</span><br><span class="out">  Security</span><br><span class="out">  System        (Right-click -> Filter Current Log)</span><br><span class="out">  Setup</span><br><br><span class="out" style="color:#E8A07A">Filter by Event Level:</span><br><span class="out">[X] Critical</span><br><span class="out">[X] Error</span><br><span class="out">[ ] Warning</span>'}], explain: '<strong>Explanation:</strong> The "System" log contains the most relevant information for sysadmins (driver failures, service crashes, boot issues). Filtering by "Error" and "Critical" helps you find why a server rebooted unexpectedly or a service stopped.' },
  
  { type: 'lesson', category: 'Log Analysis', title: 'Windows: Event Logs', subtitle: 'Get-EventLog', desc: 'For automation, use PowerShell to extract specific error logs from the System event log.', syntax: 'Get-EventLog -LogName System -EntryType Error -Newest 5', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> Get-EventLog -LogName System -EntryType Error -Newest 5</span><br><br><span class="out">Index Time         EntryType   Source                 InstanceID Message</span><br><span class="out">----- ----         ---------   ------                 ---------- -------</span><br><span class="out">1024  Oct 24 10:00 Error       Service Control...     322123... The WSearch service...</span>'}], explain: '<strong>Explanation:</strong> This command pulls the 5 most recent Error entries from the System log. This is highly useful for scripts that monitor server health and send email alerts when errors occur.' },
  
  { type: 'lesson', category: 'Log Analysis', title: 'Windows: Event Forwarding', subtitle: 'WEF / Subscriptions', desc: 'In an enterprise, you do not log into 100 servers to check Event Viewer. You forward all logs to a central collector using Windows Event Forwarding (WEF).', syntax: 'wecutil qc\nwecutil cs subscription.xml', term: [{raw: '<span class="out" style="color:#E8A07A">WEF Architecture</span><br><br><span class="out">1. Source Server: The server generating logs (e.g., WIN-SRV-01).</span><br><span class="out">2. Collector Server: The central log aggregator.</span><br><span class="out">3. Subscription: A rule that tells the collector which logs to pull.</span><br><br><span class="out" style="color:#E8A07A">Why?</span><br><span class="out">If an attacker breaches a server, the first thing they do is clear the logs. WEF sends logs in real-time to a secure collector, preserving the evidence.</span>'}], explain: '<strong>Explanation:</strong> WEF is the Windows equivalent of a Linux Syslog server. It centralizes security logs, enabling SIEM (Security Information and Event Management) tools to detect attacks across the whole network simultaneously.' },
  
  { type: 'lesson', category: 'Log Analysis', title: 'Linux: Journalctl', subtitle: 'systemd journal', desc: 'Ubuntu uses <code>journald</code> to collect system logs. The <code>journalctl</code> command queries this database.', syntax: 'journalctl -p err\njournalctl -u ssh.service', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo journalctl -p err</span><br><span class="out">-- Logs begin at Wed 2024-10-24, end at 10:15:00. --</span><br><span class="out">Oct 24 10:00:01 dorsu systemd[1]: Failed to start Docker Application...</span><br><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo journalctl -u ssh.service</span><br><span class="out">-- Shows only logs generated by the SSH service --</span>'}], explain: '<strong>Explanation:</strong> The <code>-p err</code> flag filters for priority "error" (and above). The <code>-u</code> flag filters by a specific service unit (e.g., <code>ssh.service</code>). This precision allows sysadmins to bypass irrelevant logs and find the root cause quickly.' },
  
  { type: 'lesson', category: 'Log Analysis', title: 'Linux: Live Logs', subtitle: 'tail -f', desc: 'To watch a log file update in real-time as users interact with the system, use the <code>tail -f</code> command.', syntax: 'sudo tail -f /var/log/syslog', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo tail -f /var/log/syslog</span><br><span class="out">Oct 24 10:15:01 ubu-srv-01 systemd[1]: Started Daily apt download activities.</span><br><span class="out">Oct 24 10:15:05 ubu-srv-01 sshd[1234]: Accepted password for ajsacay from 192.168.1.5</span><br><span class="out">Oct 24 10:15:10 ubu-srv-01 kernel: [ 12.345] USB device connected</span><br><br><span class="out">(Press Ctrl+C to exit the live stream)</span>'}], explain: '<strong>Explanation:</strong> <code>tail -f</code> follows the end of the file. As new log lines are written by the system, they immediately appear on your screen. This is the standard way to monitor a service while you restart it or apply a patch.' },
  
  { type: 'lesson', category: 'Log Analysis', title: 'Linux: Logrotate', subtitle: 'Preventing Disk Full', desc: 'Logs grow forever. If left unchecked, they will fill the disk and crash the server. <code>logrotate</code> automatically compresses and deletes old logs.', syntax: 'cat /etc/logrotate.conf', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">cat /etc/logrotate.conf</span><br><span class="out">weekly</span><br><span class="out">rotate 4</span><br><span class="out">create</span><br><span class="out">compress</span><br><br><span class="out" style="color:#E8A07A">Settings</span><br><span class="out">- weekly: Rotate logs every week.</span><br><span class="out">- rotate 4: Keep 4 old log files before deleting.</span><br><span class="out">- compress: Gzip the old logs to save space.</span>'}], explain: '<strong>Explanation:</strong> Without logrotate, <code>/var/log/syslog</code> would grow to gigabytes. Logrotate runs daily via cron, cutting logs into manageable chunks and deleting old ones, ensuring the disk never fills up with logs.' },
  
  { type: 'lesson', category: 'Log Analysis', title: 'Log Analysis Pipeline', subtitle: 'grep + tail', desc: 'Combine <code>tail</code> with <code>grep</code> to monitor a log file live, but only show lines matching a specific pattern (like "Error" or a specific IP).', syntax: 'sudo tail -f /var/log/syslog | grep "Failed password"', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo tail -f /var/log/auth.log | grep "Failed password"</span><br><br><span class="out">(Stream is open... waiting for matches...)</span><br><span class="out">Oct 24 10:20:01 dorsu sshd[5678]: Failed password for invalid user admin from 10.0.0.5</span><br><span class="out">Oct 24 10:20:03 dorsu sshd[5678]: Failed password for invalid user admin from 10.0.0.5</span><br><span class="out">Oct 24 10:20:05 dorsu sshd[5678]: Failed password for invalid user root from 10.0.0.5</span><br><br><span class="out">(Only lines containing "Failed password" are shown)</span>'}], explain: '<strong>Explanation:</strong> This pipeline streams the log live but filters it through grep. It is the sysadmin\'s ultimate tool for catching brute-force attacks or monitoring a specific application error while testing a patch.' },
  
  { type: 'lesson', category: 'Recovery', title: 'Windows: Service Recovery', subtitle: 'Auto-Restart', desc: 'If a critical service crashes, Windows can be configured to automatically restart it without admin intervention.', syntax: 'sc failure "Spooler" reset= 86400 actions= restart/60000/restart/60000/restart/60000', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> sc failure "Spooler" reset= 86400 actions= restart/60000/restart/60000/restart/60000</span><br><br><span class="out">[SC] ChangeServiceConfig2 SUCCESS</span><br><br><span class="out" style="color:#E8A07A">What this does:</span><br><span class="out">1st failure: Wait 60 seconds, then Restart</span><br><span class="out">2nd failure: Wait 60 seconds, then Restart</span><br><span class="out">3rd failure: Wait 60 seconds, then Restart</span>'}], explain: '<strong>Explanation:</strong> <code>sc failure</code> configures the recovery policy. <code>reset=86400</code> resets the failure counter after 24 hours. This ensures that transient glitches do not take your service offline permanently.' },
  
  { type: 'lesson', category: 'Recovery', title: 'Linux: Service Restart', subtitle: 'systemd override', desc: 'In Linux, <code>systemd</code> usually handles service restarts automatically, but you can explicitly define restart behavior using an override file.', syntax: 'sudo systemctl edit ssh.service\n[Service]\nRestart=always\nRestartSec=3', term: [{editor: "/etc/systemd/system/ssh.service.d/override.conf", code: "[Service]\nRestart=always\nRestartSec=3"}, {raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl edit ssh.service</span><br><span class="out">(Opens a blank override file in nano)</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl daemon-reload</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo systemctl restart ssh</span>'}], explain: '<strong>Explanation:</strong> <code>systemctl edit</code> creates a drop-in override file. Setting <code>Restart=always</code> and <code>RestartSec=3</code> tells systemd to wait 3 seconds and restart the service if it crashes, no matter the exit status. Run <code>daemon-reload</code> to apply the new config.' },
  
  { type: 'lesson', category: 'ITIL SOP', title: 'Patching SOP: Step 1', subtitle: 'Assessment & Planning', desc: 'Before touching a production server, a sysadmin must assess what patches are available and what impact they will have on running services.', syntax: '# 1. Assessment & Planning\n- Check update release notes\n- Identify dependencies\n- Schedule maintenance window', term: [{raw: '<span class="out" style="color:#E8A07A">SOP Step 1: Assessment</span><br><br><span class="out">1. Review Microsoft/Ubuntu release notes for known issues.</span><br><span class="out">2. Check if the patch requires a reboot.</span><br><span class="out">3. Identify if the patch affects a critical service (e.g., IIS, Apache).</span><br><span class="out">4. Schedule a maintenance window (e.g., 2:00 AM Sunday).</span><br><span class="out">5. Notify users of expected downtime.</span>'}], explain: '<strong>Explanation:</strong> Never apply patches blindly. A kernel update might break a custom driver, or a web framework update might break your application. Assessment mitigates the risk of bricking a production server.' },
  
  { type: 'lesson', category: 'ITIL SOP', title: 'Patching SOP: Step 2', subtitle: 'Testing Environment', desc: 'Deploy the patches in a staging environment that mirrors production. If the system survives, proceed to production.', syntax: '# 2. Testing Environment\n- Deploy to a test VM\n- Run application tests\n- Verify system stability', term: [{raw: '<span class="out" style="color:#E8A07A">SOP Step 2: Testing</span><br><br><span class="out">1. Snapshot the test VM (so you can roll back).</span><br><span class="out">2. Install the exact patches planned for production.</span><br><span class="out">3. Reboot the test VM.</span><br><span class="out">4. Run automated application tests.</span><br><span class="out">5. Monitor test logs for 24 hours.</span>'}], explain: '<strong>Explanation:</strong> In enterprise environments, patches must pass a Change Advisory Board (CAB). Testing provides the evidence that the patch is safe. If the test fails, you halt the rollout and report the issue.' },
  
  { type: 'lesson', category: 'ITIL SOP', title: 'Patching SOP: Step 3', subtitle: 'Production Rollout', desc: 'Deploy the verified patches to the production servers during the scheduled maintenance window.', syntax: '# 3. Production Rollout\n- Create VM snapshot/backup\n- Install patches\n- Reboot if required', term: [{raw: '<span class="out" style="color:#E8A07A">SOP Step 3: Rollout</span><br><br><span class="out">1. Take a final backup or VirtualBox snapshot of production.</span><br><span class="out">2. Run: sudo apt upgrade -y (or Install-WindowsUpdate).</span><br><span class="out">3. Reboot the server if kernel/system files were updated.</span><br><span class="out">4. Verify the server comes back online (ping).</span><br><span class="out">5. Verify critical services start automatically (systemctl status).</span>'}], explain: '<strong>Explanation:</strong> Always take a snapshot before patching production. If the server fails to boot after the patch, you can instantly restore the snapshot and restore service, turning a 4-hour outage into a 5-minute blip.' },
  
  { type: 'lesson', category: 'ITIL SOP', title: 'Patching SOP: Step 4', subtitle: 'Verification & Rollback', desc: 'After the rollout, verify the system is healthy. If it is broken, execute the rollback plan immediately.', syntax: '# 4. Verification\n- Check application health\n- Review error logs\n- Rollback if necessary', term: [{raw: '<span class="out" style="color:#E8A07A">SOP Step 4: Verification</span><br><br><span class="out">1. Log in to the server and check system uptime.</span><br><span class="out">2. Check Event Viewer / journalctl for new errors.</span><br><span class="out">3. Have a user test the core application.</span><br><span class="out">4. If broken: Revert VirtualBox snapshot or run \'apt downgrade\'.</span><br><span class="out">5. Document the success or failure in the change log.</span>'}], explain: '<strong>Explanation:</strong> Verification closes the loop. If the patch broke the application, you execute your rollback plan (restoring the snapshot). Documenting the outcome is a key ITIL principle for future reference.' },
  
  { type: 'lesson', category: 'ITIL SOP', title: 'Patching SOP: Rollback', subtitle: 'Disaster Plan', desc: 'A patching SOP is incomplete without a rollback strategy. You must know how to undo a patch if it causes a blue screen or kernel panic.', syntax: 'Windows: wusa /uninstall /kb:500123\nLinux: apt-get install package=1.0-1', term: [{raw: '<span class="out" style="color:#E8A07A">Windows Rollback</span><br><span class="cmd">> wusa /uninstall /kb:500123 /quiet /norestart</span><br><span class="out">(Uninstalls a specific Windows Update patch)</span><br><br><span class="out" style="color:#E8A07A">Linux Rollback</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">sudo apt-get install nginx=1.24.0-2ubuntu7</span><br><span class="out">(Downgrades the package to a specific known-good version)</span>'}], explain: '<strong>Explanation:</strong> Always document the exact commands needed to roll back a patch. If a kernel update breaks the network driver, you need to boot into the old kernel (GRUB menu) and downgrade the package immediately to restore service.' },
  
  { type: 'lesson', category: 'Automation', title: 'Ubuntu: Maint Script', subtitle: 'Bash Automation', desc: 'Combine the update and cleanup commands into a single Bash script to standardize server maintenance.', syntax: '#!/bin/bash\nsudo apt update && sudo apt upgrade -y\nsudo apt autoremove -y\nsudo journalctl --vacuum-time=7d', term: [{editor: "maintenance.sh", code: "#!/bin/bash\necho \"Starting server maintenance...\"\n# Update packages\nsudo apt update && sudo apt upgrade -y\n# Clean up old dependencies\nsudo apt autoremove -y\n# Clear system logs older than 7 days\nsudo journalctl --vacuum-time=7d\necho \"Maintenance complete.\""}, {raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">chmod +x maintenance.sh</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">./maintenance.sh</span>'}], explain: '<strong>Explanation:</strong> This script updates the system, removes unused packages, and clears old logs to free up disk space. <code>journalctl --vacuum-time=7d</code> deletes all journald logs older than 7 days, preventing /var from filling up.' },
  
  { type: 'lesson', category: 'Automation', title: 'Windows: Maint Script', subtitle: 'PowerShell Automation', desc: 'A PowerShell equivalent to check disk space, clear temp files, and install updates. (Requires PSWindowsUpdate module).', syntax: 'Install-WindowsUpdate -AcceptAll -AutoReboot\nGet-PSDrive C | Select-Object Used,Free', term: [{editor: "maintenance.ps1", code: "Write-Host \"Starting Windows Maintenance...\"\n# Install all available updates and reboot if needed\nInstall-WindowsUpdate -AcceptAll -AutoReboot\n# Clean up Windows Update cache\nRemove-Item -Path C:\\Windows\\SoftwareDistribution\\Download\\* -Recurse -Force\n# Check disk space\nGet-PSDrive C | Select-Object Used, Free\nWrite-Host \"Maintenance complete.\""}, {raw: '<span class="out" style="color:#E8A07A">Windows PowerShell (Admin)</span><br><span class="cmd">> .\\maintenance.ps1</span>'}], explain: '<strong>Explanation:</strong> This script automates the Windows maintenance cycle. Cleaning the SoftwareDistribution folder can free up gigabytes of space taken up by old update files. <code>Get-PSDrive C</code> reports the final disk space.' },
  
  { type: 'lesson', category: 'Automation', title: 'Dual-OS Maintenance', subtitle: 'WSL Integration', desc: 'Windows 11 can now update WSL 2 distributions via Windows Update. This unifies the patching cycle for your dual-OS environment.', syntax: 'Windows Update -> Advanced Options -> Receive updates for other Microsoft products', term: [{raw: '<span class="out" style="color:#E8A07A">Unified Patching</span><br><br><span class="out">1. Enable "Receive updates for other Microsoft products" in Windows Update settings.</span><br><span class="out">2. The WSL 2 kernel will now patch automatically alongside Windows.</span><br><br><span class="out" style="color:#E8A07A">Ubuntu inside WSL</span><br><span class="out">You still need to run `sudo apt upgrade` inside the WSL terminal to patch the Linux packages, but the virtual machine layer is managed by Windows.</span>'}], explain: '<strong>Explanation:</strong> This integration reduces the administrative burden. You don\'t need to manually run <code>wsl --update</code>; it happens through the standard Windows Update cycle, ensuring the hypervisor and kernel are always secure.' },
  
  { type: 'lesson', category: 'Verification', title: 'Verifying Reboots', subtitle: 'Uptime Checks', desc: 'After a patching cycle that requires a reboot, verify the server actually restarted and has been stable.', syntax: '# Windows:\nGet-CimInstance Win32_OperatingSystem | Select LastBootUpTime\n# Linux:\nuptime\nlast reboot', term: [{raw: '<span class="out" style="color:#E8A07A">Windows PowerShell</span><br><span class="cmd">> Get-CimInstance Win32_OperatingSystem | Select LastBootUpTime</span><br><span class="out">LastBootUpTime</span><br><span class="out">10/24/2024 2:00:05 AM</span><br><br><span class="out" style="color:#E8A07A">Ubuntu Bash</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">uptime</span><br><span class="out"> 10:30:15 up  8:30,  1 user,  load average: 0.00, 0.01, 0.05</span><br><span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">last reboot | head -n 3</span><br><span class="out">reboot   system boot  6.8.0-31-generic Wed Oct 24 02:00   still running</span>'}], explain: '<strong>Explanation:</strong> <code>uptime</code> shows how long the system has been running since the last boot. <code>last reboot</code> shows the history of reboots. If a server was supposed to patch and reboot at 2:00 AM, but uptime shows 30 days, the patching failed.' },
  
  { type: 'lesson', category: 'Verification', title: 'Verifying Disk Space', subtitle: 'df / Get-Volume', desc: 'A full disk will stop services from writing logs and cause the system to crash. Always check disk space during maintenance.', syntax: '# Linux:\ndf -h\n# Windows:\nGet-Volume', term: [{raw: '<span class="prompt"><span class="user">ajsacay@ubu-srv-01</span>:<span class="path">~</span>$</span> <span class="cmd">df -h</span><br><span class="out">Filesystem      Size  Used Avail Use% Mounted on</span><br><span class="out">/dev/sda2        24G  8.5G   14G  39% /</span><br><span class="out">tmpfs           3.9G     0  3.9G   0% /dev/shm</span><br><br><span class="out" style="color:#E8A07A">Windows PowerShell</span><br><span class="cmd">> Get-Volume</span><br><span class="out">DriveType FileSystemLabel SizeRemaining Size</span><br><span class="out">Fixed    OS               25.6 GB        50.0 GB</span>'}], explain: '<strong>Explanation:</strong> If the "Use%" column in Linux or "SizeRemaining" in Windows drops below 10%, you have a critical issue. Services like databases will crash immediately. Cleaning up old logs (<code>journalctl --vacuum-time</code>) is the fastest way to recover space.' },
  
  { type: 'lesson', category: 'Enterprise', title: 'Enterprise Patching', subtitle: 'WSUS & Landscape', desc: 'In a real enterprise with 100+ servers, you do not patch them one by one. You use centralized patch management servers.', syntax: 'Windows: WSUS (Windows Server Update Services)\nLinux:   Canonical Landscape', term: [{raw: '<span class="out" style="color:#E8A07A">Enterprise Scale Patching</span><br><br><span class="out">1. WSUS: A local Windows server that downloads patches from Microsoft.</span><br><span class="out">   - Sysadmin approves patches in WSUS.</span><br><span class="out">   - All domain computers pull patches from WSUS (saving bandwidth).</span><br><br><span class="out">2. Landscape: Canonical\'s management tool for Ubuntu.</span><br><span class="out">   - Manage 100s of Ubuntu machines from a web dashboard.</span><br><span class="out">   - Deploy packages and enforce security policies remotely.</span>'}], explain: '<strong>Explanation:</strong> Centralized patching allows a sysadmin to test a patch on a "pilot" group of computers, and if successful, deploy it to the entire company with one click, ensuring all machines are compliant.' },
  
  { type: 'lesson', category: 'Summary', title: 'Topic Summary', subtitle: 'Module 2 Complete', desc: 'You now possess the skills to maintain a dual-OS environment: patching, managing services, analyzing logs, and following an ITIL SOP.', syntax: 'sudo apt update\nsystemctl status ssh\neventvwr.msc', term: [{raw: '<span class="out" style="color:#E8A07A">Topic 8 Checklist:</span><br>[x] Patched Windows Server (sconfig / PSWindowsUpdate)<br>[x] Patched Ubuntu Server (apt / unattended-upgrades)<br>[x] Managed Services (systemctl / services.msc)<br>[x] Analyzed Logs (journalctl / Event Viewer)<br>[x] Wrote a 4-Step ITIL Patching SOP<br><br><span class="out">Next: We will deploy applications using Docker Compose.</span>'}], explain: '<strong>Explanation:</strong> Maintenance is 80% of a sysadmin\'s job. Mastering these commands ensures your servers remain secure, stable, and compliant with industry standards like ITIL.' },

  // --- 4. CLOSING SLIDE ---
  {
    type: 'closing',
    header: 'MODULE 02 · TOPIC 08',
    tag: 'End of Topic 08',
    title: 'Patch. Monitor. <em>Repeat.</em>',
    leftCardNum: '§ maintenance',
    leftCardTitle: 'The ITIL SOP',
    leftCardDesc: 'Following a structured 4-step patching SOP (Assess, Test, Deploy, Verify) ensures system stability while maintaining security in enterprise environments.',
    middleCardNum: '§ services',
    middleCardTitle: 'Systemd & Event Logs',
    middleCardDesc: 'Mastering <code>systemctl</code> and Event Viewer/journalctl allows a sysadmin to quickly identify failing components and automate their recovery.',
    rightCardNum: '§ compliance',
    rightCardTitle: 'Centralized Control',
    rightCardDesc: 'Using tools like WSUS, Landscape, and automated maintenance scripts ensures consistency across hundreds of dual-OS servers.'
  }
];
